fix (DB/NPC): Dalaran CTM fix
azerothcore/azerothcore-wotlk pull request #10058
Opened 2022-01-07 17:00 UTC by acidmanifesto

Fixes the air swimmers when they land.

## Changes Proposed:
-  Deletes CTMS of two npcs the Dalaran Visitors
-  Smart sets their inhabit type and they are just a quick 8 second skit before despawning.

## Issues Addressed:

- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/10055

## SOURCE:

- Visual comaprisons as they are none flying humanoids.

## Tests Performed:

- Builds
- Performs

## How to Test the Changes:

1. goto krauses landing in dalaran
2. watch the dalaran visitors land
3. you will be looking at a gnome and a dwarf dalaran vistor as the culprits. they now run as intended per the smart scripts.

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

2022-01-07 17:21 UTC, IntelligentQuantum requested changes
remove acore_world

2022-01-07 17:42 UTC, acidmanifesto commented
> remove acore_world
> 
> and `CreatureId` IN(32596, X); maybe

Ah. Was a quick pr before i left for my appointment currently. Will definately do it. Thanks

2022-01-07 20:12 UTC, IntelligentQuantum reviewed
`CreatureId` add ``

2022-01-07 21:40 UTC, Kitzunu requested changes

2022-01-07 21:40 UTC, Kitzunu commented on data/sql/updates/pending_db_world/rev_1641574598839293356.sql
> +DELETE FROM `creature_template_movement` WHERE  CreatureId AND (32596, 32597);
```suggestion
DELETE FROM `creature_template_movement` WHERE  `CreatureID` IN (32596, 32597);
```

2022-01-08 00:51 UTC, IntelligentQuantum approved these changes

2022-01-08 13:31 UTC, Kitzunu approved these changes

2022-01-09 15:52 UTC, merged