fix(Core/Player) Fix Rediscovering Certain Flight Paths and Zones After a Logout and Login
azerothcore/azerothcore-wotlk pull request #10083
Opened 2022-01-08 20:07 UTC by LannyE

Certain zones and flight path discoveries are removed on logout and must
be frustratingly rediscovered again

Closes Azerothcore issue #7737

## Changes Proposed:
-  It apparently fixes the conversion of strings to unsigned longs.  Certain zones and flight paths must not convert right so they do not save on a logout.  
-  Got the info from [https://github.com/TrinityCore/TrinityCore/commit/24c173f387044496d581255545ed94c988f3ae3b](url)
and [https://github.com/TrinityCore/TrinityCore/issues/13493](url)
## Issues Addressed:

- Closes #7737

## SOURCE:

## Tests Performed:

- Went the to flight masters specified in the Issues (Nutral, Bladruc, Celea) and checked to see if flight the flight was saved on logout.
- Learned spells and recipes and generally tried to break stuff.
- Went to zones like thelsamar and 
- Compiles and runs just fine.

## How to Test the Changes:

1. Go to Baldruc in Theramore and learn his flight path.  Logout and log back in and see if it still is learned/discovered
2. Go to Valley of Fangs in Badlands and discover it then logout and log back and see if you rediscover it.  
3.

## Known Issues and TODO List:

Please test this thing as I am not a great programmer. 
- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

2022-01-08 21:01 UTC, acidmanifesto commented
Code style Check reports:
![image](https://user-images.githubusercontent.com/16887899/148659850-82534506-859f-4bcd-9aaf-3cc108237925.png)

C++ 20 check reports:
![image](https://user-images.githubusercontent.com/16887899/148659832-1f49e798-a98c-4248-ae5b-0de75aa9adf3.png)

Ubuntu Checks reports:
![image](https://user-images.githubusercontent.com/16887899/148659882-54feec47-ac2f-4af0-a346-c2e7e51ca8ff.png)

2022-01-08 21:02 UTC, acidmanifesto requested changes
Fix errors a reported by the Test Results.

2022-01-08 22:49 UTC, Kitzunu requested changes
I don't think atoul is the right way to fix this.

@Winfidonarleyan we have our own better thing to do that right?

2022-01-10 23:20 UTC, acidmanifesto approved these changes

2022-01-10 23:50 UTC, Winfidonarleyan commented
> I don't think atoul is the right way to fix this.
> 
> @Winfidonarleyan we have our own better thing to do that right?

Of course `Acore::StringTo`

2022-01-10 23:50 UTC, Winfidonarleyan commented on src/common/Common.h
> +inline unsigned long atoul(char const* str) { return strtoul(str, nullptr, 10); }
No need this.
https://github.com/azerothcore/azerothcore-wotlk/blob/master/src/common/Utilities/StringConvert.h

2022-01-10 23:53 UTC, Winfidonarleyan commented
I will make a more global PR

2022-01-19 15:08 UTC, LannyE commented
Do you still need me to make the requested change or anything else?

2022-01-21 05:19 UTC, Winfidonarleyan commented
> Do you still need me to make the requested change or anything else?

Use StringConvert

2022-01-22 00:46 UTC, LannyE commented
I am working on the conversion.  Be warned my C++ skills are not that strong.  In my attempt to use `Acore::StringTo` I replaced this code in PlayerDump.cpp line 554:
`race = uint8(atoul(getnth(line, 4).c_str()));`
with
`race = uint8(Acore::StringTo<uint8>(getnth(line, 4).c_str()));`
and I get this error:
`Error	C2440	'<function-style-cast>': cannot convert from 'std::optional<uint8>' to 'uint8'`
I haven't been able to figure it out.  Any guidance on how to fix this would be appreciated.

2022-01-22 06:30 UTC, LannyE commented
Nevermind it appears PR #10121 takes care of most of this except the Chat.cpp and PlayerDump.cpp.  I just tested it and that PR does fix the flight paths and the rediscovering zones issue from #7737.  As a side note the tokenizer PR #10121 breaks the Arena 1v1 module.  That module uses the tokenizer code so now you can't compile new versions of Azerothcore with that module present.  

Do you want to close this PR since the issue it was created for is now resolved?

2022-01-23 03:27 UTC, Winfidonarleyan commented
> Nevermind it appears PR #10121 takes care of most of this except the Chat.cpp and PlayerDump.cpp. I just tested it and that PR does fix the flight paths and the rediscovering zones issue from #7737. As a side note the tokenizer PR #10121 breaks the Arena 1v1 module. That module uses the tokenizer code so now you can't compile new versions of Azerothcore with that module present.
> 
> Do you want to close this PR since the issue it was created for is now resolved?

if problem resolved - can close. I continue replace `ato**` next time

2022-02-04 00:16 UTC, closed without merging