feat(Core/Common): delete old Tokenizer
azerothcore/azerothcore-wotlk pull request #10121
Opened 2022-01-11 01:43 UTC by Winfidonarleyan

## Changes Proposed:
- Partical cherrypick https://github.com/TrinityCore/TrinityCore/commit/534a2388b7c662c8796aabb1ec8cb424879799b6

## Issues Addressed:

- Closes 

## Tests Performed:
- 
- 

## How to Test the Changes:
1.
2.
3.

## Known Issues and TODO List:
- [ ] Ban manager rework
- [ ] Replace all `atoi`

# How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

2022-01-16 22:50 UTC, Kitzunu requested changes

2022-01-16 22:50 UTC, Kitzunu commented on data/sql/updates/pending_db_world/rev_1641914952623130600.sql
> +UPDATE `creature_template_addon` SET auras = REPLACE(auras, ',', ' ');
Backticks

2022-01-16 23:15 UTC, Winfidonarleyan commented on data/sql/updates/pending_db_world/rev_1641914952623130600.sql
> +UPDATE `creature_template_addon` SET auras = REPLACE(auras, ',', ' ');
for auras?

2022-01-16 23:26 UTC, Kitzunu commented on data/sql/updates/pending_db_world/rev_1641914952623130600.sql
> +UPDATE `creature_template_addon` SET auras = REPLACE(auras, ',', ' ');
Yes

2022-01-17 03:22 UTC, Winfidonarleyan commented on data/sql/updates/pending_db_world/rev_1641914952623130600.sql
> +UPDATE `creature_template_addon` SET auras = REPLACE(auras, ',', ' ');
```suggestion
UPDATE `creature_template_addon` SET `auras` = REPLACE(auras, ',', ' ');
```

2022-01-17 03:23 UTC, Winfidonarleyan commented on data/sql/updates/pending_db_world/rev_1641914952623130600.sql
> +UPDATE `creature_template_addon` SET `auras` = REPLACE(auras, ',', ' ');
@Kitzunu can check? :D

2022-01-17 19:01 UTC, Kitzunu approved these changes

2022-01-21 07:59 UTC, merged