fix(DB/Spawning/Pooling/Pathing) Devilsaurs, Un'goro TESTING
azerothcore/azerothcore-wotlk pull request #10171
Opened 2022-01-14 03:02 UTC by malcrom

## Changes Proposed:
- Respawn, pool, and path Devilsaurs, Ironhide Devilsaurs, and Tyrant Devilsaurs  in Un'Goro crater.
- These are in three polls of two allowing 3 to be spawned at once. One east, one center, and one west in one of two paths.
- To be used with PR #10169.

## Issues Addressed:
- Closes 

## SOURCE:
Sniffing

## Tests Performed:
- Inserts
- tested spawning and pathing.

## How to Test the Changes:
1. .go c 24181 or .go c 24182 one will be spawned and pathing
2. .go c 24183 or .go c 24184 one will be spawned and pathing
3. .go c 24185 or .go c 24186 one will be spawned and pathing

2022-01-14 03:03 UTC, acidmanifesto approved these changes

2022-01-14 23:39 UTC, Kitzunu requested changes

2022-01-14 23:39 UTC, Kitzunu commented on data/sql/updates/pending_db_world/rev_1642128832605724154.sql
> +INSERT INTO pool_creature (guid, pool_entry, chance, description) VALUES
¨backticks

2022-01-14 23:39 UTC, Kitzunu commented on data/sql/updates/pending_db_world/rev_1642128832605724154.sql
> +INSERT INTO pool_creature (guid, pool_entry, chance, description) VALUES
same here

2022-01-14 23:39 UTC, Kitzunu commented on data/sql/updates/pending_db_world/rev_1642128832605724154.sql
> +INSERT INTO pool_creature (guid, pool_entry, chance, description) VALUES
here too

2022-01-15 00:02 UTC, malcrom commented on data/sql/updates/pending_db_world/rev_1642128832605724154.sql
> +INSERT INTO pool_creature (guid, pool_entry, chance, description) VALUES
Works fine

2022-01-15 00:16 UTC, Kitzunu commented on data/sql/updates/pending_db_world/rev_1642128832605724154.sql
> +INSERT INTO pool_creature (guid, pool_entry, chance, description) VALUES
\`pool_creature\`

2022-01-15 00:31 UTC, Kitzunu approved these changes

2022-01-15 00:32 UTC, merged

2022-01-15 02:31 UTC, pklloveyou commented
https://github.com/azerothcore/azerothcore-wotlk/pull/10079 Check to see here? Guid overlaps

2022-01-15 16:08 UTC, acidmanifesto commented
> #10079 Check to see here? Guid overlaps

corrected in https://github.com/azerothcore/azerothcore-wotlk/pull/10194