Fix(DB/CTM) Fix Onyxia float on ground at P2
azerothcore/azerothcore-wotlk pull request #10191
Opened 2022-01-15 04:36 UTC by betayi

## Changes Proposed:
-  Fix 10190
-  

## Issues Addressed:

- Closes #10190 

## SOURCE:

## Tests Performed:

- 
- 

## How to Test the Changes:

1.go c id 10184
2.damage to enter P2
3.watch if float on air but not on ground

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

2022-01-16 01:23 UTC, acidmanifesto requested changes

2022-01-16 01:23 UTC, acidmanifesto commented on data/sql/updates/pending_db_world/rev_1642220996463864536.sql
> +UPDATE `creature_template_movement` SET `Flight` = 1 WHERE `CreatureId` IN (10184,36538);
line break

2022-01-16 19:38 UTC, acidmanifesto approved these changes

2022-02-01 14:52 UTC, Nyeriah commented
Don't forget the workflow labels please

2022-02-01 15:00 UTC, merged