Fix(Core/Stratholme): Some adjustments to Jarien and Sothos fight
azerothcore/azerothcore-wotlk pull request #10269
Opened 2022-01-20 15:43 UTC by Nefertumm

## Changes Proposed:
-  Move ReactState to constructor to avoid aggro issues with pets
-  Added mob reference to the talk method to use $n
-  Fixed group loot issues with heirlooms

## Issues Addressed:

- Closes #10258
- Closes #9865 
- Closes https://github.com/chromiecraft/chromiecraft/issues/2830
- Closes https://github.com/chromiecraft/chromiecraft/issues/2650

## SOURCE:

## Tests Performed:

- Tested in-game

## How to Test the Changes:

With 2 chars in party:
Set the loot mode as group loot
.go creature 52149
.additem 6265
summon Void Walker
.additem 22057
use [Brazier of Invocation]
Make sure Jarien and Sothos don't attack Void Walker before conversation ends
kill Sothos/Jarien
watch the other one enrage message
Kill the other one
Loot the chest and you can now roll for the items

2022-01-20 17:55 UTC, acidmanifesto approved these changes

2022-01-21 15:54 UTC, temperrr commented
Tested

- [x] Group loot and roll
- [x] Doesnt attack pet during rp
- [ ] you can attack them during the RP, this is not correct (https://youtu.be/OH9ueV3hP1Q?t=91)

2022-01-22 15:02 UTC, Nyeriah requested changes

2022-01-22 15:02 UTC, Nyeriah commented on src/server/scripts/EasternKingdoms/Stratholme/boss_jarien_and_sothos.cpp
> +        me->SetFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_NPC);
```suggestion
        me->SetFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NON_ATTACKABLE|UNIT_FLAG_IMMUNE_TO_NPC);
```

2022-01-22 17:35 UTC, Nefertumm commented on src/server/scripts/EasternKingdoms/Stratholme/boss_jarien_and_sothos.cpp
> +        me->SetFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_NPC);
Yes! Good catch!

2022-01-22 17:37 UTC, Nefertumm commented on src/server/scripts/EasternKingdoms/Stratholme/boss_jarien_and_sothos.cpp
> +        me->SetFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_NPC);
Same with remove flag right?

2022-01-22 17:46 UTC, Nyeriah requested changes

2022-01-22 17:46 UTC, Nyeriah commented on src/server/scripts/EasternKingdoms/Stratholme/boss_jarien_and_sothos.cpp
> +        me->SetFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_NPC);
here too

2022-01-22 18:22 UTC, Nefertumm commented
Last time 4Head

2022-01-22 18:25 UTC, Nyeriah approved these changes

2022-01-22 19:22 UTC, merged