feat(DB): release ACDB 5.0.0
azerothcore/azerothcore-wotlk pull request #10292
Opened 2022-01-21 18:10 UTC by Winfidonarleyan

## Changes Proposed:
-  
-

2022-01-23 03:57 UTC, Winfidonarleyan commented
@Kitzunu can fast check?

2022-01-23 08:41 UTC, Winfidonarleyan commented
Ready

2022-01-23 08:51 UTC, Kitzunu requested changes
Fix it everywhere

2022-01-23 08:51 UTC, Kitzunu commented on data/sql/base/db_characters/arena_team_member.sql
> +  `personalRating` smallint(6) NOT NULL DEFAULT 0,
No no

2022-01-23 12:00 UTC, Winfidonarleyan commented
> 

Okay

2022-01-23 12:00 UTC, Winfidonarleyan commented
> Fix it everywhere

Okay

2022-01-25 21:08 UTC, Winfidonarleyan commented on data/sql/base/db_characters/arena_team_member.sql
> +  `personalRating` smallint(6) NOT NULL DEFAULT 0,
Done

2022-01-25 21:09 UTC, Winfidonarleyan commented
Ready, @Kitzunu can R?

2022-01-25 21:17 UTC, Kitzunu approved these changes

2022-01-25 21:17 UTC, Kitzunu commented on data/sql/base/db_characters/quest_tracker.sql
>    `id` mediumint(8) unsigned NOT NULL DEFAULT 0,
.

2022-01-25 21:17 UTC, Kitzunu commented on data/sql/base/db_world/achievement_criteria_data.sql
>    `criteria_id` mediumint(9) NOT NULL,
.

2022-01-25 21:17 UTC, Kitzunu commented on data/sql/base/db_world/achievement_reward.sql
>    `ID` mediumint(8) unsigned NOT NULL DEFAULT 0,
.

2022-01-25 22:10 UTC, Winfidonarleyan commented
@Kitzunu thanks, tomorrow replace this

2022-01-26 20:10 UTC, Winfidonarleyan commented
@Kitzunu done

2022-01-27 11:07 UTC, Nyeriah commented
Hey winfi, is there anything in the wiki that needs to be updated? What's the procedure this time? 

We should merge this ASAP, as soon as it's ready imo.

2022-01-27 14:46 UTC, Winfidonarleyan commented
> Hey winfi, is there anything in the wiki that needs to be updated? What's the procedure this time?
> 
> We should merge this ASAP, as soon as it's ready imo.

I can't find thjs info in wiki, can link?

2022-01-27 14:47 UTC, Kitzunu commented
> > Hey winfi, is there anything in the wiki that needs to be updated? What's the procedure this time?
> > We should merge this ASAP, as soon as it's ready imo.
> 
> I can't find this info in wiki, can link?

https://github.com/azerothcore/wiki/pull/640

2022-01-27 14:59 UTC, Winfidonarleyan commented
> > > Hey winfi, is there anything in the wiki that needs to be updated? What's the procedure this time?
> > > We should merge this ASAP, as soon as it's ready imo.
> > 
> > 
> > I can't find this info in wiki, can link?
> 
> [azerothcore/wiki#640](https://github.com/azerothcore/wiki/pull/640)

yes yes

2022-01-28 19:38 UTC, Kitzunu commented
@Winfidonarleyan could you just make sure that we don't have FLOAT UNSIGNED anywhere and that those use check constraints? https://www.azerothcore.org/wiki/sql-standards#float-double-decimal

2022-01-28 20:09 UTC, Winfidonarleyan commented
> @Winfidonarleyan could you just make sure that we don't have FLOAT UNSIGNED anywhere and that those use check constraints? https://www.azerothcore.org/wiki/sql-standards#float-double-decimal

Yes, I checked, everything is fine.

2022-01-29 13:35 UTC, merged