Fix(Core/WorldBoss): Azuregos rewrite
azerothcore/azerothcore-wotlk pull request #10369
Opened 2022-01-26 00:06 UTC by Nefertumm

## Changes Proposed:
-  Rewrite the whole fight.
-  Added waypoints and gossip.
-  Added waypoints for Spirit of Azuregos too.
-  Fixed mechanic for Mark of Frost
-  Use the correct Cleave and Arcane Vacuum spell.
-  Use the actual spell for teleporting the players under Azuregos.

## Issues Addressed:

- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/10336
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/10337
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/10175

## SOURCE:

## Tests Performed:

- Tested in-game

## How to Test the Changes:

1. Go Azuregos
2. See his path and check his fight.

## Known Issues and TODO List:

- [ ] Re-do the methods for remove auras based on Winfi's suggestions.
- [ ] ??? 

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

2022-01-26 00:07 UTC, Kitzunu commented on src/server/game/Maps/Map.cpp
> +void Map::RemoveAurasDueToSpellsOnPlayersInZone(std::list<uint32> spellIds, uint32 zoneId /*= 0*/)
can't you just make these two functions to one and allow a list?

2022-01-26 00:07 UTC, Kitzunu commented on src/server/game/Spells/SpellMgr.cpp
> +    ApplySpellFix({ 21147 }, [](SpellEntry* spellInfo)
add comment

2022-01-26 00:08 UTC, Kitzunu commented on src/server/scripts/Kalimdor/boss_azuregos.cpp
>      struct boss_azuregosAI : public ScriptedAI
might as well convert to new system while you rework the entire script :P

2022-01-26 05:02 UTC, Nefertumm commented
Currently waiting for https://github.com/azerothcore/azerothcore-wotlk/pull/10371 to be merged. Do not merge before.

2022-02-07 08:32 UTC, temperrr commented
Tested, 

Works as described

However, not sure if Mark of Frost should be removed after wiping. I can't find proof for it either way

2022-02-07 11:32 UTC, Nyeriah approved these changes

2022-02-09 11:03 UTC, Kitzunu requested changes

2022-02-10 07:51 UTC, Nyeriah commented
@Nefertumm check kitzunu's requests please, gotta merge this saturday

2022-02-10 09:46 UTC, Nefertumm commented
Done

2022-02-10 10:19 UTC, Kitzunu commented on src/server/scripts/Kalimdor/boss_azuregos.cpp
> +        return ValidateSpellInfo({ SPELL_MARK_OF_FROST, SPELL_AURA_OF_FROST, SPELL_MARK_OF_FROST_AURA });
```suggestion
        return ValidateSpellInfo({ SPELL_MARK_OF_FROST, SPELL_AURA_OF_FROST });
```
Only validate spells you use inside the script

2022-02-10 10:19 UTC, Kitzunu commented on src/server/scripts/Kalimdor/boss_azuregos.cpp
> +        return ValidateSpellInfo({ SPELL_ARCANE_VACUUM, SPELL_ARCANE_VACUUM_TP });
here too

2022-02-10 10:37 UTC, Kitzunu approved these changes

2022-02-10 10:51 UTC, merged