feat(Core/Player): Stats limitation
azerothcore/azerothcore-wotlk pull request #10403
Opened 2022-01-28 17:09 UTC by Kitzunu

* cherry-pick commit (https://github.com/TrinityCore/TrinityCore/commit/e18571346400281861490b36c4d35a381bc80dd8)

* closes https://github.com/azerothcore/azerothcore-wotlk/issues/3648

Co-Authored-By: Corbi <12052933+corbi@users.noreply.github.com>

## Changes Proposed:
-  Add option to choose stat limitation if one wants
- Disabled by default

## Issues Addressed:

- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/3648

## SOURCE:

## Tests Performed:

- None

## How to Test the Changes:

1. Enable the config
2. Set the limitation % to what you like
3. See that Crit/Dodge/Parry/Block percentages cannot exceed the limitation

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

2022-01-28 17:16 UTC, Nefertumm approved these changes

2022-01-28 18:56 UTC, Goatform commented
Why not simply set it to `100.0` and in case someone for some reason really wants to apply cap for stat(s) then all they would need to do is decrease the number (enable the cap feature)

2022-01-28 18:58 UTC, acidmanifesto requested changes

2022-01-28 18:58 UTC, acidmanifesto commented on src/server/game/Entities/Unit/StatSystem.cpp
> +        if (sConfigMgr->GetOption<bool>(CONFIG_STATS_LIMITS_ENABLE))
need to add #include "Config.h" to top

2022-01-28 19:20 UTC, Kitzunu commented on src/server/game/Entities/Unit/StatSystem.cpp
> +        if (sConfigMgr->GetOption<bool>(CONFIG_STATS_LIMITS_ENABLE))
ah yea, forgot about that kek

2022-01-29 21:38 UTC, Winfidonarleyan approved these changes

2022-01-30 06:54 UTC, Nyeriah approved these changes

2022-01-31 11:56 UTC, acidmanifesto approved these changes

2022-02-04 16:56 UTC, merged