fix(DB): Tallonkai Swiftroot has incorrect dialogue texts
azerothcore/azerothcore-wotlk pull request #10479
Opened 2022-02-01 18:21 UTC by ZhengPeiRu21

## Changes Proposed:
-  Add missing gossip for Tallonkai Swiftroot

## Issues Addressed:

- Closes #10474

## SOURCE:

## Tests Performed:

- Dialog now appears correct (see attach screenshot)
![Capture](https://user-images.githubusercontent.com/98835050/152027582-c971b8d2-3df5-4b61-89c7-1242400c8e81.PNG)

## How to Test the Changes:

1..go creature 49559
2.Speak with Tallonkai Swiftroot

## Known Issues and TODO List:

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

2022-02-01 18:24 UTC, Kitzunu requested changes
Yo, thanks for the PR!

There are just some small modifications I'd like you to do to keep with code standards and all that fun stuff.
If you'd like to learn more about the SQL code rules we use, you can check out https://www.azerothcore.org/wiki/sql-standards

2022-02-01 18:24 UTC, Kitzunu commented on data/sql/updates/pending_db_world/rev_1643734354433050200.sql
> +WHERE entry = 3567;
Use backticks around the column and table names https://www.azerothcore.org/wiki/sql-standards#general-standards

This line can also be done in one line

2022-02-01 18:24 UTC, Kitzunu commented on data/sql/updates/pending_db_world/rev_1643734354433050200.sql
> +WHERE `ID` = 50032;
make it one line

2022-02-01 18:24 UTC, Kitzunu commented on data/sql/updates/pending_db_world/rev_1643734354433050200.sql
> +  AND `TextID` = 50032;
make this the same line

2022-02-01 18:24 UTC, Kitzunu commented on data/sql/updates/pending_db_world/rev_1643734354433050200.sql
> +VALUES (61026, 50032);
```suggestion
INSERT INTO `gossip_menu` (`MenuID`, `TextID`) VALUES
(61026, 50032);
```

2022-02-01 18:24 UTC, Kitzunu commented on data/sql/updates/pending_db_world/rev_1643734354433050200.sql
> +VALUES ('1643734354433050200');
One line

2022-02-01 18:37 UTC, ZhengPeiRu21 commented
Thank you for the feedbacks! I have updated with the suggested changes.

2022-02-01 18:41 UTC, Kitzunu approved these changes

2022-02-01 19:28 UTC, Nefertumm requested changes

2022-02-01 19:28 UTC, Nefertumm commented on data/sql/updates/pending_db_world/rev_1643734354433050200.sql
> +        NULL, NULL, 0, 0, 0, 0, 0, 0, 0, 0, 0, NULL, NULL, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1);
```suggestion
INSERT INTO `npc_text` (`ID`, `text0_0`, `text0_1`, `BroadcastTextID0`)
VALUES (50032,
        'Well met, $N. It is good to see that $cs like yourself are taking an active part in protecting the groves.',
        'Well met, $N. It is good to see that $cs like yourself are taking an active part in protecting the groves.', 0);
```

2022-02-01 19:50 UTC, Nefertumm approved these changes

2022-02-02 00:33 UTC, Bogir commented
Where did you get `61026 ` number ?
Just last + 1 ?

2022-02-02 00:49 UTC, ZhengPeiRu21 commented
> Where did you get `61026` number ? Just last + 1 ? `50032` the same?

Yes, I am just choose next free ID for both. It is the highest existing ID + 1, except for a few very high outliers. Please let me know if there is another ID that would be better to use. Thank you!

2022-02-02 01:11 UTC, Bogir commented
> > Where did you get `61026` number ? Just last + 1 ? `50032` the same?
> 
> Yes, I am just choose next free ID for both. It is the highest existing ID + 1, except for a few very high outliers. Please let me know if there is another ID that would be better to use. Thank you!

I thought you found the numbers from the original official source.
You acted completely predictably, as the creators of custom dialogs and simple admins of private servers do. But everyone's "last+1" is exactly the one you just used. 
And `DELETE FROM  ...` may cause server error if those Id was allready taken before.

On a good note - we need to document which numbers are reserved for the AС and from which numbers we can start adding texts for "home servers".

This must be documented somehow before merging your PR. 
Let the correct continuous numbering begin with it.

2022-02-02 01:24 UTC, ZhengPeiRu21 commented
> > > Where did you get `61026` number ? Just last + 1 ? `50032` the same?
> > 
> > 
> > Yes, I am just choose next free ID for both. It is the highest existing ID + 1, except for a few very high outliers. Please let me know if there is another ID that would be better to use. Thank you!
> 
> I thought you found the numbers from the original official source. You acted completely predictably, as the creators of custom dialogs and simple admins of private servers do. But everyone's "last+1" is exactly the one you just used. And `DELETE FROM ...` may cause server error if those Id was allready taken before.
> 
> On a good note - we need to document which numbers are reserved for the AС and from which numbers we can start adding texts for "home servers".
> 
> This must be documented somehow before merging your PR. Let the correct continuous numbering begin with it.
> 
> Or, really, use auto-generated abstract number @last + 1 So this will not cause conflicts with any server's taken numbers

Thank you for kindly explaining. Is there any way to find original ID for this text and menu? I do not know if this is record in sniffs and thought all gossip_menu IDs were arbitrary. Thank you for the correction!

2022-02-02 02:43 UTC, Bogir commented
> You are absolutely right that all gossip menu IDs were arbitrary. And very often it causes conflicts on updating live servers. It's time to stop this.

2022-02-02 03:14 UTC, Nefertumm commented
The gossip menu id can be sniffed

2022-02-02 17:15 UTC, ZhengPeiRu21 commented
I have push an update to this branch to also set npcflag to 3 for this NPC, so that gossip will still appear when quest is complete. This is consistent with other NPC that have quest and gossip_menu like Entry 240 (Marshal Dughan).

2022-02-03 05:15 UTC, Bogir commented
> I have push an update to this branch to also set npcflag to 3 for this NPC, so that gossip will still appear when quest is complete. This is consistent with other NPC that have quest and gossip_menu like Entry 240 (Marshal Dughan).

I hope you have not only one enUS client for tests?

2022-02-03 07:51 UTC, Nefertumm commented
It will not show other language than English because there arent broadcast text for those texts yet. They have to be sniffed.

2022-02-03 13:43 UTC, merged

2022-02-03 13:43 UTC, acidmanifesto commented
thank you for hte PR