fix(Scripts/Commands): cs_list commands
azerothcore/azerothcore-wotlk pull request #10480
Opened 2022-02-01 18:44 UTC by IntelligentQuantum

## Changes Proposed:
-  
-  

## Issues Addressed:

- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/10477

## SOURCE:

## Tests Performed:

- Not-Tested
- 

## How to Test the Changes:

1.
2.
3.

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

2022-02-01 18:54 UTC, Kitzunu requested changes
should probably check for id2 and id3 as well :)

2022-02-01 19:29 UTC, Nefertumm approved these changes

2022-02-03 16:15 UTC, Nyeriah commented
Hey, any luck with this? You can't teleport to creatures without this command at all, very difficult

2022-02-03 17:20 UTC, IntelligentQuantum commented
> Hey, any luck with this? You can't teleport to creatures without this command at all, very difficult

.list crea xxx - works fine, for other ids idk how can i do it.

2022-02-03 17:38 UTC, Nyeriah commented
> > Hey, any luck with this? You can't teleport to creatures without this command at all, very difficult
> 
> .list crea xxx - works fine, for other ids idk how can i do it.

change the query so it's

SELECT ... FROM creature WHERE id1 = XX OR Id2 = XX OR id3 = XX

2022-02-04 21:43 UTC, Kitzunu approved these changes

2022-02-05 10:44 UTC, Nyeriah commented
Conflicts here

2022-02-05 14:31 UTC, Kitzunu commented on src/server/scripts/Commands/cs_list.cpp
> +                                          uint32(creatureId), uint32(creatureId), uint32(creatureId)count);
```suggestion
                                          uint32(creatureId), uint32(creatureId), uint32(creatureId), count);
```

2022-02-05 17:43 UTC, merged