fix(Scripts/AlteracValley): Mini bosses should evade with boss.
azerothcore/azerothcore-wotlk pull request #10544
Opened 2022-02-05 16:53 UTC by UltraNix

Fixed #10460

## Issues Addressed:

- Closes #10460
- Closes https://github.com/chromiecraft/chromiecraft/issues/2897

## Tests Performed:

- Not tested.

## How to Test the Changes:

Need more people for this, can't reproduce it solo on local AC prob
Pull one of adds
Get out of range carefully, use spells like vanish, FD when you have aggro on boss
Boss resets and his adds reset as well.

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

2022-02-18 12:40 UTC, temperrr commented
Tested:

I can still pull with hunter, taunt boss with tank, drop aggro on hunter , adds go back, boss stays.

2022-02-20 19:57 UTC, UltraNix commented
Closes as it's not a bug.

2022-02-21 09:53 UTC, temperrr commented
Reopening as it is a bug.

2022-02-26 10:45 UTC, temperrr commented
Tested:

![image](https://user-images.githubusercontent.com/20357406/155840289-db453dde-2660-476c-8b2e-1166e06dda4e.png)


how: only target the main boss, the rest is not tied to it.

2022-02-26 10:48 UTC, UltraNix commented
But you are testing something that is not related to the reported issue and it's not covered by this PR.

2022-02-26 10:53 UTC, UltraNix commented
@temperrr Try again please.

2022-02-26 10:56 UTC, temperrr commented
Fair enough, I was under the impression it would fix both. My bad on that. I'll test tomorrow again!

2022-02-27 07:16 UTC, temperrr commented
When pulling server crashed with this in log:
zsh: segmentation fault (core dumped)  ./worldserver

2022-02-27 10:33 UTC, UltraNix commented
@temperrr Do you have crashlog?

2022-02-27 11:20 UTC, temperrr commented
That was all that was in it

2022-02-27 11:36 UTC, UltraNix commented
Is your core built in `RelWitDebInfo` mode?

2022-02-27 12:12 UTC, temperrr commented
yes trying again

2022-02-27 12:18 UTC, temperrr commented
zsh: segmentation fault (core dumped)  ./worldserver

2022-02-27 12:19 UTC, temperrr commented
![image](https://user-images.githubusercontent.com/20357406/155882002-a961f950-fe56-4841-90de-bdce2f480c98.png)

2022-02-27 12:36 UTC, UltraNix commented
@temperrr You are trying to kill/aggro/evade alliance or horde boss/mini bosses?

2022-02-27 12:43 UTC, temperrr commented
Alliance one, I shoot afireball at m, then I get the aggro lines and crash

2022-02-27 12:57 UTC, UltraNix commented
@temperrr Try now.

2022-03-01 11:58 UTC, temperrr commented
Same thing :/

2022-03-05 09:52 UTC, UltraNix commented
@temperrr Just attacked alliance mini boss - no crash.

2022-03-05 10:31 UTC, temperrr commented
Ok then I am happy

2022-03-05 10:31 UTC, UltraNix commented
@temperrr So it's okay now?

2022-03-06 17:10 UTC, acidmanifesto commented
![image](https://user-images.githubusercontent.com/16887899/156933852-cd8de80c-1f05-4b0b-ad21-2128bb39c31f.png)

2022-03-06 17:11 UTC, acidmanifesto requested changes

2022-03-06 17:11 UTC, acidmanifesto commented on src/server/scripts/EasternKingdoms/AlteracValley/boss_vanndar.cpp
> +        void AttackStart(Unit* victim) override
![image](https://user-images.githubusercontent.com/16887899/156933876-d1405c65-e450-41c2-aa51-d492718ccbd2.png)

2022-03-06 18:50 UTC, acidmanifesto approved these changes

2022-03-10 12:56 UTC, merged