fix(Scripts/Items): Fix Goblin Bomb Dispenser
azerothcore/azerothcore-wotlk pull request #10612
Opened 2022-02-09 21:47 UTC by ZhengPeiRu21

## Changes Proposed:
-  Script was existing but missing malfunction explosion chance and was not assigned correctly
- Some NPC values were incorrect; these are now fixed
- All values are from TrinityCore: https://github.com/TrinityCore/TrinityCore/pull/27749

## Issues Addressed:

- Closes unreported issue

## SOURCE:

TrinityCore: https://github.com/TrinityCore/TrinityCore/pull/27749

## Tests Performed:

Summon appears:
![Capture](https://user-images.githubusercontent.com/98835050/153295531-5434581f-15d3-4ad3-8ed8-4c3a80bd0939.PNG)

Attacks nearest target, explodes then dies:
![Capture2](https://user-images.githubusercontent.com/98835050/153295566-fd45961a-a95b-4205-be97-4d962724eca2.PNG)

Malfunction Explosion working:
![Capture3](https://user-images.githubusercontent.com/98835050/153295589-93e6cc16-08da-45d4-ae2f-1658a9958971.PNG)

## How to Test the Changes:

1. .additem 10587
2. Test if it is working

## Known Issues and TODO List:

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

2022-02-09 22:37 UTC, acidmanifesto approved these changes

2022-02-14 06:55 UTC, IntelligentQuantum requested changes

2022-02-14 06:55 UTC, IntelligentQuantum commented on src/server/scripts/Spells/spell_item.cpp
> +            caster->CastSpell(caster, roll_chance_i(95) ? SPELL_SUMMON_GOBLIN_BOMB : SPELL_MALFUNCTION_EXPLOSION, true, GetCastItem());
Bracket

2022-04-02 16:22 UTC, Lynethris commented
Need a test or is it in WIP ?

2022-04-02 16:48 UTC, IntelligentQuantum commented
@Lynethris Test please

2022-04-04 18:35 UTC, ZhengPeiRu21 commented
> Need a test or is it in WIP ?

Sorry for the slow responding. Yes, please test - this is complete (unless any bug are found ^_^).

2022-04-05 01:50 UTC, porkserver commented
Tested working
Bomb summons and attacks target and dies/despawns - screenshot shows cooldown active and combat log
![Screen Shot 2022-04-04 at 8 48 37 PM](https://user-images.githubusercontent.com/273302/161663413-460039b5-60f4-4c0c-b110-f1ca32135750.png)
.

2022-04-07 15:30 UTC, acidmanifesto commented
@IntelligentQuantum Are the current changes to your liking so we can merge?

2022-04-08 05:50 UTC, IntelligentQuantum approved these changes

2022-04-09 15:37 UTC, acidmanifesto commented
Thank you for the PR

2022-04-09 15:37 UTC, merged