fix(Core/Spells): Azuregos' Mana Storm should not be interruptable
azerothcore/azerothcore-wotlk pull request #10721
Opened 2022-02-17 21:10 UTC by Nefertumm

## Changes Proposed:
-  Remove interrupt flags from spell.

## Issues Addressed:

- Closes https://github.com/chromiecraft/chromiecraft/issues/3058

## SOURCE:

## Tests Performed:

- Tested in-game

## How to Test the Changes:

1. Go Azuregos, engage. (.go c id 6109)
2. Try to interrupt Mana Storm.

2022-02-17 21:13 UTC, acidmanifesto approved these changes

2022-02-19 06:59 UTC, IntelligentQuantum approved these changes

2022-02-19 17:09 UTC, Kitzunu requested changes

2022-02-19 17:09 UTC, Kitzunu commented on src/server/game/Spells/SpellInfoCorrections.cpp
> +    // Mana Storm
```suggestion
    // Manastorm
```

2022-02-19 21:29 UTC, Kitzunu approved these changes

2022-02-22 04:23 UTC, merged