Fix event 85 AND Fix Error in #10124
azerothcore/azerothcore-wotlk pull request #10920
Opened 2022-03-07 04:15 UTC by pklloveyou

## Changes Proposed:
-  
-  

## Issues Addressed:

- Error in #10124
- 
- ```.eve s 85 ```
- Error in #6298
- 
- Wrong SQL changes, I can't restore.
- This is only a code repair. If you want to repair them completely, you need to restore some relevant database changes.

## SOURCE:

## Tests Performed:

- 
- 

## How to Test the Changes:

1.
2.
3.

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

2022-03-08 14:41 UTC, pklloveyou commented on src/server/game/AI/SmartScripts/SmartScript.cpp
> +                // xinef: my addition
This code is from the old Sunwell
In event 85, it is required, otherwise the event will not work properly

2022-03-08 14:42 UTC, pklloveyou commented on src/server/game/AI/SmartScripts/SmartScript.cpp
> +                // xinef: my addition
It was deleted in #6298

2022-03-08 14:46 UTC, acidmanifesto requested changes

2022-03-08 14:46 UTC, acidmanifesto commented on src/server/game/AI/SmartScripts/SmartScript.cpp
> +                // xinef: my addition
now when u mention event, do u mean smart event or game event? I want to look this up to ensure i got a full idea of the issue and the pr?

2022-03-08 14:58 UTC, pklloveyou commented
(85, '2011-03-22 01:00:00', '2030-12-31 07:00:00', 5184000, 35, 0, 0, 'Stitches Event', 0, 2), This event

2022-03-08 15:02 UTC, pklloveyou commented
![image](https://user-images.githubusercontent.com/18535853/157264489-7e9263d0-758e-4bfb-aa6a-f6b65c037bc4.png)

2022-03-08 15:22 UTC, acidmanifesto commented
> ![image](https://user-images.githubusercontent.com/18535853/157264489-7e9263d0-758e-4bfb-aa6a-f6b65c037bc4.png)

Thank you for the details. I truely appreciate it. I am testing something on my locale that may resolve the issue while not reverting anything. Please give me some time to explore this route first before i discuss it further with staff.

2022-03-08 16:07 UTC, acidmanifesto commented
@pklloveyou can you please test my PR https://github.com/azerothcore/azerothcore-wotlk/pull/10939 and see if it works for you now for event 85.

2022-03-09 05:17 UTC, pklloveyou commented
#10939 The problem has been solved

2022-03-09 05:17 UTC, closed without merging