Operation: Gnomeregan! [v2]
azerothcore/azerothcore-wotlk pull request #10983
Opened 2022-03-12 14:18 UTC by FALL1N1

## CHANGES PROPOSED:
-  Script the entire chain

## ISSUES ADDRESSED:
- Closes #1688

## TESTS PERFORMED: 
- [Q:25229] A Few Good Gnomes https://youtu.be/-e0h53Y55rI
- [Q:25199] Basic Orders https://youtu.be/uex8-nRpgbw
- [Q:25285] In and Out https://youtu.be/91jFSsTC9U0
- [Q:25289] One Step Forward... https://youtu.be/pzJbTsxhmwU
- [Q:25295] Press Fire https://youtu.be/b_DAifd4uxo
- [Q:25283] Prepping the Speech https://youtu.be/YXvl6X3D_nA
- [Q:25393] Operation: Gnomeregan! https://youtu.be/tCm26NzjNUw

## HOW TO TEST THE CHANGES:

Grab a drink/snack and have fun.

***Note:*** You may have to re-cmake it since we are adding a new folder in the source @ EasternKingdoms scriptfolder.

## KNOWN ISSUES AND TODO LIST:

None that I know of.
- Visuals
- Texts

(for which we need sniffs or HD videos to script them off from)

## Target branch(es):
- [x] Master

 
## How to test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here in the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

2022-03-12 14:18 UTC, FALL1N1 commented
still a WIP, so do not merge, ty

2022-03-12 14:28 UTC, Nyeriah commented on src/server/scripts/EasternKingdoms/OperationGnomeregan/operation_gnomeregan.cpp
> +                    case 71:
what is this?

2022-03-12 14:29 UTC, Nyeriah commented on src/server/scripts/EasternKingdoms/OperationGnomeregan/operation_gnomeregan.h
> +#define MEK_1_1                 "Citizens and Friends of Gnomeregan!"
all of  this should be written in proper creature_text/gossip/whatever entries and not hardcoded

2022-03-12 14:30 UTC, Nyeriah commented on src/server/scripts/EasternKingdoms/OperationGnomeregan/operation_gnomeregan.cpp
> +        void Reset()
code style here is broken

2022-03-12 14:32 UTC, Nyeriah commented
Hey,

Don't mind me asking, but did you write this yourself or did you cherry-pick it from somewhere?

2022-03-12 14:38 UTC, acidmanifesto requested changes

2022-03-12 14:38 UTC, acidmanifesto commented on data/sql/updates/pending_db_world/rev_1647094527133522600.sql
> +UPDATE `creature_template` SET `spell1` = 74153, `spell2` = 0, `spell3` = 0, `spell4` = 0 WHERE `entry` = 39682;
We do not have a spell1, spell2, spell3, spell4 collumn

2022-03-12 14:40 UTC, FALL1N1 commented
Guys, please do not comment on the code yet, this is still a WIP and a backport of the old PR here https://github.com/azerothcore/azerothcore-wotlk/pull/3678

A lot of things has to be rewritten - I know, I am working on it as we speak.


As of the original code - no, it is not known, if the author recognizes himself - feel free to add appropriate credits.
I am rewriting it to the AC standards as well as adding misc data like gobjects, npcs etc that I managed to scrap out of some sniffs.

2022-03-12 14:45 UTC, acidmanifesto commented
> Guys, please do not comment on the code yet, this is still a WIP and a backport of the old PR here #3678
> 
> A lot of things has to be rewritten - I know, I am working on it as we speak.
> 
> As of the original code - no, it is not known, if the author recognizes himself - feel free to add appropriate credits. I am rewriting it to the AC standards as well as adding misc data like gobjects, npcs etc that I managed to scrap out of some sniffs.
> 
> I will let you know once everything is ready to be reviewed or tested.

I am not trying to sound harsh on the matter. but ensure it is worked out on your local before pushing to a pr, as we got run times that could be used for other critical things at the moment.

2022-03-12 15:12 UTC, Nyeriah commented
> Guys, please do not comment on the code yet, this is still a WIP and a backport of the old PR here #3678
> 
> A lot of things has to be rewritten - I know, I am working on it as we speak.
> 
> As of the original code - no, it is not known, if the author recognizes himself - feel free to add appropriate credits. I am rewriting it to the AC standards as well as adding misc data like gobjects, npcs etc that I managed to scrap out of some sniffs.
> 
> I will let you know once everything is ready to be reviewed or tested.

Thanks for the answer. Could you tell us where you got this code from? There were incidents in the past of repositories being taken down by DMCA claims so we should be extra careful when cherry-picking code from closed sources, so we don't end up having issues ourselves. Thanks for your contribution though.

2022-03-12 15:35 UTC, FALL1N1 commented
@acidmanifesto All good, do not worry.  I push changes only when it's ready to be tested, I'm quite aware.

@Nyeriah the code was from the comments on the original issue, although the comment seems no longer available. After a quick search I managed to find some example ones:
https://github.com/Desch/MythCore
https://github.com/mynew4/pvelich
https://github.com/artkeep/trinity

None of which are the original author, it's publicly available on GitHub as well as BitBucket so I doubt we'd get DMCA because of it.

2022-03-12 15:39 UTC, acidmanifesto commented
> @acidmanifesto All good, do not worry. I push changes only when it's ready to be tested, I'm quite aware. The PR is just a placeholder so anyone with sniffs/information about the event itself can share and eventually get it as close to blizzlike as possible.
> 
> @Nyeriah the code was from the comments on the original issue, although the comment seems no longer available. After a quick search I managed to find some example ones: https://github.com/Desch/MythCore https://github.com/mynew4/pvelich https://github.com/artkeep/trinity
> 
> None of which are the original author, it's publicly available on GitHub as well as BitBucket so I doubt we'd get DMCA because of it.

original orgins was found. am waiting for a bit of information on the particular it originated from as it was a former pserver core from 2012. 

So until i hear further if it was a authorized release or not i went ahead and edited in the body of the pr the appropiate credits 
Cherry-Picked: https://github.com/rebirth-core/Rebirth---WoW/commit/4342a1061984330d1e0687cb4e355afcc33248eb
Co-Authored-By: [PatrickFarnkopfOld](https://github.com/rebirth-core/Rebirth---WoW/commits?author=PatrickFarnkopfOld)
Co-Authored-By: [FrEdDy32](https://github.com/FrEdDy32)
Co-Authored-By:[Nebukad](https://github.com/Nebukad)
Co-Authored-By:[rbkai](https://github.com/rbkai)

2022-03-14 02:29 UTC, FALL1N1 commented
still a WIP, I will update once it's ready to be tested...

2022-06-18 12:55 UTC, acidmanifesto commented
What is the current status of this? Is it abandoned?

2022-06-18 14:27 UTC, FALL1N1 commented
> What is the current status of this? Is it abandoned?

not really, I'm still gathering data for the last quest (gameobjects, texts..etc)

2022-07-10 18:48 UTC, acidmanifesto commented
Its been about 22 days since last response, and close to 3 months since last movement, is this PR abandon? If not then please fetch a upstream. If not it will be marked abandoned and closed.

2022-07-11 00:31 UTC, FALL1N1 commented
> Its been about 22 days since last response, and close to 3 months since last movement, is this PR abandon? If not then please fetch a upstream. If not it will be marked abandoned and closed.

will do tomorrow, also push the rest of the things that are now fixed

2022-07-26 14:46 UTC, acidmanifesto commented
Marked as abandon.

2022-07-26 14:46 UTC, closed without merging