fix(DB/smart_scripts): Fix Quest: Raze Direhorn Post!
azerothcore/azerothcore-wotlk pull request #10985
Opened 2022-03-12 15:14 UTC by Kosiak

## Changes Proposed:
-  Rewrite smart scripts to spawn flames gameobject on torch use, give kill credit, and despawn flames after 60s.

## Issues Addressed:

- Closes  [[Dustwallow Marsh / Quest: Raze Direhorn Post!] Tents don't catch on fire. #3093](https://github.com/chromiecraft/chromiecraft/issues/3093)

## SOURCE:

## Tests Performed:
Using [Tabetha's Torch](https://tbc.wowhead.com/item=33072/tabethas-torch)  will now set tents on fire.

## How to Test the Changes:

1. Accept quest [Raze Direhorn Post!](https://tbc.wowhead.com/quest=11150/raze-direhorn-post)
2. Use torch on tents.
3. Gives kill credit and sets tents on fire

## Known Issues and TODO List:

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

2022-03-12 15:29 UTC, Kitzunu requested changes
Yo, thanks for the PR.

Please take a minute to read https://www.azerothcore.org/wiki/sql-standards and edit your SQL file accordingly

2022-03-12 16:02 UTC, Kosiak commented
> Yo, thanks for the PR.
> 
> Please take a minute to read https://www.azerothcore.org/wiki/sql-standards and edit your SQL file accordingly

I have no idea whats wrong :d my last sql encounter was 10+ years ago and this is my first ever 2 pr requests. I would assume i dont need acore.world infront smart scripts and what else? Thank you

2022-03-23 17:31 UTC, Lynethris commented
Tested and work.

2022-03-24 10:00 UTC, Winfidonarleyan approved these changes

2022-03-27 04:25 UTC, merged