[WIP] QAston Proc System
azerothcore/azerothcore-wotlk pull request #11079
Opened 2022-03-19 08:37 UTC by IntelligentQuantum

## Changes Proposed:
-  
-  

## Issues Addressed:

- Closes 

## SOURCE:

## Tests Performed:

- 
- 

## How to Test the Changes:

1.
2.
3.

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

2022-03-31 12:27 UTC, temperrr commented
Please tell us how to test it before marking it "waiting to be tested" Thanks!

2022-03-31 18:26 UTC, Lynethris commented
Error during the build:

![Screenshot 2022-03-31 202543](https://user-images.githubusercontent.com/100411212/161124628-23724521-a913-4282-9b50-ba497c39a99d.png)

2022-04-04 04:38 UTC, IntelligentQuantum commented
@Lynethris Test Please

2022-04-04 09:17 UTC, temperrr commented
Breaks eluna

```
In file included from /mnt/data/azerothcore/modules/mod-eluna/src/LuaEngine/LuaFunctions.cpp:23:
/mnt/data/azerothcore/modules/mod-eluna/src/LuaEngine/UnitMethods.h:2827:24: fatal error: no matching constructor for initialization of 'DamageInfo'
            DamageInfo dmgInfo(unit, target, damage, nullptr, schoolmask, SPELL_DIRECT_DAMAGE);
                       ^       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/mnt/data/azerothcore/src/server/game/Entities/Unit/Unit.h:766:5: note: candidate constructor not viable: requires 4 arguments, but 6 were provided
    DamageInfo(SpellNonMeleeDamage const& spellNonMeleeDamage, DamageEffectType damageType, WeaponAttackType attackType, uint32 hitMask);
    ^
/mnt/data/azerothcore/src/server/game/Entities/Unit/Unit.h:764:5: note: candidate constructor not viable: requires at least 7 arguments, but 6 were provided
    DamageInfo(Unit* attacker, Unit* victim, uint32 damage, SpellInfo const* spellInfo, SpellSchoolMask schoolMask, DamageEffectType damageType, WeaponAttackType attackType, uint32 cleanDamage = 0);
    ^
/mnt/data/azerothcore/src/server/game/Entities/Unit/Unit.h:765:14: note: candidate constructor not viable: requires single argument 'dmgInfo', but 6 arguments were provided
    explicit DamageInfo(CalcDamageInfo& dmgInfo);
             ^
/mnt/data/azerothcore/src/server/game/Entities/Unit/Unit.h:748:7: note: candidate constructor (the implicit copy constructor) not viable: requires 1 argument, but 6 were provided
class DamageInfo
      ^
/mnt/data/azerothcore/src/server/game/Entities/Unit/Unit.h:748:7: note: candidate constructor (the implicit move constructor) not viable: requires 1 argument, but 6 were provided
2 warnings and 1 error generated.
```

Testing further without eluna bit this need fix

2022-04-04 09:24 UTC, temperrr commented
Breaks Eluna
```
In file included from /mnt/data/azerothcore/modules/mod-eluna/src/LuaEngine/LuaFunctions.cpp:23:
/mnt/data/azerothcore/modules/mod-eluna/src/LuaEngine/UnitMethods.h:2827:24: fatal error: no matching constructor for initialization of 'DamageInfo'
            DamageInfo dmgInfo(unit, target, damage, nullptr, schoolmask, SPELL_DIRECT_DAMAGE);
                       ^       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/mnt/data/azerothcore/src/server/game/Entities/Unit/Unit.h:766:5: note: candidate constructor not viable: requires 4 arguments, but 6 were provided
    DamageInfo(SpellNonMeleeDamage const& spellNonMeleeDamage, DamageEffectType damageType, WeaponAttackType attackType, uint32 hitMask);
    ^
/mnt/data/azerothcore/src/server/game/Entities/Unit/Unit.h:764:5: note: candidate constructor not viable: requires at least 7 arguments, but 6 were provided
    DamageInfo(Unit* attacker, Unit* victim, uint32 damage, SpellInfo const* spellInfo, SpellSchoolMask schoolMask, DamageEffectType damageType, WeaponAttackType attackType, uint32 cleanDamage = 0);
    ^
/mnt/data/azerothcore/src/server/game/Entities/Unit/Unit.h:765:14: note: candidate constructor not viable: requires single argument 'dmgInfo', but 6 arguments were provided
    explicit DamageInfo(CalcDamageInfo& dmgInfo);
             ^
/mnt/data/azerothcore/src/server/game/Entities/Unit/Unit.h:748:7: note: candidate constructor (the implicit copy constructor) not viable: requires 1 argument, but 6 were provided
class DamageInfo
      ^
/mnt/data/azerothcore/src/server/game/Entities/Unit/Unit.h:748:7: note: candidate constructor (the implicit move constructor) not viable: requires 1 argument, but 6 were provided
2 warnings and 1 error generated.```

2022-04-04 09:33 UTC, temperrr commented
Stormstrike (shaman talent) nature increased damage taken does not get used by shaman nature ability (example: earth shock, lightning bolt)

2022-04-04 10:59 UTC, IntelligentQuantum commented
> Breaks Eluna
> 
> ```
> In file included from /mnt/data/azerothcore/modules/mod-eluna/src/LuaEngine/LuaFunctions.cpp:23:
> /mnt/data/azerothcore/modules/mod-eluna/src/LuaEngine/UnitMethods.h:2827:24: fatal error: no matching constructor for initialization of 'DamageInfo'
>             DamageInfo dmgInfo(unit, target, damage, nullptr, schoolmask, SPELL_DIRECT_DAMAGE);
>                        ^       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> /mnt/data/azerothcore/src/server/game/Entities/Unit/Unit.h:766:5: note: candidate constructor not viable: requires 4 arguments, but 6 were provided
>     DamageInfo(SpellNonMeleeDamage const& spellNonMeleeDamage, DamageEffectType damageType, WeaponAttackType attackType, uint32 hitMask);
>     ^
> /mnt/data/azerothcore/src/server/game/Entities/Unit/Unit.h:764:5: note: candidate constructor not viable: requires at least 7 arguments, but 6 were provided
>     DamageInfo(Unit* attacker, Unit* victim, uint32 damage, SpellInfo const* spellInfo, SpellSchoolMask schoolMask, DamageEffectType damageType, WeaponAttackType attackType, uint32 cleanDamage = 0);
>     ^
> /mnt/data/azerothcore/src/server/game/Entities/Unit/Unit.h:765:14: note: candidate constructor not viable: requires single argument 'dmgInfo', but 6 arguments were provided
>     explicit DamageInfo(CalcDamageInfo& dmgInfo);
>              ^
> /mnt/data/azerothcore/src/server/game/Entities/Unit/Unit.h:748:7: note: candidate constructor (the implicit copy constructor) not viable: requires 1 argument, but 6 were provided
> class DamageInfo
>       ^
> /mnt/data/azerothcore/src/server/game/Entities/Unit/Unit.h:748:7: note: candidate constructor (the implicit move constructor) not viable: requires 1 argument, but 6 were provided
> 2 warnings and 1 error generated. 
> ```
> 
> and warnings:
> 
> ![image](https://user-images.githubusercontent.com/20357406/161514943-e97f8f19-44c0-4389-b31f-215c53feed22.png)

I know warnings and eluna are not important right now

2022-04-04 13:30 UTC, temperrr commented
warrior: Talent sword and broad does not refresh shield slam cooldown when on cooldown:

2022-04-06 05:50 UTC, IntelligentQuantum commented
@temperrr Is there another problem?

2022-04-06 07:42 UTC, temperrr commented
We are still testing other classes

2022-04-06 09:01 UTC, Lynethris commented
I will start this afternoon to test priest, mage and warlock. Sorry, I wanted to finish before "Implementation save instance gameobject".

2022-04-06 09:04 UTC, temperrr commented
Druid:

Balance:
Improved Faerie fire extra crit and hit chance does not seem to work? (no entry in list aura)
nature's grace does not trigger
Eclipse does not trigger

Feral:
Improved Leader of Pack does not give mana or hp.

Warlock:

Demonic Pact is applying on every hit instead of every crit from pet.
Molten Core does not proc of corruption

2022-04-08 05:09 UTC, Lynethris commented
-Priest: 
Shadow talent: Shadow weaving - Doesn’t proc

Mage: All seems work.

2022-04-11 18:26 UTC, Lynethris commented
DK Seems good too

2022-05-16 08:04 UTC, temperrr commented
Whats the status? :)

2022-05-16 08:06 UTC, IntelligentQuantum commented
I will work on this on Friday

2022-06-18 12:58 UTC, acidmanifesto commented
What is the current status of this? Is it abandoned?

2022-06-19 03:44 UTC, IntelligentQuantum commented
> What is the current status of this? Is it abandoned?

Nope

2022-08-31 15:48 UTC, DavuKnight commented
Currently tagged as "Waiting to be Tested"
But there are no testing steps and there are conflicts
Should this be moved to WIP instead?

2022-08-31 18:34 UTC, Maelthyrr commented
You can look above for tests. But globaly, need to check every spells and talents. It's a global system. You don't have standard progress to test it.

Merge conflicts should be for the merge on master branch. With the standard process, it should be fine. If You have an issue reply here for an update.

2022-09-16 05:50 UTC, Maelthyrr commented
@IntelligentQuantum I had to recompile but now I got merge conflicts. Could you update this to finish my test ?

2022-09-16 08:49 UTC, IntelligentQuantum commented
@Maelthyrr Done

2022-09-17 07:05 UTC, Maelthyrr commented
Strange I got many issues with the sql querie: 
- Duplicate entry '71201-spell_igb_battle_experience_check' for key 'spell_script_names.spell_id'
- Some columns unknow in spell_procs: typemask, ratePerMinute... and

2022-09-18 05:48 UTC, IntelligentQuantum commented
> Strange I got many issues with the sql querie (I've drop my db before):
> 
>     * Duplicate entry '71201-spell_igb_battle_experience_check' for key 'spell_script_names.spell_id'
> 
>     * Some columns unknow in spell_procs: typemask, ratePerMinute...

@Maelthyrr Done

2022-09-18 08:09 UTC, Maelthyrr commented
@IntelligentQuantum tested redone, and I've compare to CC PTR to be sure that it's related to this PR:

Some worlserver errors: 
- [ ] AuraEffect::HandleProcTriggerSpellAuraProc: Could not trigger spell 0 from aura 24932 proc, because the spell does not have an entry in Spell.dbc.
- [ ] AuraEffect::HandleProcTriggerSpellAuraProc: Could not trigger spell 0 from aura 48525 proc, because the spell does not have an entry in Spell.dbc.

Warlock issues:
- [ ] Molten core (talent) can proc without corruption
- [ ] Demonic Pact doesn't proc on a crit pet

Druid:
- [ ] Nature Grace doesn't proc (balance talent)
- [ ] Eclispe doesn't proc (balance talent)
- [ ] Improve faerie doesn't work (balance talent)
- [ ] Improve Leader of Pack does not give mana or hp (feral talent)

Shaman:
- [ ] Stormstrike doesn't apply damage bonus from elemental spells

2022-09-18 10:56 UTC, IntelligentQuantum commented
> @IntelligentQuantum tested redone, and I've compare to CC PTR to be sure that it's related to this PR: Almost same issues than before.
> 
> Some worlserver errors:
> 
>     * [ ]  AuraEffect::HandleProcTriggerSpellAuraProc: Could not trigger spell 0 from aura 24932 proc, because the spell does not have an entry in Spell.dbc.
> 
>     * [ ]  AuraEffect::HandleProcTriggerSpellAuraProc: Could not trigger spell 0 from aura 48525 proc, because the spell does not have an entry in Spell.dbc.
> 
> 
> Warlock issues:
> 
>     * [ ]  Molten core (talent) can proc without corruption
> 
>     * [ ]  Demonic Pact doesn't proc on a crit pet
> 
> 
> Druid:
> 
>     * [ ]  Nature Grace doesn't proc (balance talent)
> 
>     * [ ]  Eclispe doesn't proc (balance talent)
> 
>     * [ ]  Improve faerie doesn't work (balance talent)
> 
>     * [ ]  Improve Leader of Pack does not give mana or hp (feral talent)
> 
> 
> Shaman:
> 
>     * [ ]  Stormstrike doesn't apply damage bonus from elemental spells
> 
> 
> Paladin:
> 
>     * [ ]  Sacred shield aura will kill the player if he takes damage
> 
> 
> Otherwise any new issues find.

These bugs will be fixed in the new PRS.

Now this PR needs a code review, and if there is a specific problem, it should be fixed and merged quickly

Please spend time on this if you have time @Nefertumm

2022-09-18 12:08 UTC, Kitzunu commented
yea impossible to fix all the issues in one PR. 

Pro's: We get a new updated good system
Con's: We will get some broken spells.

But that is well worth it.

2022-09-18 12:09 UTC, Kitzunu commented on src/server/scripts/Outland/boss_doomlord_kazzak.cpp
> +    new spell_twisted_reflection();
RegisterSpellScript

2022-09-18 12:09 UTC, Kitzunu approved these changes

2022-09-18 17:52 UTC, Nefertumm commented
Fix the startup errors and check the codestyle task, once the tasks pass, I'll make a review

2022-09-19 08:05 UTC, IntelligentQuantum commented
:| AGAIN CONFLICT

2022-09-19 11:44 UTC, IntelligentQuantum commented
@Nefertumm Done

2022-09-21 12:34 UTC, acidmanifesto commented
Re-running workflow due to failure being unrelated to this PR

2022-09-21 16:00 UTC, acidmanifesto requested changes
certain modules will need to be checked as workflow points them out
![image](https://user-images.githubusercontent.com/16887899/191553788-a48e5d1a-a1c1-4988-91ac-6aea365de34d.png)

2022-09-21 16:00 UTC, acidmanifesto commented
merge conflict

2022-09-23 20:11 UTC, acidmanifesto approved these changes

2022-10-01 20:31 UTC, Kitzunu commented
conflicts

2022-10-02 17:39 UTC, merged

2022-10-04 16:53 UTC, Yehonal commented
Does it also close it? https://github.com/azerothcore/azerothcore-wotlk/issues/4209