fix(DB/Locale): Creature: Nayura
azerothcore/azerothcore-wotlk pull request #11355
Opened 2022-04-11 05:59 UTC by Tony931023

Description:

The proper quote is not written on this NPC. She quotes, which seems to be post-Cataclysm:

    From this dock, The Bravery travels back and forth between Stormwind and Rut'theran Village.

Expected behaviour:

According to [Wowpedia](https://wow.gamepedia.com/Nayura), the proper quote is:

    From this dock, The Bravery travels back and forth between Stormwind and Auberdine.

## SOURCE:
TC: https://github.com/TrinityCore/TrinityCore/issues/24972

## How to Test the Changes:

- .go creature id 28650

- Interact with her.

2022-04-21 03:40 UTC, Tony931023 commented
@fputs changes are only applied to translations in frFR,esS,esMX,zhCN,deDE not in enUS

2022-04-21 09:06 UTC, Lynethris commented
> @fputs changes are only applied to translations in frFR,esS,esMX,zhCN,deDE not in enUS

Why not add this in enUS?

2022-04-21 11:54 UTC, Tony931023 commented
Yes, the error is found in broadcast_text and broadcast_text_locale later I make the changes
```sql
SELECT * FROM `broadcast_text` WHERE `ID` = 28636 ;
```
```sql
SELECT * FROM `broadcast_text_locale` WHERE `ID` = 28636 ;
```

2022-04-21 13:07 UTC, Kitzunu commented
Never change any broadcast_text table.

2022-04-21 14:38 UTC, Bogir commented
If `creature_text (_locale)`, `npc_text (_locale), `gossip_menu_option (_locale) has value in `BroadcastTextID` - all texts in those tables can be safely removed. Now is the same case.

I think the PRs like this brings nothing useful.

2022-04-21 14:48 UTC, Kitzunu commented
I will not explain again what the use of it is.

2022-04-21 15:16 UTC, Bogir commented
> I will not explain again what the use of it is.

Useful? No! They do not always match the sniffed texts, and sometimes invented.
Those texts on such a scale are not exact duplicates and only harm the database optimization.
Other tables are not using duplecates of texts, only ID as key. Why are these tables still an exception?
The id as key is enough for the core.

2022-04-22 16:22 UTC, Tony931023 commented
**broadcast_text** since it cannot be modified to correct it in English and you want to have it corrected in your core, execute this Update in your world database
```sql
UPDATE `broadcast_text` SET `FemaleText` = 'From this dock, The Bravery travels back and forth between Stormwind and Auberdine.' WHERE `ID` = 28636;
```

2022-04-23 17:31 UTC, Tony931023 commented
@Lynethris this is ready to review

2022-05-08 21:41 UTC, Kitzunu requested changes

2022-05-08 21:41 UTC, Kitzunu commented on data/sql/updates/pending_db_world/rev_1649656477945100427.sql
> +(28636,"deDE","","Von diesem Dock aus fährt die Bravado zwischen Sturmwind und Auberdine hin und her.",18019);
Remove this.

2022-06-18 13:00 UTC, acidmanifesto requested changes

2022-06-18 13:00 UTC, acidmanifesto commented on data/sql/updates/pending_db_world/rev_1649656477945100427.sql
> +INSERT INTO `version_db_world` (`sql_rev`) VALUES ('1649656477945100427');
remove this link

2022-06-18 18:07 UTC, acidmanifesto approved these changes

2022-06-18 18:07 UTC, acidmanifesto commented
@Kitzunu is there anything else needed to be done with this pr?

2022-07-08 05:17 UTC, Tony931023 commented
@acidmanifesto ready

2022-07-10 18:14 UTC, acidmanifesto commented
Thank you for the PR

2022-07-10 18:14 UTC, merged