fix(DB/quest_template): Update
azerothcore/azerothcore-wotlk pull request #11394
Opened 2022-04-13 13:32 UTC by Tony931023

### Update Quest: #11393 
- ID 183 - LogDescription

2022-04-13 13:38 UTC, Nyeriah commented
@Tony931023 Please try to group the translations in a single PR, so we don't have several PRs with one line each. Just keep them at a reasonable size. Thank you very much!

2022-04-13 13:46 UTC, Tony931023 commented
If that's why the PR is in Draft, I will review each one and update the PR

2022-04-13 14:12 UTC, Kitzunu submitted a review, later dismissed

2022-04-13 14:12 UTC, Kitzunu commented on data/sql/updates/pending_db_world/rev_1649856189895360036.sql
> +UPDATE `quest_template` SET `LogDescription` = 'Talin Keeneye would like you to kill 12 Small Crag Boars.'  WHERE `ID` = @ID;
Please don't make variables for one liners as you won't reuse this ID

2022-04-14 03:48 UTC, Tony931023 commented
Ready

2022-04-16 13:33 UTC, Tony931023 commented
ready to be reviewed

2022-05-02 07:09 UTC, Lynethris commented
Tested and it's fine.

2022-05-06 13:35 UTC, acidmanifesto requested changes

2022-05-06 13:35 UTC, acidmanifesto commented on data/sql/updates/pending_db_world/rev_1649856189895360036.sql
> +
can u remove the version_db_world line please? there was a change a few days ago and we no longer require this line.

2022-05-07 14:22 UTC, acidmanifesto approved these changes

2022-06-18 11:55 UTC, acidmanifesto commented
@Kitzunu is the changes to your liking?

2022-06-18 12:47 UTC, acidmanifesto commented
Thank you for the PR.

2022-06-18 12:47 UTC, merged