Fix(Core/Spell): No visual for Suppression Aura
azerothcore/azerothcore-wotlk pull request #11404
Opened 2022-04-15 14:15 UTC by temperrr

## Changes Proposed:
-  Changes visual to 0.
-  

## Issues Addressed:

- Partially closes https://github.com/azerothcore/azerothcore-wotlk/issues/11275

## SOURCE:

## Tests Performed:

-  Tested
- 

## How to Test the Changes:

1. Go to suppression room in bwl
2. check if the fire nova effect is gone but the mist affect stays
3.

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

2022-04-15 14:21 UTC, Kitzunu requested changes

2022-04-15 14:21 UTC, Kitzunu commented on src/server/game/Spells/SpellInfoCorrections.cpp
> +    // Suppression Room Aura (BWL)
```suggestion
    // Suppression Aura
```

2022-04-15 15:11 UTC, Lynethris commented
#11337 is it not fix this ?

2022-04-15 16:34 UTC, pklloveyou commented
> @temperrr #11337 is it not fix this ?

No, Spell id13813 is also wrong

2022-04-15 16:40 UTC, pklloveyou commented
There may be many of the same mistakes

2022-04-15 16:56 UTC, Lynethris commented
@UltraNix

2022-04-15 18:48 UTC, UltraNix commented
@Lynethris ??

2022-04-15 18:54 UTC, Lynethris commented
> @Lynethris ??

@pklloveyou speak about some errors in your fixs #11341 and #11337. Spells ID will be wrong and this fix requiered. I didn't understand everything. For me, we have a duplicate fix. I'm wrong ?

2022-04-15 19:13 UTC, Lynethris commented
> > @Lynethris ??
> 
> @pklloveyou speak about some errors in your fixs #11341 and #11337. Spells ID will be wrong and this fix requiered. I don't really understand. For me, we have a duplicate fix. Am I wrong ?

2022-04-15 20:53 UTC, UltraNix commented
I don't understand @mpfans as well.

2022-04-16 06:16 UTC, Lynethris commented
I have quickly check this morning on the actual master branch and #11337 have fix the visual aura from suppression device.

![WoWScrnShot_041522_134335](https://user-images.githubusercontent.com/100411212/163664203-747f942e-1b99-4ac6-8e30-517c0beaa30f.jpg)

2022-04-16 08:17 UTC, closed without merging