Pr zg jeklik
azerothcore/azerothcore-wotlk pull request #11458
Opened 2022-04-20 19:28 UTC by Lynethris

## Changes Proposed:
- Add missing spells #11381 
- Fix wrong Spell IDs
- Fix fly issue in P2 #11386
- Fix Mind Flay issue #11386
- Fix Psychic Scream issue #11390
- Add emotes
- Add missing aura before the fight 

## Issues Addressed:

- Closes 

## SOURCE:

Many things pick from https://github.com/TrinityCore/TrinityCore/pull/27274
(Thanks @offl for you PR)

## Extra Notes:
After severals research, TC, MangosClassic, other projects and issues... It seems that nobody have found the right spell IDs from 
Chain mind flee. Also, this spells is rarely mentionned (maybe not exist on retail). So I deleted this spell for just let "Mind flay"

## Tests Performed:

- Tested IG

## How to Test the Changes:

1. .tele zulgurub
2. Engage Jeklik
3.

## Known Issues and TODO List:

- [ ] Timers need adjustements
- [ ] Bats are targetable in P2

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

2022-04-21 07:07 UTC, Kitzunu commented
You are assigning creature scripts to creatures but you havent scripted them in the core. Therefore the errors

2022-04-21 07:53 UTC, Lynethris commented
> You are assigning creature scripts to creatures but you havent scripted them in the core. Therefore the errors

Yes, I remove this modifs. I thought that simple properties modifications with bats in P1, but it seems to be related to flying bats in P2 (not touched in this PR).

2022-04-22 07:42 UTC, temperrr commented
- [x] She should cast Sonic burst, Swoop, Pierce armor and blood leech in P1 and Curse of Blood in P2.
- [ ] She isflying in humanoid form during p1, she should be a bat in p1
- [x] Using physic scream in p2
- [x] using mind flay in p2

2022-04-22 12:51 UTC, Lynethris commented
@temperrr I'm unable to reproduce this.

2022-04-23 10:39 UTC, temperrr commented
Works now. Just one odd thing, if you wipe during p1 she flies back in humanoid form which looks odd.

2022-04-23 11:08 UTC, Lynethris commented
> Works now. Just one odd thing, if you wipe during p1 she flies back in humanoid form which looks odd.

Yes, I notice this too. But not related to  this PR. I will reopen a new issue for this.

2022-04-23 12:57 UTC, Kitzunu requested changes

2022-04-23 12:57 UTC, Kitzunu commented on data/sql/updates/pending_db_world/rev_1650481776270749700.sql
> +(14517,4,0,"%s begins to cast a Great Heal!",16,0,100,0,0,0,10494,0,"High Priestess Jeklik");
newline

2022-04-23 12:57 UTC, Kitzunu commented on src/server/scripts/EasternKingdoms/ZulGurub/boss_jeklik.cpp
> +    EMOTE_SUMMON_BATS           = 3,
you never use this in script

2022-04-23 12:57 UTC, Kitzunu commented on data/sql/updates/pending_db_world/rev_1650481776270749700.sql
> +(14517,4,0,"%s begins to cast a Great Heal!",16,0,100,0,0,0,10494,0,"High Priestess Jeklik");
```suggestion
(14517,3,0,"%s emits a deafening shriek!",16,0,100,0,0,0,10370,0,"High Priestess Jeklik - EMOTE_SUMMON_BATS"),
(14517,4,0,"%s begins to cast a Great Heal!",16,0,100,0,0,0,10494,0,"High Priestess Jeklik - EMOTE_GREAT_HEAL");
```

2022-04-24 06:01 UTC, Lynethris commented on data/sql/updates/pending_db_world/rev_1650481776270749700.sql
> +(14517,4,0,"%s begins to cast a Great Heal!",16,0,100,0,0,0,10494,0,"High Priestess Jeklik");
fix

2022-04-24 06:02 UTC, Lynethris commented on src/server/scripts/EasternKingdoms/ZulGurub/boss_jeklik.cpp
> +    EMOTE_SUMMON_BATS           = 3,
Yes, it's fix now.

2022-04-26 04:11 UTC, Nefertumm commented on src/server/scripts/EasternKingdoms/ZulGurub/boss_jeklik.cpp
>                              DoCast(target, SPELL_SHADOW_WORD_PAIN);
```suggestion
                        DoCastRandomTarget((SPELL_SHADOW_WORD_PAIN, 0, true);
```

2022-04-26 04:15 UTC, Nefertumm requested changes

2022-04-26 04:15 UTC, Nefertumm commented on src/server/scripts/EasternKingdoms/ZulGurub/boss_jeklik.cpp
> +                        DoCast(me, SPELL_CURSE_OF_BLOOD);
```suggestion
                        DoCastSelf(SPELL_CURSE_OF_BLOOD);
```

2022-04-26 04:15 UTC, Nefertumm commented on src/server/scripts/EasternKingdoms/ZulGurub/boss_jeklik.cpp
> +                        DoCast(me, SPELL_GREATER_HEAL);
```suggestion
                        DoCastSelf(SPELL_GREATER_HEAL);
```

2022-04-26 04:15 UTC, Nefertumm commented on src/server/scripts/EasternKingdoms/ZulGurub/boss_jeklik.cpp
> +            DoCast(me, SPELL_BAT_FORM);
```suggestion
            DoCastSelf(SPELL_BAT_FORM);
```

2022-04-26 04:15 UTC, Nefertumm commented on data/sql/updates/pending_db_world/rev_1650481776270749700.sql
> +(14517,4,0,"%s begins to cast a Great Heal!",16,0,100,0,0,0,10494,0,"High Priestess Jeklik - EMOTE_GREAT_HEAL");
```suggestion
(14517,3,0,'%s emits a deafening shriek!',16,0,100,0,0,0,10370,0,'High Priestess Jeklik - EMOTE_SUMMON_BATS'),
(14517,4,0,'%s begins to cast a Great Heal!',16,0,100,0,0,0,10494,0,'High Priestess Jeklik - EMOTE_GREAT_HEAL');
```

2022-04-26 04:15 UTC, Nefertumm commented on src/server/scripts/EasternKingdoms/ZulGurub/boss_jeklik.cpp
> +            DoCast(me, SPELL_GREEN_CHANNELING);
```suggestion
            DoCastSelf(SPELL_GREEN_CHANNELING);
```

2022-04-28 19:51 UTC, Nefertumm commented on data/sql/updates/pending_db_world/rev_1650481776270749700.sql
> +INSERT INTO `version_db_world` (`sql_rev`) VALUES ('1650481776270749700');
Remove this line, is not useful anymore.

2022-04-29 16:27 UTC, Nefertumm approved these changes

2022-04-29 16:28 UTC, Kitzunu approved these changes

2022-04-29 16:33 UTC, Nefertumm commented
Update your branch with current master so the sql can pass the check. 👍

2022-05-03 00:02 UTC, merged