fix(Core/Item): Fix Charred Twillight Scale TrinketUpdate spell_generic.cpp
azerothcore/azerothcore-wotlk pull request #11571
Opened 2022-04-29 09:35 UTC by pklloveyou

## Changes Proposed:
-  
-  

## Issues Addressed:

- Closes 

## SOURCE:

## Tests Performed:

- 
- 

## How to Test the Changes:

1.
2.
3.

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

2022-04-29 13:32 UTC, IntelligentQuantum requested changes

2022-04-29 13:32 UTC, IntelligentQuantum commented on data/sql/updates/pending_db_world/rev_1651231168158458211.sql
> +INSERT INTO `version_db_world` (`sql_rev`) VALUES ('1651231168158458211');
delete this line

2022-04-29 16:24 UTC, IntelligentQuantum approved these changes

2022-05-05 18:50 UTC, Maelthyrr commented
What is the difference with https://github.com/azerothcore/azerothcore-wotlk/pull/11487 ?

2022-05-08 18:26 UTC, pklloveyou commented
I need to pull the code again, so close it

2022-05-15 14:23 UTC, Maelthyrr commented
Tested and work.

2022-06-15 00:40 UTC, Nyeriah commented
@pklloveyou why close?

2022-06-15 02:15 UTC, merged