fix(Core/Movement: Rewritten fleeing movement generator. Source: TrinityCore.
azerothcore/azerothcore-wotlk pull request #11586
Opened 2022-04-30 19:30 UTC by UltraNix

Fixes #5980
Fixes #9314

## Issues Addressed:

- Closes #5980
- Closes #9314
- Closes https://github.com/chromiecraft/chromiecraft/issues/677
- Closes https://github.com/chromiecraft/chromiecraft/issues/2381

## Tests Performed:

- Tested ingame.

## How to Test the Changes:

Enter Scarlet Monastery Cathedral
Progress until the closed door
Have any mob near the door and have it feared (warlock's or warrior's spells, or low hp)
Repeat from 3 until a mob's random fear movement makes it walk through the door

Join WSG battleground
Fear an enemy next to the line-of-sight object in the middle of the battleground (more info: [here](https://github.com/chromiecraft/chromiecraft/issues/677))

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

2022-04-30 19:36 UTC, Kitzunu requested changes

2022-04-30 19:36 UTC, Kitzunu commented on src/server/game/Movement/MovementGenerators/FleeingMovementGenerator.cpp
> +    owner->RemoveFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_FLEEING);
```suggestion
    owner->RemoveUnitFlag(UNIT_FLAG_FLEEING);
```

2022-04-30 19:36 UTC, Kitzunu commented on src/server/game/Movement/MovementGenerators/FleeingMovementGenerator.cpp
> +    owner->RemoveFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_FLEEING);
same here

2022-04-30 19:36 UTC, Kitzunu commented on src/server/game/Movement/MovementGenerators/FleeingMovementGenerator.cpp
> +    owner->SetFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_FLEEING);
```suggestion
    owner->SetUnitFlag(UNIT_FLAG_FLEEING);
```

2022-04-30 19:54 UTC, Kitzunu approved these changes

2022-05-05 16:54 UTC, Maelthyrr commented
Seems to work fine (tested in Scarlet dungeon and in WSG). No issues find.

<details>
![WoWScrnShot_050522_184638](https://user-images.githubusercontent.com/100411212/166973827-593a5c1d-a603-43b5-8ce8-698e65951b43.jpg)
</details>

2022-05-08 21:35 UTC, merged