Fix(Core/ZulGurub): more improvements to High Priestess Jeklik
azerothcore/azerothcore-wotlk pull request #11604
Opened 2022-05-03 05:02 UTC by Nefertumm

## Changes Proposed:
-  Move the scripts to the new system
-  Use the right spells for liquid fire.
-  Change her reset behaviour, she should tp to her balcony on wipe.
-  Add hover and gravity to bats.

## Issues Addressed:

- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/11379
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/11378
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/11386 ? maybe

## SOURCE:

Walk/Run speed from CMangos, gob diameter from VMangos.

## Tests Performed:

- Tested in-game with 2 accounts.

## How to Test the Changes:

1. Engage with Jeklik and wipe.
2. Engage again and go to P2, wait for the bats to spawn.
3. :)

2022-05-05 18:11 UTC, Maelthyrr commented
Tested and all work. Except one issue, she can summon 6 bats targetables in P2 like with "Summon bats" in P1.

2022-05-05 22:11 UTC, Nefertumm commented
try again, please

2022-05-06 19:50 UTC, Kitzunu requested changes

2022-05-06 19:50 UTC, Kitzunu commented on src/server/scripts/EasternKingdoms/ZulGurub/boss_jeklik.cpp
> +    SPELL_BOMB                  = 23970,
```suggestion
    SPELL_THROW_LIQUID_FIRE = 23970,
```

2022-05-06 19:50 UTC, Kitzunu commented on src/server/scripts/EasternKingdoms/ZulGurub/boss_jeklik.cpp
> +    SPELL_SPAWN_FLAMES          = 23971
```suggestion
    SPELL_SUMMON_LIQUID_FIRE = 23971
```

2022-05-09 06:54 UTC, Maelthyrr commented
@Nefertumm I don't know if you have see, but you are some build errors with last update. I can't test for the moment.

2022-05-09 20:57 UTC, Nefertumm commented
Oh yeah I'm kinda dumb, let me fix it real quick :P

2022-05-10 06:31 UTC, Kitzunu approved these changes

2022-05-11 06:54 UTC, Maelthyrr commented
Everything is fine.

2022-05-23 08:49 UTC, Nyeriah commented
build seems to be failing

2022-06-03 12:26 UTC, merged