fix(DB/SAI): updated text for Rune-Inscribed Parchment
azerothcore/azerothcore-wotlk pull request #11639
Opened 2022-05-05 11:58 UTC by Asthalor

## Changes Proposed:
-  Added the english and french text for the item Rune-Inscribed Parchment.

## Issues Addressed:

- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/11583

## SOURCE:

https://classic.wowhead.com/item=9568/rune-inscribed-parchment for the english text
https://fr.classic.wowhead.com/item=9568/parchemin-runique for the french text

## Tests Performed:

- Create lvl 1 shaman
- .levelup 1
- go to gornek, in the cave
- Pick the mission cutting teeth.
- .complete quest 788
- get the rune-inscribed-parchment  quest
- open the letter and check the content

## How to Test the Changes:

1. Create lvl 1 shaman
2. levelup 1
3. go to gornek, in the cave
4.   Pick the mission cutting teeth.
5. .complete quest 788
6. get the rune-inscribed-parchment  quest
7. open the letter and check the content

## Known Issues and TODO List:

- I dont have a french client. Should work tho.

Test image

![image](https://user-images.githubusercontent.com/87535580/166918541-1c35c900-9758-4eab-8171-9f1c1a6cbfff.png)

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

2022-05-08 06:50 UTC, Maelthyrr commented
Tested with enUS and FR, all work fine.

2022-05-08 08:18 UTC, Kitzunu requested changes

2022-05-08 08:18 UTC, Kitzunu commented on data/sql/updates/pending_db_world/rev_1651751512749712800.sql
> +UPDATE `page_text`  SET `Text` = "Lok-tar, $gbrother:sister. The elements beckon you closer and bid me to show you the path of the shaman. The spirits of our ancestors watch from beyond and swell wit
Backticks on id

2022-05-25 08:05 UTC, Nefertumm commented
Seems like brother;sister doesn't work. Look at the image you posted

2022-05-26 06:07 UTC, Asthalor commented
> Seems like brother;sister doesn't work. Look at the image you posted

Woops, didnt noticed. Im on it

2022-05-26 06:18 UTC, Asthalor commented
![image](https://user-images.githubusercontent.com/87535580/170428960-df30a0f4-7922-4a22-8d0b-9dbbe8e71ff1.png)

2022-05-26 18:59 UTC, Nefertumm approved these changes

2022-05-26 19:00 UTC, merged