Fix(scripts/spells) charge
azerothcore/azerothcore-wotlk pull request #11693
Opened 2022-05-08 18:32 UTC by pklloveyou

## Changes Proposed:
-  
-  

## Issues Addressed:

- Closes 

## SOURCE:

## Tests Performed:

- 
- 

## How to Test the Changes:

1.
2.
3.

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

2022-05-08 18:37 UTC, Kitzunu commented on src/server/game/Movement/MotionMaster.cpp
> +void MotionMaster::MoveCharge(PathGenerator const& path, float speed /*= SPEED_CHARGE*/, uint64 targetGUID /*= 0*/)
ObjectGuid

2022-05-08 18:42 UTC, pklloveyou commented
@Kitzunu thanks

2022-05-08 18:57 UTC, pklloveyou commented
![image](https://user-images.githubusercontent.com/18535853/167311335-df7f951c-f5ac-4068-a8c8-b2a97cfac308.png)
It has been used in my project for a long time, which can ensure that it has no errors

2022-05-08 19:07 UTC, UltraNix commented on src/server/game/Spells/Spell.cpp
> +                        float objSize = m_caster->GetCombatReach() + target->GetCombatReach();
Nope - it's has to be only target's combat reach.

2022-05-08 19:07 UTC, UltraNix commented on src/server/game/Spells/SpellEffects.cpp
> +            Position pos = unitTarget->GetFirstCollisionPosition(m_caster->GetCombatReach() + unitTarget->GetCombatReach(), unitTarget->GetRelativeAngle(m_caster));
As above.

2022-05-08 19:08 UTC, UltraNix requested changes
What issue this PR resolves?

2022-05-08 19:10 UTC, pklloveyou commented
@UltraNix --11670

2022-05-08 19:18 UTC, UltraNix commented
So this PR is not a solution to this.

2022-05-08 19:20 UTC, pklloveyou commented
They were deleted in 11534

2022-05-08 19:21 UTC, UltraNix commented
59e45c251eb has broken that.

2022-05-08 19:21 UTC, pklloveyou commented
I've deleted the scope of the battle

2022-05-08 19:22 UTC, UltraNix approved these changes
Now looks okay. 
Link it to issue.

2022-05-08 19:23 UTC, pklloveyou commented
ok

2022-05-08 20:57 UTC, Kitzunu commented
Did you test it @pklloveyou

2022-05-09 11:14 UTC, pklloveyou commented
@Kitzunu yes

2022-05-10 06:21 UTC, merged