fix(DB): Increase drop rate of Ritual Salve
azerothcore/azerothcore-wotlk pull request #11906
Opened 2022-05-29 08:02 UTC by Maelthyrr

Align with WoWgaming and WoltkDB value (80%)

## Changes Proposed:
-  Update drop rate to 80 %

## Issues Addressed:

- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/11875

## SOURCE:

Confirm also with https://wotlkdb.com/?item=6634

## Tests Performed:

- None

## How to Test the Changes:

1.Create a Tauren Shaman
2. Start Call of Earth questline from [Seer Ravenfeather](https://classic.wowhead.com/npc=5888/seer-ravenfeather)
3. See you are having difficulties gathering 2 Salves after more than 5 Shamans killed.

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

2022-05-29 08:15 UTC, IntelligentQuantum approved these changes

2022-05-30 17:07 UTC, Undeadhunter commented
Tested OK  high drop rate but not 100% for sure on the Bristleback shamans

2022-05-30 17:38 UTC, Maelthyrr commented
> Tested OK high drop rate but not 100% for sure on the Bristleback shamans

It's intend. Sources say 80%.

2022-05-31 07:37 UTC, Undeadhunter commented
I badly worded that then, 
I didn't do a complete statistical analysis but out of the 25 kills I had 4 with no drop.

2022-05-31 11:01 UTC, acidmanifesto commented
![Screenshot_20220531-065924_Chrome.jpg](https://user-images.githubusercontent.com/16887899/171158815-c3b10951-f97c-4913-98fc-78c3798a6133.jpg)

Be advise your link for reference states the site is from pserver data

2022-05-31 15:08 UTC, Maelthyrr commented
I didn't know for woltkdb. But stay the same thing, videos show that the drop is near 100% but not 100%. And it's definitely not 14% as it is the case in the DB and WoWHead. What do we do ?

2022-05-31 15:24 UTC, acidmanifesto commented
> I didn't know for woltkdb. But stay the same thing, videos show that the drop is near 100% but not 100%. And it's definitely not 14% as it is the case in the DB and WoWHead. What do we do ? 4/25 it's make 86%.

I will leave that for your discretion. This is where we will have to rely on what you feel is right. Im not home to check or match up with udb which has been a differ debate in itself as it doesnt cover conditions if any. Wowhead is diluted with their method of datamining thru addon use. But if you feel your approach from the video and other references would put it more towards a possible blizz like rate then go for it.

2022-05-31 15:46 UTC, Gultask commented
See https://github.com/azerothcore/azerothcore-wotlk/pull/9379 as they had changed the drop rate for Ritual Salve. Now, I don't really know for sure but I think there was a mistake, as the table contained in the comments says 80% and in the sql it changed to 15%
Can't really be sure since I'm not on my PC right now, but I think 80% is the correct chance.

2022-05-31 18:15 UTC, neifion-00000000 commented
Currently working on this drop rate, how high confidence do we want to be on the rate?

ATM I am 99% confident that its drop rate is between 65 and 87%, and 90% confident it is between 69 and 83% but I am working on getting those numbers better.

2022-05-31 20:04 UTC, Maelthyrr commented
> Currently working on this drop rate, how high confidence do we want to be on the rate?
> 
> (Updated)
> ATM I've mined enough data to know its 65-79% with 98% confidence  67-77 with 90% confidence
> 
> I'm currently 2/5ths of the amount I want to gather (500 samples) at which point I'd have a solid recommendation.

Thanks you si much 😊

2022-06-08 03:00 UTC, Nefertumm requested changes

2022-06-08 03:00 UTC, Nefertumm commented on data/sql/updates/pending_db_world/rev_1653810747543320600.sql
> +UPDATE  `creature_loot_template` SET `Chance` = 72 WHERE `Entry` = 2953 AND `Item` = 6634;
```suggestion
UPDATE `creature_loot_template` SET `Chance` = 72 WHERE `Entry` = 2953 AND `Item` = 6634;
```

2022-06-08 03:01 UTC, Nefertumm approved these changes

2022-06-15 02:18 UTC, merged