fix(Core/DB): Quest 'Inoculation'
azerothcore/azerothcore-wotlk pull request #11948
Opened 2022-06-03 23:50 UTC by hanabi5

## Changes Proposed:
- Removed SmartAI from Nestlewood Owlkin
- Scripted spell for inoculation

## Issues Addressed:

- Closes #5917
- Closes https://github.com/chromiecraft/chromiecraft/issues/663

## SOURCE:

[youtube](https://www.youtube.com/watch?v=a_qx4WRD27U&ab_channel=Bue)

## Tests Performed:

- Tested in-game

## How to Test the Changes:

1. .go c id 16518
2. .q a 9303
3. Use quest item on Nestlewood Owlkins to complete the quest.

## Known Issues and TODO List:

None

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

2022-06-04 00:20 UTC, Nyeriah commented
Thanks for the PR but I have an objection to this, no spell script should ever need to handle creature AI that way. What was the issue with the SAI script the creature had before?

2022-06-04 16:45 UTC, hanabi5 commented
There's no smart hook to handle periodic aura, only spell hit. If the creature gets hit by the spell, it triggers the smartai, but it should only trigger after aura is applied.
Should I make a new function to handle aura just for one creature?

2022-06-06 17:38 UTC, Kitzunu requested changes

2022-06-06 17:38 UTC, Kitzunu commented on data/sql/updates/pending_db_world/rev_1654292539705612400.sql
> +SET @SPELL_INOCULATE    = 29528;
```suggestion
SET @NESTLEWOOD_OWLKIN  := 16518;
SET @SPELL_INOCULATE   := 29528;
```

2022-06-06 17:49 UTC, Kitzunu commented on src/server/scripts/Spells/spell_generic.cpp
> +        OnEffectPeriodic += AuraEffectPeriodicFn(spell_inoculate_nestlewood_owlkin::HandleEffectPeriodic, EFFECT_0, SPELL_AURA_PERIODIC_TRIGGER_SPELL);
Effect 0: Id 6 (SPELL_EFFECT_APPLY_AURA) not SPELL_AURA_PERIODIC_TRIGGER_SPELL

2022-06-06 17:50 UTC, Kitzunu commented on src/server/scripts/Spells/spell_generic.cpp
> +        OnEffectPeriodic += AuraEffectPeriodicFn(spell_inoculate_nestlewood_owlkin::HandleEffectPeriodic, EFFECT_0, SPELL_AURA_PERIODIC_TRIGGER_SPELL);
```suggestion
        OnEffectPeriodic += AuraEffectPeriodicFn(spell_inoculate_nestlewood_owlkin::HandleEffectPeriodic, EFFECT_0, SPELL_EFFECT_APPLY_AURA);
```

2022-06-06 17:52 UTC, hanabi5 commented
I mean, the script works it's just that it doesn't pass the DB checks

2022-06-06 17:55 UTC, Kitzunu commented on src/server/scripts/Spells/spell_generic.cpp
> +class spell_inoculate_nestlewood_owlkin : public AuraScript
```suggestion
class spell_inoculate_nestlewood_owlkin : public SpellScript
```

2022-06-06 17:58 UTC, closed without merging

2022-06-06 17:59 UTC, Kitzunu commented
I am trying to fix the build, after I was asked. kek

2022-06-10 10:14 UTC, acidmanifesto commented
For those curious about this. There WAS a cmake issue on the master that was resolved yesterday dealing with sql. As for the AITarget error it was a missing include directive.