fix(DB/gossip_menu_option_locale): Populate missing locale entries from broadcast_text
azerothcore/azerothcore-wotlk pull request #11943
Opened 2022-06-03 16:11 UTC by ZhengPeiRu21

## Changes Proposed:
-  Use existing broadcast_text_locale data to populate missing gossip_menu_option_locale entries.
-  I only populated missing entries; in the case of conflicts I did not change anything

## Issues Addressed:

- Closes unreported issue

## SOURCE:

broadcast_text_locale data

## Tests Performed:

- N/A

## How to Test the Changes:

1. Use not enUS client and see gossip menu options now have before missing locale data

## Known Issues and TODO List:

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

2022-06-03 16:21 UTC, ZhengPeiRu21 commented
Sorry, I am just now realize I should first have a SQL DELETE to prevent conflict. For this large type of bulk insert, we are prefer many individual DELETEs, or just use INSERT IGNORE or REPLACE INTO?

2022-06-08 02:01 UTC, mpfans commented
发现缺少一些zhCN的翻译,如6185\6186\6187-0 等等

另外我还建议使用REPLACE INTO,然后把zhCN和zhTW单独出来,其他的语言再单独提交一个PR...

上次提交的PR因为文件过大,自动更新时出现了失败的情况.

2022-07-11 13:49 UTC, acidmanifesto commented
What is the status of this PR?

2022-07-21 15:48 UTC, ZhengPeiRu21 commented
> Do you still need to test

Thank you for willing to test! I am still needing to split this PR into multiple PR to avoid the too large SQL file, but it will still be the same updates, so it can be tested as-is. Please let me know if you see any issue!

2022-07-22 15:47 UTC, ZhengPeiRu21 commented
I have updated this PR to split each language into separate PR in order to prevent large SQL files. This PR now contains only zhCN locale data.

2022-08-27 17:01 UTC, ZhengPeiRu21 commented
I think this PR should be ready to merge. WIP tag can be remove.

2022-08-27 17:30 UTC, Nyeriah commented
Hmm SQL import is erroring

2022-08-29 09:04 UTC, yuanf225 commented
![image](https://user-images.githubusercontent.com/43561197/187165582-b3435bc6-c120-4333-9a74-3f4c8833114d.png)
I just tested it and the import is fine

2022-09-01 20:11 UTC, acidmanifesto approved these changes

2022-09-01 20:28 UTC, acidmanifesto requested changes

2022-09-01 20:28 UTC, acidmanifesto commented on data/sql/updates/pending_db_world/rev_1654272234519507300.sql
> +(10952, 0, 'zhCN', 'Lok''tar ogar！我们准备好了！兽人兄弟们，冲啊！'),
this line is erroring out the check with the ''
```suggestion
(10952, 0, 'zhCN', 'Lok tar ogar！我们准备好了！兽人兄弟们，冲啊！'),
```

2022-09-21 12:38 UTC, acidmanifesto commented
@ZhengPeiRu21 i have not forgot about this pr, however i am starting to think its because it is entirely too big with the replace is why it fails. I am going to try to split up the query and see how that goes.

2022-09-21 16:53 UTC, acidmanifesto approved these changes
I did alot of lines

2022-09-21 16:56 UTC, merged