fix(Core/Pets): Mob "soloed" by pet should not grant exp/loot to its …
azerothcore/azerothcore-wotlk pull request #11969
Opened 2022-06-05 09:11 UTC by UltraNix

…master.

Fixes #11528

## Issues Addressed:

- Closes #11528
- Closes https://github.com/chromiecraft/chromiecraft/issues/3408

## Tests Performed:

- Tested ingame.

## How to Test the Changes:

Summon hunter pet
Put pet in aggressive mode
Sit back, relax and watch the XP

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

2022-06-05 14:02 UTC, Gultask commented
It works but it's making the player need to deal a percentage of damage before they're eligible for loot/XP (40-50%, maybe?) which I think it's bad for Beast Mastery hunters that can have their pets normally deal at least 50% or more of their total damage, varying between players of course.

Using Mend Pet or pet abilities do not make the player eligible. But I don't know what's blizzlike in that case.

2022-06-05 14:30 UTC, UltraNix commented
You need to do at least 50% + 1 damage to get loot/exp - it's blizzlike.

2022-06-06 05:58 UTC, IntelligentQuantum approved these changes

2022-06-08 06:38 UTC, temperrr commented
Level 60 BM hunters pet kill monsters so quickly that this change would make them have no loot at all. This does not seem right.

2022-06-08 13:44 UTC, Nyeriah commented
Yes, I wanted to try this on retail but I pretty much remember you don't need to do much in order to get credit, definitely not 50%. Most of the time BM hunters won't get any loot or experience yes

2022-06-09 00:45 UTC, T1ti commented
I tested it and 1 tick of serpent sting was enough to give me loot

2022-06-09 00:47 UTC, Nyeriah commented
> I tested it on classic and 1 tick of serpent sting was enough to give me loot

Thanks for confirming @T1ti , I discussed this with @temperrr and that was our impression as well.

2022-06-11 07:08 UTC, UltraNix commented
I said that many times - classic is not vanilla (and especially is not wotlk).
https://github.com/TrinityCore/TrinityCore/issues/18758
https://github.com/TrinityCore/TrinityCore/issues/12478
https://github.com/TrinityCore/TrinityCore/issues/8549
https://web.archive.org/web/20160917231252/https://eu.battle.net/forums/en/wow/topic/8819991938
https://www.mmo-champion.com/threads/1798474-Sooo-Having-a-pet-makes-you-lose-loot

2022-06-11 08:14 UTC, UltraNix commented
@Gultask @temperrr Please, test it again.

2022-06-11 15:07 UTC, Gultask commented
Tested. The player now needs to land the killing blow. `.damage` until 1hp remains, send pet, don't get credit.

2022-06-11 15:19 UTC, UltraNix commented
@Gultask Should be okay now.

2022-06-11 15:39 UTC, Gultask commented
Looks great! a single point of damage is enough to give credit.
Tested loot, XP, reputation and quest credit.

2022-06-11 15:42 UTC, temperrr commented
Thanks for the test Gultask <3

2022-06-18 12:09 UTC, acidmanifesto requested changes

2022-06-18 12:09 UTC, acidmanifesto commented on src/server/game/Entities/Creature/Creature.cpp
> +    m_lootRecipientGroup(0), m_corpseRemoveTime(0), m_respawnTime(0), m_respawnDelay(300), m_corpseDelay(60), m_wanderDistance(0.0f), m_boundaryCheckTime(2500),
This is tossing a error on the compile testing. I am guess order?
![image](https://user-images.githubusercontent.com/16887899/174436842-2fa1c81b-2629-4538-8c71-bb1c13881fab.png)

2022-06-18 16:18 UTC, UltraNix commented
@acidmanifesto Should be okay.

2022-06-18 17:56 UTC, acidmanifesto requested changes

2022-06-18 17:56 UTC, acidmanifesto commented on src/server/game/Entities/Creature/Creature.cpp
> +    m_lootRecipientGroup(0), _damagedByPlayer(false), m_corpseRemoveTime(0), m_respawnTime(0), m_respawnDelay(300), m_corpseDelay(60), m_wanderDistance(0.0f), m_boundaryCheckTime(2500),
lets try moving _playerDamageReq(0) to after  m_lootRecipientGroup(0) and see how it plays from there.
![image](https://user-images.githubusercontent.com/16887899/174450801-1746bf40-f77d-4dd6-994c-10ee92794cc1.png)

2022-06-18 18:04 UTC, UltraNix commented
Try now.

2022-06-18 18:11 UTC, acidmanifesto approved these changes

2022-06-18 19:06 UTC, acidmanifesto commented
so far, the compile testing is crying that it needs to be moved over more to the right. at this point this is literally going to be commit and hope it goes green on the test. 

![image](https://user-images.githubusercontent.com/16887899/174452916-8fb5c4b8-a8a2-45a9-a3f1-5a6136ece3c0.png)

2022-06-19 11:46 UTC, acidmanifesto commented
Thank you for the PR

2022-06-19 11:46 UTC, merged