fix(Scripts/ZulGurub): Renataki - improvements:
azerothcore/azerothcore-wotlk pull request #11967
Opened 2022-06-05 07:07 UTC by UltraNix

Added missing spells and events.
Removed invalid spells
Corrected event timers
Fixes #11620
Fixes #11621

## Issues Addressed:

- Closes #11620
- Closes #11621

## Tests Performed:

- Not tested.

## How to Test the Changes:

If the Summoning Event is implemented:
`.event stop 27`
`.event stop 28`
`.event stop 30`
`.event start 29`
`.additem 19931`
`.go xyz -11905 -1911 66 309`
use the brazier and engage Renataki

else:
`.go xyz -11905 -1911 66 309`
`.npc add temp 15084`

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

2022-06-05 16:05 UTC, Gultask commented
- [ ] If everyone is hit by Gouge, the encounter ends and the boss resets.
 - [ ] Thousand Blades is only being cast once, and only on the main target from what I saw. It should be cast several times back-to-back, and changing targets if possible (3 to 5 times or maybe a constant 4 times to be more consistent) I also think it should prefer ranged targets whenever possible but I'm not 100% sure about that.
 - [ ] Vanish doesn't stop the boss from attacking the tank so stealth is broken immediately. I think he should stop doing normal melee attacks completely while stealthed, only breaking stealth for Ambush.

As for more minor issues:

 - [ ] Pets should be able to attack the boss while he's stealthed, currently they leave him alone, returning to their master instead.

2022-06-11 09:41 UTC, UltraNix commented
@Gultask Please, test it.

2022-06-11 14:41 UTC, Gultask commented
I got a build error:

```
3>I:\AC\src\common\Utilities\Containers.h(100,21): error C2678: binary '=': no operator found which takes a left-hand operand of type 'const ObjectGuid' (or there is no acceptable conversion) (compiling source file I:\AC\src\server\scripts\EasternKingdoms\ZulGurub\boss_renataki.cpp)
3>I:\AC\src\server\game\Entities\Object\ObjectGuid.h(252,1): message : could be 'ObjectGuid &ObjectGuid::operator =(ObjectGuid &&)' (compiling source file I:\AC\src\server\scripts\EasternKingdoms\ZulGurub\boss_renataki.cpp)
3>I:\AC\src\server\game\Entities\Object\ObjectGuid.h(252,1): message : or       'ObjectGuid &ObjectGuid::operator =(const ObjectGuid &)' (compiling source file I:\AC\src\server\scripts\EasternKingdoms\ZulGurub\boss_renataki.cpp)
3>I:\AC\src\common\Utilities\Containers.h(82,1): message : while trying to match the argument list '(const ObjectGuid, const ObjectGuid)' (compiling source file I:\AC\src\server\scripts\EasternKingdoms\ZulGurub\boss_renataki.cpp)
3>I:\AC\src\server\scripts\EasternKingdoms\ZulGurub\boss_renataki.cpp(190): message : see reference to function template instantiation 'void Acore::Containers::RandomResize<GuidSet>(C &,size_t)' being compiled
3>        with
3>        [
3>            C=GuidSet
3>        ]
3>Done building project "scripts.vcxproj" -- FAILED.

```


![Untitled](https://user-images.githubusercontent.com/100873791/173192483-b8b91ca9-030f-4b53-8c85-712a5fc5912d.png)

2022-06-11 14:45 UTC, UltraNix commented
@Gultask Try now.

2022-06-11 14:52 UTC, Gultask commented
```
3>I:\AC\src\server\scripts\EasternKingdoms\ZulGurub\boss_renataki.cpp(158,1): error C2664: 'void std::list<Unit *,std::allocator<Unit *>>::push_back(_Ty &&)': cannot convert argument 1 from 'ObjectGuid' to '_Ty &&'
3>        with
3>        [
3>            _Ty=Unit *
3>        ]
3>I:\AC\src\server\scripts\EasternKingdoms\ZulGurub\boss_renataki.cpp(158,1): message : Reason: cannot convert from 'ObjectGuid' to '_Ty'
3>        with
3>        [
3>            _Ty=Unit *
3>        ]
3>I:\AC\src\server\scripts\EasternKingdoms\ZulGurub\boss_renataki.cpp(158,77): message : No user-defined-conversion operator available that can perform this conversion, or the operator cannot be called
3>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.32.31326\include\list(957,10): message : see declaration of 'std::list<Unit *,std::allocator<Unit *>>::push_back' (compiling source file I:\AC\src\server\scripts\EasternKingdoms\ZulGurub\boss_renataki.cpp)
4>authserver.vcxproj -> I:\Build\bin\RelWithDebInfo\authserver.exe
3>Done building project "scripts.vcxproj" -- FAILED.

```

2022-06-11 15:15 UTC, UltraNix commented
Once again

2022-06-11 15:21 UTC, Gultask commented
```
4>   Creating library I:/Build/src/server/apps/RelWithDebInfo/authserver.lib and object I:/Build/src/server/apps/RelWithDebInfo/authserver.exp
3>boss_renataki.cpp
3>I:\AC\src\server\scripts\EasternKingdoms\ZulGurub\boss_renataki.cpp(158,1): error C2664: 'void std::list<Unit *,std::allocator<Unit *>>::push_back(_Ty &&)': cannot convert argument 1 from 'ObjectGuid' to '_Ty &&'
3>        with
3>        [
3>            _Ty=Unit *
3>        ]
3>I:\AC\src\server\scripts\EasternKingdoms\ZulGurub\boss_renataki.cpp(158,1): message : Reason: cannot convert from 'ObjectGuid' to '_Ty'
3>        with
3>        [
3>            _Ty=Unit *
3>        ]
3>I:\AC\src\server\scripts\EasternKingdoms\ZulGurub\boss_renataki.cpp(158,77): message : No user-defined-conversion operator available that can perform this conversion, or the operator cannot be called
3>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.32.31326\include\list(957,10): message : see declaration of 'std::list<Unit *,std::allocator<Unit *>>::push_back'
3>Done building project "scripts.vcxproj" -- FAILED.

```

2022-06-11 15:36 UTC, UltraNix commented
WTF

2022-06-11 15:48 UTC, UltraNix commented
Try again pull soure or rebase your local.

2022-06-11 15:50 UTC, Gultask commented
I tried it again, creating another branch. 27 errors. Uh oh. 😬 

@temperrr  could you test it in the meantime? Or maybe Maelthyr if he's available?

2022-06-11 16:05 UTC, acidmanifesto commented
> I tried it again, creating another branch. 27 errors. Uh oh. 😬
> 
> @temperrr could you test it in the meantime? Or maybe Maelthyr if he's available?

I'm doing a absolute clean setup and recompile right now. Will report back if i get any of the compile errors.

2022-06-11 16:15 UTC, acidmanifesto commented
so after compiling i get this:
```
21>D:\New folder\azerothcore-wotlk-custom\src\common\Utilities\Containers.h(100,21): error C3892: 'keepIt': you cannot assign to a variable that is const (compiling source file D:\New folder\azerothcore-wotlk-custom\src\server\scripts\EasternKingdoms\ZulGurub\boss_renataki.cpp)
21>D:\New folder\azerothcore-wotlk-custom\src\server\scripts\EasternKingdoms\ZulGurub\boss_renataki.cpp(190): message : see reference to function template instantiation 'void Acore::Containers::RandomResize<std::set<Unit *,std::less<Unit *>,std::allocator<Unit *>>>(C &,size_t)' being compiled
21>        with
21>        [
21>            C=std::set<Unit *,std::less<Unit *>,std::allocator<Unit *>>
21>        ]
```
![image](https://user-images.githubusercontent.com/16887899/173195993-97c069b2-df8e-4f1b-b255-d6c68603a2c5.png)

Verdict, Can not compile due to errors.
Windows 11, VS 2022

2022-06-11 16:19 UTC, acidmanifesto requested changes

2022-06-11 16:19 UTC, acidmanifesto commented on src/server/scripts/EasternKingdoms/ZulGurub/boss_renataki.cpp
> +        bool CanBeSeen(Player const* player) override
bool CanBeSeen(Player const* /*player*/) override

2022-06-11 16:20 UTC, acidmanifesto commented on src/server/scripts/EasternKingdoms/ZulGurub/boss_renataki.cpp
> +        bool CanBeSeen(Player const* player) override
this is in regards to the ci testing ^^

2022-06-11 16:41 UTC, UltraNix commented
@acidmanifesto Fixed.

2022-06-11 16:49 UTC, acidmanifesto commented
@Gultask i will be unavailable for a the next day and a half, if you can test and let me know. Ultranix resolved the compile issues .

2022-06-11 17:35 UTC, temperrr commented
[ ] Never vanishes (never uses ambush)
[ ] never uses gouge, or I think he tries to do it but it does not go on the chars (no combat log entries) but he does switch targets very briefly 
[x] uses thousand blades correctly

2022-06-11 17:37 UTC, temperrr commented
Seems to work as described.

2022-06-11 17:39 UTC, acidmanifesto commented
> Seems to work as described.

So its tested?

2022-06-12 07:53 UTC, UltraNix commented
@temperrr Please test pets again.

2022-06-12 16:12 UTC, Maelthyrr commented
> @temperrr Please test pets again.

Work ;)

2022-06-12 18:28 UTC, acidmanifesto approved these changes

2022-06-12 18:28 UTC, acidmanifesto commented
Approved

2022-06-13 22:12 UTC, Nefertumm commented on src/server/scripts/EasternKingdoms/ZulGurub/boss_renataki.cpp
> +                me->TextEmote("%s becomes enraged", me, false);
move this to db and then we are safe to merge

2022-06-16 14:39 UTC, merged