fix(Tools/vmaps): Fix extractor crash when some .mpq files does not exist
azerothcore/azerothcore-wotlk pull request #11976
Opened 2022-06-07 04:36 UTC by IntelligentQuantum

## Changes Proposed:
-  
-  

## Issues Addressed:

- Closes 

## SOURCE:

https://github.com/TrinityCore/TrinityCore/commit/3d7a86bf1e7596b040ebaada23d377368096da0f
## Tests Performed:

- 
- 

## How to Test the Changes:

1.
2.
3.

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

2022-06-18 12:11 UTC, acidmanifesto commented
@IntelligentQuantum can you fetch the upstream and see if the codefactor issue is resolved? its literally the only thing preventing the merge button from showing.

2022-06-19 11:48 UTC, acidmanifesto approved these changes

2022-06-22 18:00 UTC, acidmanifesto requested changes

2022-06-22 18:00 UTC, acidmanifesto commented on .gitignore
> +cmake-build-debug-event-trace/*
what is the purpose of this one?

2022-06-23 01:32 UTC, IntelligentQuantum commented on .gitignore
> +cmake-build-debug-event-trace/*
Related to Clion IDE

2022-06-28 20:03 UTC, acidmanifesto approved these changes

2022-09-21 19:47 UTC, acidmanifesto commented
Tested with select mpq's being removed, no crash. Will get with other staffers in merging it. No new map extractions is required.

2022-10-01 20:43 UTC, merged