Fix(DB/translate):Chinese translation of road signs
azerothcore/azerothcore-wotlk pull request #11981
Opened 2022-06-08 07:57 UTC by mpfans

## Changes Proposed:
* Boat to Azuremyst
* Boat to Teldrassil
* Boat to Stormwind

## Tests Performed:

- tested ingame

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

2022-06-11 16:37 UTC, acidmanifesto requested changes

2022-06-11 16:37 UTC, acidmanifesto commented on data/sql/updates/pending_db_world/rev_1654674618622504335.sql
> +(176365, 'zhCN', '开往泰达希尔的船只', '', 18019);
(176365, 'zhCN', '开往泰达希尔的船只', '', 18019); 
needs to be
(176365, 'zhCN', '开往泰达希尔的船只', '', 18019),

2022-06-11 16:38 UTC, acidmanifesto commented on data/sql/updates/pending_db_world/rev_1654674618622504335.sql
> +(176365, 'zhCN', '开往泰达希尔的船只', '', 18019);
i went ahead and changed it for you

2022-06-11 16:38 UTC, acidmanifesto approved these changes

2022-06-11 16:47 UTC, acidmanifesto commented
Thank you for the PR

2022-06-11 16:47 UTC, merged

2022-06-16 07:26 UTC, mpfans commented on data/sql/updates/pending_db_world/rev_1654674618622504335.sql
> +(176365, 'zhCN', '开往泰达希尔的船只', '', 18019);
> i went ahead and changed it for you

ty