fix(DB): Brontus spawn and pathing behaviors corrected
azerothcore/azerothcore-wotlk pull request #12052
Opened 2022-06-14 06:38 UTC by neifion-00000000

closes #6539 and addresses all additional issues mentioned

## Changes Proposed:
-  Removes existing Brontus spawn
-  Creates 3 New Pooled spawns, containing Kodos that path (and Brontus in one of them)

## Issues Addressed:

- Closes #6539 and deals with a lot of the additional details found in research

## SOURCE:

sniff data, and a lot of research, the spawn percentages were guesses and might be too generous especially with how the pool spawning works which is also more predictable than would be desired

## Tests Performed:

- Checked Pooling functionality
- Checked respawn functionality (it's a bit odd but it doesn't break the pools ever)
- Checked pathing (it's a long path x.x)

## How to Test the Changes:

1. .go xyz -3787.7153 -1848.3755 93.918015
2. Have fun with the kodos for a while

## Known Issues and TODO List:

- Spawn percentage is prolly not perfect, but I spent more than 6 hours on this, but its hard to tell for sure without spending hundreds of hours on it.
- My formations prolly aren't perfect.  I don't have a method for an exact formation.

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

2022-06-14 19:36 UTC, Maelthyrr commented
I got an issue with a pack. They are in each others. (One membe: guid 42811). I'm also unable to find brontus.

![WoWScrnShot_061422_212315](https://user-images.githubusercontent.com/100411212/173673943-2fdb4a4f-faa1-4fbe-908e-d7a5ea552ec3.jpg)

2022-06-14 19:50 UTC, Nefertumm commented on data/sql/updates/pending_db_world/rev_1655187726583284000.sql
> +('393', '394', '15', 'Brontus Kodo Pack Combo 3 -- Brontus Pack');
remove ' from ints please :D

2022-06-14 19:51 UTC, Nefertumm commented on data/sql/updates/pending_db_world/rev_1655187726583284000.sql
> +DELETE FROM `pool_pool` WHERE pool_id IN (391, 392, 393);
```suggestion
DELETE FROM `pool_pool` WHERE `pool_id` IN (391, 392, 393);
```

2022-06-14 19:51 UTC, Nefertumm commented on data/sql/updates/pending_db_world/rev_1655187726583284000.sql
> +DELETE FROM `creature` WHERE guid IN (51815);
```suggestion
DELETE FROM `creature` WHERE `guid` IN (51815);
```

2022-06-14 19:51 UTC, Nefertumm commented on data/sql/updates/pending_db_world/rev_1655187726583284000.sql
> +DELETE FROM `pool_template` WHERE entry IN (391, 392, 393);
```suggestion
DELETE FROM `pool_template` WHERE `entry` IN (391, 392, 393); 
```

2022-06-14 19:51 UTC, Nefertumm commented on data/sql/updates/pending_db_world/rev_1655187726583284000.sql
> +DELETE FROM `creature_formations` where leaderGUID in(45809, 45813, 45817);
```suggestion
DELETE FROM `creature_formations` WHERE `leaderGUID` IN (45809, 45813, 45817);
```

2022-06-14 19:56 UTC, Nefertumm commented on data/sql/updates/pending_db_world/rev_1655187726583284000.sql
> +INSERT INTO waypoint_data (id,point,position_x,position_y,position_z,orientation,delay,move_type,action,action_chance,wpguid) VALUES
```suggestion
DELETE FROM `creature_addon` WHERE `guid` IN (@NPC, @NPC+4, @NPC+8);
INSERT INTO `creature_addon` (`guid`,`path_id`,`mount`,`bytes1`,`bytes2`,`emote`,`visibilityDistanceType`,`auras`) VALUES
(@NPC,@path,0,0,1,0,0, ''),
(@NPC+4,@path,0,0,1,0,0, ''),
(@NPC+8,@path,0,0,1,0,0, '');

DELETE FROM `waypoint_data` WHERE `id`=@path;
INSERT INTO `waypoint_data` (`id`,`point`,`position_x`,`position_y`,`position_z`,`orientation`,`delay`,`move_type`,`action`,`action_chance`,`wpguid`) VALUES
```

2022-06-14 19:56 UTC, Nefertumm requested changes
Please, address what I pointed out, ty!

2022-06-14 20:03 UTC, Nefertumm commented on data/sql/updates/pending_db_world/rev_1655187726583284000.sql
> +DELETE FROM `pool_creature` WHERE guid IN (45809, 45810, 45811, 45812, 45813, 45814, 45815, 45816, 45817, 45818, 45819, 45820);
```suggestion
DELETE FROM `pool_creature` WHERE `guid` IN (45809, 45810, 45811, 45812, 45813, 45814, 45815, 45816, 45817, 45818, 45819, 45820);
```

2022-06-14 20:05 UTC, Nefertumm commented on data/sql/updates/pending_db_world/rev_1655187726583284000.sql
> +DELETE FROM `pool_creature` WHERE guid IN (45809, 45810, 45811, 45812, 45813, 45814, 45815, 45816, 45817, 45818, 45819, 45820);
Only this one left :D

2022-06-14 20:05 UTC, Maelthyrr commented
Recheck IG, and everything is fine. I pass in to be merge, but I let you fix the review ;)

Thanks for you work ! <3

2022-06-14 20:10 UTC, Nefertumm commented on data/sql/updates/pending_db_world/rev_1655187726583284000.sql
> +SET @path := @NPC * 10;
Path should be on upper case, but you can leave it as it is for this one if you want.

2022-06-14 20:14 UTC, Nefertumm approved these changes

2022-06-18 12:28 UTC, acidmanifesto commented
Thank you for the PR.

2022-06-18 12:28 UTC, merged