fix(DB/creature_template): Fix Domesticated Felboar
azerothcore/azerothcore-wotlk pull request #12057
Opened 2022-06-14 16:07 UTC by ZhengPeiRu21

## Changes Proposed:
-  Remove loot, skinning loot, and XP from Domesticated Felboar

## Issues Addressed:

- Closes #11817 

## SOURCE:

See original issue

## Tests Performed:

- Killed creature, no loot, no XP, not skinnable

## How to Test the Changes:

1. .go cr 77832
2. Kill creature, check for loot, XP, and skinnable

## Known Issues and TODO List:

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

2022-06-15 05:21 UTC, IntelligentQuantum approved these changes

2022-06-18 12:34 UTC, acidmanifesto requested changes
skinning loot was introduced in 3.0.1
https://www.wowhead.com/wotlk/npc=21195/domesticated-felboar#skinning
Will get with staff to figure out the best course of action regarding this PR and the Issue.

2022-06-18 12:39 UTC, acidmanifesto approved these changes
after research this PR is consider valid, this was one of those unique cases where the sniffs were from a earlier wraith version of it being introduced where it was removed in later versions of wraith.
![image](https://user-images.githubusercontent.com/16887899/174438026-4147fea7-a14a-41f9-98a3-b9221977af3c.png)

2022-06-18 12:39 UTC, acidmanifesto commented
Thank you for the PR

2022-06-18 12:40 UTC, merged