fix(scripts/RuinsOfAhnQiraj): Improve Kurinnaxx
azerothcore/azerothcore-wotlk pull request #12136
Opened 2022-06-21 16:26 UTC by Si1ker

## Changes Proposed:
- Cleanup/refactor
- Migrate trash spell handling from script to db
- Guides state that cleave (WideSlash) applies the 'Mortal Wound' debuff but videos demonstrate that it does not apply them. Those are separate events.
source: https://youtu.be/EgazIWGM0n0?t=30 AND https://youtu.be/idACansl4-0?t=3 / https://youtu.be/idACansl4-0?t=14

## Issues Addressed:

- Closes 

## SOURCE:

## Tests Performed:

- 
- 

## How to Test the Changes:

1.
2.
3.

## Known Issues and TODO List:

* Sand traps require scripting.

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

2022-07-10 22:04 UTC, Si1ker commented
ready

2022-07-10 23:22 UTC, acidmanifesto submitted a review, later dismissed
Now I really do like the idea of DoCastSelf in place of Docast(me,XXX) as that is more appropiate. But i am curious why are we moving thrash to a creature aura in the addons? You made mention of referencing mangos for the adjustment due to their timer, where they also have thrash on a timer as well. What was the determining factor in your choice in moving it to the db is not exactly clear to me, can you provide some insight in that decision? We had a past incident with a massive thrash pr that had to be clean up manually and just want to make sure we are not ending up in a repeat with this creature atleast.

2022-07-11 13:15 UTC, Nyeriah approved these changes

2022-07-11 13:16 UTC, Nyeriah requested changes

2022-07-15 19:47 UTC, Nefertumm commented on src/server/scripts/Kalimdor/RuinsOfAhnQiraj/boss_kurinnaxx.cpp
> +
This needs to be double-checked. This spell is usually used by boss to summon unreachable players.

2022-07-16 00:59 UTC, Gultask commented
Tested.

There is the usual inconsistency with Thrash, as it can trigger 3 times in a row and then not trigger for the next 30s. But that's expected with the aura.

The Mortal Wounds and Wide Slash events work.

One question. Would Nix PR work for this boss? So that it won't need the summon player script? Or is it different and based on distance and not due to evades? The arena is rather complex.

2022-07-16 13:29 UTC, Nefertumm commented
@Gultask indeed, that's why I wrote that it needs to be double checked. With Nix' PR it won't be needed on this PR.

2022-07-18 15:29 UTC, Si1ker commented on data/sql/updates/pending_db_world/rev_1655863615360060800.sql
> +DELETE FROM `creature_addon` WHERE `guid`=144632;
we've been using creature_addon, so will use it.

2022-07-18 15:42 UTC, Gultask commented
I took a quick look at the boss in retail and the TP mechanic was present there, albeit broken since it was spammed so hard I could not move away from the boss. I'll try it again someday with another class to see if there's a difference.

And this is the PR I was talking about: https://github.com/azerothcore/azerothcore-wotlk/pull/12193

2022-07-18 18:18 UTC, Nefertumm approved these changes

2022-07-20 17:09 UTC, merged

2022-07-20 17:10 UTC, Si1ker commented
## Known Issues and TODO List:
<!-- Is there anything else left to do after this PR? -->
* Sand traps require scripting.