fix(DB/GameObject): Add missing Alliance Bonfire in Feralas
azerothcore/azerothcore-wotlk pull request #12190
Opened 2022-06-26 08:26 UTC by Meramaf

## Changes Proposed:
-  Add missing Spawn to Alliance Bonfire in Feralas.
-  Extinguishing Kalimdor Achivement work now correctly.
- Midsummer Bonfire

## Issues Addressed:

- Closes 

## SOURCE:

## Tests Performed:

- 
- 

## How to Test the Changes:

1.
2.
3.

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

2022-06-28 06:17 UTC, Maelthyrr commented
@Meramaf why this go  is  alone (21018) ? Do  you have a source for this ?

<details>

![WoWScrnShot_062822_081140](https://user-images.githubusercontent.com/100411212/176106841-a849737d-7ad3-44dd-ae0e-31dac55deaca.jpg)

</details>

2022-06-28 07:45 UTC, Meramaf commented
> @Meramaf why this go  is  alone (21018) ? Do  you have a source for this ?
> 
> 
> 
> <details>
> 
> 
> 
> ![WoWScrnShot_062822_081140](https://user-images.githubusercontent.com/100411212/176106841-a849737d-7ad3-44dd-ae0e-31dac55deaca.jpg)
> 
> 
> 
> </details>

Im ported this from TC. Maybe it for Horde?

2022-06-28 20:28 UTC, acidmanifesto commented
https://www.wowhead.com/object=187929/alliance-bonfire
This item is for the midfiresummer fest.
Can we test with the event acitve. there is suppose to be small tent and other stuff near by. we could be missing those as well.

2022-06-28 23:02 UTC, Nefertumm commented
21018 is actually from Cataclysm. You can read more about it here https://github.com/azerothcore/azerothcore-wotlk/pull/12129

2022-07-09 10:51 UTC, Maelthyrr commented
@Meramaf so can you remove gob 21018? Thanks :)

2022-07-09 14:41 UTC, acidmanifesto requested changes
https://github.com/azerothcore/azerothcore-wotlk/pull/12190#issuecomment-1179523173

2022-07-10 16:33 UTC, acidmanifesto approved these changes

2022-07-10 17:24 UTC, Nefertumm commented on data/sql/updates/pending_db_world/extinguishing_kalimdor.sql
> +INSERT INTO `game_event_gameobject` (`eventEntry`, `guid`) VALUES ('1', '164905');
Don't use ' around integers.

2022-07-10 17:37 UTC, acidmanifesto requested changes
Pending Feedback

2022-07-10 17:38 UTC, acidmanifesto commented
marking as pending feedback and needs to research to ensure this isnt reverting another pr. that was merged

2022-10-20 13:27 UTC, acidmanifesto commented
Do we have any actual verification of this gameobject placement?

2022-10-24 08:29 UTC, Maelthyrr commented
> Do we have any actual verification of this gameobject placement?

No until the next event on woltk classic.

2023-01-15 14:18 UTC, Kitzunu commented
Closing as there is no reason to have a PR open you need to wait a year on for verification. Open an issue instead

2023-01-15 14:18 UTC, closed without merging