Script/Spell: fix Midsummer's Juggling Torch
azerothcore/azerothcore-wotlk pull request #12198
Opened 2022-06-26 14:35 UTC by Meramaf

## Changes Proposed:
-  This Fix adressed to Achievement "Juggle 40 torches in 15 seconds in Dalaran." 
https://www.wowhead.com/achievement=272/torch-juggler

## How to Test the Changes:

1. .additem 34599 40
2. .tele dalaran
3. cast item on self

2022-06-27 07:31 UTC, Meramaf commented
Tested and work

2022-06-28 06:10 UTC, Maelthyrr commented
Tested and work fine.

<details>

![WoWScrnShot_062822_080925](https://user-images.githubusercontent.com/100411212/176105765-4895cc76-ba59-41d2-9316-70edb9892695.jpg)

</details>

2022-06-28 13:07 UTC, IntelligentQuantum commented on src/server/scripts/Events/midsummer.cpp
> +            return;
Bracket

2022-06-28 13:07 UTC, IntelligentQuantum commented on src/server/scripts/Events/midsummer.cpp
> +            player->CastSpell(player, SPELL_GIVE_TORCH);
bracket

2022-06-28 20:30 UTC, acidmanifesto requested changes
please add the request missing brackets from the reviewer.

2022-06-28 22:59 UTC, Nefertumm commented on data/sql/updates/pending_db_world/juggling_torch_fix.sql
> +DELETE FROM `spell_script_names` WHERE `spell_id` = '45644';
```suggestion
DELETE FROM `spell_script_names` WHERE `spell_id` = 45644;
```
Please don't use ' around numbers unless the column data is string

2022-06-28 23:00 UTC, Nefertumm commented on src/server/scripts/Events/midsummer.cpp
> +    QUEST_TORCH_CATCHING_H           = 11923
Please, align correctly these lines :)

2022-07-02 20:27 UTC, acidmanifesto approved these changes

2022-07-02 20:30 UTC, acidmanifesto commented
Thank you for the PR

2022-07-02 20:30 UTC, merged