fix(Core/Creatures): Implemented CREATURE_FLAG_EXTRA_TELEPORT_UNREACH…
azerothcore/azerothcore-wotlk pull request #12193
Opened 2022-06-26 11:26 UTC by UltraNix

…ABLE_PLAYERS.

Fixed #11750

## Changes Proposed:
-  Creature with this flag will teleport unreachable (due to mmaps) current target to itself.
-  Non-raid mobs that cannot reach (due to mmaps) its current target will switch to another target (if any) instead of evading 

## Issues Addressed:

- Closes #11750

## Tests Performed:

- Tested ingame.

## How to Test the Changes:

`.go creature id 11382`
Aggro boss
`.gm fly on`
.go xyz -12191.968750 -1947.059570 152`
Wait at least 5 sec to see that Mandokir teleports you

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

2022-06-26 13:33 UTC, Maelthyrr commented
Tested and work fine.

2022-06-26 20:52 UTC, Nefertumm commented
Seems like this pr is doing some kind of revert

2022-06-27 09:19 UTC, Nyeriah commented
Hm this is wrong, bosses use a spell (summon player) to teleport players to themselves. The behavior here, however, is legit as it happens in some cases, but what usually happens is that the mobs teleport themselves to players (happens quite often with zg fish @ retail, they can't leave water and they end up teleporting to you inland)

2022-06-27 09:50 UTC, UltraNix commented
@Nyeriah It's hard to find these summon spells and what bosses should use it. I think flag do their job.

2022-07-01 15:33 UTC, acidmanifesto commented
> Hm this is wrong, bosses use a spell (summon player) to teleport players to themselves. The behavior here, however, is legit as it happens in some cases, but what usually happens is that the mobs teleport themselves to players (happens quite often with zg fish @ retail, they can't leave water and they end up teleporting to you inland)

So is this a no merge situation or do we merge the PR?

2022-07-01 17:27 UTC, UltraNix commented
Or course we merge it.

2022-07-01 17:46 UTC, Nyeriah commented
https://github.com/vmangos/core/blob/development/src/scripts/eastern_kingdoms/stranglethorn_vale/zulgurub/boss_mandokir.cpp

vmangos has the spell documented and it is the same I found in bwl

2022-07-01 17:49 UTC, acidmanifesto commented
Labeling as tested since it is done being tested. Need further discussion if this is correct, not correct, grey zone annakin skywalker way of doing it.

2022-07-01 17:53 UTC, Nyeriah commented
I have no issues with merging this but we have to keep in mind the bosses should be using the spells and the trash mobs behave differently depending on the situation (they either port themselves to players and on more rarer occasions (never seen but heard about it) they teleport the players to themselves)

2022-07-09 06:51 UTC, UltraNix commented
@acidmanifesto @Nyeriah Rewritten to use summon spells. Should be okay now.

2022-07-09 10:15 UTC, temperrr commented
Build failing :(

2022-07-09 10:24 UTC, UltraNix commented
@temperrr Should be okay now.

2022-07-09 14:40 UTC, acidmanifesto requested changes
dry run error
![image](https://user-images.githubusercontent.com/16887899/178110524-50a043a8-a3f1-4658-9117-088b4f563ff1.png)

2022-07-09 15:09 UTC, UltraNix commented
@acidmanifesto Should be okay now.

2022-07-09 15:52 UTC, Maelthyrr commented
Tested and work.

2022-07-09 15:56 UTC, acidmanifesto approved these changes

2022-07-09 22:43 UTC, Nefertumm commented
Update the title maybe? :D

2022-07-10 18:16 UTC, acidmanifesto submitted a review, later dismissed
Per Comment, Request title update of PR

2022-07-11 05:01 UTC, mpfans commented
@UltraNix please,tyvm

2022-07-16 07:52 UTC, UltraNix commented
@acidmanifesto Done.

2022-07-18 15:58 UTC, Si1ker commented
Good PR, although I think 5 seconds is kinda high, 5 seconds of kitting feels a lot, 3 seconds of max-kitting I think would be better. (opinion). If there's a source for 5 sec, then ignore.

2022-07-24 16:10 UTC, Nyeriah approved these changes

2022-07-24 16:10 UTC, merged