fix(Scripts/World: Spawn adds scale with raid size
azerothcore/azerothcore-wotlk pull request #12352
Opened 2022-07-10 17:21 UTC by Maelthyrr

…ssues/12279

## Changes Proposed:
-  Spawn adds will scale with raid size. Max is set to 15 adds.
-  

## Issues Addressed:

- Closes 

## SOURCE:

Cherry-pick: https://github.com/vmangos/core/blob/development/src/scripts/world/dragons_of_nightmare/boss_ysondre.cpp

## Tests Performed:

- None
- 

## How to Test the Changes:

1. Engage 
2.
3.

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

2022-07-10 17:22 UTC, Maelthyrr commented
@UltraNix can I get your review ? I'm really not sure about the line 276, but I don't find another way to use the condition isAlive and isGamemaster.

2022-07-10 17:36 UTC, acidmanifesto approved these changes

2022-07-10 17:59 UTC, UltraNix commented on src/server/scripts/World/boss_emerald_dragons.cpp
> +                    if (Player* pPlayer = attacker->GetSource()->GetOwner()->ToPlayer())
`Player* player` Say `No` to hungarian notations

2022-07-10 18:00 UTC, UltraNix commented on src/server/scripts/World/boss_emerald_dragons.cpp
> +                        if (pPlayer && pPlayer->IsAlive() && !pPlayer->IsGameMaster())
`pPlayer` check needed - done above.

2022-07-10 18:00 UTC, UltraNix requested changes
`if (Player* pPlayer = attacker->GetSource()->GetOwner()->ToPlayer())`
`attacker->GetSource()->GetOwner()` Are you sure it will never crash? `GetOwner` is always there?

2022-07-10 18:08 UTC, Maelthyrr commented
> `if (Player* pPlayer = attacker->GetSource()->GetOwner()->ToPlayer())` `attacker->GetSource()->GetOwner()` Are you sure it will never crash? `GetOwner` is always there?

It's was I asked, I don't see what use using the threatlist to check the state of players. Maybe isOnline ?

2022-07-10 18:18 UTC, Nyeriah commented
Just one consideration: game masters (gm mode on) should never be in a creature's threat list as well as dead players (but I'm not entirely sure about the second ones)

2022-07-10 18:23 UTC, Maelthyrr commented
I ask myself. If a player is in threatlist, he should be alive? If he die, he gone. So the two conditions are just useless ?

2022-07-10 18:27 UTC, Nyeriah commented
The GM one yes I'm sure, they're not valid targets so they can't be added to the threatlist. As for the dead players, I am not entirely sure, but I think we don't store references for dead players, yes

2022-07-10 18:37 UTC, temperrr commented
- [ ] 1 raider - 3 adds
- [ ] 5 raiders - 3 adds

2022-07-10 18:44 UTC, Gultask commented
I had the same results as temperrr but I tested it before the latest updates. I'll check again.

Also, I think you can remove the minimum spawn of 3 and set it to 1. In WotLK there wasn't a minimum of 3.
https://youtu.be/cheP7oKQdN4?t=39 here spawns only one.

2022-07-10 19:03 UTC, Maelthyrr commented
Need to add a check to be sure that a player is target. But I don't how treat with threatref to apply these checks. So I let someone else fix this.

2022-07-12 07:37 UTC, temperrr commented
tested, works

2022-07-12 07:39 UTC, closed without merging