fix(DB/SAI): Zulian Crocolisk has scripted movement
azerothcore/azerothcore-wotlk pull request #12460
Opened 2022-07-20 22:08 UTC by neifion-00000000

-  Adds id 2 and 3 into creature 15043's smart scripts.
-  Movement loops 30 seconds of 0 movement, 10 seconds of random movement in a small radius

## SOURCE:

Sniffed timers and estimated movement values
## Tests Performed:

- Tested in ZG, they actually maintain unison which is correct/better results than I expected.  They're quite convincing of the true behavior imo.

## How to Test the Changes:

1. Goto ZG
2. Watch any croc pack for a couple mins

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

2022-07-20 22:11 UTC, neifion-00000000 commented
special thanks @55Honey  for the radius suggestion, saved time over my first guess.

2022-07-21 00:14 UTC, ZhengPeiRu21 commented
Thank you Neifion! VMangos is having a field in their waypoint data table to set wander distance when a creature is at a waypoint with a long delay. If we see many more creatures that should be having movement patterns like this, I think we should implement that feature as well to save lots of manual scripting!

2022-07-21 02:14 UTC, neifion-00000000 commented
> Thank you Neifion! VMangos is having a field in their waypoint data table to set wander distance when a creature is at a waypoint with a long delay. If we see many more creatures that should be having movement patterns like this, I think we should implement that feature as well to save lots of manual scripting!

that won't impact this one but yes I agree, it would cut down on the what I feel is pointless need for SAI in a lot of other packs.

waypoint_data also has issues with emotes firing off in weird ways too so pretty much everything that isn't a strict path needs dealt with in SAI atm

2022-07-21 03:37 UTC, neifion-00000000 commented
found a bug in this, the mobs will now drift due to SAI random waypoint function

2022-07-22 20:30 UTC, neifion-00000000 commented
fixed, this requires #12468 to function

2022-07-23 01:16 UTC, acidmanifesto commented on data/sql/updates/pending_db_world/rev_1658354450598559500.sql
> +/* Crocs movement is a scripted action that occurs about every 30 seconds, not normal random movement */
no /* */ you sinner

2022-07-23 01:18 UTC, acidmanifesto requested changes
![image](https://user-images.githubusercontent.com/16887899/180584872-221ae038-2698-404d-bea9-29654f92ffd5.png)

2022-07-23 01:25 UTC, acidmanifesto approved these changes
Checks should be good. Too high on sugar booger to stay up for work flow to turn green.
**Snorting happy line noises**

2022-07-24 01:10 UTC, Gultask commented
Tested and it really does look much more like retail 👍

2022-07-24 16:49 UTC, Nyeriah requested changes

2022-07-24 16:49 UTC, Nyeriah commented on data/sql/updates/pending_db_world/rev_1658354450598559500.sql
> +DELETE FROM `smart_scripts` WHERE `entryorguid`=15043;
missing sourcetype, without it we risk deleting gameobject scripts for example

2022-07-24 20:21 UTC, Nyeriah approved these changes

2022-07-24 20:21 UTC, merged