fix(DB/creature_formations): Fixes Agro on pack
azerothcore/azerothcore-wotlk pull request #12494
Opened 2022-07-23 00:28 UTC by neifion-00000000

## Changes Proposed:
-  Creature formations that should have been in #12371 implemented

## SOURCE:
Retail/Sniff

## How to Test the Changes:

1.  Check to see if all the snakes agro when 1 does, particularly when pulling from the side.  See #12371 for more information.

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

2022-07-23 01:04 UTC, acidmanifesto requested changes
Review left for adjustment to pass sql check

2022-07-23 01:04 UTC, acidmanifesto commented on data/sql/updates/pending_db_world/rev_1658535848721793000.sql
> +--
remove or make this a line break.

2022-07-23 01:04 UTC, acidmanifesto commented on data/sql/updates/pending_db_world/rev_1658535848721793000.sql
> +--
remove or make this a line break.

2022-07-23 01:04 UTC, acidmanifesto commented on data/sql/updates/pending_db_world/rev_1658535848721793000.sql
> +--
remove or make this a line break.

2022-07-23 01:04 UTC, acidmanifesto commented on data/sql/updates/pending_db_world/rev_1658535848721793000.sql
> +--
remove or make this a line break.

2022-07-23 01:04 UTC, acidmanifesto commented on data/sql/updates/pending_db_world/rev_1658535848721793000.sql
> +--
remove or make this a line break.

2022-07-23 01:04 UTC, acidmanifesto commented on data/sql/updates/pending_db_world/rev_1658535848721793000.sql
> +--
remove or make this a line break.

2022-07-23 01:04 UTC, acidmanifesto commented on data/sql/updates/pending_db_world/rev_1658535848721793000.sql
> +--
remove or make this a line break.

2022-07-23 01:04 UTC, acidmanifesto commented on data/sql/updates/pending_db_world/rev_1658535848721793000.sql
> +--
remove or make this a line break.

2022-07-23 01:04 UTC, acidmanifesto commented on data/sql/updates/pending_db_world/rev_1658535848721793000.sql
> +--
remove or make this a line break.

2022-07-23 01:04 UTC, acidmanifesto commented on data/sql/updates/pending_db_world/rev_1658535848721793000.sql
> +--
remove or make this a line break.

2022-07-23 01:04 UTC, acidmanifesto commented on data/sql/updates/pending_db_world/rev_1658535848721793000.sql
> +--
remove or make this a line break.

2022-07-23 01:04 UTC, acidmanifesto commented on data/sql/updates/pending_db_world/rev_1658535848721793000.sql
> +--
remove or make this a line break.

2022-07-23 01:04 UTC, acidmanifesto commented on data/sql/updates/pending_db_world/rev_1658535848721793000.sql
> +--
remove or make this a line break.

2022-07-23 01:04 UTC, acidmanifesto commented on data/sql/updates/pending_db_world/rev_1658535848721793000.sql
> +--
remove or make this a line break.

2022-07-23 01:04 UTC, acidmanifesto commented on data/sql/updates/pending_db_world/rev_1658535848721793000.sql
> +--
remove or make this a line break.

2022-07-23 01:04 UTC, acidmanifesto commented on data/sql/updates/pending_db_world/rev_1658535848721793000.sql
> +--
remove or make this a line break.

2022-07-23 01:04 UTC, acidmanifesto commented on data/sql/updates/pending_db_world/rev_1658535848721793000.sql
> +--
remove or make this a line break.

2022-07-23 01:04 UTC, acidmanifesto commented on data/sql/updates/pending_db_world/rev_1658535848721793000.sql
> +--
remove or make this a line break.

2022-07-23 01:04 UTC, acidmanifesto commented on data/sql/updates/pending_db_world/rev_1658535848721793000.sql
> +--
remove or make this a line break.

2022-07-23 01:04 UTC, acidmanifesto commented on data/sql/updates/pending_db_world/rev_1658535848721793000.sql
> +--
remove it and make it a blank line.

2022-07-23 01:14 UTC, acidmanifesto approved these changes
**Approve Review Noises**

2022-07-27 04:04 UTC, Gultask commented
Saw no issues 👍

2022-08-01 20:09 UTC, merged