fix(Core): Crashfix.
azerothcore/azerothcore-wotlk pull request #12643
Opened 2022-08-06 08:56 UTC by UltraNix

## Tests Performed:

- More info [here](https://github.com/azerothcore/azerothcore-wotlk/pull/12347#issuecomment-1204535914)

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

2022-08-06 08:57 UTC, UltraNix commented
@Nefertumm Please, test it.

2022-08-06 11:29 UTC, pklloveyou commented on data/sql/updates/pending_db_characters/rev_1659776114435282400.sql
> +CHANGE `taxiPath` `taxiPath1` INT UNSIGNED DEFAULT 0 NOT NULL;
taxiPath0 ?

2022-08-06 11:30 UTC, pklloveyou commented on data/sql/updates/pending_db_characters/rev_1659776114435282400.sql
> +CHANGE `taxiPath` `taxiPath1` INT UNSIGNED DEFAULT 0 NOT NULL;
sorry I misread it

2022-08-06 11:50 UTC, Maelthyrr commented
Tested and no crash but I got a strange thing. When I enter in bg or dungeon, I'm quickly tp at the destination before to be tp in dungeon/bg.

https://youtu.be/OTVb6D36mEU

2022-08-06 12:37 UTC, pklloveyou commented
@Maelthyrr ```player->TeleportTo(node->map_id, node->x, node->y, node->z, player->GetOrientation());``` Delete it and there will be no "destination in 1 second"

2022-08-06 12:37 UTC, pklloveyou commented
@Maelthyrr ```player->TeleportTo(node->map_id, node->x, node->y, node->z, player->GetOrientation());``` Delete it and there will be no "destination in 1 second"

2022-08-06 17:38 UTC, Nefertumm commented on data/sql/updates/pending_db_characters/rev_1659776114435282400.sql
> +CHANGE `taxiPath` `taxiPath1` INT UNSIGNED DEFAULT 0 NOT NULL;
This query is giving me an error, probably because some of the values for this is an empty string:
`
Truncated incorrect INTEGER value: ''
`

2022-08-06 18:15 UTC, Nefertumm commented
I tested it as well and I got the same result as Maelthyrr, it flashes the endpoint position of the path before entering the bg/dungeon.
Also I suggest to remove https://github.com/azerothcore/azerothcore-wotlk/blob/master/src/server/game/Movement/MovementGenerators/WaypointMovementGenerator.cpp#L318 as it is spawning a lot of creatures and with a long uptime, it increases the update time diff.

2022-08-07 06:10 UTC, pklloveyou commented
@Nefertumm Can you try deleting these two lines of code?
``` sMapMgr->CreateMap(nodes[i]->mapid, player)->SummonCreature(1, { nodes[i]->x, nodes[i]->y, nodes[i]->z, 0.0f })->SetLevel(i ? i : 1); ```
and
``` player->TeleportTo(node->map_id, node->x, node->y, node->z, player->GetOrientation()); ```
I tested this PR after deleting and found no error

2022-08-07 07:18 UTC, Nefertumm commented
I will test it later, ty!

2022-08-07 12:59 UTC, UltraNix commented
@pklloveyou You changes work okay?

2022-08-07 13:20 UTC, pklloveyou commented
@UltraNix No errors found so far

2022-08-07 15:13 UTC, acidmanifesto requested changes

2022-08-07 15:13 UTC, acidmanifesto commented on src/server/game/Movement/MovementGenerators/WaypointMovementGenerator.cpp
> -            player->TeleportTo(node->map_id, node->x, node->y, node->z, player->GetOrientation());
error on unsued variable node now in line 364.

2022-08-07 19:04 UTC, UltraNix commented
@acidmanifesto Should be okay.

2022-08-07 19:34 UTC, acidmanifesto approved these changes
^(;,;)^ May Cthulhu Bless us all

2022-08-07 19:54 UTC, Nefertumm commented
build is complaining again, taxiNodeId is unused

2022-08-07 19:57 UTC, UltraNix commented
@Nefertumm Fixed.

2022-08-07 21:22 UTC, merged