fix(Scripts/AhnQiraj): Implemented General Andorov event.
azerothcore/azerothcore-wotlk pull request #12645
Opened 2022-08-06 15:57 UTC by UltraNix

Original author: @Rushor
Fixes #12173

## Issues Addressed:

- Closes #12173

## Tests Performed:

- Not tested.

## How to Test the Changes:

Kill Kurinnaxx
Look if NPC come or not

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

2022-08-06 16:56 UTC, Gultask commented
- [ ] They spawn immediately in Kurinnaxx's arena, and not at the start of the raid.
- [ ] They engage in combat with nearby trash around Kurinnaxx's arena.
- [ ] There's no gossip menu, right clicking on Andorov will immediately start the event.
- [ ] There's a vendor mouse icon when hovering over Andorov, even before the encounter with Rajaxx starts or ends.
- [ ] The Kaldorei Elite are all standing on top of each other.

2022-08-06 17:24 UTC, Nefertumm commented on data/sql/updates/pending_db_world/rev_1659801375917048100.sql
> +(@ENTRY,0,0,0,0,0,100,0,5000,9000,5000,9000,11,40504,0,0,0,0,0,2,0,0,0,0,0,0,0,"Swarmguard Needler - In Combat - Cast 'Cleave'");
This one is already present on the core and it is sniffed, this doesn't match the values we got from sniff, remove it, please :)

2022-08-06 17:24 UTC, Nefertumm commented on data/sql/updates/pending_db_world/rev_1659801375917048100.sql
> +(15471, 0, -8876.79, 1634.59, 21.3864, 0, 'Andronov'),
minimal but the comment is wrong, is Andorov.

2022-08-06 17:35 UTC, Nyeriah commented
I already implemented the waves...
We just need to spawn andorov

2022-08-06 17:36 UTC, UltraNix commented
@Nyeriah So why this report was not assigned to anybody nor any info that somebody is already working on it?

2022-08-06 17:50 UTC, Nyeriah commented
Because Andorov isn't related to Rajaxx waves and I didnt do anything with Andorov.

You can pull Rajaxx by talking to Andorov but they are not connected, you can skip the Andorov thing on retail altogether

I checked the code and the way the TC guys did it also doesn't match our research:
1) the timer should be two minutes (they set it to 1 min)
2) Rajaxx doesnt say anything during the waves if they get pulled by the timer (it is some sort of dps check)
3) Waves are pulled in successesion as soon as all members are dead, not on timer only

All of the above works

What was missing:
- Andorov spawn at the start of the entrance
- Talking to Andorov initiates a sequence where he walks to the arena and taunts Rajaxx and they trade a few lines
- The waves target Andorov it seems when they are pulled

So the alternative start (through gossip) was missing

2022-08-06 17:56 UTC, UltraNix commented
Okay.

2022-08-07 13:33 UTC, Maelthyrr commented
@UltraNix since the last commit is it always in WIP ? I've just tested against and I got the same issue than Gultask.

2022-08-07 13:45 UTC, UltraNix commented
It is in WIP because still waiting for proper spawn position and waypoints.

2022-08-07 13:56 UTC, Gultask commented
Ah, sorry for the delay. Here are the spawn sniffs:

<details>
 <summary>Details</summary>

ServerToClient: SMSG_UPDATE_OBJECT (0x27BA) Length: 3344 ConnIdx: 1 Time: 07/24/2022 22:57:58.490 Number: 4981
NumObjUpdates: 5
MapID: 509 (509)
HasRemovedObjects: False
Data size: 3333
[0] UpdateType: CreateObject2
[0] Object Guid: Full: 0x2030F43FA00F1BC00068F700005DF8A6 Creature/0 R3133/S26871 Map: 509 Entry: 15471 Low: 6158502
[0] Object Type: 5 (Unit)
[0] NoBirthAnim: False
[0] EnablePortals: False
[0] PlayHoverAnim: False
[0] HasMovementUpdate: True
[0] HasMovementTransport: False
[0] Stationary: False
[0] HasCombatVictim: False
[0] HasServerTime: False
[0] HasVehicleCreate: False
[0] HasAnimKitCreate: False
[0] HasRotation: False
[0] HasAreaTrigger: False
[0] HasGameObject: False
[0] HasSmoothPhasing: False
[0] ThisIsYou: False
[0] SceneObjCreate: False
[0] HasPlayerCreateData: False
[0] HasConversation: False
[0] MoverGUID: Full: 0x2030F43FA00F1BC00068F700005DF8A6 Creature/0 R3133/S26871 Map: 509 Entry: 15471 Low: 6158502
[0] MovementFlags: 1 (Forward)
[0] MovementFlags2: 0 (None)
[0] MovementFlags3: 0 (None)
[0] MoveTime: 856902151
[0] Position: X: -8538.177 Y: 1486.0956 Z: 32.39054
[0] Orientation: 3.763865470886230468
[0] Pitch: 0
[0] StepUpStartElevation: 0
[0] MoveIndex: 0
[0] Has Transport Data: False
[0] Has Fall Data: False
[0] HasSpline: True
[0] HeightChangeFailed: False
[0] RemoteTimeValid: False
[0] HasInertia: False
[0] WalkSpeed: 2.5
[0] RunSpeed: 8
[0] RunBackSpeed: 4.5
[0] SwimSpeed: 4.72221994400024414
[0] SwimBackSpeed: 2.5
[0] FlightSpeed: 7
[0] FlightBackSpeed: 4.5
[0] TurnRate: 3.141592741012573242
[0] PitchRate: 3.141592741012573242
[0] MovementForceCount: 0
[0] MovementForcesModMagnitude: 1
[0] HasMovementSpline: True
[0] ID: 4260
[0] Destination: X: -8583.434 Y: 1453.6205 Z: 32.032005
[0] MovementSplineMove: True
[0] SplineFlags: 2434793472 (CanSwim, Unknown5, Steering, Unknown10)
[0] Elapsed: 1
[0] Duration: 6967
[0] DurationModifier: 1
[0] NextDurationModifier: 1
[0] Face: 0
[0] HasSpecialTime: False
[0] PointsCount: 7
[0] HasSplineFilterKey: False
[0] HasSpellEffectExtraData: False
[0] HasJumpExtraData: False
[0] HasAnimationTierTransition: False
[0] Unknown901: False
[0] [0] Points: X: -8534.113 Y: 1489.0105 Z: 32.62407
[0] [1] Points: X: -8538.177 Y: 1486.0956 Z: 32.39054
[0] [2] Points: X: -8542.24 Y: 1483.1807 Z: 32.157013
[0] [3] Points: X: -8575.553 Y: 1459.2773 Z: 32.407005
[0] [4] Points: X: -8582.865 Y: 1454.0303 Z: 32.032005
[0] [5] Points: X: -8583.434 Y: 1453.6205 Z: 32.032005
[0] [6] Points: X: -8583.434 Y: 1453.6205 Z: 32.032005
[0] PauseTimesCount: 0
[0] FieldFlags: 4 (UnitAll)
[0] EntryID: 15471
[0] DynamicFlags: 0
[0] Scale: 1
[0] DisplayID: 15688
[0] [0] NpcFlags: 1
[0] [1] NpcFlags: 0
[0] StateSpellVisualID: 0
[0] StateAnimID: 1716
[0] StateAnimKitID: 0
[0] StateWorldEffectsQuestObjectiveID: 0
[0] SpellOverrideNameID: 0
[0] Charm: Full: 0x0
[0] Summon: Full: 0x0
[0] CharmedBy: Full: 0x0
[0] SummonedBy: Full: 0x0
[0] CreatedBy: Full: 0x0
[0] DemonCreator: Full: 0x0
[0] LookAtControllerTarget: Full: 0x0
[0] Target: Full: 0x0
[0] BattlePetCompanionGUID: Full: 0x0
[0] BattlePetDBID: 0
[0] (ChannelData) SpellID: 0
[0] (ChannelData) (SpellVisual) SpellXSpellVisualID: 0
[0] (ChannelData) (SpellVisual) ScriptVisualID: 0
[0] SummonedByHomeRealm: 0
[0] Race: 0
[0] ClassId: 2
[0] PlayerClassId: 0
[0] Sex: 0
[0] DisplayPower: 0
[0] OverrideDisplayPowerID: 0
[0] Health: 5873
[0] [0] Power: 38428
[0] [0] MaxPower: 38428
[0] [1] Power: 0
[0] [1] MaxPower: 0
[0] [2] Power: 0
[0] [2] MaxPower: 219
[0] [3] Power: 0
[0] [3] MaxPower: 0
[0] [4] Power: 0
[0] [4] MaxPower: 0
[0] [5] Power: 0
[0] [5] MaxPower: 0
[0] [6] Power: 0
[0] [6] MaxPower: 0
[0] [0] PowerRegenFlatModifier: 0
[0] [0] PowerRegenInterruptedFlatModifier: 0
[0] [1] PowerRegenFlatModifier: 0
[0] [1] PowerRegenInterruptedFlatModifier: 0
[0] [2] PowerRegenFlatModifier: 0
[0] [2] PowerRegenInterruptedFlatModifier: 0
[0] [3] PowerRegenFlatModifier: 0
[0] [3] PowerRegenInterruptedFlatModifier: 0
[0] [4] PowerRegenFlatModifier: 0
[0] [4] PowerRegenInterruptedFlatModifier: 0
[0] [5] PowerRegenFlatModifier: 0
[0] [5] PowerRegenInterruptedFlatModifier: 0
[0] [6] PowerRegenFlatModifier: 0
[0] [6] PowerRegenInterruptedFlatModifier: 0
[0] MaxHealth: 5873
[0] Level: 31
[0] EffectiveLevel: 0
[0] ContentTuningID: 1006
[0] ScalingLevelMin: 30
[0] ScalingLevelMax: 30
[0] ScalingLevelDelta: 1
[0] ScalingFactionGroup: 0
[0] ScalingHealthItemLevelCurveID: 0
[0] ScalingDamageItemLevelCurveID: 0
[0] FactionTemplate: 1608
[0] (VirtualItems) [0] ItemID: 21465
[0] (VirtualItems) [0] SecondaryItemModifiedAppearanceID: 0
[0] (VirtualItems) [0] ItemAppearanceModID: 0
[0] (VirtualItems) [0] ItemVisual: 0
[0] (VirtualItems) [1] ItemID: 21465
[0] (VirtualItems) [1] SecondaryItemModifiedAppearanceID: 0
[0] (VirtualItems) [1] ItemAppearanceModID: 0
[0] (VirtualItems) [1] ItemVisual: 0
[0] (VirtualItems) [2] ItemID: 0
[0] (VirtualItems) [2] SecondaryItemModifiedAppearanceID: 0
[0] (VirtualItems) [2] ItemAppearanceModID: 0
[0] (VirtualItems) [2] ItemVisual: 0
[0] Flags: 33280
[0] Flags2: 2097152
[0] Flags3: 0
[0] AuraState: 13631488
[0] [0] AttackRoundBaseTime: 2000
[0] [1] AttackRoundBaseTime: 2000
[0] BoundingRadius: 0.305999994277954101
[0] CombatReach: 1.5
[0] DisplayScale: 1
[0] CreatureFamily: 0
[0] CreatureType: 0
[0] NativeDisplayID: 15688
[0] NativeXDisplayScale: 1
[0] MountDisplayID: 0
[0] CosmeticMountDisplayID: 0
[0] StandState: 0
[0] PetTalentPoints: 0
[0] VisFlags: 0
[0] AnimTier: 0
[0] PetNumber: 0
[0] PetNameTimestamp: 0
[0] PetExperience: 0
[0] PetNextLevelExperience: 2147483647
[0] ModCastingSpeed: 1
[0] ModCastingSpeedNeg: 1
[0] ModSpellHaste: 1
[0] ModHaste: 1
[0] ModRangedHaste: 1
[0] ModHasteRegen: 1
[0] ModTimeRate: 1
[0] CreatedBySpell: 0
[0] EmoteState: 0
[0] BaseMana: 433
[0] SheatheState: 1
[0] PvpFlags: 1
[0] PetFlags: 0
[0] ShapeshiftForm: 0
[0] HoverHeight: 1
[0] MinItemLevelCutoff: 0
[0] MinItemLevel: 0
[0] MaxItemLevel: 0
[0] AzeriteItemLevel: 0
[0] WildBattlePetLevel: 0
[0] BattlePetCompanionExperience: 0
[0] BattlePetCompanionNameTimestamp: 0
[0] InteractSpellID: 0
[0] ScaleDuration: 100
[0] LooksLikeMountID: 0
[0] LooksLikeCreatureID: 0
[0] LookAtControllerID: -1
[0] TaxiNodesID: 0
[0] GuildGUID: Full: 0x0
[0] SilencedSchoolMask: 0
[0] NameplateAttachToGUID: Full: 0x0
[1] UpdateType: CreateObject2
[1] Object Guid: Full: 0x2030F43FA00F1C400068F700005DF8A6 Creature/0 R3133/S26871 Map: 509 Entry: 15473 Low: 6158502
[1] Object Type: 5 (Unit)
[1] NoBirthAnim: False
[1] EnablePortals: False
[1] PlayHoverAnim: False
[1] HasMovementUpdate: True
[1] HasMovementTransport: False
[1] Stationary: False
[1] HasCombatVictim: False
[1] HasServerTime: False
[1] HasVehicleCreate: False
[1] HasAnimKitCreate: False
[1] HasRotation: False
[1] HasAreaTrigger: False
[1] HasGameObject: False
[1] HasSmoothPhasing: False
[1] ThisIsYou: False
[1] SceneObjCreate: False
[1] HasPlayerCreateData: False
[1] HasConversation: False
[1] MoverGUID: Full: 0x2030F43FA00F1C400068F700005DF8A6 Creature/0 R3133/S26871 Map: 509 Entry: 15473 Low: 6158502
[1] MovementFlags: 0 (None)
[1] MovementFlags2: 0 (None)
[1] MovementFlags3: 0 (None)
[1] MoveTime: 856902151
[1] Position: X: -8538.09 Y: 1488.2867 Z: 32.484314
[1] Orientation: 4.118977069854736328
[1] Pitch: 0
[1] StepUpStartElevation: 0
[1] MoveIndex: 0
[1] Has Transport Data: False
[1] Has Fall Data: False
[1] HasSpline: False
[1] HeightChangeFailed: False
[1] RemoteTimeValid: False
[1] HasInertia: False
[1] WalkSpeed: 2.5
[1] RunSpeed: 8
[1] RunBackSpeed: 4.5
[1] SwimSpeed: 4.72221994400024414
[1] SwimBackSpeed: 2.5
[1] FlightSpeed: 7
[1] FlightBackSpeed: 4.5
[1] TurnRate: 3.141592741012573242
[1] PitchRate: 3.141592741012573242
[1] MovementForceCount: 0
[1] MovementForcesModMagnitude: 1
[1] HasMovementSpline: False
[1] PauseTimesCount: 0
[1] FieldFlags: 4 (UnitAll)
[1] EntryID: 15473
[1] DynamicFlags: 0
[1] Scale: 1
[1] DisplayID: 15691
[1] [0] N [...]

2022-08-07 19:33 UTC, UltraNix commented
@Maelthyrr @Gultask You can tets it again now.

2022-08-07 20:19 UTC, acidmanifesto requested changes
![image](https://user-images.githubusercontent.com/16887899/183309595-a5483b0b-1592-4ea6-84ba-85aacd45ac6c.png)

2022-08-07 21:43 UTC, Maelthyrr commented
Now Andorov start the entrance but he stop in the arena of Kurinaxx and start immediatly the event. So waves come until him.

![WoWScrnShot_080722_233935](https://user-images.githubusercontent.com/100411212/183312013-fe6e849b-d8bc-4422-8ff5-9a9c99d8525a.jpg)

I'm also not sure about the formation. Andorov seems very far from these Kaldorei. @Gultask is it like this on retail ?

![WoWScrnShot_080722_233853](https://user-images.githubusercontent.com/100411212/183312052-6e3e8e61-733d-4a79-9112-4c88e9c4d40d.jpg)

2022-08-08 01:10 UTC, Gultask commented
No, they should be nearby each other at all times. They also only attack enemies if you've started the event with him.
Here are some retail recordings (excuse the quality, I had to lower it)

https://user-images.githubusercontent.com/100873791/183319677-b9c1f1fe-a0ef-403b-9f56-0f681e4a75ad.mp4


https://user-images.githubusercontent.com/100873791/183319686-31df8a76-29ad-40ac-8943-cf0695bf3e31.mp4

I didn't include the end because he actually glitched out and didn't "end" the event and never offered to sell me supplies. I believe it's because I killed Rajaxx far away from him 😛

2022-08-13 06:50 UTC, UltraNix commented
@acidmanifesto Should be okay.
@Gultask Please, test it again.

2022-08-13 08:09 UTC, Nefertumm commented on data/sql/updates/pending_db_world/rev_1659801375917048100.sql
> +UPDATE `creature_template` SET `speed_walk`=1.4, `speed_run`=1.4 `entry`=15473;
missing where

2022-08-13 12:21 UTC, balleny commented
> Because Andorov isn't related to Rajaxx waves (it is just an alternate start) and I didnt do anything with Andorov.
> 
> You can pull Rajaxx by talking to Andorov but they are not connected, you can skip the Andorov thing on retail altogether
> 
> I checked the code and the way the TC guys did it also doesn't match our research:
> 
> 1. the timer should be two minutes (they set it to 1 min)
> 2. Rajaxx doesnt say anything during the waves if they get pulled by the timer (it is some sort of dps check)
> 3. Waves are pulled in succession as soon as all members are dead, not on timer only
> 4. Rajaxx should only say stuff after the wave is defeated
> 
> All of the above works
> 
> What was missing:
> 
> * Andorov spawn at the start of the entrance after Kurinaxx dies
> * Talking to Andorov initiates a sequence where he walks to the arena and taunts Rajaxx and they trade a few lines
> * The waves target Andorov it seems when they are pulled
> 
> So the alternative start (through gossip) was missing

the timer should be 3 mins as of
https://wowwiki-archive.fandom.com/wiki/General_Rajaxx
and
https://classic.wowhead.com/guides/general-rajaxx-ruins-of-ahnqiraj-strategy

2022-08-13 14:51 UTC, Maelthyrr commented
> > Because Andorov isn't related to Rajaxx waves (it is just an alternate start) and I didnt do anything with Andorov.
> > You can pull Rajaxx by talking to Andorov but they are not connected, you can skip the Andorov thing on retail altogether
> > I checked the code and the way the TC guys did it also doesn't match our research:
> > 
> > 1. the timer should be two minutes (they set it to 1 min)
> > 2. Rajaxx doesnt say anything during the waves if they get pulled by the timer (it is some sort of dps check)
> > 3. Waves are pulled in succession as soon as all members are dead, not on timer only
> > 4. Rajaxx should only say stuff after the wave is defeated
> > 
> > All of the above works
> > What was missing:
> > 
> > * Andorov spawn at the start of the entrance after Kurinaxx dies
> > * Talking to Andorov initiates a sequence where he walks to the arena and taunts Rajaxx and they trade a few lines
> > * The waves target Andorov it seems when they are pulled
> > 
> > So the alternative start (through gossip) was missing
> 
> the timer should be 3 mins as of https://wowwiki-archive.fandom.com/wiki/General_Rajaxx and https://classic.wowhead.com/guides/general-rajaxx-ruins-of-ahnqiraj-strategy

It's wrong. Tested on classic PTR.

2022-08-13 15:17 UTC, Maelthyrr commented
@UltraNix when andorov reach the arena, I can't talk with him to start event with Rajaxx waves.

2022-08-13 15:42 UTC, balleny commented
> > > Because Andorov isn't related to Rajaxx waves (it is just an alternate start) and I didnt do anything with Andorov.
> > > You can pull Rajaxx by talking to Andorov but they are not connected, you can skip the Andorov thing on retail altogether
> > > I checked the code and the way the TC guys did it also doesn't match our research:
> > > 
> > > 1. the timer should be two minutes (they set it to 1 min)
> > > 2. Rajaxx doesnt say anything during the waves if they get pulled by the timer (it is some sort of dps check)
> > > 3. Waves are pulled in succession as soon as all members are dead, not on timer only
> > > 4. Rajaxx should only say stuff after the wave is defeated
> > > 
> > > All of the above works
> > > What was missing:
> > > 
> > > * Andorov spawn at the start of the entrance after Kurinaxx dies
> > > * Talking to Andorov initiates a sequence where he walks to the arena and taunts Rajaxx and they trade a few lines
> > > * The waves target Andorov it seems when they are pulled
> > > 
> > > So the alternative start (through gossip) was missing
> > 
> > 
> > the timer should be 3 mins as of https://wowwiki-archive.fandom.com/wiki/General_Rajaxx and https://classic.wowhead.com/guides/general-rajaxx-ruins-of-ahnqiraj-strategy
> 
> It's wrong. Tested on classic PTR.

Classic PTR, which is very likely Season of Mastery - which is increased vanilla with increased difficulty.

2022-08-13 15:50 UTC, Maelthyrr commented
> > > > Because Andorov isn't related to Rajaxx waves (it is just an alternate start) and I didnt do anything with Andorov.
> > > > You can pull Rajaxx by talking to Andorov but they are not connected, you can skip the Andorov thing on retail altogether
> > > > I checked the code and the way the TC guys did it also doesn't match our research:
> > > > 
> > > > 1. the timer should be two minutes (they set it to 1 min)
> > > > 2. Rajaxx doesnt say anything during the waves if they get pulled by the timer (it is some sort of dps check)
> > > > 3. Waves are pulled in succession as soon as all members are dead, not on timer only
> > > > 4. Rajaxx should only say stuff after the wave is defeated
> > > > 
> > > > All of the above works
> > > > What was missing:
> > > > 
> > > > * Andorov spawn at the start of the entrance after Kurinaxx dies
> > > > * Talking to Andorov initiates a sequence where he walks to the arena and taunts Rajaxx and they trade a few lines
> > > > * The waves target Andorov it seems when they are pulled
> > > > 
> > > > So the alternative start (through gossip) was missing
> > > 
> > > 
> > > the timer should be 3 mins as of https://wowwiki-archive.fandom.com/wiki/General_Rajaxx and https://classic.wowhead.com/guides/general-rajaxx-ruins-of-ahnqiraj-strategy
> > 
> > 
> > It's wrong. Tested on classic PTR.
> 
> Classic PTR, which is very likely Season of Mastery - which is vanilla with increased difficulty.

Mb, it's not on classic sorry, TBC classic and Shadowlands if I did no error. Check by @Nyeriah. Don't trust always guides and wiki. They can contain errors.

2022-08-13 17:45 UTC, UltraNix commented
@Maelthyrr Should be okay now.

2022-08-13 19:19 UTC, Gultask commented
Wrong Icon & Gossip text here, this is before starting the event:

![image](https://user-images.githubusercontent.com/100873791/184507747-5c5378b1-a0cb-4833-b834-5720d08cd7fe.png)

Clicking the option also doesn't start the event.

He also seems like he didn't complete the waypoints? He's looking at the wall when he should actually be facing the other way:

![image](https://user-images.githubusercontent.com/100873791/184507789-674658ff-cd41-4db4-aa92-d7a5dd2d5d6e.png)

2022-08-14 06:57 UTC, UltraNix commented
@Maelthyrr Try now.

2022-08-14 07:30 UTC, Maelthyrr commented
@UltraNix work now, but new issue:

- [ ] When the event with Rajaxx start. The first waves is pull automaticaly, and when the first is done, the second waves doesn't come.
- [ ] When Andorov come to Rajax gate, he does a short return on the way. Is it normal?

![WoWScrnShot_081422_092614](https://user-images.githubusercontent.com/100411212/184526989-f0a92a1f-47ad-4f99-8e27-932067dd3469.jpg)

2022-08-14 08:09 UTC, UltraNix commented
@Maelthyrr Pathing corrected.
About waves - it works okay to me. After Quezz death, another pack of mobs are coming.

2022-08-14 10:24 UTC, Maelthyrr commented
Will ask to another tester because to me, Queez reset and broke waves. Even with a DB clean.

2022-08-14 15:56 UTC, Gultask commented
Same result as Maelthyrr.

1. Kill Kurinnaxx
2. start event, wait for Qeez to aggro to Andorov.
3. kill Qeez
4. Event resets, Qeez respawns, Andorov is uninteractable.

Kaldorei Elite aren't helping in the fight

Gossip option is wrong. It should actually be "Let's find out." instead of "I'd be happy to support you in the fight." ([source](https://youtu.be/5dQ1aaxtze8?t=1375))

2022-08-14 22:53 UTC, acidmanifesto approved these changes

2022-08-20 08:03 UTC, UltraNix commented
@Gultask @Maelthyrr Should be okay now.

2022-08-20 16:15 UTC, Maelthyrr commented
Everything work fine now. Big thanks @UltraNix :D 

- [X] Andorov and Kaldorei formation/pathway work without issues
- [X] Andorov wait in Kurinaxx arena
- [X] Player can launch Rajaxx event by talking with Andorov
- [X] Rajaxx waves work properly
- [X] At the ends, you can buy items from Andorov
- [X] Aura of commands work fine
- [X] If Andorov and Kaldorei are kill, it's cause any issues

2022-08-21 04:34 UTC, merged