fix (Quest 9740): The Sun Gate
azerothcore/azerothcore-wotlk pull request #12685
Opened 2022-08-09 01:48 UTC by xadowtek

Fix to quest 9740 The Sun Gate. Gate can't be desactivated and this fix it.

## Changes Proposed:
-  Fix the Sun Portal that can't be desactivated 

## Issues Addressed:

- Closes [issue 12518](https://github.com/azerothcore/azerothcore-wotlk/issues/12518)

## SOURCE:

## Tests Performed:

- Tested

## How to Test the Changes:

1. Adquire quest 9740 "The Sun Portal" in NPC Vindicator Aesom
2. Go to Sun portal location
3. Disable portal controllers
4. Disable Sun portal

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

2022-08-10 21:49 UTC, Nefertumm requested changes
Missing file extension and also, update your sql to code standards please.
If you don't know how, https://www.azerothcore.org/wiki/sql-standards
Just to point out, you're missing backticks around column names :)

2022-08-11 21:52 UTC, xadowtek commented
> Missing file extension and also, update your sql to code standards please. If you don't know how, https://www.azerothcore.org/wiki/sql-standards Just to point out, you're missing backticks around column names :)

Sorry! Now it's been fixed.

2022-08-12 04:05 UTC, Nefertumm approved these changes

2022-08-12 15:07 UTC, Maelthyrr commented
Tested and work fine. Thank for your PR :)

- [X] Can destroy controllers
- [X] Can destroy the portal
- [X] Can complete the quest

2022-08-12 15:12 UTC, Nyeriah commented
Question: can you click the portal straight away without destroying the crystals?

2022-08-12 15:17 UTC, Maelthyrr commented
> Question: can you click the portal straight away without destroying the crystals?

No

2022-08-12 15:19 UTC, merged

2022-08-12 15:19 UTC, Nyeriah commented
@xadowtek thanks for the PR 👍