fix(DB/EversongWoods): Remove sprint action from tigers
azerothcore/azerothcore-wotlk pull request #12704
Opened 2022-08-11 21:22 UTC by SoglaHash

Tigers were using sprint. Expected tigers should not use sprint.

Closes #12679

## Changes Proposed:
-  Remove smartAI script action 22863 from the tigers that use it.

## Issues Addressed:

- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/12679

## SOURCE:

## Tests Performed:

## How to Test the Changes:

```
.go c 55919
.go c 55988
```
1. Use above listed commands to go to mobs
2. Aggro and see if they cast sprint on aggro

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

2022-08-12 05:32 UTC, Nefertumm requested changes

2022-08-12 05:32 UTC, Nefertumm commented on data/sql/updates/pending_db_world/rev_1660252072288200163.sql
> +UPDATE `creature_template` SET `AIName` = 'SmartAI' WHERE `entry` IN (15651, 15652);
If these creatures already have smartai it's not needed.

2022-08-12 05:32 UTC, Nefertumm commented on data/sql/updates/pending_db_world/rev_1660252072288200163.sql
> +DELETE FROM `smart_scripts` WHERE (`entryorguid` IN (15651, 15652)) AND (`action_param1` = 22863);
Please add source_type to the condition or you could delete areatriggers or gob SAIs.

2022-09-04 06:21 UTC, Maelthyrr commented
Hi, thanks for the PR. Work fine :)

2022-09-06 18:09 UTC, Nefertumm approved these changes

2022-09-06 18:10 UTC, merged