fix(Core/Spell): implement Eclispe script
azerothcore/azerothcore-wotlk pull request #13225
Opened 2022-10-02 22:18 UTC by Maelthyrr

Cherry-pick from TC:
*https://github.com/TrinityCore/TrinityCore/commit/dbba3ad5a50a424e54c677b8201c3171ca3fb1b5 *https://github.com/TrinityCore/TrinityCore/commit/9612ac0e276a6435a6e030937d13ef2852708c9b

Co-authored: ariel- <ariel-@users.noreply.github.com>

## Changes Proposed:
-  fix Eclispe proc after https://github.com/azerothcore/azerothcore-wotlk/pull/11079
-  

## Issues Addressed:

- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/13221

## Tests Performed:

- None

## How to Test the Changes:

1. Create a druid
2. Get some crit stuff and eclispe talent
3. Cast starfire
4. Look if eclispe proc

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

2022-10-03 19:17 UTC, Nefertumm requested changes

2022-10-03 19:17 UTC, Nefertumm commented on src/server/scripts/Spells/spell_druid.cpp
> +        eventInfo.GetActor()->CastSpell(eventInfo.GetActor(), SPELL_DRUID_ECLIPSE_LUNAR_PROC, aurEff);
```suggestion
        eventInfo.GetActor()->CastSpell(eventInfo.GetActor(), SPELL_DRUID_ECLIPSE_LUNAR_PROC, TRIGGERED_FULL_MASK, nullptr, aurEff);
```

2022-10-03 19:17 UTC, Nefertumm commented on src/server/scripts/Spells/spell_druid.cpp
> +        eventInfo.GetActor()->CastSpell(eventInfo.GetActor(), SPELL_DRUID_ECLIPSE_SOLAR_PROC, aurEff);
```suggestion
        eventInfo.GetActor()->CastSpell(eventInfo.GetActor(), SPELL_DRUID_ECLIPSE_SOLAR_PROC, TRIGGERED_FULL_MASK, nullptr, aurEff);
```

2022-10-04 08:15 UTC, temperrr commented
tested, works

2022-10-04 17:41 UTC, Kitzunu approved these changes

2022-10-04 17:46 UTC, Nefertumm approved these changes

2022-10-08 17:25 UTC, closed without merging