fix(Scripts/NPC): Arcanite Dragonling
azerothcore/azerothcore-wotlk pull request #13233
Opened 2022-10-03 02:23 UTC by grimgravy

## Issues Addressed:

- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/12284

## SOURCE:

https://www.youtube.com/watch?v=xi2Rvi4VfCs
## Tests Performed:

- Tested in game

## How to Test the Changes:

1.
2.
3.

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

2022-10-08 04:21 UTC, Gultask commented
It works. It suffers from the common problems nearly all these summons have but it works 😅 👍

2022-10-08 16:37 UTC, Nefertumm requested changes

2022-10-08 16:37 UTC, Nefertumm commented on src/server/scripts/World/npcs_special.cpp
> +        events.ScheduleEvent(EVENT_FLAME_BREATH, 12000);
```suggestion
        events.ScheduleEvent(EVENT_FLAME_BUFFET, 4s);
        events.ScheduleEvent(EVENT_FLAME_BREATH, 12s);
```

2022-10-08 16:37 UTC, Nefertumm commented on src/server/scripts/World/npcs_special.cpp
> +                events.RepeatEvent(12000);
```suggestion
                DoCastVictim(SPELL_FLAME_BUFFET);
                events.Repeat(12s);
```

2022-10-08 16:37 UTC, Nefertumm commented on src/server/scripts/World/npcs_special.cpp
> +                events.RepeatEvent(24000);
```suggestion
                DoCastVictim(SPELL_FLAME_BREATH);
                events.Repeat(24s);
```

2022-10-08 16:37 UTC, Nefertumm commented on src/server/scripts/World/npcs_special.cpp
> +            return;
Is this okay to be down here?

2022-10-08 19:29 UTC, grimgravy commented on src/server/scripts/World/npcs_special.cpp
> +            return;
it doesn't change anything

2022-10-09 00:47 UTC, Nefertumm approved these changes

2022-10-15 15:03 UTC, acidmanifesto commented
Thank you for the PR

2022-10-15 15:03 UTC, merged