fix(CORE/dbupdate)): allow to pass MySQL password via env
azerothcore/azerothcore-wotlk pull request #13404
Opened 2022-10-13 23:15 UTC by Yehonal

## Changes Proposed:

- allow to pass MySQL password via env. This will stop the mysql password warning issue 
- fixed devContainer override file issue
- added authserver dry-run in our CI

## Issues Addressed:

- Closes 

## SOURCE:

## Tests Performed:

- 
- 

## How to Test the Changes:

1.
2.
3.

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

2022-10-14 13:28 UTC, acidmanifesto requested changes

2022-10-14 13:28 UTC, acidmanifesto commented on src/common/Utilities/StartProcess.cpp
> +
white space

2022-10-15 16:18 UTC, Winfidonarleyan commented
This warnings only for mysql

2022-10-15 20:25 UTC, acidmanifesto approved these changes

2022-10-15 21:19 UTC, Yehonal commented
> This warnings only for mysql

Can you test this PR on another db?

2022-10-17 08:49 UTC, Naios commented
@Yehonal Seems like you have fixed a long outstanding issue of my DBUpdater implementation, nice.
We would like to cherry-pick this fix to TrinityCore as well.

Could you agree to license your change also under GPL? Otherwise we cannot pick it over because AGPL (AzerothCore) is more constrained than GPL (TrinityCore).

2022-10-17 08:53 UTC, merged

2022-10-17 14:06 UTC, Yehonal commented
> @Yehonal Seems like you have fixed a long outstanding issue of my DBUpdater implementation, nice. We would like to cherry-pick this fix to TrinityCore as well.
> 
> Could you agree to license your change also under GPL? Otherwise we cannot pick it over because AGPL (AzerothCore) is more constrained than GPL (TrinityCore).

No prob, as long as you set `-c user.name=Yehonal-c user.email=yehonal.azeroth@gmail.com`  while cherry-picking

2022-10-17 14:14 UTC, Nyeriah commented
It is worth mentioning that AGPLv3 disregards user consent when it comes to the propagation of the license. That means a file receiving code originally licensed as AGPLv3 will necessarily follow the more restrictive license.

2022-10-17 14:38 UTC, Naios commented
@Yehonal thank you, of course the commit will be made with you as original author listed.

@Nyeriah You can never disregard user consent if he allows that his own intellectual work is also licensed under a another license.
By following your logic Yehonal would waive their rights to his original work by just commiting it to an AGPL repo, which is not the case. You always keep ownership of your own (personal) work regardless if you decide to sublicense it through an open-source licensed or not. Therefore Yehonal can allow to sublicense their changes under the GPL as well. *Note: this is no legal advice.*

2022-10-17 14:54 UTC, Nyeriah commented
@Naios it’s the non-legal advice we got from FSF

2022-10-17 19:41 UTC, Yehonal commented
New PR available here: https://github.com/azerothcore/azerothcore-wotlk/pull/13449