fix(DB/gameobject): Improve Terokkar Forest gathering nodes
azerothcore/azerothcore-wotlk pull request #13466
Opened 2022-10-20 01:52 UTC by Gultask

I still need to find open unused GUIDs and do some preliminary testing. I can't seem to be able to repopulate my DB so I'm out of a local for now.

## Changes Proposed:
-  Replaces MASTER pools
-  Introduces 37 new sniffed ore nodes
- Creates pool_pools for Khorium and Rich Adamantite
- 2% for Fel Iron Khorium, 3% for Adamantite Khorium and 4% for Rich Adamantite Khorium
- Rich Adamantite has 30% chance
- See comment for more info

## Issues Addressed:

- Closes 

## SOURCE:

WotLK Classic for numbers, Retail for the sniffs

## Tests Performed:

- 1 pass, not tested respawn yet.

## How to Test the Changes:

1. Use Gathermate/Gatherer
2. Tap the nodes (don't pick them yet!)
3. Count all spawns, compare to the images below, see if they correlate
4. Pick them. See if it respawns later

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

2022-10-20 11:20 UTC, acidmanifesto commented
> I can't seem to be able to repopulate my DB so I'm out of a local for now.

Please fetch the upstream of the pr.

2022-10-20 12:34 UTC, acidmanifesto requested changes

2022-10-20 12:34 UTC, acidmanifesto commented on data/sql/updates/pending_db_world/rev_1666109692456128300.sql
> +(@POOLMOTHER+11, 1, 'Terokkar Forest - Fel Iron Deposit - Group 12'),
```suggestion
(@POOLMOTHER+11, 1, 'Terokkar Forest - Fel Iron Deposit - Group 12');
```

2022-10-20 12:34 UTC, acidmanifesto commented on data/sql/updates/pending_db_world/rev_1666109692456128300.sql
> +(@GUID+119, 181557, 530, 3519, 0, 1, 1, -2306.47, 5454.43, 5.74422, -1.76278, 0, 0, 0, 0, 3600, 255, 1, '', 0),
```suggestion
(@GUID+119, 181557, 530, 3519, 0, 1, 1, -2306.47, 5454.43, 5.74422, -1.76278, 0, 0, 0, 0, 3600, 255, 1, '', 0);
```

2022-10-20 12:34 UTC, acidmanifesto commented on data/sql/updates/pending_db_world/rev_1666109692456128300.sql
> +(@POOL+48, 1, 'Terokkar Forest - Adamantite Deposit / Khorium Vein'),
```suggestion
(@POOL+48, 1, 'Terokkar Forest - Adamantite Deposit / Khorium Vein');
```

2022-10-20 12:34 UTC, acidmanifesto commented on data/sql/updates/pending_db_world/rev_1666109692456128300.sql
> +(@POOLMOTHER+5, 1, 'Terokkar Forest - Adamantite / Rich / Khorium - Group 17'),
```suggestion
(@POOLMOTHER+5, 1, 'Terokkar Forest - Adamantite / Rich / Khorium - Group 17');
```

2022-10-20 12:54 UTC, Gultask commented on data/sql/updates/pending_db_world/rev_1666109692456128300.sql
> +(@POOLMOTHER+5, 1, 'Terokkar Forest - Adamantite / Rich / Khorium - Group 17'),
Thanks! 😛

2022-10-20 12:55 UTC, Gultask commented
> > I can't seem to be able to repopulate my DB so I'm out of a local for now.
> 
> Please fetch the upstream of the pr.

Didn't work for me. Worldserver still crashing and dbupdater just doesn't care.

2022-10-20 13:01 UTC, acidmanifesto commented
this is interesting. it doesnt like your use of defines for the entries. it sees it as NULL, which is why it is not being accepted by the world.
![image](https://user-images.githubusercontent.com/16887899/196955707-caaa4f09-fbe7-4f74-b2e3-3a2e81f9478b.png)

2022-10-20 13:02 UTC, acidmanifesto commented
@Kitzunu do you have any ideas what he can do to make his sql passible?

2022-10-20 13:03 UTC, Gultask commented
I didn't define anything yet because it's WIP, it's all commented 😛

2022-10-20 13:06 UTC, acidmanifesto commented
> I didn't define anything yet because it's WIP, it's all commented 😛
> 
> I need to rebuild the DB to get free entries, but I can't for now.

gotcha.

2022-10-20 13:07 UTC, Gultask commented
Gave it another shot and it worked. Building the DB right now. I'll define the entries ASAP 👍

2022-10-23 08:35 UTC, Kitzunu approved these changes

2022-11-02 01:01 UTC, acidmanifesto approved these changes

2022-11-03 22:29 UTC, merged