fix(Scripts/Temple of AhnQiraj): Slime Toxin clouds should despawn 10…
azerothcore/azerothcore-wotlk pull request #13492
Opened 2022-10-22 11:44 UTC by UltraNix

… sec after Viscidus death.

Fixes #13420

## Issues Addressed:

- Closes #13420
- Closes https://github.com/chromiecraft/chromiecraft/issues/4221

## Tests Performed:

- Not tested.

## How to Test the Changes:

`.go c 87938`
Wait till he creates some Toxin couds.
Kill him.
Observe that Toxin clouds dissapeares 10 sec after death.

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

2022-10-22 14:16 UTC, acidmanifesto requested changes

2022-10-22 14:16 UTC, acidmanifesto commented on src/server/scripts/Kalimdor/TempleOfAhnQiraj/boss_viscidus.cpp
> +    void JustDied(Unit* killer) override
unused variable killer

2022-10-22 14:57 UTC, UltraNix commented
@acidmanifesto Done.

2022-10-22 14:58 UTC, acidmanifesto approved these changes

2022-10-25 01:32 UTC, Gultask commented
It works 👍

2022-10-25 13:43 UTC, merged