fix(Core/Players): Players should nt able to rest in unfriendly taver…
azerothcore/azerothcore-wotlk pull request #13493
Opened 2022-10-22 14:55 UTC by UltraNix

…ns. Original author: @Rushor

Fixes #13459

 

## Issues Addressed:

- Closes #13459
- Closes https://github.com/chromiecraft/chromiecraft/issues/4248

## Tests Performed:

- Tested ingame.

## How to Test the Changes:

horde
.tele lakehire
.go xyz -9232 -2156 65

alliance
.tele brill
.go xyz 2249 248 35

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

2022-10-22 18:17 UTC, acidmanifesto requested changes

2022-10-22 18:17 UTC, acidmanifesto commented on data/sql/updates/pending_db_world/rev_1666450482825467900.sql
> +4847);
line break

2022-10-22 18:17 UTC, acidmanifesto commented on data/sql/updates/pending_db_world/rev_1666450482825467900.sql
> +
white space

2022-10-23 11:01 UTC, acidmanifesto approved these changes

2022-10-28 03:26 UTC, IntelligentQuantum approved these changes

2022-10-29 10:15 UTC, merged