fix(DB/SmartAI): Improve Hellfire SmartAI part 1
azerothcore/azerothcore-wotlk pull request #13611
Opened 2022-10-30 15:27 UTC by Gultask

Authored by: https://github.com/ZenoX92

## Changes Proposed:
- Adds comments, replaces some SAI
- Replaces some unnecessary casts with creature_template_addon auras
- Some minor adjustments

## Issues Addressed:

- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/13602
- Closes https://github.com/chromiecraft/chromiecraft/issues/4340

## SOURCE:

## Tests Performed:

- 
- 

## How to Test the Changes:

1.
2.
3.

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

2022-11-12 18:18 UTC, Nefertumm requested changes
There are a lot of double quotes for strings in the sql, remember we use single quotes for them, change them whenever you can, please 👍

2022-11-12 18:55 UTC, Gultask commented
Ahh it was from porting from TC. Done 👍

2022-11-15 15:24 UTC, BeefSteaker commented
Tested, all work

2022-11-18 05:59 UTC, Nefertumm approved these changes

2022-11-21 22:21 UTC, merged