fix(scripts/ZulGurub): Add "Whirlwind" - High Priestess Arlokk
azerothcore/azerothcore-wotlk pull request #13637
Opened 2022-11-01 19:31 UTC by Si1ker

## Changes Proposed:
-  Add "Whirlwind"
-  Some improvements to "Mark of Arlokk"

## SOURCE:

https://classic.warcraftlogs.com/reports/z7dxmQW2RBNC9br4#fight=6&hostility=1&type=damage-done&source=42&ability=15589

https://www.wowhead.com/classic/guide/high-priestess-arlokk-zul-gurub-strategy

## Tests Performed:

- Tested in-game

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

2022-11-12 21:31 UTC, Gultask commented
The Whirlwind is fine but I saw something strange with Mark of Arlokk.
The first cycle, Two had the Mark, and all adds attacked them. When the Mark of Arlokk target switched to One, the Prowlers didn't switch target as well, instead they stayed on Two, occasionally turning to face One, but turning away just as fast.
The Prowlers slowly changed to the new target though, one at a time. When it was time to cast Mark of Arlokk again, about half the Prowlers were attacking the correct target, while the other half was still attacking the old one.

![image](https://user-images.githubusercontent.com/100873791/201495243-eebf6c1e-3627-46cc-a78b-e361b4a823cf.png)

2022-11-15 01:41 UTC, Si1ker commented
@Gultask updated.

2022-11-18 17:43 UTC, Si1ker commented
@Gultask pump

2022-11-26 02:47 UTC, Si1ker commented
@Gultask 🤔

2022-11-26 17:29 UTC, Gultask commented
Sorry. Low amount of testers + too much on my plate at the moment.

2022-11-27 05:57 UTC, Si1ker commented
> Sorry. Low amount of testers + too much on my plate at the moment.

@Gultask It's not to test but approve, I removed buggy mark behavior, and that's it, it is ready.

2022-12-03 13:28 UTC, Si1ker commented
cc @FrancescoBorzi

2022-12-12 09:59 UTC, FrancescoBorzi commented
@Si1ker why closing this?

2023-01-22 16:54 UTC, acidmanifesto requested changes

2023-01-22 16:54 UTC, acidmanifesto commented on src/server/scripts/EasternKingdoms/ZulGurub/boss_arlokk.cpp
> -EndScriptData */
is there a reason why this is being removed?

2023-01-22 17:05 UTC, closed without merging