fix(Core/Loot): Fix quest items looting system
azerothcore/azerothcore-wotlk pull request #13720
Opened 2022-11-06 12:59 UTC by MikaMauger

## Changes Proposed:
Fixes quest items distribution as described in this [issue](https://github.com/TrinityCore/TrinityCore/issues/22829). Problem applies to AC aswell.

I'll complete this description soon.

## Issues Addressed:

- Closes 

## SOURCE:

## Tests Performed:

- 
- 

## How to Test the Changes:

1.
2.
3.

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

2022-11-06 17:46 UTC, Kitzunu requested changes
Thanks for the contribution. I know it is still draft, but would still like to point out some things so that you don't need to change more stuff later :D

2022-11-06 17:46 UTC, Kitzunu commented on src/server/game/Loot/LootMgr.cpp
> +bool LootItem::AllowedForPlayer(Player const *player, ObjectGuid source) const
```suggestion
bool LootItem::AllowedForPlayer(Player const* player, ObjectGuid source) const
```
always this way

2022-11-06 17:46 UTC, Kitzunu commented on src/server/game/Loot/LootMgr.cpp
> +    Player *lootOwner = (roundRobinPlayer) ? ObjectAccessor::FindPlayer(roundRobinPlayer) : player;
same here

2022-11-06 17:46 UTC, Kitzunu commented on src/server/game/Loot/LootMgr.cpp
> +    auto* ql = new QuestItemList();
I'd prefer to refrain to use auto in this case, to easier know what this variable is pointing to.

2022-11-06 17:46 UTC, Kitzunu commented on src/server/game/Loot/LootMgr.cpp
> +        if (!item.freeforall) {
move bracket to newline

2022-11-06 17:46 UTC, Kitzunu commented on src/server/game/Loot/LootMgr.cpp
> +    auto* ql = new QuestItemList();
same as above

2022-11-06 17:46 UTC, Kitzunu commented on src/server/game/Loot/LootMgr.h
> +    bool AllowedForPlayer(Player const *player, ObjectGuid source) const;
same as above

2022-11-06 17:46 UTC, Kitzunu commented on src/server/game/Loot/LootMgr.cpp
> +bool LootItem::AllowedForPlayer(Player const *player, ObjectGuid source) const
For more code standards you can read here https://www.azerothcore.org/wiki/cpp-code-standards

2022-11-11 13:51 UTC, Valdifer commented
Tested it in Zul'gurub with the quest 8201 and works, tested all loot modes

2022-12-06 15:42 UTC, Nyeriah approved these changes

2022-12-06 15:42 UTC, merged

2022-12-06 15:42 UTC, Nyeriah commented
Thanks for the PR :+1:

2022-12-08 22:55 UTC, Nyeriah commented
@MikaMauger Please take a look into this: https://github.com/chromiecraft/chromiecraft/issues/4542

Master looters can't see quest items to give them out anymore

2022-12-09 07:09 UTC, MikaMauger commented
I will.