fix(DB/Loot): Syndicate emblems in junkboxes
azerothcore/azerothcore-wotlk pull request #13750
Opened 2022-11-08 20:25 UTC by BeefSteaker

## Changes Proposed:
-  Remove Syndicate emblems from Battered Junkbox and Worn Junkbox

## Issues Addressed:

- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/11360

## SOURCE:

## Tests Performed:

- Checked Kiera loot table after running SQL query
- opened a few boxes and no obvious issues, but low sample size

## How to Test the Changes:

1. .setskill 633 300 300
2. .additem 16882
3. .additem 16883

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

2022-11-10 11:42 UTC, temperrr approved these changes

2022-11-12 03:01 UTC, Nefertumm commented on data/sql/updates/pending_db_world/removeloot.sql
> +DELETE FROM `item_loot_template` WHERE (`Entry` = 16882 or `Entry` = 16883) AND (`Item` IN (17124));
Use `Entry` IN instead of or expression

2022-11-12 12:18 UTC, Kitzunu requested changes
Correct the statement above

2022-11-12 13:33 UTC, BeefSteaker commented
Fixed

2022-11-12 13:51 UTC, Kitzunu commented on data/sql/updates/pending_db_world/removeloot.sql
> +DELETE FROM `item_loot_template` WHERE `Entry` in (16882, 16883) AND (`Item` IN (17124));
```suggestion
DELETE FROM `item_loot_template` WHERE `Entry` IN (16882, 16883) AND (`Item` IN (17124));
```

2022-11-12 13:52 UTC, BeefSteaker commented on data/sql/updates/pending_db_world/removeloot.sql
> +DELETE FROM `item_loot_template` WHERE `Entry` in (16882, 16883) AND (`Item` IN (17124));
Thanks

2022-11-12 13:57 UTC, Kitzunu approved these changes

2022-11-13 18:42 UTC, Nefertumm approved these changes

2022-11-13 18:43 UTC, merged