fix(DB/SmartAI): Unliving Stalker Viper Sting heroic only
azerothcore/azerothcore-wotlk pull request #13815
Opened 2022-11-13 23:10 UTC by BeefSteaker

## Changes Proposed:
-  Unliving Stalker casts Viper Sting in heroic mode only

## Issues Addressed:

- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/13784

## SOURCE:

## Tests Performed:

- 
- 

## How to Test the Changes:

1..tele ac
2. Unliving Stalker is called by Auchenai Soulpriest/Monk/Vindicator, of which there are several at the beginning of the dungeon. But they have several types of NPCs to summon, so you may need to kill them and .resp

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

2022-11-14 07:31 UTC, Nefertumm requested changes
The filename can't contain spaces

2022-11-14 17:37 UTC, Nefertumm approved these changes

2022-11-15 20:05 UTC, Kitzunu commented on data/sql/updates/pending_db_world/heroicViperSting.sql
> +Update `smart_scripts` set `event_flags`=4 WHERE (`entryorguid` = 18501) AND (`source_type` = 0) AND (`id` IN (4));
Always use Versals for SQL Keywords, such as UPDATE and SET

2022-11-15 20:05 UTC, Kitzunu requested changes
above

2022-11-15 20:35 UTC, BeefSteaker commented
my bad, client usually does that automatically, must have changed this one manually

2022-11-16 04:29 UTC, merged