fix(DB/loot): Adjust AQ40 Idols and coffers
azerothcore/azerothcore-wotlk pull request #13998
Opened 2022-11-29 17:36 UTC by Gultask

## Changes Proposed:
- Large Coffer Pools increased based on Retail Sniffs

## Issues Addressed:

- Closes 

## SOURCE:

Retail, Cmangos

## Tests Performed:

- Query runs
- 

## How to Test the Changes:

1.
2.
3.

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

2022-11-29 20:25 UTC, Kitzunu requested changes

2022-11-29 20:25 UTC, Kitzunu commented on data/sql/updates/pending_db_world/rev_1669742453928322100.sql
> +UPDATE `creature_loot_template` SET `QuestRequired`=0, `Chance`=0.5 WHERE `Item` BETWEEN 20874 AND 20882;
Please do not use BETWEEN here. Use IN so we can see all affected rows

2022-12-01 04:14 UTC, Kitzunu approved these changes

2022-12-06 17:28 UTC, Nyeriah commented
Please don't forget the tags so PRs dont get lost, quite easy for them to get lost amidst 100s

2022-12-06 17:28 UTC, merged