fix(Core/Battlefield): Wintergrasp Workshops SW/SE to Attacker
azerothcore/azerothcore-wotlk pull request #14104
Opened 2022-12-09 15:12 UTC by Valdifer

At the setup|Battlestart|Battleend of wintergrasp all WS were belonging to attacker team, now only SW and SE are owned by Attacker, the rest are for Defender team

https://github.com/azerothcore/azerothcore-wotlk/issues/603

Valdifer

## Changes Proposed:
-  Set WS/GY from SW/SE to Attacker and the rest to Defender
-  Relocate alliance players when attacking WG to not appear in the air

## Issues Addressed:

- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/603

## SOURCE:

## Tests Performed:

- Build without error
- Capturing wintergrasp and wait until next battle to capture again with the contrary faction
- Restartint the server to see the owner of WG

## How to Test the Changes:

1. Join WG war
2. Check workshops capturepoints sliders are correct
3. Win wintergrasp (Alliance or Horde)
4. Wait until the next war (You can change the timer in worldconfig.dist or editing the values in acore_characters.worldstates)
5. Join WG war
6. Check workshops capturepoints sliders are correct
7. Win wintergrasp (Alliance or Horde)
8. Restart the server
9. Starting again on Step1

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

2023-01-22 16:42 UTC, acidmanifesto requested changes

2023-01-22 16:42 UTC, acidmanifesto commented on src/server/game/Battlefield/Zones/BattlefieldWG.cpp
> +
```suggestion
```

2023-01-22 16:42 UTC, acidmanifesto commented on src/server/game/Battlefield/Zones/BattlefieldWG.cpp
> +
remove the excess line break

2023-01-27 00:29 UTC, acidmanifesto approved these changes

2023-03-07 13:19 UTC, Maelthyrr commented
Hi thanks for the PR. Everythings look fine 👍 

- [X] After each battle workshop captured reset to the correct team
- [X] Tested with horde win in attacker, defender, alliance, attacker, defender

2023-03-17 14:24 UTC, Maelthyrr approved these changes

2023-03-17 14:26 UTC, merged