fix(DB/Texts): Added texts to Halazzi.
azerothcore/azerothcore-wotlk pull request #14124
Opened 2022-12-11 10:19 UTC by UltraNix

Fixes #8744

## Issues Addressed:

- Closes #8744

## Tests Performed:

- Not tested.

## How to Test the Changes:

`.go c 86195`
combat with Halazzi

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

2022-12-11 10:24 UTC, Kitzunu requested changes

2022-12-11 10:24 UTC, Kitzunu commented on data/sql/updates/pending_db_world/rev_1670753866467974200.sql
> +(23577,4,0,'Spirit, come back to me!',14,0,100,0,0,12022,0,0,'Halazzi - SAY_COMBINE'),
in Core this is SAY_MERGE, update the comment accordingly.

2022-12-11 10:24 UTC, Kitzunu commented on data/sql/updates/pending_db_world/rev_1670753866467974200.sql
> +(23577,2,1,'You gonna leave in pieces!',14,0,100,0,0,12024,0,0,'Halazzi - SAY_MELEE'),
In Core this is SAY_SABER, update the comment accordingly.

2022-12-11 10:24 UTC, Kitzunu commented on data/sql/updates/pending_db_world/rev_1670753866467974200.sql
> +(23577,1,1,'Ya all gonna fail!',14,0,100,0,0,12027,0,0,'Halazzi - SAY_PLAYER_KILL'),
In Core this is SAY_KILL, update the comment accordingly.

2022-12-17 08:27 UTC, UltraNix commented
@Kitzunu Done.

2022-12-17 08:39 UTC, Kitzunu approved these changes

2023-01-07 17:30 UTC, Maelthyrr commented
Hi, tested and work fine :) Thanks.

2023-01-07 19:30 UTC, merged