fix(DB/Quest): Rework support for 'Someone Else's Hard Work Pays Off'
azerothcore/azerothcore-wotlk pull request #14258
Opened 2022-12-17 15:21 UTC by Nyeriah

## Changes Proposed:
-  
-  

## Issues Addressed:

- Closes https://github.com/chromiecraft/chromiecraft/issues/4566

## SOURCE:

## Tests Performed:

- 
- 

## How to Test the Changes:

1.
2.
3.

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

2022-12-20 01:10 UTC, Nyeriah commented
I've identified an issue with the second last power core thing, where the scort npc mentions some mobs/attack wave but nothing actually spawns. Otherwise this works, needs sniff to wrap up that last pack though.

2022-12-21 08:38 UTC, Buggyswires commented
Bug confirmed. I did the escort with a group and was the only one actually having the quest.
I didn't die, but the npc still just disappeared at the end without giving credit.

2022-12-21 11:38 UTC, Nyeriah commented
> Bug confirmed. I did the escort with a group and was the only one actually having the quest.
> I didn't die, but the npc still just disappeared at the end without giving credit.

This doesn’t relate to this PR I presume

2023-01-01 11:49 UTC, Nyeriah commented
Please test this and check if it works, it's still better than a fully broken quest I assume

2023-01-03 09:42 UTC, Sneften commented
Tested ✅ 
Got quest complete on 2 characters.

Only thing that's not working is when the groups spawn to ambush you, they just spawn and stand still. Won't enter combat unless you aggro them.
Blizz-like they spawn and run to the escort NPC "forcing" combat.

2023-01-03 20:32 UTC, Gultask commented
sql file can't be ran twice:
![image](https://user-images.githubusercontent.com/100873791/210436692-ed3c095f-0eba-47ac-8cbc-31d71f1fa5f2.png)

2023-01-03 21:20 UTC, Nyeriah commented
> sql file can't be ran twice: ![image](https://user-images.githubusercontent.com/100873791/210436692-ed3c095f-0eba-47ac-8cbc-31d71f1fa5f2.png)

Correct. SQL that alters table structure can't be ran twice and there's nothing we can do about it

2023-01-03 21:24 UTC, Gultask approved these changes

2023-01-03 21:24 UTC, Gultask commented
That's unfortunate :c

2023-01-03 21:25 UTC, Gultask requested changes
wait, sorry. It's missing deletes

2023-01-03 21:26 UTC, Gultask requested changes

2023-01-03 21:26 UTC, Gultask commented on data/sql/updates/pending_db_world/rev_1671290232250846500.sql
> +INSERT INTO `waypoints` (`entry`,`pointid`,`position_x`,`position_y`,`position_z`,`point_comment`) VALUES
```suggestion
DELETE FROM `waypoints` WHERE `entry` IN (19666,1967100,1967101,1967102);
INSERT INTO `waypoints` (`entry`,`pointid`,`position_x`,`position_y`,`position_z`,`point_comment`) VALUES
```

2023-01-03 21:30 UTC, acidmanifesto commented
Suggestion. Mark as merge later. Then merge before squash day

2023-01-04 21:24 UTC, Gultask approved these changes

2023-01-04 22:36 UTC, Gultask commented
> Tested ✅ Got quest complete on 2 characters.
> 
> Only thing that's not working is when the groups spawn to ambush you, they just spawn and stand still. Won't enter combat unless you aggro them. Blizz-like they spawn and run to the escort NPC "forcing" combat.

There's a flag set to make the group aggro the player immediately so I don't know why it's not firing. Maybe changing to script owner will fix it but I've had several problems with that as well

You can try that by changing like 70 to:
```sql
(1967105,9,4,0,0,0,100,0,0,0,0,0,0,107,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,"Cryo-Engineer Sha'heen - On Script - Summon Group 0"),
```

2023-01-04 22:41 UTC, Nyeriah commented
The amount of time I've available to invest into this rages widely, plus it's SAI and I detest SAI. If anyone wants to try addressing the issues reported, feel free to, you can edit the file as you will. Otherwise I will return to it later, much later

2023-01-04 22:45 UTC, Gultask commented
Yeah, don't worry about it. I'm planning on testing it later too, seeing if changing the parameter works :)

2023-01-06 05:06 UTC, Gultask reviewed
This works

2023-01-06 05:06 UTC, Gultask commented on data/sql/updates/pending_db_world/rev_1671290232250846500.sql
> +(1967107,9,4,0,0,0,100,0,1000,1000,0,0,0,107,1,1,0,0,0,0,1,0,0,0,0,0,0,0,0,"Cryo-Engineer Sha'heen - On Script - Summon Group 1"),
```suggestion
(1967107,9,4,0,0,0,100,0,1000,1000,0,0,0,107,1,0,1,0,0,0,1,0,0,0,0,0,0,0,0,"Cryo-Engineer Sha'heen - On Script - Summon Group 1"),
```

2023-01-31 13:50 UTC, Nyeriah commented
Squash days may or may not happen before the end of times, should we merge?

2023-01-31 14:04 UTC, Gultask commented
yeah

2023-01-31 21:53 UTC, merged