fix(Core/Auras): SPELL_AURA_MOD_SCALE should scale additively instead…
azerothcore/azerothcore-wotlk pull request #14425
Opened 2022-12-30 06:00 UTC by Nefertumm

… of multiplicatively

Co-authored-by: Shauren <shauren.trinity@gmail.com>

## Changes Proposed:
-  Make AURA_MOD_SCALE additive instead of multiplicative.

## Issues Addressed:

- Closes -

## SOURCE:

## Tests Performed:

- Tested in-game with ...
- 

## How to Test the Changes:

1.
2.
3.

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

2022-12-31 16:39 UTC, Kitzunu requested changes

2023-01-02 18:05 UTC, Gultask commented
- Vekniss Borer: No change
- Spells such as 16711 and 8212 still stack, but doesn't look like it is multiplicative 
- On NPCs the Gor'Drek Ointment for quest 10488 works
- Cast spell 31691 (SHRINK) on self, then cast a bunch of 31698 (GROW) on self. It was fine.

2023-01-02 22:06 UTC, Nefertumm commented
zzzzzzzzzzzzzzzzzzzzzzzzzzzzzz

2023-01-02 23:08 UTC, Gultask commented
Tested pets as well. They grow when leveling up and retain that size when dismissed.

2023-01-02 23:16 UTC, Gultask approved these changes

2023-01-02 23:43 UTC, merged