refactor(DB): Adjust table/column names to consistent standards.
azerothcore/azerothcore-wotlk pull request #14503
Opened 2023-01-05 07:40 UTC by heyitsbench

## Changes Proposed:
- Adjusts table/column names in auth, characteres, and world DBs to [recent SQL standards](https://www.azerothcore.org/wiki/sql-standards#naming-of-tables-and-columns), as well as subjectively improving various column names.

## Issues Addressed:

- Closes #11005

## SOURCE:

N/A

## Tests Performed:

- Tested each query individually to make sure no errors occurred on my local DBs.

## How to Test the Changes:

1. Run the queries.
2. Observe that the auth/worldservers load properly and nothing changes in-game.

## Known Issues and TODO List:

- This is obviously not done. I'm opening this now so that any feedback on table/column name changes have time to be seen by contributors/reviewers/maintainers alike, and any changes that should be made can be made. The SQL queries don't have any work left to do on my end unless changes are requested, all that's left is adjusting the names in queries within the core.
- [X] Auth DB rename query.
- [X] Characters DB rename query.
- [X] World DB rename query.
- [X] Auth DB query core adjustments.
- [x] Characters DB query core adjustments.
- [ ] World DB query core adjustments.

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

2023-01-05 07:41 UTC, heyitsbench commented
Also of note, this does include the changes proposed in [this PR](https://github.com/azerothcore/azerothcore-wotlk/pull/13058).

2023-01-05 17:32 UTC, Kitzunu commented
Exclude broadcast_text and make a seperate PR for that

2023-01-05 17:51 UTC, heyitsbench commented
> Exclude broadcast_text and make a seperate PR for that

[Done](https://github.com/azerothcore/azerothcore-wotlk/pull/14509).

2023-01-09 00:16 UTC, heyitsbench commented
May be rather obvious, but this will likely bork most if not all parts of [Keira](https://github.com/azerothcore/Keira3). I can update modules and the wiki in time, but I am very unfamiliar with Keira, so it probably won't be me who updates that.

2023-01-09 09:15 UTC, Helias commented
I do not dislike this renaming, but it will break Keira3, AoWoW and many other applications 😢 
Moreover, we will differ from TC a lot after this, which is a little benefit

I do not remember if the fields name on TC 8-10.x (or our current one) are sniffed from the retail, so they probably match with the official/retail fields name

Are we sure to do this?

2023-01-09 09:20 UTC, FrancescoBorzi commented
I agree with @Helias , sorry but I don't think the amount of work here is worth the benefit. There are many other things that are more important for the project.

@heyitsbench if you still want to do this please prepare a fix also for all the tools such as Keira3, aowow, etc... but honestly I would not do it.

2023-01-09 09:21 UTC, FrancescoBorzi requested changes

2023-01-09 09:21 UTC, FrancescoBorzi commented on data/sql/updates/pending_db_auth/redo-auth.sql
> +ALTER TABLE `account`
PR blocked until there is an equivalent PR for all the main tools depending on all the tables changed here. And it's a lot of work.

2023-01-09 09:23 UTC, Nyeriah commented
I thought this PR aligned the names with TC. If that’s not the case then I don’t think that’s something we’re looking for. Otherwise, could try breaking the PR by parts so there aren’t too many renames to address

2023-01-09 09:42 UTC, Helias commented
this could break also several modules unfortunately

2023-01-09 12:32 UTC, heyitsbench commented
I'm closing this for now. After further discussion, I will open a much smaller PR to include the changes in [this PR](https://github.com/azerothcore/azerothcore-wotlk/pull/13058), as well as align a few column names to TC, but I will not continue working on aligning the DB to a general consistent standard, due to preference of parity with TC.

2023-01-09 12:32 UTC, closed without merging