fix(DB/Locale): deDE fix offer reward texts #01
azerothcore/azerothcore-wotlk pull request #14614
Opened 2023-01-10 17:41 UTC by ohkasdasf

Process of translation: only original sources of deDE texts by researching multiple sources, only in rare occasions reverse translation by searching for related quest items/NPCs and using these names to reconstruct a proper translation. 

This fixes:

Coldridge (Eisklamm), Coldridgetal (Eisklammtal), Doomhammers (Schicksalshammers), Fizzle (Fizzel), Fizzledowser (Rutenwünschels), Fizzlebub (Zischelbub), Burning Blade (Brennende Klinge), Ashenvale (Eschental), Darkspeartrolle/Darkspears/Darkspearstamm (Dunkelspeere, Dunkelspeertrolle, -stamm), Splintertree (Splitterholzposten), Moonglade (Mondlichtung), Crossroads (Wegekreuz), Burg Shadowfang/Shadowfang Keep (Burg Schattenfang), Lord Shadowbreaker (Lord Schattenbruch, Darrowshire (Darroheim), Redpath (Rotpfad), Booty Bay (Beutebucht), Dizzywig (Flunkerblick), Hearthglen (Herdweiler), Chillwindspitze (Zugwindspitze), Steamwheedle-Kartell (Dampfdruckkartell), Steamboil (Kesseldampf), Steamwheedle-Bilge-Rum (Dampfdruckrum), Wizzlecrank (Kurbelwizz), Blightcaller (Pestrufer), Twilight-Hammer, -klan (Schattenhammer/Schattenhammerklan), Fathom-Kern (Tiefenkern), Blackfathom Deeps (Tiefschwarze Grotte), Blackrock-* (Schwarzfels-*), Corporal (Korporal), Thunderheart (Donnerherz), Thunderhorn (Donnerhörner), Grimbooze (Schnapsbart), Hawkwind (Falkenwind), Moonbreeze (Mondhauch), Shadowglen (Laubschattental), Ironbands Areal (Eisenbands Lager), Bloodhoof (Bluthuf), Frostwolf (Frostwölfe), Ratchet (Ratschet), Stormrage (Sturmgrimm), Stormpike (Sturmlanzen/-garde), Feathermoon (Mondfeder), Sputtervale/Sputtervalve (Stotterspritter), Jonespyre (Lebenshand), Staghelm (Hirschhaupt), Southshore (Süderstade)

for quests turn in/reward text entries for the deDE localisation with proper casus/declension (these are not proper translated names of locations/NPCs that have been left over by Blizzard since their language localisations in TBC in 2006 and onward).

Fixed a typo for 184: LEute - Leute.

Added missing turn in/reward text entries for 1642, 1780, 1781, 1786, 1788 (all part of Paladin Redemption quest chain). Removed an outwritten name (Maljona) and replaced with $N for 1644.

Added missing turn in texts for 5237, 5405, 5503, 11451.

Replaced post-Cataclysm turn in/reward text entries of quests 929, 933, 935, 6388, 6391, 6392, 6983, 7383.

(There are probably more changes in the file that aren't further explained here as it was hard to keep track of everything. If you think I made a mistake or have questions please contact me directly.)

## Changes Proposed:
-  Fixing a lot in the quest_offer_reward_locale table.

## Issues Addressed:

- Fixing some of the tasks in https://github.com/azerothcore/azerothcore-wotlk/issues/14244
Referring to my other two bug reports from CC Github:
- https://github.com/chromiecraft/chromiecraft/issues/4697
- https://github.com/chromiecraft/chromiecraft/issues/4745

## SOURCE:

- Read the text on top.

## Tests Performed:

- Not tested.

## How to Test the Changes:

All of the changes are to reward texts of quests, can be tested by completing quests or simply reviewing the changed file.

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

2023-01-10 17:44 UTC, heyitsbench commented
Not necessarily related to this PR, but if you are eventually planning on hitting any fields related to `quest_template_locale` (which I believe your original issues relate to), feel free to grab from [this collection of sniffed data](https://github.com/azerothcore/azerothcore-wotlk/issues/14209#issuecomment-1365679645) for that table.

2023-01-11 14:19 UTC, Samsequel requested changes

2023-01-11 14:19 UTC, Samsequel commented on data/sql/updates/pending_db_world/deDE-locale-fix-01-reward.sql
> +(7383, 'deDE', 'In der Nähe des Orakelbaums... kann man fast spüren, wie die Weisheit Gestalt annimmt. Lasst mich mit der Geschichte fortfahren...$B$BTeldrassil wuchs und gedieh, und der Erzdruide wa
```suggestion
(7383, 'deDE', 'In der Nähe des Orakelbaums... kann man fast spüren, wie die Weisheit Gestalt annimmt. Lasst mich mit der Geschichte fortfahren...$B$BTeldrassil wuchs und gedieh, und der Erzdruide wandte sich an die Großdrachen, um deren Segen zu erhalten, den sie in längst vergangenen Zeiten über Nordrassil verbreitet hatten. Nozdormu jedoch, der Lord der Zeit, weigerte sich, seinen Segen zu spenden und tadelte den Druiden wegen seiner Arroganz. Einig mit Nozdormu widersetzte sich auch Alexstrasza Hirschhaupt und ohne ihren Segen entartete Teldrassil und wuchs auf unvorhersehbare Weise...', 0),
```

Forgot comma

2023-02-11 11:03 UTC, Nyeriah approved these changes

2023-02-11 11:03 UTC, merged