fix(Scripts/Underbog): Rework Swamplord Muselek
azerothcore/azerothcore-wotlk pull request #14724
Opened 2023-01-21 01:06 UTC by Nyeriah

## Changes Proposed:
-  
-  

## Issues Addressed:

- Closes 

## SOURCE:

## Tests Performed:

- 
- 

## How to Test the Changes:

1.
2.
3.

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

2023-01-21 01:12 UTC, Gultask approved these changes

2023-01-21 01:12 UTC, acidmanifesto requested changes

2023-01-21 01:12 UTC, acidmanifesto commented on src/server/scripts/Outland/CoilfangReservoir/underbog/boss_swamplord_muselek.cpp
> +    void UpdateAI(uint32 diff) override
Diff unused

2023-01-21 08:08 UTC, Kitzunu commented
You forget to load the new script file :)

2023-01-21 08:12 UTC, Kitzunu commented
https://github.com/azerothcore/azerothcore-wotlk/blob/master/src/server/scripts/Outland/outland_script_loader.cpp

2023-01-21 11:44 UTC, Nyeriah commented
Ye ye, this is not ready for review...
I still need to change a lot of stuff, I just reopened it cus the other one got screwed by merge conflicts that I cba to solve

2023-03-07 18:07 UTC, Maelthyrr commented
Always in WIP?

2023-03-07 18:53 UTC, Nyeriah commented
Need to script the bear and I can’t manage to get his movement to work to my hearts content as of yet, more important stuff required my attention so this got put in the freezer

2023-05-13 17:44 UTC, merged