Defias Henchman
azerothcore/azerothcore-wotlk pull request #14807
Opened 2023-01-31 04:59 UTC by M4th3m4tic4l

## Changes Proposed:
-  Removes all drops related to that item and updates the probability of dropping on Defias Henchman by 5%.

## Issues Addressed:

- https://github.com/chromiecraft/chromiecraft/issues/2220
- https://github.com/azerothcore/azerothcore-wotlk/issues/8844

## SOURCE:

https://www.wowhead.com/classic/item=1927/deadmines-cleaver
https://www.wowhead.com/classic/npc=594/defias-henchman

## Tests Performed:

- 
![Defias](https://user-images.githubusercontent.com/111697701/215669590-3d8a2ed6-9928-4c16-b069-b95e53dd2edd.PNG)

## How to Test the Changes:

1. Insert the new statment in your world database and execute the statement SELECT * FROM `creature_loot_template` WHERE `Reference` = 24076;

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

2023-02-04 14:42 UTC, Maelthyrr commented
Tested and work fine. Thanks :)

2023-02-27 02:30 UTC, Gultask requested changes

2023-02-27 02:30 UTC, Gultask commented on data/sql/updates/pending_db_world/rev_1675140644244916700.sql
> +DELETE FROM `reference_loot_template` WHERE `Entry` = 594 AND `Item` = 1927;
```suggestion
DELETE FROM `creature_loot_template` WHERE `Entry` = 594 AND `Item` = 1927;
```

2023-04-02 18:37 UTC, Nyeriah commented
@Gultask this ready?

2023-04-02 18:52 UTC, Gultask approved these changes

2023-04-02 20:24 UTC, merged