fix(DB/SmartScript)) Sundered Rumblers wrong use of Summon Sundered Shard
azerothcore/azerothcore-wotlk pull request #14831
Opened 2023-01-31 23:39 UTC by M4th3m4tic4l

## Changes Proposed:
-  Casts Summon Sundered Shard on death
-  Says text "Sundered Rumbler shatters into shards."

## Issues Addressed:

- https://github.com/azerothcore/azerothcore-wotlk/issues/14818
- https://github.com/chromiecraft/chromiecraft/issues/4908

## SOURCE:

https://youtu.be/HX8haCDIVT0?t=165

## Tests Performed:

- 
![WoWScrnShot_013123_181633](https://user-images.githubusercontent.com/111697701/215908430-81755f8c-4a02-482a-9588-baa53475bbfd.jpg)

## How to Test the Changes:

1. Insert the changes in your world database
2. .go c 67708
3. .damage 50000

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

2023-02-04 14:37 UTC, Maelthyrr commented
Tested and work fine. Now he cast "Summon Sundered Shard" only on death and emote is present.

2023-02-11 01:02 UTC, Nyeriah requested changes

2023-02-11 01:02 UTC, Nyeriah commented on data/sql/updates/pending_db_world/rev_1675207681546911800.sql
> +(18881,0,0,"Sundered Rumbler shatters into shards.",16,0,100,0,0,0,0,0,"Sundered Rumbler - Emote");
Missing broadcasttextId

You can find it by searching the broadcast_text table

```sql
SELECT * FROM `broadcast_text` WHERE `MaleText` LIKE "%shatters into shards%";
```

Or

```sql
SELECT * FROM `broadcast_text` WHERE `FemaleText` LIKE "%shatters into shards%";
```

2023-02-11 01:03 UTC, Nyeriah commented on data/sql/updates/pending_db_world/rev_1675207681546911800.sql
> +(18881,0,0,"Sundered Rumbler shatters into shards.",16,0,100,0,0,0,0,0,"Sundered Rumbler - Emote");
![image](https://user-images.githubusercontent.com/47818697/218228807-80475330-8d82-4849-9d7c-cdf77019a7c5.png)

Should be 19115

2023-02-11 03:09 UTC, Nyeriah approved these changes

2023-02-11 03:09 UTC, Nyeriah commented on data/sql/updates/pending_db_world/rev_1675207681546911800.sql
> +(18881,0,0,"Sundered Rumbler shatters into shards.",16,0,100,0,0,0,19115,0,"Sundered Rumbler - Emote");
```suggestion
(18881,0,0,"%s shatters into shards.",16,0,100,0,0,0,19115,0,"Sundered Rumbler - Emote");
```

2023-02-11 11:02 UTC, merged