fix(DB/Quest): improve A Dip in the Moonwell
azerothcore/azerothcore-wotlk pull request #15259
Opened 2023-03-04 11:49 UTC by grimgravy

## Issues Addressed:

- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/13473
- Closes https://github.com/chromiecraft/chromiecraft/issues/4268

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

2023-03-07 18:04 UTC, Maelthyrr commented
Hi, thanks for the PR. Tested and work fine. When dismissed, the channeling is canceled. The quest can always be complete

2023-03-14 02:05 UTC, IntelligentQuantum approved these changes

2023-03-25 13:16 UTC, grimgravy commented
I need to modify the writing

2023-06-27 17:55 UTC, Kitzunu requested changes

2023-06-27 17:55 UTC, Kitzunu commented on data/sql/updates/pending_db_world/rev_1677930037418943000.sql
> +UPDATE `creature_template` SET `ScriptName`='npc_controller' WHERE entry IN (17178, 19405);
backticks on entry

2023-06-28 20:27 UTC, Kitzunu approved these changes

2023-07-29 19:52 UTC, Kitzunu commented
merge conflict

2023-08-06 01:16 UTC, merged