fix(DB/Locale): deDE fixes for achievement reward
azerothcore/azerothcore-wotlk pull request #15302
Opened 2023-03-07 19:21 UTC by ohkasdasf

## Changes Proposed:
-  Fixes several typos and wrong entries for the deDE localisation for the achievement_reward_locale table.

## Issues Addressed:

- Closes an unreported issue.

## SOURCE:

## Tests Performed:

- Has not been tested.

## How to Test the Changes:

1. Complete the respective achievement with a deDE client (check IDs)
2. Check your mail.

## Known Issues and TODO List:

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

2023-03-08 08:55 UTC, 55Honey requested changes

2023-03-08 08:55 UTC, 55Honey commented on data/sql/updates/pending_db_world/fix-achievement-reward-locale.sql
> +(3478, 'deDE', 'Der vergessene Puter', 'Könnt Ihr begreifen, wie es dieser fette Truthahn lebendig durch den November geschaft hat?!$B$BAlle seine Freunde sind auf den reich gedeckten Tischen servier
geschaft -> geschafft
```suggestion
(3478, 'deDE', 'Der vergessene Puter', 'Könnt Ihr begreifen, wie es dieser fette Truthahn lebendig durch den November geschafft hat?!$B$BAlle seine Freunde sind auf den reich gedeckten Tischen serviert worden. Mit Moosbeerenchutney und Gewürzbrotfüllung und... OOOH... jetzt bekomme ich Hunger. Egal! Er ist jetzt ganz allein. Deswegen habe ich überlegt, ob Ihr Euch vielleicht um Ihn kümmern würdet. In meinem Laden ist einfach nicht mehr genug Platz für ihn!$B$BHaltet ihn nur bitte von Kochstellen fern. Er bekommt in ihrer Nähe immer so einen merkwürdigen Blick...$B$B--Breanni'),
```

2023-03-08 08:55 UTC, 55Honey commented on data/sql/updates/pending_db_world/fix-achievement-reward-locale.sql
> +(3656, 'deDE', 'Der vergessene Puter', 'Könnt Ihr begreifen, wie es dieser fette Truthahn lebendig durch den November geschaft hat?!$B$BAlle seine Freunde sind auf den reich gedeckten Tischen servier
geschaft -> geschafft
```suggestion
(3656, 'deDE', 'Der vergessene Puter', 'Könnt Ihr begreifen, wie es dieser fette Truthahn lebendig durch den November geschafft hat?!$B$BAlle seine Freunde sind auf den reich gedeckten Tischen serviert worden. Mit Moosbeerenchutney und Gewürzbrotfüllung und... OOOH... jetzt bekomme ich Hunger. Egal! Er ist jetzt ganz allein. Deswegen habe ich überlegt, ob Ihr Euch vielleicht um Ihn kümmern würdet. In meinem Laden ist einfach nicht mehr genug Platz für ihn!$B$BHaltet ihn nur bitte von Kochstellen fern. Er bekommt in ihrer Nähe immer so einen merkwürdigen Blick...$B$B--Breanni'),
```

2023-03-08 08:56 UTC, 55Honey commented
Thanks for the PR @ohkasdasf !

2023-03-14 21:55 UTC, Maelthyrr approved these changes

2023-04-22 13:20 UTC, Gultask approved these changes

2023-04-22 13:23 UTC, merged