refactor(DB/Misc): Improve loading time
azerothcore/azerothcore-wotlk pull request #15433
Opened 2023-03-17 11:11 UTC by Kitzunu

* NOTE: Running these SQL files can take several minutes (up to 30minutes depending on your system!)

* This will improve loading time over 50%

## Changes Proposed:
* NOTE: Running these SQL files can take several minutes (up to 30minutes depending on your system!)
* It can feel like the updater gets stuck or freezses. It doesnt. Just a lot of queries. A small price to pay one time for a big improvement in performance

On my system it took about 3-4 minutes to run it

-  Update engine, collation and get rid of MEDIUMINT in all databases
-  These changes will cut loading worldserver by over 50%

Before these changes
`WORLD: World Initialized In 0 Minutes 18 Seconds`

After these changes
`WORLD: World Initialized In 0 Minutes 7 Seconds`

## SOURCE:

Inspired by https://github.com/TrinityCore/TrinityCore/commit/c102baf99e1640df72a25444e3f206e1920a0b18
## Tests Performed:

- Tested on local machiene. Huge improvement in loading times.

## How to Test the Changes:

1. Import the changes with the autoupdater (Risk is that using i.e Heidi it will crash du to Heidi being mediocre)
2. See performance bonus 😎 

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

2023-03-17 17:37 UTC, acidmanifesto approved these changes

2023-03-19 13:03 UTC, Winfidonarleyan commented
- Before PR 7-8 secs
-

2023-03-19 14:12 UTC, Kitzunu commented
So now the question is, do we value MySQL or MariaDB more

2023-03-20 00:40 UTC, Gultask commented
@noisiver Would you be interested in trying as well?

2023-03-21 01:12 UTC, noisiver commented
Keep in mind that my MariaDB server (version 10.6.11) dedicated to AzerothCore runs with a very low amount of resources so performance is ass when compared to something decent but you can see the difference in times.

Before: 15-18 seconds
After: 22-23 seconds

I don't really care about a few seconds. Assuming it does in fact help with startup times for MySQL and those seconds were so important to me I would just switch to MySQL. I'm not going to try using MySQL though.

2023-03-21 18:58 UTC, Kitzunu commented
I will put To Be Merged as I see the gain as greater than the loss to MariaDB

Also the vast majority of AC maintainers use MySQL

2023-03-22 00:34 UTC, noisiver commented
> I will put To Be Merged as I see the gain as greater than the loss to MariaDB
> 
> Also the vast majority of AC maintainers use MySQL

I agree. If someone feels it's so important to save those seconds they can switch to MySQL. We're not talking minutes here after all so the loss is (in my opinion) minimal.

2023-04-22 13:35 UTC, Gultask requested changes

2023-04-22 13:35 UTC, Gultask commented on data/sql/updates/pending_db_world/rev_1679045387127819800.sql
> +ALTER TABLE `creature_onkill_reputation` MODIFY `RewOnKillRepValue2` INT NOT NULL DEFAULT '0';
https://github.com/azerothcore/azerothcore-wotlk/pull/15818/files

2023-04-22 15:39 UTC, Gultask commented on data/sql/updates/pending_db_world/rev_1679045387127819800.sql
> +ALTER TABLE `creature_onkill_reputation` MODIFY `RewOnKillRepValue2` INT NOT NULL DEFAULT '0';
```suggestion
```

2023-04-23 12:49 UTC, Gultask requested changes
https://github.com/azerothcore/azerothcore-wotlk/pull/14099

2023-04-23 20:48 UTC, Kitzunu commented
Yea I dont need to update anything for it.

2023-04-23 20:51 UTC, Gultask approved these changes

2023-04-23 21:00 UTC, merged