fx(DB/Quest): The Stories Dead Men Tell Quest Fix
azerothcore/azerothcore-wotlk pull request #16887
Opened 2023-08-03 21:05 UTC by Vanheden

Added script to the graves.

## Changes Proposed:
Add so it plays the scenes etc.

## Issues Addressed:
Fixed the Roleplay at the Graves.
https://www.youtube.com/watch?v=GZKXSFzAhhs&ab_channel=Roddan

## SOURCE:
Source from Sniff & Youtube: https://www.youtube.com/watch?v=FOctMDsnJDM&ab_channel=WorldOfWarcraftGuidesAndGameplay

## Tests Performed:
I tested it ingame several times and it works.

## How to Test the Changes:

1. .q add 13643
2. Click the graves.

## Known Issues and TODO List:
Nothing so far

2023-08-03 22:36 UTC, elthehablo commented
Works well. The npcs die when they are spawned, this is the cause of the sound and the animation. Afaik there is a way to change them to have a permanent "dead" state. Probably have to change that in `creature_template_addon`

2023-08-03 22:38 UTC, elthehablo commented
![image](https://github.com/azerothcore/azerothcore-wotlk/assets/83884799/e0dd6b3a-ac35-4f65-ba93-25c94743fd44)

2023-08-03 22:39 UTC, Vanheden commented
> Works well. The npcs die when they are spawned, this is the cause of the sound and the animation. Afaik there is a way to change them to have a permanent "dead" state. Probably have to change that in `creature_template_addon`

Yeah I used Sniff data to find out the spells etc. On the first grave **Sir Wendell Balfour** I had to add his Feign Death as a Aura instead of spellcast. For some reason he didn't spawn dead like **Lorien Sunblaze** did.

2023-08-03 22:39 UTC, elthehablo commented
buttt if it's sniffed (which you did a nice job as, as far as I can tell) I really wonder how blizz did it

2023-08-03 22:40 UTC, Vanheden commented
> buttt if it's sniffed (which you did a nice job as, as far as I can tell) I really wonder how blizz did it

Yeah also noticed the Dwarf when he's dead. He lays on his stomach but from a video 6 months ago he lays on his back and from a video back in legion he lays dead on his stomach to, kinda weird

2023-08-03 22:42 UTC, elthehablo commented
> > buttt if it's sniffed (which you did a nice job as, as far as I can tell) I really wonder how blizz did it
> 
> Yeah also noticed the **Conall Irongrip** when he's dead. He lays on his stomach but from a video 6 months ago he lays on his back and from a video back in legion he lays dead on his stomach to, kinda weird

maybe difference between models/animations? idk

2023-08-03 22:50 UTC, Vanheden commented
> > > buttt if it's sniffed (which you did a nice job as, as far as I can tell) I really wonder how blizz did it
> > 
> > 
> > Yeah also noticed the **Conall Irongrip** when he's dead. He lays on his stomach but from a video 6 months ago he lays on his back and from a video back in legion he lays dead on his stomach to, kinda weird
> 
> maybe difference between models/animations? idk

Yeah can be.

2023-08-05 17:01 UTC, Maria-sequel requested changes

2023-08-05 17:01 UTC, Maria-sequel commented on data/sql/updates/pending_db_world/questfix.sql
> +DELETE FROM `conditions` WHERE `SourceTypeOrReferenceId` = 22 AND `SourceEntry` = 194537 AND `SourceId` = 1;
you can combine these with the other sourceId= 1 with 
```AND `SourceEntry` IN ( 194537, 194539, etc) ```
Same with comibining the sourceid = 0's.

Also, you can keep 1 whiteline between different sets, but it's common to use only 1 whiteline on AC

2023-09-17 19:44 UTC, Kitzunu approved these changes

2023-09-20 20:41 UTC, merged