fix(DB/Quest): Return To Obadei
azerothcore/azerothcore-wotlk pull request #16891
Opened 2023-08-04 18:41 UTC by Vanheden

## Changes Proposed:

Fixes the dialogue .

## Issues Addressed:

Fixed the NPC Text after Quest Completion.

Closes: https://github.com/azerothcore/azerothcore-wotlk/issues/16199

## SOURCE:

Retail WoW & Youtube Videos.

## Tests Performed:

Tried it out ingame and it works and here's a video of it.

https://www.youtube.com/watch?v=plEzy8o2eu4&ab_channel=Roddan

## How to Test the Changes:

1. .q add 9423
2. .q complete 9423
3. Turn in the Quest.

## Known Issues and TODO List:

None that I'm aware of.

2023-08-05 16:57 UTC, Maria-sequel requested changes

2023-08-05 16:57 UTC, Maria-sequel commented on data/sql/updates/pending_db_world/ReturnToObadei.sql
> +
extra whitespaces here and at the bottom

2023-08-12 15:32 UTC, GastonCK commented
Author provided a video testing it, does this need another test?

2023-08-25 11:54 UTC, Nyeriah commented
Please fix the SQL file (remove the extra blank lines) so this can be merged

2023-08-25 21:47 UTC, elthehablo commented
abandoned?

2023-09-17 19:46 UTC, Kitzunu approved these changes

2023-09-20 20:41 UTC, merged