fix(DB/SAI) Add spore burst with 15% trigger chance
azerothcore/azerothcore-wotlk pull request #16985
Opened 2023-08-12 12:13 UTC by ChrisCGalbraith

## Changes Proposed:
This PR proposes changes to:
-  [ ] Core (units, players, creatures, game systems).
-  [ ] Scripts (bosses, spell scripts, creature scripts).
-  [X] Database (SAI, creatures, etc).

If your pull request promotes complex changes that require a detailed explanation, please describe them in detail specifying what your solution is and what is it meant to address.

## Issues Addressed:

- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/16593

## SOURCE:

The changes have been validated through:
- [ ] Live research (checked on live servers, e.g Classic WotLK, Retail, etc.)
- [ ] Sniffs (remember to share them with the open source community!)
- [ ] Video evidence, knowledge databases or other public sources (e.g forums, Wowhead, etc.)
- [ ] The changes promoted by this pull request come partially or entirely from another project (cherry-pick). **Cherry-picks must be committed using the proper --author tag in order to be accepted, thus crediting the original authors, unless otherwise unable to be found**

## Tests Performed:

This PR has been:
- [X] Tested in-game by the author.
- [ ] Tested in-game by other community members/someone else other than the author/has been live on production servers.
- [ ] This pull request requires further testing and may have edge cases to be tested.

## How to Test the Changes:

- [ ] This pull request can be tested by following the reproduction steps provided in the linked issue
- [ ] This pull request requires further testing. Provide steps to test your changes. If it requires any specific setup e.g multiple players please specify it as well.

1. Teleport to SSC - pull a sporebat, observe the spore burst being cast randomly (15%)

## Known Issues and TODO List:

Nothing TODO.

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

2023-08-12 15:51 UTC, Kitzunu commented on data/sql/updates/pending_db_world/rev_1691842029005931700.sql
> +(21246, 0, 1, 0, 0, 0, 15, 0, 0, 0, 0, 0, 0, 11, 38471, 2, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 'Serpentshrine Sporebat - In Combat - Cast \'Spore Burst\'');
please add a newline at the end of the file

2023-08-12 15:52 UTC, Kitzunu commented
What is the source for the timers?

2023-08-12 17:45 UTC, ChrisCGalbraith commented
Got no sniffs for this.

 [Spore Burst](https://www.wowhead.com/tbc/spell=38471/spore-burst) indicates a 15% chance which is what I put in the `chance` field whilst leaving any timers blank.

2023-08-14 11:26 UTC, elthehablo commented
> Got no sniffs for this.
> 
> [Spore Burst](https://www.wowhead.com/tbc/spell=38471/spore-burst) indicates a 15% chance which is what I put in the `chance` field whilst leaving any timers blank.

Why not make the event happen on aggro then? `event_type` 4

2023-08-14 11:29 UTC, elthehablo requested changes

2023-08-14 11:29 UTC, elthehablo commented on data/sql/updates/pending_db_world/rev_1691842029005931700.sql
> +(21246, 0, 1, 0, 0, 0, 15, 0, 0, 0, 0, 0, 0, 11, 38471, 2, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 'Serpentshrine Sporebat - In Combat - Cast \'Spore Burst\'');
```sql
(21246, 0, 1, 0, 4, 0, 15, 0, 0, 0, 0, 0, 0, 11, 38471, 2, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 'Serpentshrine Sporebat - In Combat - Cast \'Spore Burst\'');

```

2023-08-14 11:34 UTC, elthehablo requested changes
this makes it so it has a 15% chance of triggering on aggro, which I assume is the intended behaviour?

2023-08-14 12:13 UTC, Nyeriah commented
On aggro is only cast once, on aggro, never repeats

2023-08-14 12:30 UTC, elthehablo commented
> On aggro is only cast once, on aggro, never repeats

Right. Which I understood to be the correct behaviour needed here? Spell has a 15% cast to be triggered, on aggro?

2023-08-14 16:53 UTC, elthehablo commented
> Why do you think that it is only ever cast on aggro?

Because you had no timers

2023-08-15 00:23 UTC, ChrisCGalbraith commented
My understanding is that if no timers are implemented but a % chance is, then whenever the event is fired (which should be every combat update where no other event is fired) there is a 15% chance of that event running? 

Without actual sources though this entire thing is speculative.

2023-08-15 07:33 UTC, elthehablo commented
> My understanding is that if no timers are implemented but a % chance is, then whenever the event is fired (which should be every combat update where no other event is fired) there is a 15% chance of that event running? 
> 
> Without actual sources though this entire thing is speculative.

But I think combat update is like 50ms so that would be 15% every 50ms essentially meaning it will be on average cast more than 2 times per second. Unless I am mistaken. Lemme take a look at smart scripts and how it deals with the parameters for IC event

2023-08-15 07:42 UTC, elthehablo commented
![Screenshot_20230815_094056_GitHub.jpg](https://github.com/azerothcore/azerothcore-wotlk/assets/83884799/e918b160-db07-4a3a-869b-45c33d1cfd62)

Sorry on mobile. But I think this outlines that when the timers are set to 0 a no repeat flag is added. So I think this means that the event triggers once. But ofc this is logical when you have no repeat timer. This is why I suggested to change to SE 4

2023-08-15 08:52 UTC, ChrisCGalbraith commented
Interesting, I see what you mean. but is this not specifically for `SMART_EVENT_TARGET_BUFFED`?.

I've just double checked on this branch and the spore bat IS repeating the event more than once in the same pull

2023-08-15 08:58 UTC, elthehablo commented
> Interesting, I see what you mean. but is this not specifically for `SMART_EVENT_TARGET_BUFFED`?.
> 
> I've just double checked on this branch and the spore bat IS repeating the event more than once in the same pull

Okay I stand corrected

2023-08-15 09:26 UTC, elthehablo commented
I think I was just very confused with how this is supposed to work hehe

2023-08-24 15:07 UTC, Gultask reviewed
OK!
So after some time I gathered what I could :p 

1. Charge ID is wrong. It should be 38461 with timers
Initial 4850-19400
Repeat 10900-14500

2. According to Mangos Spore Burst is
Initial 0-0
Repeat 24000-36800
with chance of 100

2023-08-24 17:19 UTC, Gultask commented
> > My understanding is that if no timers are implemented but a % chance is, then whenever the event is fired (which should be every combat update where no other event is fired) there is a 15% chance of that event running?
> > Without actual sources though this entire thing is speculative.
> 
> But I think combat update is like 50ms so that would be 15% every 50ms essentially meaning it will be on average cast more than 2 times per second. Unless I am mistaken. Lemme take a look at smart scripts and how it deals with the parameters for IC event

If an event has a repeat timer of 0, it will automatically add the NOT_REPEATABLE flag during worldserver startup. Not only for TARGET_BUFFED since everything up in the case switches will also apply to them.

2023-09-17 19:51 UTC, Kitzunu approved these changes

2023-09-20 20:41 UTC, merged