refactor(Core/Script): Refactor Void Reaver boss script to new scheduler
azerothcore/azerothcore-wotlk pull request #17044
Opened 2023-08-20 13:48 UTC by ChrisCGalbraith

## Changes Proposed:
This PR proposes changes to:
-  [ ] Core (units, players, creatures, game systems).
-  [X] Scripts (bosses, spell scripts, creature scripts).
-  [ ] Database (SAI, creatures, etc).

If your pull request promotes complex changes that require a detailed explanation, please describe them in detail specifying what your solution is and what is it meant to address.

## Issues Addressed:

- Refactoring to new scheduling system

## SOURCE:

The changes have been validated through:
- [ ] Live research (checked on live servers, e.g Classic WotLK, Retail, etc.)
- [ ] Sniffs (remember to share them with the open source community!)
- [ ] Video evidence, knowledge databases or other public sources (e.g forums, Wowhead, etc.)
- [ ] The changes promoted by this pull request come partially or entirely from another project (cherry-pick). **Cherry-picks must be committed using the proper --author tag in order to be accepted, thus crediting the original authors, unless otherwise unable to be found**

## Tests Performed:

This PR has been:
- [X] Tested in-game by the author.
- [ ] Tested in-game by other community members/someone else other than the author/has been live on production servers.
- [X] This pull request requires further testing and may have edge cases to be tested.

## How to Test the Changes:

- [ ] This pull request can be tested by following the reproduction steps provided in the linked issue
- [ ] This pull request requires further testing. Provide steps to test your changes. If it requires any specific setup e.g multiple players please specify it as well.

1. Teleport to Tempest Keep: The Eye
2. Engage Void Reaver
3. Observe abilities

## Known Issues and TODO List:

- [X] Sometimes after SPELL_POUNDING completes there are 2x SPELL_ARCANE_ORB's released. This is certainly to do with
the scheduling I've implemented.

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

2023-08-20 13:59 UTC, elthehablo commented
Nice work. I am on mobile so might have missed something, but if UpdateAI only has the update victim, scheduler update and melee attack you can just omit it. It is already inherited from BossAI

2023-08-22 13:15 UTC, elthehablo requested changes
remove UpdateAI

2023-08-22 21:22 UTC, ChrisCGalbraith commented
Removed the `UpdateAI` override - however there's still sometimes a double `Arcane Orb` after `Pounding` completes its channel.

2023-08-22 21:32 UTC, elthehablo commented
> Removed the `UpdateAI` override - however there's still sometimes a double `Arcane Orb` after `Pounding` completes its channel. 

The code for it looks a bit strange. What is it supposed to do?

2023-08-22 21:32 UTC, elthehablo commented
Generally you can do DoCastRandomTarget but range is handled a bit differently there.

2023-08-22 23:34 UTC, elthehablo commented
Oh I know the problem. That is because scheduler queues things. If you want the orbs to consistently show up in this case you should use a different taskscheduler or you can delay events for a specific cast time. Because he's casting pounding, two orbs are queued up in the meantime

2023-08-22 23:36 UTC, elthehablo commented
Also TaskScheduler doesn't need to be included generally. `TaskScheduler scheduler` is also inherited from BossAI. But for my above mentioned issue you might want to use this anyway. Although delaying probably works

2023-08-22 23:39 UTC, elthehablo requested changes

2023-08-22 23:39 UTC, elthehablo commented on src/server/scripts/Outland/TempestKeep/Eye/boss_void_reaver.cpp
> +            DoCastSelf(SPELL_POUNDING, false);
```suggestion
            DoCastSelf(SPELL_POUNDING, false);
            scheduler.DelayAll(3s);
```

2023-08-22 23:39 UTC, elthehablo commented on src/server/scripts/Outland/TempestKeep/Eye/boss_void_reaver.cpp
> +        scheduler.Schedule(600s, [this](TaskContext context)
```suggestion
        scheduler.Schedule(10min, [this](TaskContext context)
```

very nitpicky but looks nicer

2023-08-22 23:39 UTC, elthehablo commented on src/server/scripts/Outland/TempestKeep/Eye/boss_void_reaver.cpp
> +#include "TaskScheduler.h"
```suggestion
```
not needed if you don't use another TaskScheduler

2023-08-23 08:48 UTC, ChrisCGalbraith commented
> > Removed the `UpdateAI` override - however there's still sometimes a double `Arcane Orb` after `Pounding` completes its channel.
> 
> The code for it looks a bit strange. What is it supposed to do?

This is the original code, and I *think* that it's meant to check if there is a target further than 18 yards first, and arcane orb them. If there is no target that far away then its able to cast the orb on anyone within 20 yards. So if the whole raid is stacked they get orbed. But if you have at least one person > 18 yrds away then they can bait the orbs.

2023-08-23 12:54 UTC, ChrisCGalbraith commented
So currently with a DelayAll(3s), the double queued arcane orbs issue is solved. However, I think it might be better to only delay the orbs if possible. Is this a situation where putting the orb schedule into a group and only delaying the group would be the better implementation?

2023-09-05 09:40 UTC, Nyeriah commented
@ChrisCGalbraith please update your branch, the CI is stuck

2023-09-05 16:16 UTC, merged