fix(DB/Locale): ruRU Client Locale
azerothcore/azerothcore-wotlk pull request #17106
Opened 2023-08-29 12:57 UTC by SergeyBliznec

Adding Russian language support for most gameplay elements (quests, books, game objects, etc.).

## Changes Proposed:
This PR proposes changes to:
Adds missing Russian strings in localization tables.

## Issues Addressed:

- Closes 
https://github.com/azerothcore/azerothcore-wotlk/issues/15135
https://github.com/azerothcore/azerothcore-wotlk/issues/14222
https://github.com/azerothcore/azerothcore-wotlk/issues/14228
https://github.com/azerothcore/azerothcore-wotlk/issues/14225
https://github.com/azerothcore/azerothcore-wotlk/issues/14224
https://github.com/azerothcore/azerothcore-wotlk/issues/14208
https://github.com/azerothcore/azerothcore-wotlk/issues/14229
https://github.com/azerothcore/azerothcore-wotlk/issues/14226
https://github.com/azerothcore/azerothcore-wotlk/issues/14208

## SOURCE:

https://github.com/azerothcore/azerothcore-wotlk/issues?q=russian
https://github.com/SergeyBliznec/azerothcore-rudb
https://github.com/NeatElves/wotlk-ytdbdb

## Tests Performed:

Tested on LAN server. No problems found.

## How to Test the Changes:

1. Requires ruRU client

## Known Issues and TODO List:

The quest_getering_locale table doesn't work.

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

2023-09-06 08:06 UTC, VitaliyBabkov approved these changes
I confirm that the quests have been translated.
![Снимок экрана 2023-09-06 120226](https://github.com/azerothcore/azerothcore-wotlk/assets/144212892/b2a564e0-7205-465d-b0ce-1bd5b777689e)
![Снимок экрана 2023-09-06 120245](https://github.com/azerothcore/azerothcore-wotlk/assets/144212892/2f9141b4-82c5-470b-842d-8df32d40b533)
![Снимок экрана 2023-09-06 120302](https://github.com/azerothcore/azerothcore-wotlk/assets/144212892/f9ece64d-627c-4512-8d80-4e751fa5c377)
![Снимок экрана 2023-09-06 120317](https://github.com/azerothcore/azerothcore-wotlk/assets/144212892/04b9f6b6-cfcf-4907-a1e3-be886716c9be)
![Снимок экрана 2023-09-06 120333](https://github.com/azerothcore/azerothcore-wotlk/assets/144212892/1befb44e-ab6d-450c-a11e-2db0fa369043)
![Снимок экрана 2023-09-06 120349](https://github.com/azerothcore/azerothcore-wotlk/assets/144212892/de3970b8-a49d-4d74-abbc-1d1782b2a0ff)
![Снимок экрана 2023-09-06 120421](https://github.com/azerothcore/azerothcore-wotlk/assets/144212892/a58291d8-675e-4396-9cff-e634950bc3ca)

2023-09-06 08:26 UTC, VitaliyBabkov approved these changes
Game objects also received a translation.

2023-09-08 18:03 UTC, Kitzunu requested changes
Also just do it for the texts you are actually fixing. Do not just re-add every text that already exists.

2023-09-08 18:03 UTC, Kitzunu commented on data/sql/updates/pending_db_world/achievement_reward_locale.sql
> +REPLACE INTO `achievement_reward_locale` (`ID`, `Locale`, `Subject`, `Text`) VALUES
no. dont use replace into. use delete insert or update

see https://www.azerothcore.org/wiki/sql-standards

2023-09-17 16:49 UTC, Kitzunu commented
I will close this as it is not an acceptable format for the SQL changes.

2023-09-17 16:49 UTC, closed without merging