fix (DB/SAI): Stratholme/Baron Rivendare (10440) encounter fixes
azerothcore/azerothcore-wotlk pull request #17398
Opened 2023-10-01 03:13 UTC by kjack9

## Changes Proposed:
This PR proposes changes to:
-  [ ] Core (units, players, creatures, game systems).
-  [ ] Scripts (bosses, spell scripts, creature scripts).
-  [X] Database (SAI, creatures, etc).

If your pull request promotes complex changes that require a detailed explanation, please describe them in detail specifying what your solution is and what is it meant to address.

## Issues Addressed:

- Closes #12257
- Closes https://github.com/chromiecraft/chromiecraft/issues/3709

## SOURCE:

The changes have been validated through:
- [X] Live research (checked on live servers, e.g Classic WotLK, Retail, etc.)
- [ ] Sniffs (remember to share them with the open source community!)
- [X] Video evidence, knowledge databases or other public sources (e.g forums, Wowhead, etc.)
- [ ] The changes promoted by this pull request come partially or entirely from another project (cherry-pick). **Cherry-picks must be committed using the proper --author tag in order to be accepted, thus crediting the original authors, unless otherwise unable to be found**

## Tests Performed:

This PR has been:
- [X] Tested in-game by the author.
- [ ] Tested in-game by other community members/someone else other than the author/has been live on production servers.
- [ ] This pull request requires further testing and may have edge cases to be tested.

## How to Test the Changes:

- [ ] This pull request can be tested by following the reproduction steps provided in the linked issue
- [ ] This pull request requires further testing. Provide steps to test your changes. If it requires any specific setup e.g multiple players please specify it as well.

1. `.go xyz 4032.49 -3357.65 115.06 329 1.52`
2. Engage Baron Rivendare (10440)
3. Observe that all six Mindless Skeletons (11197) enter the fight each time the Baron summons adds (spells 17475 to 17480)
4. `.gm on`
5. Observe that the Mindless Skeletons (11197) are despawned when the Baron has reset

![image](https://github.com/azerothcore/azerothcore-wotlk/assets/19712078/2c3813fc-867a-47d2-8931-300385af1c90)

Note that there are two skeletons in each position (they despawn before three stack up).

I ran the fight for 5 minutes straight and did not observe any incidents of less than 6 skeletons arriving at the center nor was there any issue with timing.

## Known Issues and TODO List:

None

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

2023-10-01 07:21 UTC, elthehablo requested changes

2023-10-01 07:21 UTC, elthehablo commented on data/sql/updates/pending_db_world/rev_1696128697046487685.sql
> +(10440, 0, 0, 0, 0, 0, 100, 0, 4000, 9000, 7000, 11000, 0, 0, 11, 15284, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 'Every 7 - 11 seconds (4 - 9s initially) - Self: Cast spell 15284 on Victim'),
Change the comments to the more modern standard "Baron Rivendare - IC - Cast full spell name"

2023-10-01 07:22 UTC, elthehablo commented
Ideally we would the skeleton spawn position sniffed

2023-10-01 07:48 UTC, kjack9 commented
I will make the formatting changes you requested.

> Ideally we would want the skeleton spawn position sniffed

I presume the original positions I'm changing match the actual game. That being said, they break the encounter entirely (Baron heals himself with no way to stop it). So I guess the question is is it better to leave it broken (as it has been for at [least a year](https://github.com/chromiecraft/chromiecraft/issues/3709) and likely a lot longer) pending a rewrite of the movement system, or is it better to move the positions forward slightly so the encounter works again?

I leave that decision up to you.

2023-10-01 07:52 UTC, elthehablo commented
> I will make the formatting changes you requested.
> 
> > Ideally we would want the skeleton spawn position sniffed
> 
> I presume the original positions I'm changing match the actual game. That being said, they break the encounter entirely (Baron heals himself with no way to stop it). So I guess the question is is it better to leave it broken (as it has been for at [least a year](https://github.com/chromiecraft/chromiecraft/issues/3709) and likely a lot longer) pending a rewrite of the movement system, or is it better to move the positions forward slightly so the encounter works again?
> 
> I leave that decision up to you.

Unfortunately you can't just presume that some old work on AC makes sense. I'd prefer to see someone up to sniff the positions so we can have them correct. If that doesn't happen then we can think about other things. Thanks for the work on this!

2023-10-01 07:57 UTC, kjack9 commented
> > I will make the formatting changes you requested.
> > > Ideally we would want the skeleton spawn position sniffed
> > 
> > 
> > I presume the original positions I'm changing match the actual game. That being said, they break the encounter entirely (Baron heals himself with no way to stop it). So I guess the question is is it better to leave it broken (as it has been for at [least a year](https://github.com/chromiecraft/chromiecraft/issues/3709) and likely a lot longer) pending a rewrite of the movement system, or is it better to move the positions forward slightly so the encounter works again?
> > I leave that decision up to you.
> 
> Unfortunately you can't just presume that some old work on AC makes sense. I'd prefer to see someone up to sniff the positions so we can have them correct. If that doesn't happen then we can think about other things. Thanks for the work on this!

Understood. Seems to shame to have it broken, but I don't have the knowledge at this point to go sniff the fight to see what's going on. Maybe once I get some other projects wrapped up. I'll leave it up to you guys if this is worth implementing in the meantime.

2023-10-01 07:58 UTC, elthehablo commented
> > > I will make the formatting changes you requested.
> > > > Ideally we would want the skeleton spawn position sniffed
> > > 
> > > 
> > > I presume the original positions I'm changing match the actual game. That being said, they break the encounter entirely (Baron heals himself with no way to stop it). So I guess the question is is it better to leave it broken (as it has been for at [least a year](https://github.com/chromiecraft/chromiecraft/issues/3709) and likely a lot longer) pending a rewrite of the movement system, or is it better to move the positions forward slightly so the encounter works again?
> > > I leave that decision up to you.
> > 
> > Unfortunately you can't just presume that some old work on AC makes sense. I'd prefer to see someone up to sniff the positions so we can have them correct. If that doesn't happen then we can think about other things. Thanks for the work on this!
> 
> Understood. Seems to shame to have it broken, but I don't have the knowledge at this point to go sniff the fight to see what's going on. Maybe once I get some other projects wrapped up. I'll leave it up to you guys if this is worth implementing in the meantime.

Would you be able to fix it if you got unparsed sniffs? It is a valuable skill to learn imo. If not, I can try finding the coordinates for you if I get a sniff

2023-10-01 08:13 UTC, kjack9 commented
I simply don't have the cycles to pick up a new discipline right now, unfortunately - I'm assuming it's not a matter of opening up Wireshark and reading the XYZ values. That being said, if you point me in the right direction to get started, I will see what I can make time for in the coming weeks/months.

2023-10-01 09:36 UTC, elthehablo commented
| spellID (guess) | x                        | y                        | z                        | o                        |
| --------------- | ------------------------ | ------------------------ | ------------------------ | ------------------------ |
| 17480           | 4012.92                  | -3365.7                  | 116.334335               | 0.744701027870178222     |
| 17479           | 4009.1                   | -3352.31                 | 116.795334               | 0.299199998378753662     |
| 17478           | 4013.96                  | -3338.65                 | 116.32533                | 6.093992233276367187     |
| 17477           | 4051.75                  | -3339.05                 | 116.32433                | 3.340002059936523437     |
| 17476           | 4055.96                  | -3351.46                 | 116.669334               | 2.870002031326293945     |
| 17475           | 4053.11                  | -3364.98                 | 116.48534                | 2.286992073059082031     |

Verified Build: 50664

I think these are the correct values for the spawns. The positions are taken from an update object which in this case is the packet you receive when a creature spawns in. All 6 are collected at the same time so these are very likely to be correct. I compared to the old values and linked them to each spell that was closest to the new value.

2023-10-01 19:47 UTC, kjack9 commented
I did some testing and while those coordinates are certainly more accurate than the old ones, they fail at about the same rate.

Here is the SQL I'm using:
```SQL
DELETE FROM `spell_target_position` WHERE `ID`=17475 AND `EffectIndex`=0;
INSERT INTO `spell_target_position` (`ID`, `EffectIndex`, `MapID`, `PositionX`, `PositionY`, `PositionZ`, `Orientation`, `VerifiedBuild`) VALUES (17475, 0, 329, 4053.11, -3364.98, 116.485340, 2.29, 0);
DELETE FROM `spell_target_position` WHERE `ID`=17476 AND `EffectIndex`=0;
INSERT INTO `spell_target_position` (`ID`, `EffectIndex`, `MapID`, `PositionX`, `PositionY`, `PositionZ`, `Orientation`, `VerifiedBuild`) VALUES (17476, 0, 329, 4055.96, -3351.46, 116.669334, 2.87, 0);
DELETE FROM `spell_target_position` WHERE `ID`=17477 AND `EffectIndex`=0;
INSERT INTO `spell_target_position` (`ID`, `EffectIndex`, `MapID`, `PositionX`, `PositionY`, `PositionZ`, `Orientation`, `VerifiedBuild`) VALUES (17477, 0, 329, 4051.75, -3339.05, 116.324330, 3.34, 0);
DELETE FROM `spell_target_position` WHERE `ID`=17478 AND `EffectIndex`=0;
INSERT INTO `spell_target_position` (`ID`, `EffectIndex`, `MapID`, `PositionX`, `PositionY`, `PositionZ`, `Orientation`, `VerifiedBuild`) VALUES (17478, 0, 329, 4013.96, -3338.65, 116.325330, 6.09, 0);
DELETE FROM `spell_target_position` WHERE `ID`=17479 AND `EffectIndex`=0;
INSERT INTO `spell_target_position` (`ID`, `EffectIndex`, `MapID`, `PositionX`, `PositionY`, `PositionZ`, `Orientation`, `VerifiedBuild`) VALUES (17479, 0, 329, 4009.10, -3352.31, 116.795334, 0.10, 0);
DELETE FROM `spell_target_position` WHERE `ID`=17480 AND `EffectIndex`=0;
INSERT INTO `spell_target_position` (`ID`, `EffectIndex`, `MapID`, `PositionX`, `PositionY`, `PositionZ`, `Orientation`, `VerifiedBuild`) VALUES (17480, 0, 329, 4012.92, -3365.70, 116.334335, 0.74, 0);
```

I see pretty consistent failures in the skeletons to spawn correctly. This round has two missing:

![Screenshot from 2023-10-01 15-41-51](https://github.com/azerothcore/azerothcore-wotlk/assets/19712078/6843171e-e10e-4e21-94d6-e132b50421a0)

I think the reason my custom ones work is that they're above a flat surface (the ground) rather than on the bone piles. I would guess that something about the geometry of those piles is causing this issue, but that's well outside of my wheelhouse.

I can submit the updated coordinate SQL to this PR and it will increase accuracy, but it will also still cause the fight to fail until the underlying pathing/spawning mechanic is fixed in the unknown future. Or we can implement my slightly tweaked positions and the fight works fine today. How do you want to proceed?

2023-10-01 19:54 UTC, elthehablo commented
> I did some testing and while those coordinates are certainly more accurate than the old ones, they fail at about the same rate.
> 
> Here is the SQL I'm using:
> ```SQL
> DELETE FROM `spell_target_position` WHERE `ID`=17475 AND `EffectIndex`=0;
> INSERT INTO `spell_target_position` (`ID`, `EffectIndex`, `MapID`, `PositionX`, `PositionY`, `PositionZ`, `Orientation`, `VerifiedBuild`) VALUES (17475, 0, 329, 4053.11, -3364.98, 116.485340, 2.29, 0);
> DELETE FROM `spell_target_position` WHERE `ID`=17476 AND `EffectIndex`=0;
> INSERT INTO `spell_target_position` (`ID`, `EffectIndex`, `MapID`, `PositionX`, `PositionY`, `PositionZ`, `Orientation`, `VerifiedBuild`) VALUES (17476, 0, 329, 4055.96, -3351.46, 116.669334, 2.87, 0);
> DELETE FROM `spell_target_position` WHERE `ID`=17477 AND `EffectIndex`=0;
> INSERT INTO `spell_target_position` (`ID`, `EffectIndex`, `MapID`, `PositionX`, `PositionY`, `PositionZ`, `Orientation`, `VerifiedBuild`) VALUES (17477, 0, 329, 4051.75, -3339.05, 116.324330, 3.34, 0);
> DELETE FROM `spell_target_position` WHERE `ID`=17478 AND `EffectIndex`=0;
> INSERT INTO `spell_target_position` (`ID`, `EffectIndex`, `MapID`, `PositionX`, `PositionY`, `PositionZ`, `Orientation`, `VerifiedBuild`) VALUES (17478, 0, 329, 4013.96, -3338.65, 116.325330, 6.09, 0);
> DELETE FROM `spell_target_position` WHERE `ID`=17479 AND `EffectIndex`=0;
> INSERT INTO `spell_target_position` (`ID`, `EffectIndex`, `MapID`, `PositionX`, `PositionY`, `PositionZ`, `Orientation`, `VerifiedBuild`) VALUES (17479, 0, 329, 4009.10, -3352.31, 116.795334, 0.10, 0);
> DELETE FROM `spell_target_position` WHERE `ID`=17480 AND `EffectIndex`=0;
> INSERT INTO `spell_target_position` (`ID`, `EffectIndex`, `MapID`, `PositionX`, `PositionY`, `PositionZ`, `Orientation`, `VerifiedBuild`) VALUES (17480, 0, 329, 4012.92, -3365.70, 116.334335, 0.74, 0);
> ```
> 
> I see pretty consistent failures in the skeletons to spawn correctly. This round has two missing:
> 
> ![Screenshot from 2023-10-01 15-41-51](https://github.com/azerothcore/azerothcore-wotlk/assets/19712078/6843171e-e10e-4e21-94d6-e132b50421a0)
> 
> I think the reason my custom ones work is that they're above a flat surface (the ground) rather than on the bone piles. I would guess that something about the geometry of those piles is causing this issue, but that's well outside of my wheelhouse.
> 
> I can submit the updated coordinate SQL to this PR and it will increase accuracy, but it will also still cause the fight to fail until the underlying pathing/spawning mechanic is fixed in the unknown future. Or we can implement my slightly tweaked positions and the fight works fine today. How do you want to proceed?

Can you test with your z coordinates and the x y and o from the sniffs?

2023-10-01 19:56 UTC, elthehablo commented
Scratch that. I am working on something. Standby

2023-10-01 20:03 UTC, elthehablo commented
Can you try the following?

- 17480: X: 4053.11 Y: -3364.98 Z: 116.402 Orientation: 2.286992073059082031
- 17479 X: 4055.96 Y: -3351.46 Z: 116.586 Orientation: 2.870002031326293945
- 17478 X: 4051.75 Y: -3339.05 Z: 116.241 Orientation: 3.340002059936523437
- 17477 X: 4013.96 Y: -3338.65 Z: 116.242 Orientation: 6.093992233276367187
- 17476 X: 4009.1 Y: -3352.31 Z: 116.712 Orientation: 0.299199998378753662
- 17475 X: 4012.92 Y: -3365.7 Z: 116.251 Orientation: 0.744701027870178222

2023-10-01 21:25 UTC, kjack9 commented
> Can you try the following?
> 
>     * 17480: X: 4053.11 Y: -3364.98 Z: 116.402 Orientation: 2.286992073059082031
> 
>     * 17479 X: 4055.96 Y: -3351.46 Z: 116.586 Orientation: 2.870002031326293945
> 
>     * 17478 X: 4051.75 Y: -3339.05 Z: 116.241 Orientation: 3.340002059936523437
> 
>     * 17477 X: 4013.96 Y: -3338.65 Z: 116.242 Orientation: 6.093992233276367187
> 
>     * 17476 X: 4009.1 Y: -3352.31 Z: 116.712 Orientation: 0.299199998378753662
> 
>     * 17475 X: 4012.92 Y: -3365.7 Z: 116.251 Orientation: 0.744701027870178222

```SQL
DELETE FROM `spell_target_position` WHERE `ID`=17475 AND `EffectIndex`=0;
INSERT INTO `spell_target_position` (`ID`, `EffectIndex`, `MapID`, `PositionX`, `PositionY`, `PositionZ`, `Orientation`, `VerifiedBuild`) VALUES (17475, 0, 329, 4012.92, -3365.70, 116.251, 0.745, 0);
DELETE FROM `spell_target_position` WHERE `ID`=17476 AND `EffectIndex`=0;
INSERT INTO `spell_target_position` (`ID`, `EffectIndex`, `MapID`, `PositionX`, `PositionY`, `PositionZ`, `Orientation`, `VerifiedBuild`) VALUES (17476, 0, 329, 4009.10, -3352.31, 116.712, 0.299, 0);
DELETE FROM `spell_target_position` WHERE `ID`=17477 AND `EffectIndex`=0;
INSERT INTO `spell_target_position` (`ID`, `EffectIndex`, `MapID`, `PositionX`, `PositionY`, `PositionZ`, `Orientation`, `VerifiedBuild`) VALUES (17477, 0, 329, 4013.96, -3338.65, 116.242, 6.094, 0);
DELETE FROM `spell_target_position` WHERE `ID`=17478 AND `EffectIndex`=0;
INSERT INTO `spell_target_position` (`ID`, `EffectIndex`, `MapID`, `PositionX`, `PositionY`, `PositionZ`, `Orientation`, `VerifiedBuild`) VALUES (17478, 0, 329, 4051.75, -3339.05, 116.241, 3.340, 0);
DELETE FROM `spell_target_position` WHERE `ID`=17479 AND `EffectIndex`=0;
INSERT INTO `spell_target_position` (`ID`, `EffectIndex`, `MapID`, `PositionX`, `PositionY`, `PositionZ`, `Orientation`, `VerifiedBuild`) VALUES (17479, 0, 329, 4055.96, -3351.46, 116.586, 2.870, 0);
DELETE FROM `spell_target_position` WHERE `ID`=17480 AND `EffectIndex`=0;
INSERT INTO `spell_target_position` (`ID`, `EffectIndex`, `MapID`, `PositionX`, `PositionY`, `PositionZ`, `Orientation`, `VerifiedBuild`) VALUES (17480, 0, 329, 4053.11, -3364.98, 116.402, 2.287, 0);
```

It *seems* to be some better? But still has pretty reliable failures. I saw one round where only half the skeletons made it.

Just to confirm, I am doing the following to test each time:
- Converting the position data into SQL that I'm including each time
- Apply that SQL to the DB while the game is running
- `.reload spell_target_position`

I did confirm that I can change the positioning of the spell while the server is running in this way.

2023-10-01 21:38 UTC, elthehablo commented
Is there a specific one that fails every time?

2023-10-01 21:41 UTC, kjack9 commented
> Is there a specific one that fails every time?

Negative, there doesn't appear to be a pattern. Sometimes I get all six, sometimes I get half.

![Screenshot from 2023-10-01 17-22-20](https://github.com/azerothcore/azerothcore-wotlk/assets/19712078/6a58bbcb-7160-4a77-8548-6eeddf7d6333)

2023-10-01 21:44 UTC, elthehablo commented
Hrmmm and can you try moving the z coordinates up a bit? There seems to be bigger problems here

2023-10-01 21:47 UTC, kjack9 commented
> Hrmmm and can you try moving the z coordinates up a bit? There seems to be bigger problems here

That's actually the first thing I tried before I moved the positions to in front of the bone piles. I just tested again, and moving the Z coordinate up by 2 units produces the same inconsistent result.

2023-10-02 03:54 UTC, kjack9 commented
Wow, talk about a rabbit hole. I think I figured out what's going on here.

The spells in question (for example 17475) have the effect [SPELL_EFFECT_SUMMON](https://www.azerothcore.org/wiki/spell-effects-reference) with a EffectMiscValueA of our skellies (11197).

![image](https://github.com/azerothcore/azerothcore-wotlk/assets/19712078/4377c7e7-ebb2-4c6a-b454-02ac402ed649)

Now, the spell also has a radius of 0-0, which should in theory mean that the summon appears exactly where it's targeted (making some assumptions here). The [AC docs ](https://www.azerothcore.org/wiki/spell-effects-reference) indicate that the Radius is the spawn range.

However, that's not what's happening...after the first summon. The spell always lands at the exact right spot (see the spell effect in the video below), but the actual summon is appearing in a radius around that point.

In this test, I have done `.learn 17475` on myself and set the `spell_target_position` to the exact spot I'm standing in at the beginning of the video. When I activate the spell, the FIRST summon always appears right on top of me. But if I keep making summons, the ones after the first are all over the map.

https://www.youtube.com/watch?v=Zuuc-yvQ5SI

Interestingly, if I wait for the first summon to despawn before triggering the next one, the next one is correctly spawned on my position. Demonstrated here: https://youtu.be/Zuuc-yvQ5SI?si=gLEmKoaYlPzx8rde&t=31

Based on my from-the-hip guess, I think what we're seeing here is logic implemented to keep guardians from stacking up on top of each other. However in this case, it is causing them to spawn inside the WALL, rather than falling through the floor. That's why raising the Z value doesn't do anything, and why moving the spell target forward fixed the issue.

Unfortunately, spell debugs weren't much help in this case:

```
SpellMgr::GetSpellForDifficultyFromSpell: Spell id for instance mode is 17475 (original 17475)
Spell::prepare: spell id 17475 source 0 caster 0 customCastFlags 0 mask 0
Spell: 17475 Effect : 28
Spell: 17475 Effect : 28
```

I think bigger brains than mine are going to be required to figure this out. Do you think its worth it to implement this change as-is since it fixes the immediate issue? Or should we move this to an Issue report that may get fixed...who knows when?

2023-10-02 05:26 UTC, elthehablo commented
I wonder if you slightly alter the spawn radius you might fix this. Because a slight offset should make them not spawn on top of each other

2023-10-02 05:28 UTC, elthehablo commented
I'd like you to at least push the sniffed spell locations I posted in the comment above (not the table but the one below it). Make sure to add the VerifiedBuild and then maybe try to add a slight radius

2023-10-02 05:34 UTC, kjack9 commented
> I wonder if you slightly alter the spawn radius you might fix this. Because a slight offset should make them not spawn on top of each other

The problem isn't them spawning on top of each other. After the first one is spawned and move away, the NEXT one gets spawned somewhere in the radius. Increasing the radius I'm pretty sure would make the problem worse.

I have updated the values in the branch to the more-accurate but definitely-broken sniffer coordinates.

2023-10-02 05:43 UTC, elthehablo commented
> > I wonder if you slightly alter the spawn radius you might fix this. Because a slight offset should make them not spawn on top of each other
> 
> The problem isn't them spawning on top of each other. After the first one is spawned and move away, the NEXT one gets spawned somewhere in the radius. Increasing the radius I'm pretty sure would make the problem worse.
> 
> I have updated the values in the branch to the more-accurate but definitely-broken sniffer coordinates.
> 
> 

But the radius is 0 and bound to the spell destination location, no?

2023-10-02 05:43 UTC, elthehablo commented
So the radius here would be an offset from that position

2023-10-02 06:47 UTC, kjack9 commented
> So the radius here would be an offset from that position

Discussed on Discord - the problem now is that the radius is too large (including outside the wall). AC is not honoring the 0 radius of the spell in combination with the `spell_target_position` value.

2023-10-02 08:09 UTC, Nyeriah commented
Aran water elementals had the same issue; I just increased the radius since it’s illogical as they’re mutually exclusive

2023-10-02 08:58 UTC, kjack9 commented
> Aran water elementals had the same issue; I just increased the radius since it’s illogical as they’re mutually exclusive

Would you prefer I workaround the issue with moving the positioning slightly, adjusting the radius through a spell override, or waiting until the root cause is fixed?

2023-10-14 07:40 UTC, kjack9 commented
> Aran water elementals had the same issue; I just increased the radius since it’s illogical as they’re mutually exclusive

@Nyeriah Thanks for pointing me towards that, I didn't know about that way to alter spells - awesome!

I made the last commit basically emulating the changes you made with Aran's Water Elementals - changing the range to 50k yards. While it _may_ be slightly better, I'm unfortunately still seeing misses. This is with the sniff that @elthehablo used to get those spawn values.

![image](https://github.com/azerothcore/azerothcore-wotlk/assets/19712078/e6026c09-c239-4e39-b84b-1d1e005c2264)

Middle left is missing, and it moves around sporadically.

I also redid my test with me standing still and using the spell myself. The undead guys still spawn in a radius around me.

I also tried this change:

```c++
    ApplySpellFix({ 17475, 17476, 17477, 17478, 17479, 17480 }, [](SpellInfo* spellInfo)
    {
        spellInfo->Effects[EFFECT_0].RadiusEntry = sSpellRadiusStore.LookupEntry(EFFECT_RADIUS_0_5_YARDS);
    });
```
And the effect was the same.

Did I misunderstand what change needed to be made?

2023-10-14 07:56 UTC, kjack9 commented
Additional information: commenting out [these lines](https://github.com/azerothcore/azerothcore-wotlk/blob/608f1c92fad0d418a0b70f90905ea93a14f70148/src/server/game/Spells/SpellEffects.cpp#L6085-L6086) completely fixes the problem. It's not a real fix since it will affect lots of things it shouldn't, but it's definitely the follow angle change that is causing the sporadic spawn locations.

2023-10-14 08:50 UTC, kjack9 commented
If and when PR #17506 gets merged, we can still use this PR to make the positions more accurate and to work on the SAI script.

2023-10-16 22:10 UTC, elthehablo commented
so now with the other PR and sniffed positions this should be accurate, no?

2023-10-16 22:19 UTC, kjack9 commented
> so now with the other PR and sniffed positions this should be accurate, no?

You got it.

I have noticed there's some issues with the SAI for Baron - his cast to raise dead and the actual cast desync over time. That being said, it's an existing issue and I'm planning on fixing it in a future PR. I believe this should be safe to merge and will at least make the fight complete-able.

2023-10-16 22:22 UTC, kjack9 commented
> > so now with the other PR and sniffed positions this should be accurate, no?
> 
> You got it.
> 
> I have noticed there's some issues with the SAI for Baron - his cast to raise dead and the actual cast desync over time. That being said, it's an existing issue and I'm planning on fixing it in a future PR. I believe this should be safe to merge and will at least make the fight complete-able.

Strike that, I think I have an unintentional change that is causing the timing issue. Standby while I roll that back.

2023-10-16 23:10 UTC, kjack9 commented
Reverted the stray timing change and kept the summon kill on reset and the comment updates. Tested on my server and confirmed the fight runs fine for several minutes without any desync issues.

As far as I'm concerned, this should be good to merge.

2023-10-17 06:30 UTC, elthehablo commented on data/sql/updates/pending_db_world/rev_1696128697046487685.sql
> +INSERT INTO `spell_target_position` (`ID`, `EffectIndex`, `MapID`, `PositionX`, `PositionY`, `PositionZ`, `Orientation`, `VerifiedBuild`) VALUES (17475, 0, 329, 4012.92, -3365.70, 116.251, 0.745, 0);
```suggestion
INSERT INTO `spell_target_position` (`ID`, `EffectIndex`, `MapID`, `PositionX`, `PositionY`, `PositionZ`, `Orientation`, `VerifiedBuild`) VALUES (17475, 0, 329, 4012.92, -3365.70, 116.251, 0.745, 50664);
```

2023-10-17 06:32 UTC, elthehablo requested changes

2023-10-17 06:32 UTC, elthehablo commented on data/sql/updates/pending_db_world/rev_1696128697046487685.sql
> +INSERT INTO `spell_target_position` (`ID`, `EffectIndex`, `MapID`, `PositionX`, `PositionY`, `PositionZ`, `Orientation`, `VerifiedBuild`) VALUES (17480, 0, 329, 4053.11, -3364.98, 116.402, 2.287, 0);
```suggestion
DELETE FROM `spell_target_position` WHERE `ID`=17475 AND `EffectIndex`=0;
INSERT INTO `spell_target_position` (`ID`, `EffectIndex`, `MapID`, `PositionX`, `PositionY`, `PositionZ`, `Orientation`, `VerifiedBuild`) VALUES (17475, 0, 329, 4012.92, -3365.70, 116.251, 0.745, 50664);
DELETE FROM `spell_target_position` WHERE `ID`=17476 AND `EffectIndex`=0;
INSERT INTO `spell_target_position` (`ID`, `EffectIndex`, `MapID`, `PositionX`, `PositionY`, `PositionZ`, `Orientation`, `VerifiedBuild`) VALUES (17476, 0, 329, 4009.10, -3352.31, 116.712, 0.299, 50664);
DELETE FROM `spell_target_position` WHERE `ID`=17477 AND `EffectIndex`=0;
INSERT INTO `spell_target_position` (`ID`, `EffectIndex`, `MapID`, `PositionX`, `PositionY`, `PositionZ`, `Orientation`, `VerifiedBuild`) VALUES (17477, 0, 329, 4013.96, -3338.65, 116.242, 6.094, 50664);
DELETE FROM `spell_target_position` WHERE `ID`=17478 AND `EffectIndex`=0;
INSERT INTO `spell_target_position` (`ID`, `EffectIndex`, `MapID`, `PositionX`, `PositionY`, `PositionZ`, `Orientation`, `VerifiedBuild`) VALUES (17478, 0, 329, 4051.75, -3339.05, 116.241, 3.340, 50664);
DELETE FROM `spell_target_position` WHERE `ID`=17479 AND `EffectIndex`=0;
INSERT INTO `spell_target_position` (`ID`, `EffectIndex`, `MapID`, `PositionX`, `PositionY`, `PositionZ`, `Orientation`, `VerifiedBuild`) VALUES (17479, 0, 329, 4055.96, -3351.46, 116.586, 2.870, 50664);
DELETE FROM `spell_target_position` WHERE `ID`=17480 AND `EffectIndex`=0;
INSERT INTO `spell_target_position` (`ID`, `EffectIndex`, `MapID`, `PositionX`, `PositionY`, `PositionZ`, `Orientation`, `VerifiedBuild`) VALUES (17480, 0, 329, 4053.11, -3364.98, 116.402, 2.287, 50664);
```

with sniffed positions, we add verified build (build which we took the values from) to have a quick history reference for any potential work in the future

2023-10-17 07:07 UTC, elthehablo approved these changes

2023-10-17 08:39 UTC, merged