fix(DB/Quest): Spanish text for Mebok Mizzyrix greeting
azerothcore/azerothcore-wotlk pull request #17634
Opened 2023-11-02 23:30 UTC by trdillon

## Changes Proposed:

This PR proposes changes to:
-  [ ] Core (units, players, creatures, game systems).
-  [ ] Scripts (bosses, spell scripts, creature scripts).
-  [x] Database (SAI, creatures, etc).

## Issues Addressed:

- Closes #16312 

## SOURCE:

The changes have been validated through:
- [ ] Live research (checked on live servers, e.g Classic WotLK, Retail, etc.)
- [ ] Sniffs (remember to share them with the open source community!)
- [x] Video evidence, knowledge databases or other public sources (e.g forums, Wowhead, etc.)
- [ ] The changes promoted by this pull request come partially or entirely from another project (cherry-pick). **Cherry-picks must be committed using the proper --author tag in order to be accepted, thus crediting the original authors, unless otherwise unable to be found**

![16312](https://github.com/azerothcore/azerothcore-wotlk/assets/26350151/b7182570-91d0-49b9-a20e-78fa1ea1d297)

## Tests Performed:

This PR has been:
- [x] Tested in-game by the author.
- [ ] Tested in-game by other community members/someone else other than the author/has been live on production servers.
- [ ] This pull request requires further testing and may have edge cases to be tested.

## How to Test the Changes:

- [x] This pull request can be tested by following the reproduction steps provided in the linked issue
- [ ] This pull request requires further testing. Provide steps to test your changes. If it requires any specific setup e.g multiple players please specify it as well.

1.
2.
3.

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

2023-11-04 14:48 UTC, Valdifer commented
Little thing:
It says 'el humana' when should be 'la humana'

2023-11-04 14:53 UTC, Valdifer requested changes
Little thing:
It says 'el humana' when should be 'la humana'

INSERT INTO `acore_world`.`quest_greeting_locale` (`ID`, `locale`, `Greeting`) VALUES (3446, 'esMX', '¡Sí, sí, sí! ¡Justo $gel:la $r que estaba buscando!$B$B¡Siéntate! Tenemos mucho que hablar.');
INSERT INTO `acore_world`.`quest_greeting_locale` (`ID`, `locale`, `Greeting`) VALUES (3446, 'esES', '¡Sí, sí, sí! ¡Justo $gel:la $r que estaba buscando!$B$B¡Siéntate! Tenemos mucho que hablar.');

2023-11-04 21:22 UTC, trdillon commented
Thanks for pointing that out, I've added those changes.

2023-11-07 11:42 UTC, elthehablo commented
What is the source on the text?

2023-11-07 11:55 UTC, trdillon commented
I used the screenshot in the original issue under expected behavior.

2023-11-07 11:57 UTC, elthehablo commented
Oh I missed that. My bad. Thanks for the PR

2023-11-07 11:59 UTC, elthehablo commented
Need some changes on sql formatting though. Take a look at the [AC sql standards](https://www.azerothcore.org/wiki/sql-standards) please

2023-11-07 22:40 UTC, trdillon commented
My apologies, I missed that part when I was checking out the wiki. The latest commit should conform to the standards.

2023-11-07 22:49 UTC, elthehablo commented
It doesn't, unfortunately. Missing new line and delete before insert

2023-11-07 22:55 UTC, closed without merging

2023-11-08 06:54 UTC, elthehablo commented
Why did you close this?

2023-11-08 17:26 UTC, elthehablo commented on data/sql/updates/pending_db_world/rev_1698965454224484600.sql
> +(3446, 'esES', '¡Sí, sí, sí! ¡Justo $gel:la; $r que estaba buscando!$B$B¡Siéntate! Tenemos mucho que hablar.');
```suggestion
--
DELETE FROM `quest_greeting_locale` WHERE `ID` = 3446 AND `locale` IN ('esMX', 'esES');
INSERT INTO `quest_greeting_locale` (`ID`, `locale`, `Greeting`) VALUES
(3446, 'esMX', '¡Sí, sí, sí! ¡Justo $gel:la; $r que estaba buscando!$B$B¡Siéntate! Tenemos mucho que hablar.'),
(3446, 'esES', '¡Sí, sí, sí! ¡Justo $gel:la; $r que estaba buscando!$B$B¡Siéntate! Tenemos mucho que hablar.');

```