ix(Scripts/IcecrownCitadel): Make Gunship Battle insta-wipe when no-one is outside of cannons
azerothcore/azerothcore-wotlk pull request #17856
Opened 2023-11-25 19:02 UTC by 0x7FFF

Instant lose on Gunship Battle if no-one is outside

## Changes Proposed:

This PR proposes changes to:
-  [ ] Core (units, players, creatures, game systems).
-  [X] Scripts (bosses, spell scripts, creature scripts).
-  [ ] Database (SAI, creatures, etc).

## Issues Addressed:

- None in the issues tab

## SOURCE:

Prior to Mists of Pandaria's patch 5.1 soloing Gunship Battle was not possible, because it would insta-wipe (insta-destroy) the ship.
https://www.bluetracker.gg/wow/topic/gb-en/5967569061-you-can-solo-gunship-cthun/

The changes have been validated through:
- [X] Live research (checked on live servers, e.g Classic WotLK, Retail, etc.)
- [ ] Sniffs (remember to share them with the open source community!)
- [ ] Video evidence, knowledge databases or other public sources (e.g forums, Wowhead, etc.)
- [ ] The changes promoted by this pull request come partially or entirely from another project (cherry-pick). **Cherry-picks must be committed using the proper --author tag in order to be accepted, thus crediting the original authors, unless otherwise unable to be found**

## Tests Performed:

This PR has been:
- [X] Tested in-game by the author.
- [ ] Tested in-game by other community members/someone else other than the author/has been live on production servers.
- [ ] This pull request requires further testing and may have edge cases to be tested.

## How to Test the Changes:

- [X] This pull request can be tested by following the reproduction steps provided in the linked issue
- [ ] This pull request requires further testing. Provide steps to test your changes. If it requires any specific setup e.g multiple players please specify it as well.

1. .go xyz -437.276 1959.755 208.174 631 (Horde)
.go xyz -437.257 2435.229 191.233 631 (Alliance)
2. Start Gunship Battle event
3. Sit inside cannon (solo)

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

2023-11-26 19:37 UTC, Kitzunu commented
build failing, also please update the branch to latest master

2023-11-26 19:42 UTC, Kitzunu commented on src/server/scripts/Northrend/IcecrownCitadel/boss_icecrown_gunship_battle.cpp
> +            for (Map::PlayerList::const_iterator itr = pl.begin(); itr != pl.end(); ++itr) {
curly on a new line, see https://www.azerothcore.org/wiki/cpp-code-standards

2023-11-26 19:42 UTC, Kitzunu commented on src/server/scripts/Northrend/IcecrownCitadel/boss_icecrown_gunship_battle.cpp
> +                    if (!p->GetVehicle()) {
same here

2023-11-26 19:42 UTC, Kitzunu commented on src/server/scripts/Northrend/IcecrownCitadel/boss_icecrown_gunship_battle.cpp
> +            for (Map::PlayerList::const_iterator itr = pl.begin(); itr != pl.end(); ++itr) {
(or dont use it for oneliners)

2023-11-26 22:14 UTC, Kitzunu approved these changes

2023-11-26 22:50 UTC, Nyeriah commented
Question: at some point during the encounter every cannon gets frozen and players must kill the mages to resume the encounter. Therefore during that period of time, nobody will be inside a vehicle. I don't see this scenario being checked so is it safe to assume that a wipe will be triggered?

2023-11-26 22:52 UTC, elthehablo commented on src/server/scripts/Northrend/IcecrownCitadel/boss_icecrown_gunship_battle.cpp
> +            Map::PlayerList const& pl = me->GetMap()->GetPlayers();
Can use map->DoForAllPlayers here

2023-11-26 22:53 UTC, Nyeriah commented
Furthermore, please add this to a timer considering UpdateAI() ticks every millesecond and the current code iterates through the map player storage every millesecond which is not very resource efficient

2023-11-26 22:53 UTC, heyitsbench commented
> I don't see this scenario being checked
```
if (!p->GetVehicle())
{
    // At least one player is outside a cannon, return --->without<--- resetting event.
    return;
}

2023-11-26 22:56 UTC, Nyeriah commented
> > I don't see this scenario being checked
> 
> ```
> if (!p->GetVehicle())
> {
>     // At least one player is outside a cannon, return --->without<--- resetting event.
>     return;
> }
> ```

Thanks, I had misunderstood the logic behind it. The other point I've raised remains relevant though.

2023-11-28 23:18 UTC, Kitzunu requested changes
Please see to the reviews above

2023-11-30 21:25 UTC, qwe900 commented
i think with alot of players using autobalance or simimal things i would not change this.

2023-11-30 21:27 UTC, Kitzunu commented
If this is blizzlike we should implement this in the core. Doesn't matter if it breaks a module, then the module author or maintainer can fix it from the module

2023-12-01 07:49 UTC, elthehablo commented
Not to mention that it would be really easy to patch again in that module after fixing this

2023-12-05 17:15 UTC, LannyE commented
Just to add my half cent to the discussion as a person who solos a lot, with the worldserver.conf being chock-full of non-blizzlike behavior to customize your experience would it be possible to make this as an option (defaulted to enable wipe, of course) in the conf?  This would make it so a server admin wouldn't have to wait for a fix to a module or module(s) to continue playing the way they used to.

2024-03-11 20:45 UTC, sudlud commented
@0x7FFF what's the state of this PR? 🙂
There are pending reviews and also a suggestion to make it a config option to disable this feature maybe, do you want to update the PR?

2024-06-30 17:51 UTC, closed without merging

2024-06-30 17:51 UTC, Kitzunu commented
Closed in favor of https://github.com/azerothcore/azerothcore-wotlk/pull/19239