fix(DB/Tanaris): move Aquementas to SAI using sniffs as source
azerothcore/azerothcore-wotlk pull request #18027
Opened 2023-12-17 22:38 UTC by elthehablo

## Changes Proposed:

This PR proposes changes to:
-  [ ] Core (units, players, creatures, game systems).
-  [ ] Scripts (bosses, spell scripts, creature scripts).
-  [x] Database (SAI, creatures, etc).

## Issues Addressed:

- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/12994
- Closes https://github.com/chromiecraft/chromiecraft/issues/4048

## SOURCE:

The changes have been validated through:
- [x] Live research (checked on live servers, e.g Classic WotLK, Retail, etc.)
- [x] Sniffs (remember to share them with the open source community!)
- [ ] Video evidence, knowledge databases or other public sources (e.g forums, Wowhead, etc.)
- [ ] The changes promoted by this pull request come partially or entirely from another project (cherry-pick). **Cherry-picks must be committed using the proper --author tag in order to be accepted, thus crediting the original authors, unless otherwise unable to be found**

## Tests Performed:

This PR has been:
- [x] Tested in-game by the author.
- [ ] Tested in-game by other community members/someone else other than the author/has been live on production servers.
- [ ] This pull request requires further testing and may have edge cases to be tested.

## How to Test the Changes:

- [x] This pull request can be tested by following the reproduction steps provided in the linked issue
- [ ] This pull request requires further testing. Provide steps to test your changes. If it requires any specific setup e.g multiple players please specify it as well.

1.
2.
3.

## Known Issues and TODO List:

- [ ] https://github.com/azerothcore/azerothcore-wotlk/issues/7514

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

2023-12-27 01:07 UTC, Nyeriah approved these changes

2023-12-27 01:08 UTC, Nyeriah commented
Startup errors

2023-12-27 01:08 UTC, Nyeriah requested changes
Error

2023-12-27 07:49 UTC, elthehablo commented
This is WIP, sorry forgot to add the label

2023-12-29 10:52 UTC, elthehablo commented
Apparently prio of linked events skip condition checking. Which kinda makes sense

2023-12-29 11:29 UTC, elthehablo commented
Changed the condition. Item req conditions are a mess and don't seem to work well here. If anyone knows more about these item req conditions and can help it would be appreciated.

2023-12-29 11:38 UTC, elthehablo commented
```sql
DELETE FROM `conditions` WHERE `SourceTypeOrReferenceId` = 22 AND `SourceEntry` = 9453 AND `SourceId` = 0 AND `SourceGroup` = 18;
INSERT INTO `conditions` (`SourceTypeOrReferenceId`, `SourceGroup`, `SourceEntry`, `SourceId`, `ElseGroup`, `ConditionTypeOrReference`, `ConditionTarget`, `ConditionValue1`, `ConditionValue2`, `ConditionValue3`, `NegativeCondition`, `ErrorType`, `ErrorTextId`, `ScriptName`, `Comment`) VALUES
(22, 18, 9453, 0, 1, 2, 0, 11169, 1, 0, 0, 0, 0, '', 'Has 1 book of aquor'),
(22, 18, 9453, 0, 1, 2, 0, 11522, 1, 0, 1, 0, 0, '', 'Does not have totem'),
(22, 18, 9453, 0, 1, 2, 0, 11172, 11, 0, 0, 0, 0, '', 'Has 11 silvery claws'),
(22, 18, 9453, 0, 1, 2, 0, 11173, 1, 0, 0, 0, 0, '', 'Has 1 irontree heart');
```

this doesn't work, for instance

2024-01-07 10:14 UTC, Kitzunu commented
Make the comments more "SAI" like or more descriptive. In this case, it would be

```sql
(22, 18, 9453, 0, 0, 47, 0, 4005, 8, 0, 0, 0, 0, '', 'Run SAI if player Has quest Aquementas OR');
(22, 18, 9453, 0, 1, 2, 0, 11169, 1, 0, 0, 0, 0, '', 'Run SAI if player has 1 book of aquor AND'),
(22, 18, 9453, 0, 1, 2, 0, 11522, 1, 0, 1, 0, 0, '', 'Run SAI if player Does not have totem AND'),
(22, 18, 9453, 0, 1, 2, 0, 11172, 11, 0, 0, 0, 0, '', 'Run SAI if player Has 11 silvery claws AND'),
(22, 18, 9453, 0, 1, 2, 0, 11173, 1, 0, 0, 0, 0, '', 'Run SAI if player Has 1 irontree heart');
```

Is this the intended order of how you want it to work?

2024-01-07 10:16 UTC, elthehablo commented
> Make the comments more "SAI" like or more descriptive. In this case, it would be
> 
> ```sql
> (22, 18, 9453, 0, 0, 47, 0, 4005, 8, 0, 0, 0, 0, '', 'Run SAI if player Has quest Aquementas OR');
> (22, 18, 9453, 0, 1, 2, 0, 11169, 1, 0, 0, 0, 0, '', 'Run SAI if player has 1 book of aquor AND'),
> (22, 18, 9453, 0, 1, 2, 0, 11522, 1, 0, 1, 0, 0, '', 'Run SAI if player Does not have totem AND'),
> (22, 18, 9453, 0, 1, 2, 0, 11172, 11, 0, 0, 0, 0, '', 'Run SAI if player Has 11 silvery claws AND'),
> (22, 18, 9453, 0, 1, 2, 0, 11173, 1, 0, 0, 0, 0, '', 'Run SAI if player Has 1 irontree heart');
> ```
> 
> Is this the intended order of how you want it to work?

No. The quest part can be scrapped. I just left that as a placeholder until I could figure out the item conditions

2024-01-07 10:16 UTC, elthehablo commented
I wanna match what the conditions in the script do

2024-01-07 10:17 UTC, Kitzunu commented
But if I understand you correctly the entire check to see if the player has an item doesn't work. Which I don't get because I don't see any issues.

Does it work with only 1 item condition?
Does it work for something else other than SAI SourceType?
Otherwise I think you need to debug it in the core too see what happens

2024-01-07 10:23 UTC, elthehablo commented
> But if I understand you correctly the entire check to see if the player has an item doesn't work. Which I don't get because I don't see any issues.
> 
> Does it work with only 1 item condition?
> Does it work for something else other than SAI SourceType?
> Otherwise I think you need to debug it in the core too see what happens

The check didn't work with any item condition I think. At least not as intended.

The quest status SAI condition does work.

I am unfamiliar how to debug SAI

2024-01-07 10:23 UTC, elthehablo commented
Okay nvm I have an idea. Just put some logs in the smartai code in the core

2024-01-07 10:24 UTC, Kitzunu commented
> Okay nvm I have an idea. Just put some logs in the smartai code in the core

The superior way to debug 😎 

But yea sounds like some internal issue

2024-01-07 12:03 UTC, elthehablo commented
Not too trivial to debug it seems. Looks like it won't even reach the case in the switch statement for conditiontype

2024-01-07 12:03 UTC, elthehablo commented
![image](https://github.com/azerothcore/azerothcore-wotlk/assets/83884799/cd20a81a-d5a9-4ea2-bfac-a4660a9e6f06)
here

2024-01-07 12:11 UTC, elthehablo commented
idek when the conditions are fired. seems like it isn't fired when the SAI event is fired for some reason. very odd

2024-01-07 13:46 UTC, Kitzunu commented
Check if the condition is even loaded.

As good and fun outlogs can be, I do recommend using Breakpoints at times. See https://www.azerothcore.org/wiki/run-worldserver-and-authserver-in-visual-studio for how to start the servers in Visual Studio so you can actively debug it

2024-06-22 18:44 UTC, avarishd commented
Status?

2024-06-22 20:18 UTC, elthehablo commented
> Status?

Depression

2024-06-23 20:24 UTC, Gultask commented
I'll help

2024-06-23 20:46 UTC, Gultask commented
What a weird quest

2024-06-23 20:53 UTC, Gultask commented
![image](https://github.com/azerothcore/azerothcore-wotlk/assets/100873791/9af52275-d7d6-4b2f-95e8-c004fc76210d)
found you

2024-06-23 22:23 UTC, Gultask commented on data/sql/updates/pending_db_world/aquementas.sql
> +(22, 18, 9453, 0, 0, 47, 0, 4005, 8, 0, 0, 0, 0, '', 'Has quest Aquementas');
```suggestion
--
DELETE FROM `smart_scripts` WHERE (`source_type` = 0 AND `entryorguid` = 9453);
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `event_param5`, `event_param6`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_param4`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES
(9453, 0, 0, 0, 0, 0, 100, 0, 10200, 10200, 12600, 15840, 0, 0, 11, 15089, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 'Aquementas - In Combat - Cast \'Frost Shock\''),
(9453, 0, 1, 0, 0, 0, 100, 0, 11800, 11800, 29300, 30480, 0, 0, 11, 13586, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 'Aquementas - In Combat - Cast \'Aqua Jet\''),
(9453, 0, 2, 0, 54, 0, 100, 0, 0, 0, 0, 0, 0, 0, 80, 945300, 2, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 'Aquementas - On Just Summoned - Run Script'),
(9453, 0, 3, 0, 58, 0, 100, 0, 0, 945300, 0, 0, 0, 0, 80, 945301, 2, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 'Aquementas - On Path 945300 Finished - Run Script');

DELETE FROM `smart_scripts` WHERE (`entryorguid` = 945300) AND (`source_type` = 9);
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `event_param5`, `event_param6`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_param4`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES
(945300, 9, 0, 0, 0, 0, 100, 0, 0, 0, 0, 0, 0, 0, 11, 7398, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 'Aquementas - Actionlist - Cast \'Birth\''),
(945300, 9, 1, 0, 0, 0, 100, 0, 0, 0, 0, 0, 0, 0, 2, 35, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 'Aquementas - Actionlist - Set Faction 35'),
(945300, 9, 2, 0, 0, 0, 100, 0, 400, 400, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 'Aquementas - Actionlist - Say Line 0'),
(945300, 9, 3, 0, 0, 0, 100, 0, 0, 0, 0, 0, 0, 0, 53, 0, 945300, 0, 0, 0, 2, 1, 0, 0, 0, 0, 0, 0, 0, 0, 'Aquementas - Actionlist - Start Waypoint Path 945300');

DELETE FROM `smart_scripts` WHERE (`source_type` = 9 AND `entryorguid` = 945301);
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `event_param5`, `event_param6`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_param4`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES
(945301, 9, 0, 0, 0, 0, 100, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 21, 40, 0, 0, 0, 0, 0, 0, 0, 'Aquementas - Actionlist - Say Line 1'),
(945301, 9, 1, 0, 0, 0, 100, 0, 0, 0, 0, 0, 0, 0, 66, 0, 0, 0, 0, 0, 0, 21, 40, 0, 0, 0, 0, 0, 0, 0, 'Aquementas - Actionlist - Set Orientation Closest Player'),
(945301, 9, 2, 0, 0, 0, 100, 0, 2400, 2400, 0, 0, 0, 0, 1, 2, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 'Aquementas - Actionlist - Say Line 2'),
(945301, 9, 3, 0, 0, 0, 100, 0, 2400, 2400, 0, 0, 0, 0, 1, 3, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 'Aquementas - Actionlist - Say Line 3'),
(945301, 9, 4, 0, 0, 0, 100, 0, 0, 0, 0, 0, 0, 0, 11, 13910, 2, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 'Aquementas - Actionlist - Cast \'Create Elemental Totem\''),
(945301, 9, 5, 0, 0, 0, 100, 0, 0, 0, 0, 0, 0, 0, 57, 11172, 11, 0, 0, 0, 0, 17, 0, 40, 0, 0, 0, 0, 0, 0, 'Aquementas - Actionlist - Remove Item \'Silvery Claws\' 11 Times'),
(945301, 9, 6, 0, 0, 0, 100, 0, 0, 0, 0, 0, 0, 0, 57, 11173, 1, 0, 0, 0, 0, 17, 0, 40, 0, 0, 0, 0, 0, 0, 'Aquementas - Actionlist - Remove Item \'Irontree Heart\' 1 Time'),
(945301, 9, 7, 0, 0, 0, 100, 0, 0, 0, 0, 0, 0, 0, 56, 11522, 1, 0, 0, 0, 0, 17, 0, 40, 0, 0, 0, 0, 0, 0, 'Aquementas - Actionlist - Add Item \'Silver Totem of Aquementas\' 1 Time'),
(945301, 9, 8, 0, 0, 0, 100, 0, 800, 800, 0, 0, 0, 0, 2, 91, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 'Aquementas - Actionlist - Set Faction 91'),
(945301, 9, 9, 0, 0, 0, 100, 0, 400, 400, 0, 0, 0, 0, 49, 0, 0, 0, 0, 0, 0, 21, 40, 0, 0, 0, 0, 0, 0, 0, 'Aquementas - Actionlist - Start Attacking');

DELETE FROM `event_scripts` WHERE `id` = 3708;
INSERT INTO `event_scripts` (`id`, `delay`, `command`, `datalong`, `datalong2`, `dataint`, `x`, `y`, `z`, `o`) VALUES
(3708, 3, 10, 9453, 300000, 0, -8179.4556, -5169.8413, 3.9927793, 1.343903542);

UPDATE `creature_template` SET `AIName` = 'SmartAI', `ScriptName` = '' WHERE `entry` = 9453;

DELETE FROM `waypoints` WHERE `entry` = 945300;
INSERT INTO `waypoints` (`entry`, `pointid`, `position_x`, `position_y`, `position_z`, `orientation`, `delay`, `point_comment`) VALUES
(945300, 1, -8183.2085, -5121.261, 6.3173885, NULL, 0, 'Aquementas'),
(945300, 2, -8183.7007, -5114.497, 7.2097836, NULL, 0, 'Aquementas'),
(945300, 3, -8184.022, -5108.7856, 8.065002, NULL, 0, 'Aquementas'),
(945300, 4, -8181.2485, -5093.14, 11.191019, NULL, 0, 'Aquementas'),
(945300, 5, -8170.1807, -5077.4907, 16.019186, NULL, 0, 'Aquementas');

DELETE FROM `conditions` WHERE (`SourceTypeOrReferenceId` = 17) AND (`SourceGroup` = 0) AND (`SourceEntry` = 13978);
INSERT INTO `conditions` (`SourceTypeOrReferenceId`, `SourceGroup`, `SourceEntry`, `SourceId`, `ElseGroup`, `ConditionTypeOrReference`, `ConditionTarget`, `ConditionValue1`, `ConditionValue2`, `ConditionValue3`, `NegativeCondition`, `ErrorType`, `ErrorTextId`, `ScriptName`, `Comment`) VALUES
(17, 0, 13978, 0, 0, 2, 0, 11172, 11, 0, 0, 0, 0, '', 'Spell \'Summon Aquementas\' (13978) needs 11 \'Silvery Claws\' (11172) in inventory'),
(17, 0, 13978, 0, 0, 2, 0, 11173, 1, 0, 0, 0, 0, '', 'Spell \'Summon Aquementas\' (13978) needs 1 \'Irontree Heart\' (11173) in inventory');

```

2024-06-23 22:28 UTC, Gultask commented
Rewrote it to make it prettier ig.

Ok so my resolution is this. This quest needs a spell & aura script, but I don't know how to make them lmao

The spell 13910 seems to give all players in 30y an aura. At that point I think the aura checks the items, if it has the items, they are removed, and then it makes the player cast 13909 on themselves. Once the spell script is made, then we can remove the Add Item and Remove Item action with no problem.

Also, we can't really use conditions on the SAI here, because it has no Invoker, since the spell calls an event, and thus the invoker is not the player, but the event. It's a weird quest.

2024-06-25 20:30 UTC, Kitzunu commented
I believe in you making a spell and aura script!

What needs to be made? is it just this?
> The spell 13910 seems to give all players in 30y an aura. At that point I think the aura checks the items, if it has the items, they are removed, and then it makes the player cast 13909 on themselves.

Then it should be pretty easy to do

2024-06-25 20:43 UTC, avarishd commented
13910 has a duration of 0.1s, check item requirement on OnRemove and then do 13909

2024-06-26 19:53 UTC, avarishd commented
Depending if the aura is applied or not here are the scripts. (Only difference is the visual effect)
```sql
DELETE FROM `spell_script_names` WHERE `spell_id`=13910;
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (13910, 'spell_gen_create_elemental_totem');
```

Shows effect no matter if conditions are met.

<details>
<summary>Shows effect no matter if the conditions are met.</summary>

```c++
// 13910 - Force Create Elemental Totem
enum ElementalTotem
{
    SPELL_CREATE_ELEMENTAL_TOTEM = 13909, // Serverside, creates [11522] Silver Totem of Aquementas
    ITEM_SILVERY_CLAWS           = 11172,
    ITEM_IRONTREE_HEART          = 11173
};

class spell_gen_create_elemental_totem : public AuraScript
{
    PrepareAuraScript(spell_gen_create_elemental_totem);

    bool Validate(SpellInfo const* /*spellInfo*/) override
    {
        return ValidateSpellInfo({ SPELL_CREATE_ELEMENTAL_TOTEM });
    }

    void OnApply(AuraEffect const* /*aurEff*/, AuraEffectHandleModes /*mode*/)
    {
        Unit* target = GetTarget();
        if (!target && !target->ToPlayer())
            return;

        if (Player* player = target->ToPlayer())
        {
            if (player->HasItemCount(ITEM_IRONTREE_HEART, 1) && player->HasItemCount(ITEM_SILVERY_CLAWS, 11))
            {
                player->DestroyItemCount(ITEM_IRONTREE_HEART, 1, true);
                player->DestroyItemCount(ITEM_SILVERY_CLAWS, 11, true);
                player->CastSpell(player, SPELL_CREATE_ELEMENTAL_TOTEM, true);
            }
            else
            {
                return;
            }
        }
    }

    void Register() override
    {
      OnEffectApply += AuraEffectApplyFn(spell_gen_create_elemental_totem::OnApply, EFFECT_0, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
    }
};
```

</details>

<details>
<summary>Only shows effect once the conditions are met.</summary>

```c++
// 13910 - Force Create Elemental Totem
enum ElementalTotem
{
    SPELL_CREATE_ELEMENTAL_TOTEM = 13909, // Serverside, creates [11522] Silver Totem of Aquementas
    ITEM_SILVERY_CLAWS           = 11172,
    ITEM_IRONTREE_HEART          = 11173
};

class spell_gen_create_elemental_totem : public SpellScript
{
    PrepareSpellScript(spell_gen_create_elemental_totem);

    void FilterTargets(std::list<WorldObject*>& targets)
    {
        targets.remove_if([&](WorldObject const* target) -> bool
        {
            if (!target->ToPlayer())
                return true;

            return (!target->ToPlayer()->HasItemCount(ITEM_IRONTREE_HEART, 1) && !target->ToPlayer()->HasItemCount(ITEM_SILVERY_CLAWS, 11));
        });
    }

    void HandleAfterHit()
    {
        Unit* target = GetHitUnit();

        if (Player* player = target->ToPlayer())
        {
            if (player->HasItemCount(ITEM_IRONTREE_HEART, 1) && player->HasItemCount(ITEM_SILVERY_CLAWS, 11))
            {
                player->DestroyItemCount(ITEM_IRONTREE_HEART, 1, true);
                player->DestroyItemCount(ITEM_SILVERY_CLAWS, 11, true);
                player->CastSpell(player, SPELL_CREATE_ELEMENTAL_TOTEM, true);
            }
        }
    }

    void Register() override
    {
        AfterHit += SpellHitFn(spell_gen_create_elemental_totem::HandleAfterHit);
        OnObjectAreaTargetSelect += SpellObjectAreaTargetSelectFn(spell_gen_create_elemental_totem::FilterTargets, EFFECT_0, TARGET_UNIT_SRC_AREA_ENEMY);
    }
};
```
</details>

2024-07-27 11:27 UTC, Nyeriah commented
@elthehablo @Gultask this ready for merge?

2024-07-27 15:25 UTC, Gultask commented
Need to port avarishd's spellscript into the pr still

2025-02-09 11:11 UTC, Kitzunu commented
Closing as abandoned. Feel free to pick it up later

2025-02-09 11:11 UTC, closed without merging