fix(DB): Portal: Karazhan usable in battlegrounds
azerothcore/azerothcore-wotlk pull request #18177
Opened 2024-01-15 13:53 UTC by Hellcat404

## Changes Proposed:

This PR proposes changes to:
-  [ ] Core (units, players, creatures, game systems).
-  [ ] Scripts (bosses, spell scripts, creature scripts).
-  [x] Database (SAI, creatures, etc).

## Issues Addressed:

- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/18173

## SOURCE:

The changes have been validated through:
- [ ] Live research (checked on live servers, e.g Classic WotLK, Retail, etc.)
- [ ] Sniffs (remember to share them with the open source community!)
- [ ] Video evidence, knowledge databases or other public sources (e.g forums, Wowhead, etc.)
- [ ] The changes promoted by this pull request come partially or entirely from another project (cherry-pick). **Cherry-picks must be committed using the proper --author tag in order to be accepted, thus crediting the original authors, unless otherwise unable to be found**

## Tests Performed:

This PR has been:
- [x] Tested in-game by the author.
- [ ] Tested in-game by other community members/someone else other than the author/has been live on production servers.
- [ ] This pull request requires further testing and may have edge cases to be tested.

## How to Test the Changes:

- [x] This pull request can be tested by following the reproduction steps provided in the linked issue
- [ ] This pull request requires further testing. Provide steps to test your changes. If it requires any specific setup e.g multiple players please specify it as well.

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

2024-01-15 21:32 UTC, Nyeriah commented
Might not be possible to check but there's a spell attribute to prevent casting in pvp zones. Depending on the message sent to client when spell fails maybe that should be used instead of disable. I dont remember how disables handle this specifically tbh

2024-01-15 23:39 UTC, Hellcat404 commented
After taking a look, I think you're right - I'll make a change in conditions to give a spell cast result instead of using disables.

I saw the ritual of summoning disable in the database but I think that should also be moved to conditions

2024-01-16 18:31 UTC, elthehablo requested changes
I don't understand why the update query is there? better to just delete and insert the whole line

2024-01-21 11:41 UTC, Kitzunu commented on data/sql/updates/pending_db_world/rev_1705323899511928342.sql
> +INSERT INTO `conditions` (`SourceTypeOrReferenceId`, `SourceGroup`, `SourceEntry`, `SourceId`, `ElseGroup`, `ConditionTypeOrReference`, `ConditionTarget`, `ConditionValue1`, `ConditionValue2`, `Condi
https://www.azerothcore.org/wiki/sql-standards#compact-queries

2024-01-29 06:32 UTC, elthehablo requested changes
You can put the delete statements together with an in on the map ids to clean up the file and do an insert with multiple lines

```sql
INSERT INTO TABLE VALUES
(something),
(something),
(something);
```

2024-01-29 06:32 UTC, elthehablo commented on data/sql/updates/pending_db_world/rev_1705323899511928342.sql
> +INSERT INTO `conditions` (`SourceTypeOrReferenceId`, `SourceGroup`, `SourceEntry`, `SourceId`, `ElseGroup`, `ConditionTypeOrReference`, `ConditionTarget`, `ConditionValue1`, `ConditionValue2`, `Condi
Typo

2024-01-29 06:32 UTC, elthehablo commented on data/sql/updates/pending_db_world/rev_1705323899511928342.sql
> +INSERT INTO `conditions` (`SourceTypeOrReferenceId`, `SourceGroup`, `SourceEntry`, `SourceId`, `ElseGroup`, `ConditionTypeOrReference`, `ConditionTarget`, `ConditionValue1`, `ConditionValue2`, `Condi
Another typo

2024-03-28 11:20 UTC, pangolp commented
Update the SQL file. But I'm not sure how to test this.

2024-07-18 18:24 UTC, closed without merging