fix(DB/Gameobject): Fix Silithyst Geyser click invalid
azerothcore/azerothcore-wotlk pull request #18279
Opened 2024-02-07 01:11 UTC by disgrace2013

Fix Silithyst Geyser click invalid.

## Changes Proposed:

This PR proposes changes to:
-  [ ] Core (units, players, creatures, game systems).
-  [ ] Scripts (bosses, spell scripts, creature scripts).
-  [ ] Database (SAI, creatures, etc).

## Issues Addressed:

- Closes 

## SOURCE:

The changes have been validated through:
- [ ] Live research (checked on live servers, e.g Classic WotLK, Retail, etc.)
- [ ] Sniffs (remember to share them with the open source community!)
- [ ] Video evidence, knowledge databases or other public sources (e.g forums, Wowhead, etc.)
- [ ] The changes promoted by this pull request come partially or entirely from another project (cherry-pick). **Cherry-picks must be committed using the proper --author tag in order to be accepted, thus crediting the original authors, unless otherwise unable to be found**

## Tests Performed:

This PR has been:
- [ ] Tested in-game by the author.
- [ ] Tested in-game by other community members/someone else other than the author/has been live on production servers.
- [ ] This pull request requires further testing and may have edge cases to be tested.

## How to Test the Changes:

- [ ] This pull request can be tested by following the reproduction steps provided in the linked issue
- [ ] This pull request requires further testing. Provide steps to test your changes. If it requires any specific setup e.g multiple players please specify it as well.

1.
2.
3.

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

2024-02-09 16:29 UTC, pangolp commented
Beyond the line break, which I already mentioned in another message, I think we have a problem. Inside the folder:

```
azerothcore/data/sql/updates/pending_db_world/
|-- create_sql.sh
```

You have that script, what it does is generate an SQL file, and where you must copy the code. I don't know if it works the way you did. I always generate the file with the script.

To correct the error, you would have to create the file with the script, copy the content of one file into another, delete the one you uploaded and take advantage of the line break. Then upload the commit, and see if it passes the tests. I hope I can help you with the explanation and that you can do it. If you need help, let me know.

2024-02-09 17:15 UTC, pangolp commented
@disgrace2013 You forgot to leave an empty line at the end of the document.

2024-02-09 17:30 UTC, pangolp commented
Remember that the file had to be generated with the script, which is located inside the folder. Beyond that, and you can leave a line at the beginning of the document as well as I show you in the image, the truth is that I don't know why the tests fail, they shouldn't.

![image](https://github.com/azerothcore/azerothcore-wotlk/assets/2810187/db92db85-e61b-4b4b-9f39-2f7612e63479)

I can't think of another cause, but I generated these changes and we continue to see what the fault could be. Remember to generate the document with the folder script and inside it, add the information.

2024-02-09 17:45 UTC, disgrace2013 commented
replace the file

2024-02-09 17:54 UTC, pangolp commented
Add me to the discord stevej#5879 and I'll see if I can help you.

2024-02-09 18:10 UTC, disgrace2013 commented
I don't know how to replace the file, this is my first PR .

2024-02-09 18:12 UTC, pangolp commented
> I don't know how to replace the file, this is my first PR .

Don't worry, I noticed.
That's why I invited you to write to me on discord.
It happened to all of us the first time.

2024-02-09 19:13 UTC, elthehablo requested changes
Remove whitelines

2024-02-09 19:13 UTC, elthehablo commented on data/sql/updates/pending_db_world/Silithyst-Geyser-fix.sql
> +
```suggestion
```

2024-02-09 19:13 UTC, elthehablo commented on data/sql/updates/pending_db_world/Silithyst-Geyser-fix.sql
> +
```suggestion
```

2024-02-09 22:15 UTC, pangolp commented
Beyond those changes, which I was going to suggest as well, they don't pass the tests, it's strange. If I could avoid the file, I would do it myself, but it won't let me. Although the idea is to help you so you can learn. We have all had problems the first time we wanted to collaborate.

2024-02-10 04:31 UTC, closed without merging

2024-02-10 16:18 UTC, pangolp commented
Why did you close the pull request? What happened? Don't give up, come on, it's possible! The first time it's hard to understand the mechanics, but then it becomes very repetitive. Plus, we are here to help you.

2024-02-10 16:25 UTC, disgrace2013 commented
> Why did you close the pull request? What happened? Don't give up, come on, it's possible! The first time it's hard to understand the mechanics, but then it becomes very repetitive. Plus, we are here to help you.

I have openned a new PR and it was be checked Successfull.