fix(Scripts/Hyjal): Rewrite Battle for Mount Hyjal
azerothcore/azerothcore-wotlk pull request #18460
Opened 2024-02-29 21:38 UTC by Gultask

## Changes Proposed:

This PR proposes changes to:
-  [ ] Core (units, players, creatures, game systems).
-  [X] Scripts (bosses, spell scripts, creature scripts).
-  [X] Database (SAI, creatures, etc).

## Issues Addressed:

- Closes 

## SOURCE:

The changes have been validated through:
- [ ] Live research (checked on live servers, e.g Classic WotLK, Retail, etc.)
- [X] Sniffs (remember to share them with the open source community!)
- [ ] Video evidence, knowledge databases or other public sources (e.g forums, Wowhead, etc.)
- [ ] The changes promoted by this pull request come partially or entirely from another project (cherry-pick). **Cherry-picks must be committed using the proper --author tag in order to be accepted, thus crediting the original authors, unless otherwise unable to be found**

A lot has been provided by the CMangos team, mainly wave positions.
Pathing has been sniffed by me for the most part.

## Tests Performed:

This PR has been:
- [ ] Tested in-game by the author.
- [ ] Tested in-game by other community members/someone else other than the author/has been live on production servers.
- [ ] This pull request requires further testing and may have edge cases to be tested.

## How to Test the Changes:

- [ ] This pull request can be tested by following the reproduction steps provided in the linked issue
- [ ] This pull request requires further testing. Provide steps to test your changes. If it requires any specific setup e.g multiple players please specify it as well.

1. .ins u all
2. .tele hyjalsummit
3.

## Known Issues and TODO List:

- [ ] If summons are up when a reset happens, the worldserver crashes
- [ ] Crash prevention
- [ ] Thrall, Tyrande
- [ ] Trash scripting
- [ ] Boss modernization
- [ ] DB rework for bases

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

2024-03-01 21:13 UTC, heyitsbench commented
Will this resolve the following issues?
https://github.com/azerothcore/azerothcore-wotlk/issues/4170
https://github.com/azerothcore/azerothcore-wotlk/issues/4171
https://github.com/azerothcore/azerothcore-wotlk/issues/4172

2024-03-01 21:34 UTC, Gultask commented
some already done others not yet, but yea

2024-03-04 19:57 UTC, elthehablo commented
You're insane dude. Nice work

2024-03-04 23:39 UTC, heyitsbench commented
> // It stopped?

As temperamental as the weather.

2024-03-07 20:53 UTC, Gultask commented on data/sql/updates/pending_db_world/rev_1708737709108426300.sql
> +SET @OGUID := 81488;
changed
```suggestion
SET @OGUID := 81623;
```

2024-03-09 12:22 UTC, Nyeriah commented
Someone did a bad merge and messed up his branch…

2024-03-09 12:27 UTC, Nyeriah requested changes
This branch needs to be rebased and force-pushed to the commit before the merge so the polution goes away before the PR can be accepted and merged.

2024-03-09 14:45 UTC, Helias commented
> Someone did a bad merge and messed up his branch…

oops

2024-03-09 14:52 UTC, closed without merging