Update Astromancer timings
azerothcore/azerothcore-wotlk pull request #18655
Opened 2024-04-02 19:47 UTC by balleny

## Changes Proposed:

This PR proposes changes to:
-  [ ] Core (units, players, creatures, game systems).
-  [x] Scripts (bosses, spell scripts, creature scripts).
-  [ ] Database (SAI, creatures, etc).

## Issues Addressed:

- Closes https://github.com/chromiecraft/chromiecraft/issues/6876 and https://github.com/chromiecraft/chromiecraft/issues/6870

## SOURCE:

The changes have been validated through:
- [ ] Live research (checked on live servers, e.g Classic WotLK, Retail, etc.)
- [ ] Sniffs (remember to share them with the open source community!)
- [x] Video evidence, knowledge databases or other public sources (e.g forums, Wowhead, etc.)
- [ ] The changes promoted by this pull request come partially or entirely from another project (cherry-pick). **Cherry-picks must be committed using the proper --author tag in order to be accepted, thus crediting the original authors, unless otherwise unable to be found**
see sources in issues
## Tests Performed:

This PR has been:
- [ ] Tested in-game by the author.
- [ ] Tested in-game by other community members/someone else other than the author/has been live on production servers.
- [ ] This pull request requires further testing and may have edge cases to be tested.

## How to Test the Changes:

- [ ] This pull request can be tested by following the reproduction steps provided in the linked issue
- [ ] This pull request requires further testing. Provide steps to test your changes. If it requires any specific setup e.g multiple players please specify it as well.

1.
2.
3.

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

2024-04-02 20:07 UTC, elthehablo commented
Are the sources purely based on DBM timers? What are the sources on that? Or is that unconfirmed?

2024-04-02 20:43 UTC, balleny commented
based on DBM timers, matching with https://youtu.be/FEYAX7l5H6A?t=5229
off by 0,8 seconds on this https://youtu.be/YlCfJB7RN6U?t=697
overall issue is that the whole transition isnt consistent with retail: she should teleport into the center first, then spawn 3 lightspots, then yell, then wait 1 second to disappear. Only then the 4 second timer for agents and the 20 seconds timer for becoming visible again should start. that is why many addons have 4 or 6 seconds timer. The yell is triggering the raid addons but she is actually just starting the timers after disappearing

so far my conclusion from observing different retail videos.

2024-04-02 20:50 UTC, elthehablo commented
Okay that is fair. Please fix your titles for archiving purposes though

2024-04-02 20:51 UTC, balleny commented
might actually make more sense to implement 5 seconds for the moment, but all the wrong things described can be observed well in here https://youtu.be/Cu3tFi68vK4?t=1917

2024-04-03 17:10 UTC, balleny commented
added all but the line to trigger the blink spell
should likely be serverside spell not a CLEU one
coordinates based on sniffs provided @ heyitsbench

2024-04-03 22:36 UTC, heyitsbench commented on src/server/scripts/Outland/TempestKeep/Eye/boss_astromancer.cpp
> +            // blink to room center in this line using SPELL_TELEPORT_START_POSITION and START_POSITION_X, START_POSITION_Y, START_POSITION_Z
Current suspect is [33244](https://wowgaming.altervista.org/aowow/?spell=33244) (thanks to jedbouk on Discord for finding it) as it is noted as used by Solarian on TBCC Wowhead, would likely need its destination position set in DB to be used however.

2024-04-09 09:08 UTC, PkllonG commented
PR what status. I'm using it on my server.

2024-04-10 16:50 UTC, elthehablo commented on src/server/scripts/Outland/TempestKeep/Eye/boss_astromancer.cpp
> +            // blink to room center in this line using SPELL_TELEPORT_START_POSITION and START_POSITION_X, START_POSITION_Y, START_POSITION_Z
then let's incorporate that in here

2024-04-10 16:52 UTC, balleny commented on src/server/scripts/Outland/TempestKeep/Eye/boss_astromancer.cpp
> +            // blink to room center in this line using SPELL_TELEPORT_START_POSITION and START_POSITION_X, START_POSITION_Y, START_POSITION_Z
see also L41, its already included - just need someone to write the actual cast of the ability

2024-04-10 16:52 UTC, balleny commented on src/server/scripts/Outland/TempestKeep/Eye/boss_astromancer.cpp
> +            // blink to room center in this line using SPELL_TELEPORT_START_POSITION and START_POSITION_X, START_POSITION_Y, START_POSITION_Z
positions for the cast are also included in L59-61

2024-04-21 19:53 UTC, elthehablo approved these changes

2024-04-21 19:59 UTC, elthehablo requested changes

2024-04-21 19:59 UTC, elthehablo commented on src/server/scripts/Outland/TempestKeep/Eye/boss_astromancer.cpp
> +            }).scheduler.Schedule(2s, [this](TaskContext)
don't need to repeat .scheduler, you are still invoking Schedule on the same scheduler

2024-04-21 19:59 UTC, elthehablo commented on src/server/scripts/Outland/TempestKeep/Eye/boss_astromancer.cpp
> +            }).scheduler.Schedule(3s, [this](TaskContext)
same here

2024-04-22 10:09 UTC, balleny reviewed
done

2024-04-22 11:22 UTC, elthehablo approved these changes

2024-04-22 11:22 UTC, merged

2024-04-22 12:54 UTC, balleny commented
This shouldnt have been merged yet given that that the teleport/blink spell was still missing
LL154
// blink to room center in this line using SPELL_TELEPORT_START_POSITION and START_POSITION_X, START_POSITION_Y, START_POSITION_Z

2024-04-22 13:02 UTC, elthehablo commented
Nobody was gonna take this branch and write the script for you. So it should be incorporated in a different PR. Is the fight still working like this?

2024-04-22 13:03 UTC, elthehablo commented
Looks that way but am on mobile so can't really check it well rn