fix(Core/Events) Implement Fireworks Spectacular
azerothcore/azerothcore-wotlk pull request #18860
Opened 2024-05-05 19:52 UTC by sudlud

## Changes Proposed:

This PR proposes changes to:
-  [x] Core (units, players, creatures, game systems).
-  [x] Scripts (bosses, spell scripts, creature scripts).
-  [x] Database (SAI, creatures, etc).

## Issues Addressed:

- Closes #16677

## SOURCE:

The changes have been validated through:
- [ ] Live research (checked on live servers, e.g Classic WotLK, Retail, etc.)
- [x] Sniffs (remember to share them with the open source community!)
- [x] Video evidence, knowledge databases or other public sources (e.g forums, Wowhead, etc.)
- [ ] The changes promoted by this pull request come partially or entirely from another project (cherry-pick). **Cherry-picks must be committed using the proper --author tag in order to be accepted, thus crediting the original authors, unless otherwise unable to be found**

Thanks @heyitsbench for sniffing all firework shows!

## Tests Performed:

This PR has been:
- [x] Tested in-game by the author.
- [ ] Tested in-game by other community members/someone else other than the author/has been live on production servers.
- [ ] This pull request requires further testing and may have edge cases to be tested.

## How to Test the Changes:

- [ ] This pull request can be tested by following the reproduction steps provided in the linked issue
- [ ] This pull request requires further testing. Provide steps to test your changes. If it requires any specific setup e.g multiple players please specify it as well.

event runs for 18 hours
.event start 72

firework shows start at the full hour and last for about 11-12 minutes
at the locations there are kegs, tables, mugs and revelers
revelers emote regularly 
revelers cheer at show end
toasting goblets spawn at show end for 10 minutes

Booty Bay Bruisers are replaced by sleeping Drunken Bruisers

visit firework vendors
Fizzlebang Booms
.go c 12523
Ziggle Sparks
.go c 12524
Wizbang Booms
.go c 12525
Lillian Singh
.go c 12526
Jaxxil Sparks
.go c 12527
Kizzak Sparks
.go c 12528

visit firework locations
Stormwind
.go c 420000
Thunder Bluff
.go c 420019
Booty Bay
.go c 420055
Teldrassil
.go c 420136
Ironforge
.go c 420155
Undercity
.go c 420179
Orgrimmar
.go c 420198
Shattrath (Scryer)
.go c 420217
Shattrath (Aldor)
.go c 420227
Exodar
.go c 420235
Silvermoon
.go c 420254

enjoy

## Known Issues and TODO List:

- [ ] reveler gossip texts
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

2024-05-06 19:20 UTC, Kitzunu commented
damn

2024-05-11 12:42 UTC, elthehablo commented
Awesome work @sudlud . I'll give this a test and a review promptly

2024-05-11 12:59 UTC, elthehablo requested changes

2024-05-11 12:59 UTC, elthehablo commented on src/server/scripts/Events/firework_show/firework_show.cpp
> +    void initShow()
We use Pascal Case for function names

2024-05-11 20:01 UTC, elthehablo commented
Works well, nice work

2024-05-11 20:02 UTC, elthehablo approved these changes

2024-05-12 14:42 UTC, sudlud commented on src/server/scripts/Events/firework_show/firework_show.cpp
> +    void initShow()
I'll update the file later today

2024-05-12 16:39 UTC, merged