fix(DB/gameobject):Remove the Church of the Holy Light with flowers and small mounds
azerothcore/azerothcore-wotlk pull request #18879
Opened 2024-05-10 14:15 UTC by fangshun2004

Added flower and small mounds to the event
Removed East Plaguelands - Church of the Holy Light with flowers and small mounds. Because they are creatures during the "Rimblat Earthshatter" dialogue event, small mounds are generated while kneeling, and flowers are spawned on the ground using the spell Rimblat Grows Flower DND (27824) and disappear after a while

## Changes Proposed:

This PR proposes changes to:
-  [ ] Core (units, players, creatures, game systems).
-  [ ] Scripts (bosses, spell scripts, creature scripts).
-  [x] Database (SAI, creatures, etc).

## Issues Addressed:

- Closes 

## SOURCE:

The changes have been validated through:
- [x] Live research (checked on live servers, e.g Classic WotLK, Retail, etc.)
- [x] Sniffs (remember to share them with the open source community!)
- [ ] Video evidence, knowledge databases or other public sources (e.g forums, Wowhead, etc.)
- [ ] The changes promoted by this pull request come partially or entirely from another project (cherry-pick). **Cherry-picks must be committed using the proper --author tag in order to be accepted, thus crediting the original authors, unless otherwise unable to be found**

## Tests Performed:

This PR has been:
- [x] Tested in-game by the author.
- [ ] Tested in-game by other community members/someone else other than the author/has been live on production servers.
- [ ] This pull request requires further testing and may have edge cases to be tested.

## How to Test the Changes:

- [ ] This pull request can be tested by following the reproduction steps provided in the linked issue
- [ ] This pull request requires further testing. Provide steps to test your changes. If it requires any specific setup e.g multiple players please specify it as well.

1. .go c 54186
2. wait
3.

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

2024-05-11 07:29 UTC, pvp100com commented
Perfect repair.

2024-05-11 12:35 UTC, elthehablo requested changes

2024-05-11 12:35 UTC, elthehablo commented on data/sql/updates/pending_db_world/rev_1715349752817459800.sql
> +DELETE FROM `conditions` WHERE `SourceTypeOrReferenceId` = 22 AND `SourceEntry` = 16134 AND `SourceId` = 0;
this does not exist in the db as far as I can tell, so why delete?

2024-05-11 12:35 UTC, elthehablo commented on data/sql/updates/pending_db_world/rev_1715349752817459800.sql
> +DELETE FROM `gameobject` WHERE `id` = 181104;
```suggestion
DELETE FROM `gameobject` WHERE `id` = 181104 AND `guid` = 45965;
```

2024-05-11 12:35 UTC, elthehablo commented on data/sql/updates/pending_db_world/rev_1715349752817459800.sql
> +DELETE FROM `gameobject` WHERE `id` = 181103;
```suggestion
DELETE FROM `gameobject` WHERE `id` = 181103 AND `guid` = 45964;
```

2024-05-13 19:45 UTC, elthehablo approved these changes
Thanks for the pr once again

2024-05-13 19:45 UTC, merged