fix(DB/Core/Quests): Fix quest 11881
azerothcore/azerothcore-wotlk pull request #20241
Opened 2024-10-18 17:16 UTC by cgrahamseven

Move quest 11881 to the core for better scripted control and more blizzlike behavior.

Closes AzerothCore issue #20239

## Changes Proposed:

This PR proposes changes to:
-  [x] Core (units, players, creatures, game systems).
-  [x] Scripts (bosses, spell scripts, creature scripts).
-  [x] Database (SAI, creatures, etc).

## Issues Addressed:

- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/20239

## SOURCE:

The changes have been validated through:
- [x] Live research (checked on live servers, e.g Classic WotLK, Retail, etc.)
- [ ] Sniffs (remember to share them with the open source community!)
- [x] Video evidence, knowledge databases or other public sources (e.g forums, Wowhead, etc.)
- [ ] The changes promoted by this pull request come partially or entirely from another project (cherry-pick). **Cherry-picks must be committed using the proper --author tag in order to be accepted, thus crediting the original authors, unless otherwise unable to be found**

## Tests Performed:

This PR has been:
- [x] Tested in-game by the author.
- [ ] Tested in-game by other community members/someone else other than the author/has been live on production servers.
- [ ] This pull request requires further testing and may have edge cases to be tested.

## How to Test the Changes:

- [x] This pull request can be tested by following the reproduction steps provided in the linked issue
- [ ] This pull request requires further testing. Provide steps to test your changes. If it requires any specific setup e.g multiple players please specify it as well.

1. .quest add 11881 (horde only)
2. Go to crashed flying machine in scalding pools area of borean tundra
3. Use item Jenny's whistle
4. Jenny spawns and should maintain speed value of speed_run from db in creature_template while following player, not run at the same speed as player
5. Allow Jenny to get aggro from mob and observe aura Crates Carried losing stacks along with visual effect of crates dropping from Jenny
6. Any damage after stacks from Crates Carried has dropped to zero should despawn Jenny
7. Run Jenny back to Fezzix in Taunka'le village. 
8. When Jenny is within 15 meters of Fezzix, you should receive completion of quest
9. Jenny walks back to fezzix and then despawns

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

2024-11-15 06:30 UTC, Grimdhex commented
This PR can't be done with SAI ?

2024-11-16 04:34 UTC, cgrahamseven commented
> This PR can't be done with SAI ?

It was previously SAI but it was broken. The summoned NPC would immediately despawn on damage taken. I also added a feature to temp summons to prevent them from inheriting their owner's speed values since this NPC in particular runs alot slower than the player. Previously, the summon would act like a warlock pet or hunter pet and match speed with the player. Additionally, there are some events that are part of this quest that are easier to handle in a script as opposed to SAI. It's working pretty damn close to the original blizzard quest now.

2024-12-14 18:24 UTC, Exitare commented
Tested PR. 
Works like a charm. 
Thanks for the clear testing instructions. 
I tested both scenarios, loosing crates up until a despawn as well as a successful quest completion.

2024-12-14 18:32 UTC, Kitzunu requested changes

2024-12-14 18:32 UTC, Kitzunu commented on data/sql/updates/pending_db_world/rev_1729269741948776900.sql
> +SET `speed_run` = 1, `speed_walk` = 0.8, `speed_swim` = 0.6, `AIName` = "", `ScriptName` = "npc_jenny"
speed values are sniffed. They don't change unless you have sniffed values

2024-12-14 18:32 UTC, Kitzunu commented on src/server/scripts/Northrend/zone_borean_tundra.cpp
> +    new npc_jenny();
Use the new registry model.

RegisterCreatureAI()

2025-01-19 05:19 UTC, cgrahamseven commented
> After the changes does this still need testing? Also @cgrahamseven the changes asked.

@TheSCREWEDSoftware I don't have the time right now to look into the change requested by @Kitzunu to use RegisterCreatureAI. The NPC is not a ScriptedAI. If you'd like the PR either revert it back to the previous registration or have someone else do whatever conversion is necessary. Thanks

2025-03-13 20:20 UTC, Kitzunu commented on src/server/game/Entities/Creature/TemporarySummon.h
> +    bool m_InheritsOwnerSpeed = true; /// Adjust whether this summon inherits its owners speed/velocity
dont use hungarian notation

2025-03-15 08:16 UTC, sudlud commented
latest updated requires https://github.com/azerothcore/azerothcore-wotlk/pull/21711 to be merged before

2025-03-16 19:28 UTC, sudlud approved these changes

2025-03-16 19:29 UTC, merged