Fix(SQL): Bonechewer Behemoth casts abilities
azerothcore/azerothcore-wotlk pull request #20420
Opened 2024-11-02 19:16 UTC by IntelligentQuantum

## Changes Proposed:

This PR proposes changes to:
-  [ ] Core (units, players, creatures, game systems).
-  [ ] Scripts (bosses, spell scripts, creature scripts).
-  [x] Database (SAI, creatures, etc).

## Issues Addressed:

- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/20379

## SOURCE:

The changes have been validated through:
- [ ] Live research (checked on live servers, e.g Classic WotLK, Retail, etc.)
- [ ] Sniffs (remember to share them with the open source community!)
- [ ] Video evidence, knowledge databases or other public sources (e.g forums, Wowhead, etc.)
- [ ] The changes promoted by this pull request come partially or entirely from another project (cherry-pick). **Cherry-picks must be committed using the proper --author tag in order to be accepted, thus crediting the original authors, unless otherwise unable to be found**

## Tests Performed:

This PR has been:
- [ ] Tested in-game by the author.
- [ ] Tested in-game by other community members/someone else other than the author/has been live on production servers.
- [x] This pull request requires further testing and may have edge cases to be tested.

## How to Test the Changes:

https://github.com/azerothcore/azerothcore-wotlk/issues/20379
- [ ] This pull request can be tested by following the reproduction steps provided in the linked issue
- [ ] This pull request requires further testing. Provide steps to test your changes. If it requires any specific setup e.g multiple players please specify it as well.

1.
2.
3.

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

2024-11-02 21:05 UTC, Nyeriah commented
Something is doubling up the scheduling of SAI combat abilities. With this PR he will cast it twice and then never again (still bugged).

2024-11-04 08:50 UTC, Rorschach91 commented
The Fel stomp seems to work well, but Meteor keeps getting thrown twice in a row.

2024-12-14 22:32 UTC, Exitare commented
Sorry, if i tested too early, but i saw another commit changing the SAI, so i just tested it again.
The behaviour remains largely like @Rorschach91 described it. 
Meteor is cast twice and after Fel Stomp not 1 second after pull.

2024-12-14 23:51 UTC, Rorschach91 commented
> Sorry, if i tested too early, but i saw another commit changing the SAI, so i just tested it again. The behaviour remains largely like @Rorschach91 described it. Meteor is cast twice and after Fel Stomp not 1 second after pull.

This is a general issue that regard the smartscript itself (not only the Behemoths).

2024-12-26 21:07 UTC, TheSCREWEDSoftware requested changes
Add the `source_type`

2024-12-26 22:25 UTC, TheSCREWEDSoftware commented
> Something is doubling up the scheduling of SAI combat abilities. With this PR he will cast it twice and then never again (still bugged).

While making my own fixes to this SAI and asking @Rorschach91 to test them to see if that's how they behave (correcly).

Currently in my SAI:
- If he's far he will cast fiery comet (current target) if he's close he will use fel stomp (at random target9. He always charge on agro and he will enrage (with text) at 30%

He told he still double casts. I can every single time (if he's SAI is not on cooldown the repeat of that spell) he will always cast the fiery if you started combat in his max range. Charge has 30y and the fiery has 40y

https://github.com/user-attachments/assets/7f33b07c-9700-4345-b932-52f7962d40ff

https://github.com/user-attachments/assets/a0c66264-d8ae-42b2-bb70-1b9631940602

@Nyeriah does this give you any more insight? I can constantly replicate it

2025-02-17 08:15 UTC, sudlud commented
Closing this PR for now, please feel free to reopen and continue working on it anytime in the future :)

2025-02-17 08:15 UTC, closed without merging