fix(DB/player_factionchange_achievement & "quests & "reputations)
azerothcore/azerothcore-wotlk pull request #20480
Opened 2024-11-08 02:08 UTC by TheSCREWEDSoftware

## Changes Proposed:

Tables:
`player_factionchange_achievement`
`player_factionchange_quests`
`player_factionchange_reputations`

Are having their tables drop and created to add the new comment column and their respective data.

This PR proposes changes to:
-  [ ] Core (units, players, creatures, game systems).
-  [ ] Scripts (bosses, spell scripts, creature scripts).
-  [x] Database (SAI, creatures, etc).

## Issues Addressed:
- None to my knowledge

## SOURCE:

- [ ] Live research (checked on live servers, e.g Classic WotLK, Retail, etc.)
- [ ] Sniffs (remember to share them with the open source community!)
- [ ] Video evidence, knowledge databases or other public sources (e.g forums, Wowhead, etc.)
- [ ] The changes promoted by this pull request come partially or entirely from another project (cherry-pick). **Cherry-picks must be committed using the proper --author tag in order to be accepted, thus crediting the original authors, unless otherwise unable to be found**
- Other tables have, these don't, rationally makes no sense to not have them.

## Tests Performed:

This PR has been:
- [x] Tested in-game by the author.
- [ ] Tested in-game by other community members/someone else other than the author/has been live on production servers.
- [ ] This pull request requires further testing and may have edge cases to be tested.

## How to Test the Changes:

- [x] This pull request can be tested by following the reproduction steps provided in the linked issue
- [ ] This pull request requires further testing. Provide steps to test your changes. If it requires any specific setup e.g multiple players please specify it as well.

## Known Issues and TODO List:

- [x] `player_factionchange_achievement`
- [ ] `player_factionchange_quests`
- [ ] `player_factionchange_reputations`

2024-11-14 05:07 UTC, Grimdhex commented
The PR is ready to be review ?

2024-11-14 11:17 UTC, TheSCREWEDSoftware commented
Yes it is

2024-11-15 06:11 UTC, Grimdhex approved these changes

2024-11-15 09:31 UTC, sudlud commented
there was still an ongoing discussion about this in discord iirc.

2024-12-22 08:46 UTC, Kitzunu commented
Whats up with this @sudlud

2024-12-22 10:40 UTC, Kitzunu requested changes
Okay. This is what I think.

Adding redundant things to the Database that can be easily checked is unnecessary. So I would in that case remove player_factionchange_quests as you can just do join query.

For achievement and rep I am more open to it as the defined values are not stored in the database.

I also think you should make the columns NULL DEFAULT NULL

2024-12-22 12:15 UTC, Grimdhex commented
I think, that the wrong way. We just need to make the effort to review and improve our wiki.

2024-12-22 12:37 UTC, TheSCREWEDSoftware commented
> I think also that the wrong way. We just need to make the effort to review and improve our wiki.

Can you elaborate more on this?

2025-02-17 12:50 UTC, sudlud commented
can you please address Kitzunus comment so we can move forward and get this into a mergable state :)

2025-02-17 16:08 UTC, TheSCREWEDSoftware commented
@Kitzunu and @sudlud looks good now?

2025-02-17 19:44 UTC, sudlud commented
i think you maybe deleted to much, builds are failing

2025-02-17 20:00 UTC, TheSCREWEDSoftware commented
@sudlud to my understanding si the `TEXT NULL DEFAULT NULL` not at the pc to see how is supposed to look. I dont think text null default null is correct

2025-02-18 00:44 UTC, TheSCREWEDSoftware commented
Codestyle is failing related to `DELETE`. Otherwise it's working fine

2025-03-01 23:32 UTC, Kitzunu approved these changes

2025-03-01 23:33 UTC, merged