feat(Core/AuctionHouse): Implement Auction House getAll scan
azerothcore/azerothcore-wotlk pull request #20511
Opened 2024-11-10 15:58 UTC by jerryshell

This is a simple but effective implementation.
More scenarios may need to be considered in the future, such as player scan interval control, but I'd like to submit a small commit first.

## Changes Proposed:

This PR proposes changes to:
-  [x] Core (units, players, creatures, game systems).
-  [ ] Scripts (bosses, spell scripts, creature scripts).
-  [ ] Database (SAI, creatures, etc).

## Issues Addressed:

- https://github.com/azerothcore/azerothcore-wotlk/issues/5068

## SOURCE:

The changes have been validated through:
- [ ] Live research (checked on live servers, e.g Classic WotLK, Retail, etc.)
- [ ] Sniffs (remember to share them with the open source community!)
- [ ] Video evidence, knowledge databases or other public sources (e.g forums, Wowhead, etc.)
- [ ] The changes promoted by this pull request come partially or entirely from another project (cherry-pick). **Cherry-picks must be committed using the proper --author tag in order to be accepted, thus crediting the original authors, unless otherwise unable to be found**

## Tests Performed:

This PR has been:
- [x] Tested in-game by the author.
- [ ] Tested in-game by other community members/someone else other than the author/has been live on production servers.
- [ ] This pull request requires further testing and may have edge cases to be tested.

## How to Test the Changes:

- [ ] This pull request can be tested by following the reproduction steps provided in the linked issue
- [ ] This pull request requires further testing. Provide steps to test your changes. If it requires any specific setup e.g multiple players please specify it as well.

1. I've tested it on my local server using [TradeSkillMaster](https://github.com/Wrath-AddOns/TradeSkillMasterPlus) (with an auction house of 25k items)

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

2024-11-11 07:49 UTC, elthehablo requested changes

2024-11-11 07:49 UTC, elthehablo commented on src/server/game/AuctionHouse/AuctionHouseMgr.cpp
> +        uint32& count, uint32& totalcount, uint8 getAll, AuctionSortOrderVector const& sortOrder, Milliseconds searchTimeout)
What is the thought process behind it being a uint8 and not a bool? I believe we should change it

2024-11-11 09:35 UTC, Takenbacon commented
Should keep in mind 3.x client network protocol has a hard limit on packet size, auctionhouse getAll is the only packet from my memory that has the potential to exceed it if uncapped, someone would need to do the math but if I recall right it's around 55-60k items.

2024-11-11 11:07 UTC, walkline commented
Since the current auction implementation has race conditions, I would expect requests like this to make the situation worse.

2024-11-12 19:58 UTC, walkline commented
> Since the current auction implementation has race conditions, I would expect requests like this to make the situation worse.

More details here - https://github.com/azerothcore/azerothcore-wotlk/issues/20538

2024-11-21 03:49 UTC, natugrumu commented
I cannot begin to express how much I am looking forward to this being implemented.

2024-12-08 23:41 UTC, jerryshell commented
https://github.com/azerothcore/azerothcore-wotlk/pull/20830

2024-12-08 23:41 UTC, closed without merging