fix(Scripts/IcecrownCitadel): Sindragosa P3 Exploit
azerothcore/azerothcore-wotlk pull request #20938
Opened 2024-12-16 18:30 UTC by manstfu

## Changes Proposed:

This PR proposes changes to:
-  [x] Core (units, players, creatures, game systems).
-  [x] Scripts (bosses, spell scripts, creature scripts).
-  [ ] Database (SAI, creatures, etc).

## Issues Addressed:

- Closes #18570
- Closes #2385

## SOURCE:

The changes have been validated through:
- [x] Live research (checked on live servers, e.g Classic WotLK, Retail, etc.)

https://www.wowhead.com/wotlk/it/news/icc-sindragosa-line-of-sight-clarification-wotlk-classic-335143
https://us.forums.blizzard.com/en/wow/t/sindragosa-ice-tomb-los/1673573/2

- [ ] Sniffs (remember to share them with the open source community!)
- [ ] Video evidence, knowledge databases or other public sources (e.g forums, Wowhead, etc.)
- [ ] The changes promoted by this pull request come partially or entirely from another project (cherry-pick). **Cherry-picks must be committed using the proper --author tag in order to be accepted, thus crediting the original authors, unless otherwise unable to be found**

## Tests Performed:

This PR has been:
- [x] Tested in-game by the author.
- [ ] Tested in-game by other community members/someone else other than the author/has been live on production servers.
- [x] This pull request requires further testing and may have edge cases to be tested.

## How to Test the Changes:

- [ ] This pull request can be tested by following the reproduction steps provided in the linked issue
- [ ] This pull request requires further testing. Provide steps to test your changes. If it requires any specific setup e.g multiple players please specify it as well.

**Before**

[Mystic Buffet](https://www.wowhead.com/wotlk/spell=70127/mystic-buffet) not stacking if tank stay behind [Ice Tomb](https://www.wowhead.com/wotlk/npc=36980/ice-tomb)

https://github.com/user-attachments/assets/06825848-f71e-439a-9e37-9f2256839041

**After**
Mystic Buffet applying correctly if player is near Ice Tomb and Sindragosa

https://github.com/user-attachments/assets/22477523-564e-4cb3-836f-7830d6e8755e

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

2024-12-16 18:40 UTC, manstfu commented
This acts PR as a quick fix for the problem that arises as described in

```
This is **how Line of Sight works with temporary objects** like ice blocks and is not a bug. You must turn off your auto attack if the Ice Block **is close enough to the boss for you to melee**, or it will not block LoS.
[SOURCE](https://us.forums.blizzard.com/en/wow/t/sindragosa-ice-tomb-los/1673573/2)
```

I think there should be a general implementation for this, not just on a boss-by-boss basis. It needs to be implemented for all temporary objects!"

2024-12-16 22:28 UTC, TheSCREWEDSoftware commented
Do you consider this ready to be reviewed or you're still changing this?

2024-12-18 00:17 UTC, sogladev commented
I found that this doesn't address the issues linked. I can still avoid stacks when I shouldn't :cry: 

For tank cheesing, instead of range checking, consider using what you quoted:

> > This is **how Line of Sight works with temporary objects** like ice blocks and is not a bug. You must turn off your auto attack if the Ice Block **is close enough to the boss for you to melee**, or it will not block LoS.
> > [SOURCE](https://us.forums.blizzard.com/en/wow/t/sindragosa-ice-tomb-los/1673573/2)
> 

You can check for attacking state, if set then the unit can get hit
```
        if (unit->IsUnit() && unit->ToUnit()->HasUnitState(UNIT_STATE_MELEE_ATTACKING) && unit->ToUnit()->IsWithinMeleeRange(_caster))
            return
```

@manstfu do you see a way to make this generic? So it also applies to sapphiron's ice tombs

While testing I found it odd that ice tombs placed near the boss proved immunity from Mystic Buffet, but still allowed for casts. I expect once the tomb prevents my casting by line of sight, then I'm also safe from Mystic Buffet

DynamicMapTree LoS checking is similar to calling IsWithinLOSInMap with `LINEOFSIGHT_CHECK_GOBJECT_ALL`. I found that checking this way is more consistent with player cast checking:

```
    bool operator()(WorldObject* unit) const
    {
        if (unit->IsUnit() && unit->ToUnit()->HasUnitState(UNIT_STATE_MELEE_ATTACKING) && unit->ToUnit()->IsWithinMeleeRange(_caster))
            return false;
        return !_caster->IsWithinLOSInMap(unit, VMAP::ModelIgnoreFlags::Nothing, LINEOFSIGHT_CHECK_GOBJECT_ALL);
    }
```

Red crosses are in LoS Ice Tombs and do not prevent casting, also do not prevent Mystic Buffet. So Ice Tomb should be placed some minimum distance or it doesn't provide LoS

![sindy_LOS_2024-12-17_23-43](https://github.com/user-attachments/assets/f3efa352-a303-4168-8882-1a0f7067be53)


### setup:
ironforge dummies
```
place cube
.npc add 36980
.gobject add 201722
```

```
set dummy to sindy
.npc set model 30362
```

```
test commands
.debug los
.cast back 70127 triggered
```

2024-12-18 09:53 UTC, sudlud commented
Please merge master for CI codecheck fix

2025-01-10 14:32 UTC, sogladev requested changes
![sindy_los](https://github.com/user-attachments/assets/172eb229-6dd0-4b98-abb0-44637ff06b2e)

This pic shows that regular gobj LoS includes combat reach, so hiding behind a cube that is inside reach (aka can auto attack) is not safe. Proposed changes fix this.

2025-01-10 20:59 UTC, sogladev approved these changes

2025-02-06 10:54 UTC, merged