fix(Core/Player): Cold Blood & Mutilate crit with both weapons
azerothcore/azerothcore-wotlk pull request #20965
Opened 2024-12-18 22:25 UTC by sogladev

## Changes Proposed:

This PR proposes changes to:
-  [x] Core (units, players, creatures, game systems).
-  [ ] Scripts (bosses, spell scripts, creature scripts).
-  [ ] Database (SAI, creatures, etc).

## Issues Addressed:

- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/20027

## SOURCE:

The changes have been validated through:
- [ ] Live research (checked on live servers, e.g Classic WotLK, Retail, etc.)
- [ ] Sniffs (remember to share them with the open source community!)
- [ ] Video evidence, knowledge databases or other public sources (e.g forums, Wowhead, etc.)
- [ ] The changes promoted by this pull request come partially or entirely from another project (cherry-pick). **Cherry-picks must be committed using the proper --author tag in order to be accepted, thus crediting the original authors, unless otherwise unable to be found**

## Tests Performed:

This PR has been:
- [ ] Tested in-game by the author.
- [ ] Tested in-game by other community members/someone else other than the author/has been live on production servers.
- [ ] This pull request requires further testing and may have edge cases to be tested.

## How to Test the Changes:

- [ ] This pull request can be tested by following the reproduction steps provided in the linked issue
- [ ] This pull request requires further testing. Provide steps to test your changes. If it requires any specific setup e.g multiple players please specify it as well.

1.
2.
3.

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

2024-12-19 18:41 UTC, Kitzunu commented on src/server/game/Entities/Player/Player.cpp
> +            if (mod->op == SPELLMOD_CRITICAL_CHANCE && spellInfo->GetFirstRankSpell()->Id == 5374)
dont hardcode. at least add `id /*spell name*/)

2024-12-20 14:54 UTC, Digital365Staking requested changes
// Define a constant for the Mutilate spell (Rank 1) ID for better readability and maintainability
constexpr uint32_t MUTILATE_RANK_1_ID = 5374; // Mutilate (Rank 1)

// Special case for Mutilate: do not consume the critical chance modifier if it's the main hand
if (mod->op == SPELLMOD_CRITICAL_CHANCE && spellInfo->GetFirstRankSpell()->Id == MUTILATE_RANK_1_ID) {
    // Skip consuming the critical modifier for Mutilate (Rank 1)
    return;
}

2025-01-03 12:44 UTC, Nyeriah commented
Only thing left here is for someone to test it, then we can merge it

2025-01-16 15:54 UTC, TheSCREWEDSoftware commented
Can test this later on the day when I get home

2025-01-16 19:06 UTC, TheSCREWEDSoftware commented
![image](https://github.com/user-attachments/assets/0eab905b-e155-4657-8bd0-f29b86341620)

I can't pull the PR

2025-01-16 19:48 UTC, sogladev commented
> I can't pull the PR @sogladev

tested in a win10 VM with latest gh desktop and different gh user
- opening with github desktop fails with the same error
- github CLI works fine

2025-01-16 19:51 UTC, TheSCREWEDSoftware commented
After the merge i was able to pull it
![image](https://github.com/user-attachments/assets/850a4a09-317a-471a-8323-4153172faa14)

2025-01-16 20:30 UTC, TheSCREWEDSoftware commented
@sogladev tell me if this is the intended behaviour (i dont know if i tested it correctly, i can re-tested and record it again if it's the case). https://www.youtube.com/watch?v=04vF0cdSnws&feature=youtu.be

2025-01-16 20:41 UTC, TheSCREWEDSoftware reviewed
PR Tested, waiting validation from the Author to see if it's the intended result

2025-01-16 21:15 UTC, sogladev commented
> @sogladev tell me if this is the intended behaviour (i dont know if i tested it correctly, i can re-tested and record it again if it's the case). https://www.youtube.com/watch?v=04vF0cdSnws&feature=youtu.be

The mutilate spell doesn't consume the aura if the spell misses. Only if it lands, the 2 mutilate spells (MH+OH) trigger and both should crit.  This looks correct from the video.

There is some odd cooldown behavior.  See 0:12 Press Cold Blood, character gains aura but the ability doesn't go on infinite CD?  :thinking: I see you have Shadow Dance and Hunger for Blood talents, this shouldn't be possible on a blizzlike character. I suspect this could explain the odd "on cd" behavior. 

Could you try again with a character with a blizzlike spell+talent setup? Also, if you record again, could you put the target with the combo point counter + damage numbers in frame?

2025-01-16 21:33 UTC, TheSCREWEDSoftware commented
Just finishing testing your other PR (naxramas rp) one i will re compile this one after. Do you prefer me video wise to just record the fullscreen (without zoom)

2025-01-16 21:37 UTC, sogladev commented
> Just finishing testing your other PR (naxramas rp) one i will re compile this one after. Do you prefer me video wise to just record the fullscreen (without zoom)
> 
> I was also using .cheat power, cooldown and cast if not mistaken

I can't say what effect cheats have; I try to not use them for this kind of stuff. No need to zoom, you can set font larger if the chat box is not readable.

2025-01-16 22:27 UTC, TheSCREWEDSoftware commented
@sogladev https://www.youtube.com/watch?v=d6LMdNtIDPA&ab_channel=TheSCREWEDSoftware couldn't test more cold blood as it 3 min cooldown :|

2025-01-16 22:33 UTC, TheSCREWEDSoftware commented
Another test with 5 combo points than cold than mutilate https://www.youtube.com/watch?v=NI2RUmLFImU&feature=youtu.be

2025-01-16 23:12 UTC, sogladev commented
From the earlier footage double crit is correct. 

> @sogladev https://www.youtube.com/watch?v=d6LMdNtIDPA&ab_channel=TheSCREWEDSoftware couldn't test more cold blood as it 3 min cooldown :|

0:33 cold blood -> sinister strike. :smile:  Does cold blood + mutilate give the correct amount of combo points? 
> Mutilate(main-hand) Crit + Mutilate(off-hand) Crit = 3 combo points.
^from issue sources

2025-01-16 23:24 UTC, TheSCREWEDSoftware commented
> From the earlier footage double crit is correct.
> 
> > @sogladev https://www.youtube.com/watch?v=d6LMdNtIDPA&ab_channel=TheSCREWEDSoftware couldn't test more cold blood as it 3 min cooldown :|
> 
> 0:33 cold blood -> sinister strike. 😄 Does cold blood + mutilate give the correct amount of combo points?
> 
> > Mutilate(main-hand) Crit + Mutilate(off-hand) Crit = 3 combo points.
> > ^from issue sources, with Seal Fate talent

![image](https://github.com/user-attachments/assets/e8631a98-bcf9-4731-9a98-58976a73b9f1)

![image](https://github.com/user-attachments/assets/5adcbf25-a199-4d84-8415-64c4fa7ad0e2)

Since it crit (it's a guranteed crit right?) it gave the 2 points

2025-01-16 23:35 UTC, sogladev commented
> Since it crit (it's a guranteed crit right?) it gave the 2 points

I'm not certain of Focused Attacks. I assume Cold Blood -> Mutilate should proc this only talent only once and grant 2 energy points total. 

More important is the Seal Fate talent which should grant Cold Blood -> Mutilate 3 combo points total

2025-01-19 16:37 UTC, closed without merging