breaking(Core/PLayerScript) Align player script function names
azerothcore/azerothcore-wotlk pull request #21020
Opened 2024-12-23 00:58 UTC by Exitare

This is a breaking change, as this is changing almost all Playerscript hooks to align the names between the header and cpp file and also introduces a convention after which these hooks are named. Essentially they are all called OnPlayer... 

## Changes Proposed:

This PR proposes changes to:
-  [x] Core (units, players, creatures, game systems).
-  [x] Scripts (bosses, spell scripts, creature scripts).
-  [ ] Database (SAI, creatures, etc).

## Issues Addressed:

- Closes #19423

## SOURCE:

The changes have been validated through:
- [ ] Live research (checked on live servers, e.g Classic WotLK, Retail, etc.)
- [ ] Sniffs (remember to share them with the open source community!)
- [ ] Video evidence, knowledge databases or other public sources (e.g forums, Wowhead, etc.)
- [ ] The changes promoted by this pull request come partially or entirely from another project (cherry-pick). **Cherry-picks must be committed using the proper --author tag in order to be accepted, thus crediting the original authors, unless otherwise unable to be found**

## Tests Performed:

This PR has been:
- [x] Tested in-game by the author.
- [ ] Tested in-game by other community members/someone else other than the author/has been live on production servers.
- [ ] This pull request requires further testing and may have edge cases to be tested.

## How to Test the Changes:

- [ ] This pull request can be tested by following the reproduction steps provided in the linked issue
- [ ] This pull request requires further testing. Provide steps to test your changes. If it requires any specific setup e.g multiple players please specify it as well.

1. Compile
2. Start server
3. Login and see whether all the scripts are working.

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

2024-12-23 01:13 UTC, Exitare commented
CI is failing because of breaking changes related to the modules

2024-12-25 23:52 UTC, sudlud commented
Can you please prepare PR(s) for the affected modules from the failed module ci. Thanks

2024-12-28 06:33 UTC, sudlud requested changes
See my last comment.

2025-01-04 20:28 UTC, Exitare commented
Who is maintainer of the module?

2025-01-04 20:33 UTC, sudlud commented
The immediate relevant modules are those that fail in the modules build of this pr.
Other modules can be updated later on.

Any staff member can approve and merge PRs on modules under the azerothcore organization on GitHub.

2025-01-05 00:41 UTC, Exitare commented
PR opened.
https://github.com/azerothcore/mod-anticheat/pull/141

2025-01-21 21:01 UTC, Exitare commented
Is there a chance that this can move forward?

2025-02-16 07:04 UTC, sudlud commented
10 modules need an update

```
/home/runner/work/azerothcore-wotlk/azerothcore-wotlk/modules/mod-transmog/src/transmog_scripts.cpp:1049:92: fatal error: only virtual member functions can be marked 'override'
 1049 |     void OnEquip(Player* player, Item* it, uint8 /*bag*/, uint8 /*slot*/, bool /*update*/) override

/home/runner/work/azerothcore-wotlk/azerothcore-wotlk/modules/mod-pvp-titles/src/mod_pvp_titles.cpp:118:34: fatal error: only virtual member functions can be marked 'override'
  118 |     void OnLogin(Player *player) override

/home/runner/work/azerothcore-wotlk/azerothcore-wotlk/modules/mod-multi-client-check/src/mod_multilogincheck.cpp:39:34: fatal error: only virtual member functions can be marked 'override'
   39 |     void OnLogin(Player* player) override

/home/runner/work/azerothcore-wotlk/azerothcore-wotlk/modules/mod-low-level-rbg/src/LowLevelRBG.cpp:115:26: fatal error: no member named 'CanJoinInBattlegroundQueue' in 'ScriptMgr'; did you mean 'OnPlayerCanJoinInBattlegroundQueue'?
  115 |         if (!sScriptMgr->CanJoinInBattlegroundQueue(player, ObjectGuid::Empty, bgTypeId, false, err) && err <= 0)
      |                          ^~~~~~~~~~~~~~~~~~~~~~~~~~
      |                          OnPlayerCanJoinInBattlegroundQueue

/home/runner/work/azerothcore-wotlk/azerothcore-wotlk/modules/mod-eluna/src/ElunaLuaEngine_SC.cpp:526:87: fatal error: only virtual member functions can be marked 'override'
  526 |     bool CanPlayerUseChat(Player* player, uint32 type, uint32 lang, std::string& msg) override

/home/runner/work/azerothcore-wotlk/azerothcore-wotlk/modules/mod-duel-reset/src/DuelReset_scripts.cpp:47:56: fatal error: only virtual member functions can be marked 'override'
   47 |     void OnDuelStart(Player *player1, Player *player2) override {

/home/runner/work/azerothcore-wotlk/azerothcore-wotlk/modules/mod-desertion-warnings/src/DesertionWarnings.cpp:28:88: fatal error: only virtual member functions can be marked 'override'
   28 |     void OnBattlegroundDesertion(Player* player, const BattlegroundDesertionType type) override

/home/runner/work/azerothcore-wotlk/azerothcore-wotlk/modules/mod-cfbg/src/CFBG_SC.cpp:113:34: fatal error: only virtual member functions can be marked 'override'
  113 |     void OnLogin(Player* player) override

/home/runner/work/azerothcore-wotlk/azerothcore-wotlk/modules/mod-autobalance/src/ABPlayerScript.h:20:42: fatal error: only virtual member functions can be marked 'override'
   20 |     void         OnLogin(Player* Player) override;

/home/runner/work/azerothcore-wotlk/azerothcore-wotlk/modules/mod-anticheat/src/AnticheatScripts.cpp:43:35: fatal error: only virtual member functions can be marked 'override'
   43 |     void OnLogout(Player* player) override
```

2025-02-16 13:51 UTC, sudlud approved these changes

2025-02-16 13:59 UTC, merged