fix(DB/Creature) Illidari Nightlord's Fear can be interrupted
azerothcore/azerothcore-wotlk pull request #21031
Opened 2024-12-23 18:28 UTC by Exitare

## Changes Proposed:

This PR proposes changes to:
-  [ ] Core (units, players, creatures, game systems).
-  [ ] Scripts (bosses, spell scripts, creature scripts).
-  [x] Database (SAI, creatures, etc).

## Issues Addressed:

- Closes #21023 

## SOURCE:

The changes have been validated through:
- [ ] Live research (checked on live servers, e.g Classic WotLK, Retail, etc.)
- [ ] Sniffs (remember to share them with the open source community!)
- [x] Video evidence, knowledge databases or other public sources (e.g forums, Wowhead, etc.)
- [ ] The changes promoted by this pull request come partially or entirely from another project (cherry-pick). **Cherry-picks must be committed using the proper --author tag in order to be accepted, thus crediting the original authors, unless otherwise unable to be found**

## Tests Performed:

This PR has been:
- [ ] Tested in-game by the author.
- [ ] Tested in-game by other community members/someone else other than the author/has been live on production servers.
- [ ] This pull request requires further testing and may have edge cases to be tested.

## How to Test the Changes:

- [x] This pull request can be tested by following the reproduction steps provided in the linked issue
- [ ] This pull request requires further testing. Provide steps to test your changes. If it requires any specific setup e.g multiple players please specify it as well.

1.
2.
3.

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

2024-12-24 10:47 UTC, TheSCREWEDSoftware requested changes
Don't use the full value of mechanic flag otherwise is hard to read (to understand was added and also not the way AzerothCore standandards.

You can use our [Bits and Bytes](https://www.azerothcore.org/wiki/bit-and-bytes-tutorial) Tutorial as reference how to work with BitMask values

I will use an example of adding a immunity mechanic:
```sql
UPDATE `creature_template` SET `mechanic_immune_mask` = `mechanic_immune_mask` | 4 WHERE `entry` = 23576;
```

Here we know we are adding immune mechanic "4" (which is disarm) to the current existing me immune mechanic. If flag was 2 now becomes 6 (2+4).

`|` to add and `&~` to remove.

Example of removing the mechanic: 

```sql
UPDATE `creature_template` SET `mechanic_immune_mask` = `mechanic_immune_mask` & ~2048 WHERE (`entry` = 22056);
```

We are removing removing STUN mechanic from that creature.

2024-12-24 11:40 UTC, Grimdhex commented
Codestyle work now, just need to adress multip;e lines

2024-12-25 21:30 UTC, Nyeriah commented
Please comply with code style as mentioned by @TheSCREWEDSoftware

2024-12-26 08:38 UTC, sudlud approved these changes

2024-12-26 08:49 UTC, merged