fix(CORE/Commands): .cheat god lowering hp to 1 and .cheat power not refilling power
azerothcore/azerothcore-wotlk pull request #3299
Opened 2020-08-15 13:39 UTC by peti446

## CHANGES PROPOSED:
-  On power resource update to have maximum value if .cheat power is enabled
-  Dont check if player has enough power to cast spell if .cheat power is enabled
-  Changed SendSpellNonMelee...Log to send damage as absorb instead of damage to avoid client prediction lowering hp bar when .cheat god is enabled but still be able to debug damage from enemies (looking at absorb log)
- Avoid fall damage while .god mode is enabled

## ISSUES ADDRESSED:

- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/3257
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/1534

## TESTS PERFORMED:
- Activated god mode (.cheat god) and infinite power (.cheat power) on a warrior, dk, rouge and mage
- Went to ICC Raid
- Pulled all till first boss and all attacking for 5 minutes
- Checked my hp bar is 100%
- Attacked mobs with many different spells that consume power
- Checked that power bar ddi not get below 95%

## HOW TO TEST THE CHANGES:

For .cheat god
1. Activate god mode (.cheat god)
2. Go to ICC or any other instance zone with many mobs
3. Pull many mobs and let them attack for  a while
4. Check that HP bar did not go down

For .cheat power
1. Create class (warrior, DK, rouge and any Mana clasS)
2. Activate .cheat power on each
3. Use spells
4. Check that resource did not go down and its always at 95%-100% even outside combat.

## KNOWN ISSUES AND TODO LIST:

- [ ]
- [ ] 

## Target branch(es):
- [x] Master

 
## How to test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here in the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

2020-08-15 20:37 UTC, Kitzunu commented on src/server/game/Entities/Unit/Unit.cpp
> +            data << uint32(absorb);                  // absorb
Fix space for comment

2020-08-15 20:37 UTC, Kitzunu commented on src/server/game/Entities/Unit/Unit.cpp
> +    //IF we are in cheat mode we swap absorb with damage and set daamge to 0, this way we can still debug damage but our hp bar will not drop
daamage -> damage

2020-08-15 20:38 UTC, Kitzunu commented on src/server/game/Entities/Unit/Unit.cpp
> +    case SPELL_AURA_PERIODIC_DAMAGE_PERCENT:
indentation

2020-08-15 20:38 UTC, Kitzunu commented on src/server/game/Entities/Unit/Unit.cpp
> +    data << uint32(absorb);                            // AbsorbedDamage
comment spacinbg

2020-08-16 12:24 UTC, FrancescoBorzi commented on src/server/game/Entities/Player/Player.cpp
> +                UpdateUInt32Value(UNIT_FIELD_POWER1 + power, 0);
let's add brackets here, it's safer:

```
if(power == POWER_RAGE || power == POWER_RUNIC_POWER)
{
                UpdateUInt32Value(UNIT_FIELD_POWER1 + power, 0);
}
```

2021-03-16 20:07 UTC, Si1ker commented
@peti446 Would you be able to resolve the conflicts in this PR? Apologize we didn't catch it at the time with the importance it deserves.

2021-03-16 22:07 UTC, peti446 commented
@Si1ker Done :)

2021-03-16 22:16 UTC, Si1ker approved these changes

2021-03-16 22:19 UTC, Si1ker commented
Thank you very much @peti446 !
Really appreciated, we're gonna keep an eye on this 👀

2021-03-21 03:52 UTC, Delcidx commented
TESTED, working great.
- HP bar keeps in 100% with cheat god on.
![test2](https://user-images.githubusercontent.com/75182283/111892393-c2365980-89c0-11eb-8e05-51b65f00aa1a.png)

- Energy/Mana keeps in 100% while using spells with cheat power on.
![tested](https://user-images.githubusercontent.com/75182283/111892985-54d8f780-89c5-11eb-89fb-c328aca7eefe.png)

- Rage/Runic Power does not drop below 98% with cheat power on.
![tested2](https://user-images.githubusercontent.com/75182283/111892988-599dab80-89c5-11eb-8c95-6b6f8e62d631.png)

2021-03-21 04:04 UTC, Si1ker commented
@peti446 Thanks for the PR, it's a valuable contribution to the project! ⭐ 

@Delcidx Great testing report, we appreciated it very much! 🎉

2021-03-21 04:06 UTC, Kitzunu requested changes

2021-03-21 04:06 UTC, Kitzunu commented on src/server/game/Entities/Player/Player.cpp
> +    //If .cheat power is on alwas have the max power
always

2021-03-21 04:06 UTC, Kitzunu commented on src/server/game/Entities/Unit/Unit.cpp
> +            return 0;
brackets

2021-03-21 04:06 UTC, Kitzunu commented on src/server/game/Entities/Unit/Unit.cpp
> +    data << uint32(damage);                                 // damage amount
blanks

2021-03-21 04:06 UTC, Kitzunu commented on src/server/game/Entities/Unit/Unit.cpp
> +    data << uint32(absorb);                                 // AbsorbedDamage
blanks

2021-03-21 04:06 UTC, Kitzunu commented on src/server/game/Entities/Unit/Unit.cpp
> +    data << uint32(damage);                                 // damage amount
blanks

2021-03-21 04:06 UTC, Kitzunu commented on src/server/game/Entities/Unit/Unit.cpp
> +    data << uint32(absorb);                                 // AbsorbedDamage
blanks

2021-03-21 04:06 UTC, Kitzunu commented on src/server/game/Entities/Unit/Unit.cpp
> +            data << uint32(absorb);                         // absorb
blanks

2021-03-21 04:06 UTC, Kitzunu commented on src/server/game/Entities/Unit/Unit.cpp
> +            }
indentation of the whole thing

2021-03-21 04:06 UTC, Kitzunu commented on src/server/game/Spells/Spell.cpp
> +        return SPELL_CAST_OK;
brackets

2021-03-21 04:06 UTC, Kitzunu commented on src/server/game/Spells/Spell.cpp
> +            return SPELL_CAST_OK;
brackets

2021-03-21 04:08 UTC, Kitzunu commented on src/server/game/Entities/Unit/Unit.cpp
> +    data << uint32(damage);                                 // damage amount
my bad, I missed the comment :P

2021-03-21 13:18 UTC, FrancescoBorzi commented
thanks @Delcidx for testing this!

2021-03-21 13:36 UTC, peti446 commented
@Kitzunu Fixed the brackets and indentation :)

2021-03-21 14:15 UTC, merged

2021-03-21 14:15 UTC, FrancescoBorzi commented
good job @peti446 , thanks @Si1ker @Kitzunu for reviewing this and @Delcidx for testing. Nice team work!