fix(DB/Quest): gameobject loot and related responsible spell script
azerothcore/azerothcore-wotlk pull request #3340
Opened 2020-08-24 21:05 UTC by Helias

Thanks @r0m1ntik94 for the fix.

## ISSUES ADDRESSED:
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/3224

## TESTS PERFORMED:
- executed successfully the SQL query into the database

## HOW TO TEST THE CHANGES:
- complete the quest https://www.wowhead.com/quest=12713/betrayal

## Target branch(es):
- [x] Master

 
## How to test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here in the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

2020-08-24 21:22 UTC, FrancescoBorzi requested changes

2020-08-24 21:22 UTC, FrancescoBorzi commented on data/sql/updates/pending_db_world/rev_1598302868929248922.sql
> +(57553, 0, 571, 5875.43, -1981.37, 234.671, 0, 0); -- Escape Voltarus
missing `DELETE` before `INSERT`

2020-08-24 21:24 UTC, Helias commented on data/sql/updates/pending_db_world/rev_1598302868929248922.sql
> +(57553, 0, 571, 5875.43, -1981.37, 234.671, 0, 0); -- Escape Voltarus
done

2020-08-24 21:25 UTC, FrancescoBorzi approved these changes

2020-08-28 16:56 UTC, felwyn commented
Have to complete the quest chain because it requires special abilities for my character before I encounter Drakuru

Hang on guys!

2020-08-28 17:13 UTC, felwyn commented
Completed the quest. Got Drakuru's Skull and Spell was working too.

2020-09-13 15:49 UTC, merged