fix(DB/Quest): gluttonous lurkers: improve the current SmartAI
azerothcore/azerothcore-wotlk pull request #3341
Opened 2020-08-24 21:09 UTC by Helias

Thanks @r0m1ntik94 for the fix.

## CHANGES PROPOSED
- improve the current SmartAI

## ISSUES ADDRESSED:
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/3227

## TESTS PERFORMED:
- executed successfully the SQL query into the database

## HOW TO TEST THE CHANGES:
- complete the quest https://www.wowhead.com/quest=12713/betrayal

## Target branch(es):
- [x] Master

 
## How to test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here in the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

2020-08-24 21:24 UTC, FrancescoBorzi requested changes

2020-08-24 21:24 UTC, FrancescoBorzi commented on data/sql/updates/pending_db_world/rev_1598303195521812924.sql
> +DELETE FROM `smart_scripts`WHERE `entryorguid`= 28202;
this `DELETE` is bad! they primary key of `smart_scripts` is `entryorguid` AND `source_type`. If you don't specify the `source_type`, you can accidentally remove other scripts. Be careful when using `DELETE`

2020-08-24 21:24 UTC, FrancescoBorzi commented on data/sql/updates/pending_db_world/rev_1598303195521812924.sql
> +(28202, 0, 1, 0, 31, 0, 100, 1, 50927, 0, 0, 0, 0, 41, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 'Zul\'Drak Rat - On Spellhit target \'Create Zul\'Drak Rat\' - Despawn Instant');
newline

2020-08-25 08:07 UTC, FrancescoBorzi approved these changes

2020-08-25 08:09 UTC, PivanDepolo commented
works fine!

2020-08-25 11:24 UTC, Kitzunu commented on data/sql/updates/pending_db_world/rev_1598303195521812924.sql
> +INSERT INTO `smart_scripts` VALUES
Missing (`Entryorguid, [....] VALUES

2020-08-25 17:25 UTC, Helias commented on data/sql/updates/pending_db_world/rev_1598303195521812924.sql
> +INSERT INTO `smart_scripts` VALUES
added!

2020-09-15 13:47 UTC, merged