[NPC] Silvermoon Pet Trainer
azerothcore/azerothcore-wotlk pull request #3393
Opened 2020-08-31 13:52 UTC by Knindzagxg

Transfering from SC by @FrancescoBorzi request.

Update and corrections for Silvermoon Pet Trainer.

2020-08-31 16:43 UTC, Geekena commented
tested
no error or problems

2020-08-31 17:55 UTC, FrancescoBorzi approved these changes

2020-08-31 18:07 UTC, Kitzunu requested changes
This GUID is already IN USE by another Creature!

Please make sure to always use a FREE GUID when you add new creatures.

creature
---
```sql
SELECT * FROM `creature` WHERE guid = 248570
```
| guid | id | map | zoneId | areaId | spawnMask | phaseMask | modelid | equipment_id | position_x | position_y | position_z | orientation | spawntimesecs | wander_distance | currentwaypoint | curhealth | curmana | MovementType | npcflag | unit_flags | dynamicflags | ScriptName | VerifiedBuild | 
| ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | --- | ---: | 
| 248570 | 32803 | 571 | 0 | 0 | 1 | 1 | 0 | 0 | 3936,92 | -595,444 | 241,153 | 5,95157 | 120 | 0 | 0 | 1 | 0 | 0 | 0 | 0 | 0 |  | 0 |

2020-08-31 18:16 UTC, Knindzagxg commented
Sorted xP

2020-08-31 18:19 UTC, Kitzunu commented on data/sql/updates/pending_db_world/rev_1598881374545560300.sql
> +DELETE FROM `creature` WHERE `id` = 40405;
```suggestion
DELETE FROM `creature` WHERE `id` = 40405 AND `guid` = @CGUID;
```

You ALWAYS need to delete the Primary Key.

2020-08-31 22:53 UTC, FrancescoBorzi commented
@Kitzunu error:

```
ERROR 1054 (42S22) at line 112550: Unknown column 'spawndist' in 'field list'
```

@Geekena on which AC version are you testing?

2020-08-31 22:54 UTC, Kitzunu commented
Spawndist hasnt existed for MONTHS

2020-08-31 22:55 UTC, Kitzunu commented
It is wanderdistance/wander_distance I cant remember

2020-08-31 22:57 UTC, Kitzunu commented
https://github.com/azerothcore/azerothcore-wotlk/commit/8a1eab2c2330537a36e1f1fdae56ea9ad40b5e43 April

2020-09-05 13:48 UTC, Knindzagxg commented
Just saw mate, had no time before :S
My core is updated, i just xfered from SC link you gave.
Havent tested myself sadly.

Gonna sort in next few, just came home xP

2020-09-06 08:37 UTC, Knindzagxg commented
SQL sorted now, gonna test it as well.

2020-09-06 08:44 UTC, Knindzagxg commented
Ok, it seems someone moved this and Dalaran fountain before but havent marked as done.

Its double spawn again, and i think there is no this for this and Dalaran F. PRs.
Can someone check and confirm double spawns so we can close?

2020-09-06 11:48 UTC, FrancescoBorzi commented
closing as discussed on Discord

2020-09-06 11:48 UTC, closed without merging