refact(CORE/Mail): Avoid big mail loading and saving time.
azerothcore/azerothcore-wotlk pull request #3420
Opened 2020-09-01 18:40 UTC by peti446

## CHANGES PROPOSED:
-  Changed the way mail is handled to only have 50 mail loaded from the DB when the client request mail update to keep load time low and avoid crashes with big amount of mails.
-  Save changed mail when new mail is fetched as now the mail size is much lower and can be done without problems

## TESTS PERFORMED:
- Build on windows with no errors
- Created a character with 150K mails to test loading time when mail is opened
- Send mail between characters, from console and AH with no apparent errors

## HOW TO TEST THE CHANGES:

- Use the mail system as much as possible with different characters online and offline. Including AH.
- Send many mails to a character to check load time

## Target branch(es):
- [x] Master

 
## How to test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here in the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

2020-09-07 20:23 UTC, Helias requested changes

2020-09-07 20:23 UTC, Helias commented on src/server/game/Entities/Player/Player.cpp
```suggestion
    for (PlayerMails::iterator itr = m_mailCache.begin(); itr != m_mailCache.end(); ++itr)
    {
        delete *itr;
    }

```

2020-09-07 20:23 UTC, Helias commented on src/server/game/Entities/Player/Player.cpp
> +    {
is this curly brackets necessary?

2020-09-07 20:23 UTC, Helias commented on src/server/game/Entities/Player/Player.cpp
```suggestion
    for (PlayerMails::iterator itr = m_mailCache.begin(); itr != m_mailCache.end(); ++itr)
    {
        if ((*itr)->messageID == id)
        {
            return (*itr);
        }
    }
```

2020-09-07 20:23 UTC, Helias commented on src/server/game/Entities/Player/Player.cpp
```suggestion
    if (m_nextMailDelivereTime > time(nullptr))
    {
        return;
    }

```

2020-09-07 20:23 UTC, Helias commented on src/server/game/Entities/Player/Player.cpp
```suggestion
    if (!GetMailCacheSize() || !m_mailsUpdated)
    {
        return;
    }    

```

2020-09-07 20:23 UTC, Helias commented on src/server/game/Mails/Mail.cpp
> +                pReceiver->AddMItem(mailItemIter->second);
```suggestion
            for (MailItemMap::iterator mailItemIter = m_items.begin(); mailItemIter != m_items.end(); ++mailItemIter)
            {
                pReceiver->AddMItem(mailItemIter->second);
            }
```

2020-09-09 18:30 UTC, peti446 commented on src/server/game/Entities/Player/Player.cpp
> +    {
No not really, changed it :)

2020-09-09 19:41 UTC, Helias approved these changes

2020-09-09 19:42 UTC, Helias commented
Need to fix the build

2020-09-09 19:47 UTC, peti446 commented
Should be done with next commit no idea how the line got duplicated 🤔

2020-09-19 13:50 UTC, FrancescoBorzi commented
@peti446 there are conflicts

2020-09-21 08:11 UTC, locus313 commented
@peti446 I am working on testing this. Could you provide the details of how you created the 150k mail on a character? (not tried to do that before)

2020-09-21 08:16 UTC, peti446 commented
@locus313 I used a soap script running in the background for a while while I was playing around:
`
<?php

$conn = new SoapClient(NULL, array(
    'location' => 'http://127.0.0.1:7878/',
    'uri' => 'urn:AC',
    'style' => SOAP_RPC,
    'login' => 'test2',
    'password' => 'test'
));

function generateRandomString($length = 10) {
    $characters = '0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ';
    $charactersLength = strlen($characters);
    $randomString = '';
    for ($i = 0; $i < $length; $i++) {
        $randomString .= $characters[rand(0, $charactersLength - 1)];
    }
    return $randomString;
}
            
for($x = 0; $x <= 120000; $x++)
{
    echo $conn->executeCommand(new SoapParam('.send mail Tseae "'.generateRandomString(10).'" "'. generateRandomString(150) .'"', 'command'));
}
 `

2020-09-21 09:19 UTC, locus313 commented
@peti446 I used your script above without any problems. But I did find that when I login to the character that was the target for the generated mails. The worldserver crashes after a few seconds. I am using docker on centos 7 for my testing.

2020-09-21 17:44 UTC, peti446 commented
@locus313 Thanks will have a look on Linux see if I can reproduce the crash. Did you see any error message before the crash ?

2020-09-21 20:02 UTC, locus313 commented
@peti446 did not see any error message before the crash.

2020-10-20 20:10 UTC, FrancescoBorzi commented
@azerothcore/testers can anyone please check this?

2020-10-20 22:50 UTC, peti446 commented
The crash @locus313 referred should now be fixed.

2020-10-21 01:23 UTC, locus313 commented
Just tested. No crash this time :). Look good.

2020-10-21 13:20 UTC, merged