fix(DB/Creature): remove mobs from brewfest camp
azerothcore/azerothcore-wotlk pull request #3497
Opened 2020-09-22 01:53 UTC by locus313

## CHANGES PROPOSED:
-  remove hostile and non-hostile mobs from brewfest camp

## ISSUES ADDRESSED:
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/3496

## TESTS PERFORMED:
- Applied sql and restart server
- Screenshot of test in https://github.com/azerothcore/azerothcore-wotlk/issues/3496

## HOW TO TEST THE CHANGES:

1. Go to the brewfest camp right outside orgrimmar
2. Check if you seen any hostile or non-hostile mobs within the camp area 

## KNOWN ISSUES AND TODO LIST:

## Target branch(es):
- [x] Master

 
## How to test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here in the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

2020-09-22 09:17 UTC, FrancescoBorzi approved these changes

2020-09-24 19:48 UTC, genion18 commented
is this are not better when you makes this creatures in an Event?

Then the event start are the Creature Hidden and then not creature unhidden.

2020-09-24 20:41 UTC, Kitzunu commented
No because you assign a creature to an event.
Like

Event X active == Creatue P visible

You cannot do it the other way around

2020-09-24 21:15 UTC, genion18 commented
ah, okay. is not implemented yet. thanks for this info.

2020-09-27 07:34 UTC, Mitradis commented
STOP THIS F/// SHIT PLZ.

INSERT INTO `game_event_creature` (`eventEntry`,`guid`) VALUES
(5,137686),
(-24,21026),
(-24,12379),
(-24,21034),
(-24,7370),
(-24,7369),
(-24,12386),
(-24,12369),
(-24,22473),
(-24,22188),
(-70,21026),
(-70,12379),
(-70,21034),
(-70,7370),
(-70,7369),
(-70,12386),
(-70,12369),
(-70,22473),
(-70,22188);
DELETE FROM `game_event_creature` WHERE `eventEntry` IN (-26,33);

2020-09-27 07:36 UTC, Mitradis commented
AND HOW MANY NPCs you deleting like this??? WTF.

2020-09-27 10:31 UTC, FrancescoBorzi commented
@Mitradis what? Sorry I don't understand your concern, what minus? Where?

2020-09-27 12:38 UTC, locus313 commented
@Mitradis Thanks for pointing out about the `game_event_creature` table. But do note that the contributors on this project are all at different skill levels and in many cases are still learning. (that includes me)
@FrancescoBorzi I see in the info here:
https://www.azerothcore.org/wiki/game_event_creature
about he minus option for the `game_event_creature` table.

I ran a new test using the `game_event_creature` table and using the minus does indeed remove the mobs from the brewfest camp area. I will update the pr shortly. Here is a screenshot from the test I just ran:
![image](https://user-images.githubusercontent.com/4015312/94365180-98405200-0083-11eb-9a47-319ea3375549.png)

2020-09-27 14:23 UTC, FrancescoBorzi commented
Ah ok, now I get it. At first, I didn't see any minus in the PR so I assumed the comment was maybe a mistake.

Thanks @Mitradis for your feedback!

2020-09-27 14:24 UTC, FrancescoBorzi approved these changes

2020-09-27 15:02 UTC, genion18 commented
And this is what i mean, creature hidden in an event and unhidden where event is end.

2020-09-27 15:47 UTC, Si1ker commented
I asked if this could be possible in the past few days @FrancescoBorzi @Kitzunu 
![image](https://user-images.githubusercontent.com/61223313/94369310-29282500-00a6-11eb-9858-85551117bfa4.png)











On the other hand... @Mitradis  Thanks for the tip and stuff but... (I will say it as you would :) )  why the f*ck you have to come with "STOP THIS F/// SHIT PLZ." and  "Admins seriously, you don't know this?".

Is it impossible for you to say "Hello, I think there is a better way to do this.. etc etc.."

AzerothCore is maintained by people with different skills and knowledge (as it is already said above) with passion for AC, most of the time the 'top devs' are dedicated to private projects where they earn for their work so they avoid to come here and do stuff for free and contribute to this open-source. Every single PR, makes AC evolve, there are bad PRs with good intentions and good PRs that may break something which is fixed then with another PR in the near future.

'The knowledge is welcome, the modals.. simply appreciated.'

2020-09-27 16:06 UTC, Kitzunu commented
Actually I did not know of that :)

2020-09-29 08:22 UTC, Kitzunu requested changes
Keywords should ALWAYS be within \` \` whatever those quotes are called :P

2020-09-29 08:22 UTC, Kitzunu commented on data/sql/updates/pending_db_world/rev_1600739072121853409.sql
> +INSERT INTO `game_event_creature` (eventEntry,guid) VALUES
```suggestion
INSERT INTO `game_event_creature` (`eventEntry`, `guid`) VALUES
```

2020-09-29 08:22 UTC, Kitzunu commented on data/sql/updates/pending_db_world/rev_1600739072121853409.sql
> +INSERT INTO `game_event_creature` (eventEntry,guid) VALUES
```suggestion
INSERT INTO `game_event_creature` (`eventEntry`, `guid`) VALUES
```

2020-09-29 21:37 UTC, locus313 commented
Thanks. I was trying to remember that, but overlooked those ones.

2020-10-19 08:17 UTC, merged