fix(DB/SAI): Speaker Mar'grom
azerothcore/azerothcore-wotlk pull request #3509
Opened 2020-09-27 21:44 UTC by Si1ker

This PR will fix the following NPC=
ID: 18693
Name: Speaker Mar'grom

Reference for combat and dialogues are taken from: https://www.wowhead.com/npc=18693/speaker-margrom#comments
![image](https://user-images.githubusercontent.com/61223313/94376358-63f68100-00d7-11eb-9cac-95912f253257.png)

## CHANGES PROPOSED:
-  Add 4 different quotes when in combat
-  Add 6 (unused) dialogues when passive/moving
-  Improve SAI combat handling

## ISSUES ADDRESSED:
- Closes #3507 

## TESTS PERFORMED:
- Applied SQL
- Tested in-game

## HOW TO TEST THE CHANGES:

Before applying SQL changes
- .go c 151923 / 151924 / 151925 / 151926 / 151927 until finding him.
- .gm off
- Stand around him without any combat: You will notice there is no dialogue while he is around
- Enter in combat with him: You will also notice he does not say something when in combat
After applying SQL changes
- Test 1: Stand around him (around 20-30 yards should be enough), you will see different speeches being said for his comrades around
- Test 2: Enter in combat with him, he will say a quote
- Test 3: He has 4 spells, a fire-resistance buff (after any damage), a fireball (when at high HP), a frost ball (at medium-low HP), and a small fire spell (when he reaches low HP)
- 🐱 works!

## KNOWN ISSUES AND TODO LIST:

- Nothing to do here from now on, the NPC is 100% completed

## Target branch(es):
- [x] Master

 
## How to test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here in the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

2020-09-27 23:47 UTC, Remberance commented
Thank you for perfecting this, i will learn how to make sai more perfect contimue.

2020-09-28 07:44 UTC, FrancescoBorzi approved these changes

2020-09-28 09:02 UTC, Helias requested changes

2020-09-28 09:02 UTC, Helias commented on data/sql/updates/pending_db_world/rev_1601240498542654700.sql
> +('18693', '0', '0', '0', '1', '0', '100', '0', '15000', '30000', '40000', '60000', '0', '1', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', 'Speaker Mar\'grom - In Combat
you could avoid to use strings when numbers are expected

2020-09-28 13:47 UTC, Si1ker commented
@FrancescoBorzi @Helias  Done, check again.

2020-09-28 13:49 UTC, Helias approved these changes

2020-09-29 05:28 UTC, Remberance commented
![image](https://user-images.githubusercontent.com/4078506/94516130-b3fc5180-0257-11eb-9f90-ce41fdcb94a7.png)
 worked

2020-09-29 07:33 UTC, FrancescoBorzi commented
good job @Si1ker and thanks @Remberance for testing!

2020-10-05 08:03 UTC, Helias approved these changes

2020-10-25 09:11 UTC, merged