fix(DB/Zone):improved Eastern Plaguelands
azerothcore/azerothcore-wotlk pull request #3514
Opened 2020-09-28 17:36 UTC by Knindzagxg

Eastern Plaguelands are now fully updated, since some creatures in zone was missing SmartAI.

Working on every zone at the moment, and will post updates once i'm done with each.

To test it:
Apply SQL
Restart your server

You can manually spawn NPC by ID to check SmartAI or you can go to zone and check like that as well.

.npc add ID
or
.tele to zone and run / test around.

2020-09-28 17:41 UTC, Si1ker approved these changes
Looks good, I'll have this tested today at night. 🐱

2020-10-01 09:00 UTC, Si1ker commented
Only one failed, included is the change required in order to make it work. 🐱 



Scourge Siege Engineer
![image](https://user-images.githubusercontent.com/61223313/94779886-d770ea80-0384-11eb-8ebc-209fd66683ad.png)


Scarlet Inquisitor = Wrong   @Knindzagxg 
They never use it because they only have health.
![image](https://user-images.githubusercontent.com/61223313/94779955-efe10500-0384-11eb-8f32-b72ea3d2dd1e.png)

I have found why.. we're gonna need this change since the spell costs 300p mana, I did the change and it goes in accordance with his new SAI
```sql
UPDATE `creature_template` SET `unit_class`=2 WHERE  `entry`=15162;
```
Do you want to include the change here o do you want me to do a quick PR for it? ping me on dc for this.

Living Decay - Between 40-80% Health
![image](https://user-images.githubusercontent.com/61223313/94780051-1010c400-0385-11eb-8a79-5ff4a044ddb2.png)


Mossflayer Zombie - In Combat
![image](https://user-images.githubusercontent.com/61223313/94780076-1bfc8600-0385-11eb-947c-7c27a13884c4.png)


Plaguehound Runt - In Combat
![image](https://user-images.githubusercontent.com/61223313/94780090-23bc2a80-0385-11eb-9bbb-30e583e73c1e.png)


Large Vile Slime - On Aggro
![image](https://user-images.githubusercontent.com/61223313/94780128-32a2dd00-0385-11eb-915f-42e10292c73a.png)

Large Vile Slime - Between 30-60% Health
![image](https://user-images.githubusercontent.com/61223313/94780158-40586280-0385-11eb-827e-a1ab66153525.png)

Large Vile Slime - Between 10-20% Health
![image](https://user-images.githubusercontent.com/61223313/94780183-49493400-0385-11eb-973b-dbeb439aad8b.png)

2020-10-01 09:40 UTC, Kitzunu commented
The question is...
A) should he cast it
B) should he have mana?
C) i believe there is a flag to ignore spell cost 👍

2020-10-01 09:45 UTC, Knindzagxg commented
Awesome tests mate.

We can include / change, tho think Kiz is right.
There should be flag for casting, but will check once im home.

2020-10-02 05:12 UTC, Knindzagxg commented
Updated unit_class.

Wasn't able to find mask ID to ignore mana requirements.
Also, trough wowhead comments people confirming they will cast it.

2020-10-02 09:13 UTC, Helias requested changes

2020-10-02 09:13 UTC, Helias commented on data/sql/updates/pending_db_world/rev_1601314356612298800.sql
> +UPDATE `creature_template` SET `unit_class`= '2' WHERE `entry`=15162;
don't use strings when integers are expected

2020-10-02 16:24 UTC, Si1ker commented
@Knindzagxg  @Kitzunu  Just to keep records that other options were tried.

Tried unit_flag

32 | 0x00000020 | UNIT_FLAG_PREPARATION | Don't take reagents for spells with SPELL_ATTR_EX5_NO_REAGENT_WHILE_PREP
-- | -- | -- | --



Tried unit_flags2

262144 | 0x00040000 | UNIT_FLAG2_ALLOW_CHEAT_SPELLS | allows casting spells with AttributesEx7 & SPELL_ATTR7_IS_CHEAT_SPELL
-- | -- | -- | --


Only the change suggested (which Knindzagxg already changed here) will work with the new SAI.

@Helias  String numeric value fixed, PR good to go !

2020-10-02 16:25 UTC, Si1ker approved these changes

2020-10-02 17:56 UTC, Knindzagxg commented
Yeah, tried few my self but no luck sadly.

2020-10-02 21:36 UTC, Helias approved these changes

2020-10-26 10:37 UTC, merged