fix(DB/Creature):improved Defender of Timbermaw
azerothcore/azerothcore-wotlk pull request #3523
Opened 2020-09-29 16:20 UTC by Knindzagxg

Fix for Defender of Timbermaw.

On spawn it will cast heal.
While active, it will help with few Lighting Bolts on random enemies.

To test:

.additem 21326
.mod rep 576 50000

Pull few mobs and damage then just a little to have agrro.
Use trinket and wait for heal / damage on them.

Should close #3521

2020-09-29 19:39 UTC, r0m1ntik94 commented
Work

2020-09-29 20:51 UTC, FrancescoBorzi approved these changes

2020-10-02 02:37 UTC, wizzymore commented
It works but i don't think this is the correct behaviour:
https://classic.wowhead.com/item=21326/defender-of-the-timbermaw#comments:id=2711857
" - He will heal party members if they are below half health." Currently it heals everyone.
Also:
https://www.youtube.com/watch?v=lIYbQ6QA-DI&t=1m48s

2020-10-02 05:27 UTC, Knindzagxg commented
I will check more into, but wasnt able to find about party.
Will do more tests today after work.

2020-10-02 09:14 UTC, Helias requested changes

2020-10-02 09:14 UTC, Helias commented on data/sql/updates/pending_db_world/rev_1601396210900255400.sql
> +UPDATE `creature_template` SET `unit_class` = '8' WHERE `entry` = 15720;
don't use strings when integers are expected

2020-10-02 15:00 UTC, Knindzagxg commented
Updated.

On respawn will cast Heal on owner as we had before.
During fight, it will assist with 3-5 Lighting bolts and will cast owner or someone in party if bellow 50% hp.

2020-10-03 09:06 UTC, FrancescoBorzi approved these changes

2020-10-31 07:16 UTC, Si1ker approved these changes

2020-10-31 09:40 UTC, Helias approved these changes

2020-10-31 10:39 UTC, merged