DB/Dungeon/Quest): Brother against brother
azerothcore/azerothcore-wotlk pull request #3547
Opened 2020-10-05 03:44 UTC by wizzymore

## CHANGES PROPOSED:
- Make Lakka visible on heroic

## ISSUES ADDRESSED:
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/3034

## TESTS PERFORMED:
- .go c 132569 with dungeon difficulty on heroic

## HOW TO TEST THE CHANGES:

Change dungeon difficulty on heroic
.quest add 10097
.go c 132569

## KNOWN ISSUES AND TODO LIST:

## Target branch(es):
- [x] Master

 
## How to test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here in the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

2020-10-05 07:58 UTC, Helias approved these changes

2020-10-05 10:15 UTC, FrancescoBorzi commented on data/sql/updates/pending_db_world/rev_1601869322546655200.sql
> +DELETE FROM `creature` WHERE (`id` = 18956) AND (`guid` IN (132569));
same as the other PR

2020-10-05 10:16 UTC, FrancescoBorzi requested changes

2020-10-05 10:16 UTC, FrancescoBorzi commented on data/sql/updates/pending_db_world/rev_1601869322546655200.sql
> +DELETE FROM `creature` WHERE (`id` = 18956) AND (`guid` IN (132569));
same as the other PR

2020-11-08 21:27 UTC, Racknar0 commented
Now if the cage appears in Hero 
Tested


![image](https://user-images.githubusercontent.com/38267074/98484686-4ab91800-21df-11eb-9057-17c2a91ef3e6.png)

2020-11-08 21:42 UTC, FrancescoBorzi approved these changes

2020-11-09 00:14 UTC, merged