fix(DB/Quest):Fix Quest Kibler's Exotic Pets
azerothcore/azerothcore-wotlk pull request #3710
Opened 2020-11-16 01:17 UTC by KaizerAce

You we're able to complete quest anywhere without the required creature being anywhere near you.

Closes AzerothCore Issue #582

## CHANGES PROPOSED:
-  Add condition to the spell
-  

## ISSUES ADDRESSED:
- Closes issue #582

## TESTS PERFORMED:
- Executed SQL
-Tried to complete quest anywhere in the world
- Teleported near needed creature and watched it work

## HOW TO TEST THE CHANGES:

.quest add 4729
attempt to use added item "it should not work"

now do this:
.go c 40169
use item again

## KNOWN ISSUES AND TODO LIST:

- [ ]
- [ ] 

## Target branch(es):
- [x] Master

 
## How to test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here in the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

2020-11-16 01:31 UTC, Kitzunu requested changes
This will fix the sql error
And add a useful comment to it :)

2020-11-16 01:31 UTC, Kitzunu commented on data/sql/updates/pending_db_world/rev_1605488437069394200.sql
> +(17, 0, 15998, 0, 0, 29, 0, 10221, 3, 0, 0, 0, 0, '', Add creature requirement to Empty Worg Pup Cage);
```suggestion
(17, 0, 15998, 0, 0, 29, 0, 10221, 3, 0, 0, 0, 0, '', 'Empty Worg Pup Cage requires Bloodaxe Worg Pup (3y)');
```

2020-11-16 03:46 UTC, KaizerAce commented
> This will fix the sql error
> And add a useful comment to it :)

Thank you, way better description lol

2020-11-16 09:38 UTC, FrancescoBorzi approved these changes

2020-11-20 21:17 UTC, Si1ker approved these changes
Tested ✔️ 

If no in range, cannot do that yet.
![image](https://user-images.githubusercontent.com/61223313/99850695-6f987e00-2b43-11eb-91b4-d1f97c11b80a.png)

Now Im in range so I can
![image](https://user-images.githubusercontent.com/61223313/99850728-7b844000-2b43-11eb-9496-79f15f9e298a.png)

And... completed..
![image](https://user-images.githubusercontent.com/61223313/99850749-88089880-2b43-11eb-91b2-2752bfed29e5.png)

2020-11-21 14:19 UTC, FrancescoBorzi commented
thank you @KaizerAce for this contribution and of course @Si1ker for the tests and screenshots!

2020-11-24 16:18 UTC, merged