fix(db/spell_custom_attr):  Correct debuffs incorrectly set as positive buffs
azerothcore/azerothcore-wotlk pull request #3798
Opened 2020-11-28 20:17 UTC by Voxstrasza

## CHANGES PROPOSED:
-  Change 'Phase Punch' to correctly be applied as a debuff on Algalon 10 and 25
-  Change 'Wrath of the Plaguebringer' to correctly be applied as debuff on Noth the Plaguebringer 10 and 25
-  Change 'Shadow Prison' to correctly be applied as debuff on Blood-Prince Council on Heroic mode (unknown if it's 10 or 25)
-  Change 'Recently Bandaged' to correctly be applied as debuff when being bandaged

## ISSUES ADDRESSED:
- #3149 placed spells to be modified as positive/negative within the database; but the original PR set spells that are supposed to be negative as positive. 

## TESTS PERFORMED:
- I only tested Algalon - deleting the row in the table set 'Phase Punch' as a debuff

## HOW TO TEST THE CHANGES:
- Apply SQL, restart server, create character
- Get one of the debuffs listed via `.aura` command and check if it applies as a debuff or positive buff, or run the raid and test actively

## KNOWN ISSUES AND TODO LIST:
- There are more spells in this table that I don't have the time to check, needs thorough testing to see what belongs where

## Target branch(es):
- [x] Master

2020-11-28 20:24 UTC, FrancescoBorzi commented
@locus313 looks like we found a case where the `;` check fails.

The issue is the comment after the last `;` in this case, which is totally valid, but the check doesn't realise it.

2020-11-28 20:26 UTC, Voxstrasza commented
> 
> 
> @locus313 looks like we found a case where the `;` check fails.
> 
> The issue is the comment after the last `;` in this case, which is totally valid, but the check doesn't realise it.

In order to avoid the failed check, I can remove the comments when the PR is complete - but consider this a WIP as there are more debuffs listed as buffs that need to be checked out and removed.

2020-11-28 21:28 UTC, Voxstrasza commented
After reviewing the original PR, it seems that Phase Punch is the only one incorrectly listed - updated this PR and is ready for review

2020-11-28 22:35 UTC, locus313 commented
@FrancescoBorzi Thanks for pointing this out. I got a solution for this and submitted a pr to update the check. https://github.com/azerothcore/azerothcore-wotlk/pull/3799

2020-11-29 03:56 UTC, Si1ker commented
@Voxstrasza  This one still appears as buff instead of debuff so people can right-click on it to remove it from themselves.
.tele gruul

![image](https://user-images.githubusercontent.com/61223313/100532951-80d92e80-31c4-11eb-86b3-a3e67b9e45cd.png)

2020-12-02 10:26 UTC, FrancescoBorzi requested changes

2020-12-02 10:26 UTC, FrancescoBorzi commented on data/sql/updates/pending_db_world/rev_1606594157029530500.sql
> +INSERT INTO `spell_custom_attr` (`spell_id`, `attributes`) VALUES ('33130', '12288');
always use a `DELETE` before an `INSERT` (this makes your query re-executable), also do not use quotes for numeric values

2020-12-03 08:00 UTC, FrancescoBorzi requested changes

2020-12-03 08:00 UTC, FrancescoBorzi commented on data/sql/updates/pending_db_world/rev_1606594157029530500.sql
> +INSERT INTO `spell_custom_attr` (`spell_id`, `attributes`) VALUES (33130,12288);
please add a `DELETE` of `33130` before its `INSERT`

2020-12-04 14:07 UTC, FrancescoBorzi approved these changes

2020-12-05 19:17 UTC, Voxstrasza commented
@FrancescoBorzi is this ok for merge?

2020-12-05 20:31 UTC, FrancescoBorzi commented
the code looks ok but I haven't tested myself

 @Si1ker so have you tested this? should it be merged?

2020-12-10 00:28 UTC, Si1ker approved these changes

2020-12-13 21:44 UTC, Voxstrasza commented
@Si1ker @FrancescoBorzi good for merge?  there might be more debuffs/buffs out there that are messed up but i can fix that in another pr when it's found

2020-12-14 13:13 UTC, FrancescoBorzi commented
I haven't checked this myself, tagging @Si1ker

2020-12-14 16:26 UTC, merged