fix(DB/gossip_menu_option): Give me a Bomber!
azerothcore/azerothcore-wotlk pull request #3830
Opened 2020-12-01 19:55 UTC by LukasVolgger

## CHANGES PROPOSED:
- Remove duplicated gossip menu option (TC also doesn't have it or deleted it)

Before
![2020-12-01 11_04_28-World of Warcraft](https://user-images.githubusercontent.com/55922592/100789957-782c6680-3417-11eb-9536-47330241b248.png)

After
![2020-12-01 11_11_14-World of Warcraft](https://user-images.githubusercontent.com/55922592/100789967-7c588400-3417-11eb-9d95-eabe0da5dfcd.png)

## ISSUES ADDRESSED:
- None

## TESTS PERFORMED:
- Applied SQL
- Tested ingame (See Screenshots)

## HOW TO TEST THE CHANGES:

- .q rem 13373 & .q a 13373
- .go c 1977169
- Talk to the NPC, he should have only one gossip menu option
## KNOWN ISSUES AND TODO LIST:

- [ ]
- [ ] 

## Target branch(es):
- [x] Master

 
## How to test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here in the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

2020-12-01 20:29 UTC, Si1ker requested changes

2020-12-01 20:29 UTC, Si1ker commented on data/sql/updates/pending_db_world/rev_1606850752274331900.sql
> +DELETE FROM `gossip_menu_option` WHERE  `MenuID`=10120 AND `OptionID`=1;
```suggestion
DELETE FROM `gossip_menu_option` WHERE  `MenuID`=10120 AND `OptionID`=1;

```

2020-12-01 20:33 UTC, Si1ker approved these changes

2020-12-01 22:35 UTC, Si1ker commented
@LukasVolgger 

core-build / ubuntu-20.04-clang-with-modules (pull_request) Failing after 4m — ubuntu-20.04-clang-with-modules

(and many others...)

2020-12-01 20:50:39 addToGossipMenuItems: GossipMenuId 10120 Item 1 not found
2020-12-01 20:50:39 Not handled grouped condition, SourceGroup 10120
2020-12-01 20:50:39 addToGossipMenuItems: GossipMenuId 10120 Item 1 not found
2020-12-01 20:50:39 Not handled grouped condition, SourceGroup 10120

2020-12-01 23:34 UTC, FrancescoBorzi approved these changes

2020-12-01 23:35 UTC, FrancescoBorzi requested changes

2020-12-01 23:35 UTC, FrancescoBorzi commented on data/sql/updates/pending_db_world/rev_1606850752274331900.sql
> +DELETE FROM `gossip_menu_option` WHERE  `MenuID`=10120 AND `OptionID`=1;
this change is causing startup errors:

```
2020-12-01 20:50:17 addToGossipMenuItems: GossipMenuId 10120 Item 1 not found
2020-12-01 20:50:17 Not handled grouped condition, SourceGroup 10120
2020-12-01 20:50:17 addToGossipMenuItems: GossipMenuId 10120 Item 1 not found
2020-12-01 20:50:17 Not handled grouped condition, SourceGroup 10120
```

so the build fails

2020-12-02 08:53 UTC, LukasVolgger commented
Updated conditions - Source TC DB. Please test!

2021-01-01 22:14 UTC, pklloveyou commented
Tested

2021-01-01 22:44 UTC, FrancescoBorzi commented
thanks @LukasVolgger and @pklloveyou !

2021-01-09 15:39 UTC, merged