fix(DB/Creature): Laris Geardawdle (9616) missing text
azerothcore/azerothcore-wotlk pull request #4134
Opened 2021-01-02 15:36 UTC by r0m1ntik

## Changes Proposed:
-  Add condition for dialog with npc
-  Add text in gossip_menu

## Issues Addressed:
- Closes [4131](https://github.com/azerothcore/azerothcore-wotlk/issues/4133)

## Tests Performed:
![Снимок экрана 2021-01-02 в 16 22 41](https://user-images.githubusercontent.com/40755539/103460628-0b5b0380-4d18-11eb-8a0b-bd10f7c63154.png)
![Снимок экрана 2021-01-02 в 16 31 43](https://user-images.githubusercontent.com/40755539/103460630-0d24c700-4d18-11eb-846e-ea4f9b3cc25d.png)
![Снимок экрана 2021-01-02 в 16 31 46](https://user-images.githubusercontent.com/40755539/103460631-0dbd5d80-4d18-11eb-96e6-865444c337c7.png)
![Снимок экрана 2021-01-02 в 16 31 49](https://user-images.githubusercontent.com/40755539/103460632-0dbd5d80-4d18-11eb-8fa0-951fa0354138.png)
![Снимок экрана 2021-01-02 в 16 31 52](https://user-images.githubusercontent.com/40755539/103460634-0e55f400-4d18-11eb-9859-3d1888d2da83.png)

## How to Test the Changes:

1) Apply SQL
2) .go cr id 9616
3) .q add 4512 and .q complete 4512
4) .q add 4513
5) **View dialog**

## Target Branch(es):
- [x] Master

 
## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here in the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

2021-01-02 17:40 UTC, FrancescoBorzi approved these changes

2021-01-02 17:40 UTC, FrancescoBorzi commented
good job @r0m1ntik !

2021-01-02 17:51 UTC, JamesGent commented
Tested and works fine on my end.

2021-01-03 00:29 UTC, FrancescoBorzi commented
thanks @JamesGent for confirming the solution!

2021-01-03 00:33 UTC, Kitzunu requested changes
For good measures incase the tables would ever change.

2021-01-03 00:33 UTC, Kitzunu commented on data/sql/updates/pending_db_world/rev_1609601212878725000.sql
> +    (15, 2405, 0, 0, 0, 9, 0, 4513, 0, 0, 0, 0, 0, '', 'Show gossip option if quest \'A Little Slime Goes a Long Way (Part 2)\' is taken');
```suggestion
INSERT INTO `gossip_menu` (`MenuID`, `TextID`) VALUES
(2405, 3077),
(2405, 3097),
(2405, 3098),
(2405, 3099),
(2406, 3100),
(2407, 3101),
(2408, 3102);
DELETE FROM `conditions` WHERE `SourceTypeOrReferenceId` = 14 AND `SourceGroup` = 2405;
INSERT INTO `conditions` (`SourceTypeOrReferenceId`, `SourceGroup`, `SourceEntry`, `SourceId`, `ElseGroup`, `ConditionTypeOrReference`, `ConditionTarget`, `ConditionValue1`, `ConditionValue2`, `ConditionValue3`, `NegativeCondition`, `ErrorType`, `ErrorTextId`, `ScriptName`, `Comment`) VALUES
(14, 2405, 3097, 0, 0, 8, 0, 4512, 0, 0, 0, 0, 0, '', 'Show gossip text 3099 if quest \'A Little Slime Goes a Long Way (Part 1)\' is rewarded'),
(14, 2405, 3097, 0, 0, 9, 0, 4513, 0, 0, 1, 0, 0, '', 'Show gossip text 3099 if quest \'A Little Slime Goes a Long Way (Part 2)\' is not taken'),
(14, 2405, 3099, 0, 0, 9, 0, 4513, 0, 0, 0, 0, 0, '', 'Show gossip text 3099 if quest \'A Little Slime Goes a Long Way (Part 2)\' is taken'),
(14, 2405, 3098, 0, 0, 8, 0, 4513, 0, 0, 0, 0, 0, '', 'Show gossip text 3098 if quest \'A Little Slime Goes a Long Way (Part 2)\' is rewarded'),
(15, 2405, 0, 0, 0, 9, 0, 4513, 0, 0, 0, 0, 0, '', 'Show gossip option if quest \'A Little Slime Goes a Long Way (Part 2)\' is taken');
```

2021-01-07 00:35 UTC, merged