Fix issue 4127
azerothcore/azerothcore-wotlk pull request #4135
Opened 2021-01-02 15:57 UTC by r0m1ntik

## Changes Proposed:
-  Change npc count in zone

## Issues Addressed:
- Closes [4127](https://github.com/azerothcore/azerothcore-wotlk/issues/4127)

## Tests Performed:
**Before fix:**
![Снимок экрана 2021-01-02 в 16 47 55](https://user-images.githubusercontent.com/40755539/103461021-5de9ef00-4d1b-11eb-98a2-f551ef79c619.png)
![Снимок экрана 2021-01-02 в 16 48 01](https://user-images.githubusercontent.com/40755539/103461023-5fb3b280-4d1b-11eb-84ab-2423e6505d9c.png)
**After fix:**
![Снимок экрана 2021-01-02 в 16 48 59](https://user-images.githubusercontent.com/40755539/103461027-68a48400-4d1b-11eb-9ca7-6f451eb76394.png)
![Снимок экрана 2021-01-02 в 16 49 08](https://user-images.githubusercontent.com/40755539/103461029-693d1a80-4d1b-11eb-9d3d-8a21ff6f1c79.png)

## How to Test the Changes:

1) Apply sql
2) .go cr 47249

## Target Branch(es):
- [x] Master

 
## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here in the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

2021-01-02 16:47 UTC, wizzymore approved these changes
One thing that might need to be change is from DELETE BY ID to DELETE BY ID AND GUID. Not sure about this though.
The spawns look okay now.

2021-01-02 17:05 UTC, Kitzunu commented
Yes. Delete with ID and GUID please

2021-01-03 00:38 UTC, Kitzunu requested changes

2021-01-03 00:38 UTC, Kitzunu commented on data/sql/updates/pending_db_world/rev_1609602692076885000.sql
> +    (47268, 1986, 1, 0, 0, 1, 1, 709, 0, 10893, 986.807, 1337.14, 2.47837, 300, 0, 0, 71, 0, 0, 0, 0, 0, '', 0);
```suggestion
INSERT INTO `creature`  (`guid`, `id`, `map`, `zoneId`, `areaId`, `spawnMask`, `phaseMask`, `modelid`, `equipment_id`, `position_x`, `position_y`, `position_z`, `orientation`, `spawntimesecs`, `wander_distance`, `currentwaypoint`, `curhealth`, `curmana`, `MovementType`, `npcflag`, `unit_flags`, `dynamicflags`, `ScriptName`, `VerifiedBuild`) VALUES
(46958, 1986, 1, 0, 0, 1, 1, 709, 0, 10901.5, 877.607, 1330.02, 4.54922, 300, 5, 0, 71, 0, 1, 0, 0, 0, '', 0),
(46971, 1986, 1, 0, 0, 1, 1, 709, 0, 10948.4, 894.388, 1337.57, 2.37731, 300, 5, 0, 71, 0, 1, 0, 0, 0, '', 0),
(46972, 1986, 1, 0, 0, 1, 1, 709, 0, 10946.9, 868.31, 1333.54, 2.07776, 300, 5, 0, 71, 0, 1, 0, 0, 0, '', 0),
(46974, 1986, 1, 0, 0, 1, 1, 709, 0, 10934.6, 866.205, 1332.33, 0.647587, 300, 5, 0, 71, 0, 1, 0, 0, 0, '', 0),
(46981, 1986, 1, 0, 0, 1, 1, 709, 0, 10906, 861.33, 1328.92, 1.37518, 300, 5, 0, 71, 0, 1, 0, 0, 0, '', 0),
(46997, 1986, 1, 0, 0, 1, 1, 709, 0, 10898.4, 899.52, 1323.7, 2.03641, 300, 5, 0, 71, 0, 1, 0, 0, 0, '', 0),
(46998, 1986, 1, 0, 0, 1, 1, 709, 0, 10880.6, 873.212, 1325.12, 3.64265, 300, 5, 0, 71, 0, 1, 0, 0, 0, '', 0),
(46999, 1986, 1, 0, 0, 1, 1, 709, 0, 10868.7, 864.152, 1326.22, 5.12821, 300, 5, 0, 71, 0, 1, 0, 0, 0, '', 0),
(47000, 1986, 1, 0, 0, 1, 1, 709, 0, 10860.8, 860.262, 1327.82, 5.9069, 300, 5, 0, 71, 0, 1, 0, 0, 0, '', 0),
(47001, 1986, 1, 0, 0, 1, 1, 709, 0, 10842.7, 884.155, 1333.06, 5.17599, 300, 5, 0, 71, 0, 1, 0, 0, 0, '', 0),
(47002, 1986, 1, 0, 0, 1, 1, 709, 0, 10834.3, 900.392, 1334.86, 4.43627, 300, 5, 0, 71, 0, 1, 0, 0, 0, '', 0),
(47003, 1986, 1, 0, 0, 1, 1, 709, 0, 10825, 900.829, 1335.63, 2.77949, 300, 5, 0, 71, 0, 1, 0, 0, 0, '', 0),
(47004, 1986, 1, 0, 0, 1, 1, 709, 0, 10934.8, 961.053, 1325.38, 3.91643, 300, 0, 0, 71, 0, 0, 0, 0, 0, '', 0),
(47006, 1986, 1, 0, 0, 1, 1, 709, 0, 10987.4, 959.655, 1336.21, 1.93931, 300, 0, 0, 71, 0, 0, 0, 0, 0, '', 0),
(47008, 1986, 1, 0, 0, 1, 1, 709, 0, 10953.2, 941.028, 1340.61, 0.306411, 300, 5, 0, 71, 0, 1, 0, 0, 0, '', 0),
(47009, 1986, 1, 0, 0, 1, 1, 709, 0, 10939.5, 918.482, 1340, 1.89603, 300, 5, 0, 71, 0, 1, 0, 0, 0, '', 0),
(47010, 1986, 1, 0, 0, 1, 1, 709, 0, 10696.7, 822.492, 1323.19, 5.59532, 300, 5, 0, 71, 0, 1, 0, 0, 0, '', 0),
(47012, 1986, 1, 0, 0, 1, 1, 709, 0, 10721.4, 884.235, 1328.18, -1.25852, 300, 0, 0, 71, 0, 0, 0, 0, 0, '', 0),
(47016, 1986, 1, 0, 0, 1, 1, 709, 0, 10804.8, 944.245, 1335.96, -0.130181, 300, 0, 0, 71, 0, 0, 0, 0, 0, '', 0),
(47017, 1986, 1, 0, 0, 1, 1, 709, 0, 10829.9, 938.924, 1336.01, 2.86993, 300, 0, 0, 71, 0, 0, 0, 0, 0, '', 0),
(47018, 1986, 1, 0, 0, 1, 1, 709, 0, 10846.5, 966.492, 1335.8, 1.04653, 300, 0, 0, 71, 0, 0, 0, 0, 0, '', 0),
(47021, 1986, 1, 0, 0, 1, 1, 709, 0, 10906.4, 970.732, 1338.31, 5.91386, 300, 0, 0, 71, 0, 0, 0, 0, 0, '', 0),
(47023, 1986, 1, 0, 0, 1, 1, 709, 0, 10917.7, 959.212, 1339.72, 1.05716, 300, 5, 0, 71, 0, 1, 0, 0, 0, '', 0),
(47029, 1986, 1, 0, 0, 1, 1, 709, 0, 10942, 966.046, 1327.18, -2.13105, 300, 0, 0, 71, 0, 0, 0, 0, 0, '', 0),
(47030, 1986, 1, 0, 0, 1, 1, 709, 0, 10977.9, 977.973, 1335.13, 3.34604, 300, 0, 0, 71, 0, 0, 0, 0, 0, '', 0),
(47031, 1986, 1, 0, 0, 1, 1, 709, 0, 10988.4, 942.037, 1336.3, 4.35619, 300, 5, 0, 71, 0, 1, 0, 0, 0, '', 0),
(47037, 1986, 1, 0, 0, 1, 1, 709, 0, 10735.7, 902.511, 1332.48, 1.54551, 300, 5, 0, 71, 0, 1, 0, 0, 0, '', 0),
(47038, 1986, 1, 0, 0, 1, 1, 709, 0, 10665.8, 934.3, 1322, 1.40995, 300, 5, 0, 71, 0, 1, 0, 0, 0, '', 0),
(47039, 1986, 1, 0, 0, 1, 1, 709, 0, 10972.9, 937.654, 1337.93, 3.62358, 300, 5, 0, 71, 0, 1, 0, 0, 0, '', 0),
(47052, 1986, 1, 0, 0, 1, 1, 709, 0, 10963.4, 922.714, 1340.44, 4.23278, 300, 5, 0, 71, 0, 1, 0, 0, 0, '', 0),
(47053, 1986, 1, 0, 0, 1, 1, 709, 0, 10922.2, 939.819, 1322.27, 1.36314, 300, 5, 0, 71, 0, 1, 0, 0, 0, '', 0),
(47054, 1986, 1, 0, 0, 1, 1, 709, 0, 10681.9, 882.404, 1320.55, 5.86431, 300, 0, 0, 71, 0, 0, 0, 0, 0, '', 0),
(47055, 1986, 1, 0, 0, 1, 1, 709, 0, 10704.6, 944.455, 1328.3, 4.38078, 300, 0, 0, 71, 0, 0, 0, 0, 0, '', 0),
(47056, 1986, 1, 0, 0, 1, 1, 709, 0, 10889.4, 917.586, 1326.64, 5.77704, 300, 0, 0, 71, 0, 0, 0, 0, 0, '', 0),
(47057, 1986, 1, 0, 0, 1, 1, 709, 0, 10866.7, 917.293, 1331.2, 1.25664, 300, 0, 0, 71, 0, 0, 0, 0, 0, '', 0),
(47060, 1986, 1, 0, 0, 1, 1, 709, 0, 10788.4, 933.77, 1336.79, 6.27289, 300, 5, 0, 71, 0, 1, 0, 0, 0, '', 0),
(47061, 1986, 1, 0, 0, 1, 1, 709, 0, 10769.4, 925.903, 1338.38, 0.601829, 300, 0, 0, 71, 0, 0, 0, 0, 0, '', 0),
(47062, 1986, 1, 0, 0, 1, 1, 709, 0, 10679.8, 900.103, 1320.82, 4.15732, 300, 0, 0, 71, 0, 0, 0, 0, 0, '', 0),
(47208, 1986, 1, 0, 0, 1, 1, 709, 0, 10727, 952.523, 1332.22, 1.0757, 300, 5, 0, 71, 0, 1, 0, 0, 0, '', 0),
(47249, 1986, 1, 0, 0, 1, 1, 709, 0, 10751.2, 924.089, 1337.09, 2.08465, 300, 0, 0, 71, 0, 0, 0, 0, 0, '', 0),
(47262, 1986, 1, 0, 0, 1, 1, 709, 0, 10843.2, 957.249, 1335.49, 3.94444, 300, 0, 0, 71, 0, 0, 0, 0, 0, '', 0),
(47263, 1986, 1, 0, 0, 1, 1, 709, 0, 10864.9, 979.124, 1336.56, 3.40339, 300, 0, 0, 71, 0, 0, 0, 0, 0, '', 0),
(47266, 1986, 1, 0, 0, 1, 1, 709, 0, 10728.2, 871.7, 1328.7, 2.65916, 300, 5, 0, 71, 0, 1, 0, 0, 0, '', 0),
(47267, 1986, 1, 0, 0, 1, 1, 709, 0, 10708, 873.924, 1324.61, 1.77671, 300, 5, 0, 71, 0, 1, 0, 0, 0, '', 0),
(47268, 1986, 1, 0, 0, 1, 1, 709, 0, 10893, 986.807, 1337.14, 2.47837, 300, 0, 0, 71, 0, 0, 0, 0, 0, '', 0);
```

2021-01-04 15:24 UTC, Kitzunu approved these changes

2021-01-04 15:25 UTC, merged

2021-01-04 15:25 UTC, Kitzunu commented
Thanks ^~^