fix(Core/Spell): Val'anyr periodic healings proc and move to new proc system
azerothcore/azerothcore-wotlk pull request #4216
Opened 2021-01-05 18:18 UTC by r0m1ntik

## Changes Proposed:
-  Move to "new" proc system

## Issues Addressed:
- Closes [4207](https://github.com/azerothcore/azerothcore-wotlk/issues/4207)

## Tests Performed:
- Tested in game (work fine)

## How to Test the Changes:

1) cast heal in game (periodic or not)

## Known Issues and TODO List:

- [ ]
- [ ] 

## Target Branch(es):
- [x] Master

 
## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here in the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

2021-01-05 18:21 UTC, Kitzunu commented
"new" proc system would be `spell_proc` but that is not fully implemented :D

2021-01-05 18:23 UTC, Kitzunu requested changes

2021-01-05 18:23 UTC, Kitzunu commented on data/sql/updates/pending_db_world/rev_1609870134525124000.sql
> +UPDATE `spell_proc_event` SET `procFlags` = 279552, `procEx` = 786432 WHERE `entry` = 64411;
Pls add flags like this `x`=`x`|Flag1|Flag2|Flag3 to easily see what flags have been added

2021-01-05 18:31 UTC, r0m1ntik commented
> "new" proc system would be `spell_proc` but that is not fully implemented :D

is empty :D

2021-01-05 18:35 UTC, Kitzunu commented
I know :D
Btw thanks for the change =)

2021-01-06 05:29 UTC, pklloveyou commented
Tested
![image](https://user-images.githubusercontent.com/18535853/103732819-38166000-5023-11eb-8b61-92dc3b2e8d76.png)

2021-01-15 22:42 UTC, Kitzunu commented
merge conflict

2021-03-22 02:18 UTC, Si1ker approved these changes

2021-03-22 02:40 UTC, merged