Correct class trainer icons.
azerothcore/azerothcore-wotlk pull request #4277
Opened 2021-01-14 08:29 UTC by lineagedr

## Changes Proposed:
-  Correct the class trainer icons
-  

## Issues Addressed:
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/4249

## Tests Performed:
-
-

## How to Test the Changes:

Clear wow cache before testing.

## Known Issues and TODO List:

- [ ]
- [ ] 

## Target Branch(es):
- [x] Master

 
## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here in the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

2021-01-14 11:23 UTC, Helias requested changes

2021-01-14 11:23 UTC, Helias commented on src/server/game/Handlers/QueryHandler.cpp
> +                data << ci->IconName;
```suggestion
            if (Player* player = GetPlayer())
            {
                data << player->getClass() == ci->trainer_class ?  "Trainer" : "Speak";
            }
            else
            {
                data << ci->IconName;
            }
```

2021-01-14 11:23 UTC, Helias commented on src/server/game/Handlers/QueryHandler.cpp
> +            data << ci->IconName;                           // "Directions" for guard, string for Icons 2.3.0
```suggestion
        else
        {
            data << ci->IconName;                           // "Directions" for guard, string for Icons 2.3.0
        }
```

2021-01-15 00:21 UTC, pklloveyou commented
tested

2021-01-15 01:41 UTC, Voxstrasza commented
tested, works good.

2021-01-15 02:34 UTC, Kitzunu commented
Please fix the build :)

2021-01-15 06:46 UTC, closed without merging

2021-01-15 09:13 UTC, Voxstrasza commented
@lineagedr why close?

2021-01-15 12:36 UTC, lineagedr commented
@Voxstrasza HandleCreatureQueryOpcode is only sent once per account and then cached in wow. Login with a warrior you'll see all works well. Now login with a different char you'll see that only the Warrior trainer has the spellbook icon. This PR won't fix it.

2021-01-15 19:54 UTC, BarbzYHOOL commented
What can be done then?