Fix Creature Movement Bugs:
azerothcore/azerothcore-wotlk pull request #4544
Opened 2021-02-11 17:32 UTC by Footman

## Changes Proposed:
- fix UpdateEnvironmentIfNeeded was changing flying creature status all the time. closes: #4447
- fix hovering state was causing bugs at #4466
- add animation state priortiy: fly > hover > ground

## Target Branch(es):
- [x] Master

 
## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here in the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

2021-02-11 17:36 UTC, FrancescoBorzi requested changes

2021-02-11 17:36 UTC, FrancescoBorzi commented on src/server/game/Entities/Creature/Creature.cpp
> +    }
@Footman why don't just wrap this code into a method as it's repeated twice?

2021-02-11 19:02 UTC, FrancescoBorzi commented
@azerothcore/testers @pklloveyou @mpfans please test this PR, it's related to the movement/pathfinding changes

2021-02-12 06:50 UTC, locus313 commented
tested, looks good.

2021-02-12 10:36 UTC, FrancescoBorzi approved these changes

2021-02-12 10:42 UTC, merged

2021-02-27 11:22 UTC, disclosurez commented
this issue is still happening on rimefang etc

https://i.imgur.com/0GOhoTH.jpg

2021-02-27 11:28 UTC, disclosurez commented
lana'thel too

https://cdn.discordapp.com/attachments/813104786043699220/814572752617996348/unknown.png