fix(DB/Creature): Patroling-Deathguards-chain-aggro-range
azerothcore/azerothcore-wotlk pull request #4632
Opened 2021-02-22 20:11 UTC by Stifler82

## Changes Proposed:
- Fixed NPC: [Deathguard Abraham](https://wotlkdb.com/?npc=1735)
- Also fixed all [Brill](https://wowgaming.altervista.org/aowow/?zone=159) NPCs having the same problem.
- Now the Guards no longer interact with mobs, but only with "Opposite Faction" enemies.

## Issues Addressed:
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/4499
- Closes https://github.com/chromiecraft/chromiecraft/issues/59

## Tests Performed:
- Tested in game and working
- Tested on Windows 10 (64)
- **Video Test:** [Patroling Deathguards chain aggro range](https://youtu.be/GAgINSUQdac)

## How to Test the Changes:

## Known Issues and TODO List:

- [ ]
- [ ] 

## Target Branch(es):
- [x] Master

 
## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here in the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

2021-02-22 20:25 UTC, Zoidwaffle commented
I don't know these guards that well, but a lot of other guards, would also attack unfriendly NPC's and not just the opposing faction.

So I'm not sure this is Bliz-like tbh. Just a suggestion - and I suck at SAI so I could be wrong, but wouldn't some "Guard SmartAI" where they are faster at returning to their waypoints be better? Like aggro stuff really close, once OOC, get back to the WP again?

2021-02-22 20:30 UTC, Stifler82 commented
> I don't know these guards that well, but a lot of other guards, would also attack unfriendly NPC's and not just the opposing faction.
> 
> So I'm not sure this is Bliz-like tbh. Just a suggestion - and I suck at SAI so I could be wrong, but wouldn't some "Guard SmartAI" where they are faster at returning to their waypoints be better? Like aggro stuff really close, once OOC, get back to the WP again?

@Zoidwaffle 
But the problem wasn't the NPCs not returning to their waypoint, the problem was that the players used these NPCs to kill mobs and exping for free.

2021-02-22 22:52 UTC, Helias requested changes

2021-02-22 22:52 UTC, Helias commented on data/sql/updates/pending_db_world/rev_1614022899539097500.sql
> +UPDATE `creature_template` SET `unit_flags` = 4608, `type` = 7 WHERE (`entry` = 727);
- https://www.azerothcore.org/wiki/Dealing-with-SQL-files read the Flags section
- you could group all of them like this
```SQL
UPDATE `creature_template` SET `unit_flags` = ...., `type` = 6 WHERE `entry` IN (1735,5725,3547,2314,1743,1515,2114,1518,10055,1745,2309,4773,4731,2311,2137,33996,1746,1652,2135,2136,2118,2134,1738,1742,10665,10666);
UPDATE `creature_template` SET `unit_flags` = ..., `type` = 7 WHERE (`entry` = 727);
```

2021-02-23 10:18 UTC, FrancescoBorzi approved these changes
changed `entry = (727)` to `entry = 727` and approved

2021-02-23 19:28 UTC, Helias approved these changes

2021-02-25 00:30 UTC, merged