fix(DB/object) Archbishop Alonsus Faol misplaced plaque in Stormwind
azerothcore/azerothcore-wotlk pull request #4846
Opened 2021-03-15 03:11 UTC by WojtekNosal

## Changes Proposed:
-  Placing Archbishop Alonsus Faol plaque in the right place

## Issues Addressed:
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/4642

## Tests Performed:
- Tested in-game now plaque is correctly positioned
![WoWScrnShot_031521_035930](https://user-images.githubusercontent.com/19744435/111098720-5da07800-8544-11eb-866a-966a927fd6c0.jpg)
![WoWScrnShot_031521_035918](https://user-images.githubusercontent.com/19744435/111098722-5ed1a500-8544-11eb-88d4-08561f29fc49.jpg)

## How to Test the Changes:
- Go to Stormwind Cathedral District
- Check Archbishop Alonsus Faol plaque placed on the fountain

## Target Branch(es):
- [x] Master

 
## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here in the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

2021-03-15 04:05 UTC, markvetx commented
Hi! According to [this](https://www.wowhead.com/object=177199/archbishop-alonsus-faol#screenshots) it should be placed on it's back to the ground, so it should face upwards. 

It looks okay on vmangos tho, but have an identical position values in 'gameobject' table

2021-03-15 04:14 UTC, Si1ker commented
> Hi! According to [this](https://www.wowhead.com/object=177199/archbishop-alonsus-faol#screenshots) it should be placed on it's back to the ground, so it should face upwards.
> 
> It looks okay on vmangos tho, but have an identical position values in 'gameobject' table

Correct.

![image](https://user-images.githubusercontent.com/61223313/111102782-8c055f80-8512-11eb-9539-03b87976660f.png)

Upwards :)

2021-03-15 10:09 UTC, WojtekNosal commented
Ohh sorry I've checked WoWHead for plaque placement but tought it should be like that. Thanks guys for pointing me out the correct plaque position, I will commit fix later today, cheers!

2021-03-17 21:30 UTC, WojtekNosal commented
Plaque is now correctly positioned
![WoWScrnShot_031721_220650](https://user-images.githubusercontent.com/19744435/111541046-4514a580-8770-11eb-9fad-819bd11c299a.jpg)

2021-03-17 21:35 UTC, Si1ker requested changes
Numbers are not strings, avoid using  ' '  if you are not changing auras.

2021-03-17 21:35 UTC, Si1ker commented on data/sql/updates/pending_db_world/rev_1615775571176561100.sql
> +UPDATE `gameobject` SET `position_x` = '-8640.98', `position_y` = '760', `position_z` = '98.38' WHERE `guid` = 26628;
```suggestion
UPDATE `gameobject` SET `position_x` = -8640.98, `position_y` = 760, `position_z` = 98.38 WHERE `guid` = 26628;
```

2021-03-17 21:40 UTC, Si1ker approved these changes
Tested. ✔️ 

/* Affected rows: 2  Found rows: 0  Warnings: 0  Duration for 3 queries: 0.000 sec. */

![image](https://user-images.githubusercontent.com/61223313/111542373-41b0f800-8737-11eb-83e9-92767fa2ddcf.png)

2021-03-18 20:56 UTC, Voxstrasza approved these changes

2021-03-18 21:50 UTC, merged