Mass update vanilla creature damages
azerothcore/azerothcore-wotlk pull request #4927
Opened 2021-03-20 21:46 UTC by T1ti

## Changes Proposed:
Based on the bestiary book : 
-Updated Molten Core, BWL and AQ 40 bosses damages
-Updated all Molten Core trash damages
-Updated a bunch of vanilla creatures by ID (checked creatures that had a modifier hgiher than 1, from ID 1 to 4625)

## Tests Performed:
-Querries is executed properly
-checked some beasts in game with beast lore

## How to Test the Changes:
 - teleport to a creature modified by this PR with `.go c id xxx`
-let the creature hit you without armor to test the damages(nude character still has a bit of armor) or use beast lore and check the damages

## Target Branch(es):
- [x] Master

 
## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here in the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

2021-03-21 05:18 UTC, T1ti commented
I'm gonna stop there, it's already a lot.
Would be nice if we had a way to track the verified mobs.

2021-03-21 15:24 UTC, FrancescoBorzi commented
thanks @T1ti , summoning @Knindzagxg

2021-03-21 17:18 UTC, Zoidwaffle commented
Hm, could it be tracked in the VerifiedBuild column or perhaps add another column to creature_template?

2021-03-21 22:03 UTC, Knindzagxg commented
Will check once im back tomorrow from work.

2021-03-24 02:27 UTC, T1ti commented
Any testers ? :(

2021-03-26 15:50 UTC, Knindzagxg commented
Had no time sadly, but will check during weekend mate.

2021-03-26 17:09 UTC, FrancescoBorzi commented
@azerothcore/testers @pklloveyou please check this

2021-03-27 18:05 UTC, Knindzagxg commented
Tested more then 60% and looks good so far.
Will keep checking a bit more later and tomorrow.

PS. We will have to check all TBC / Wotlk ones as well.

2021-03-27 18:56 UTC, T1ti commented
> Tested more then 60% and looks good so far.
> Will keep checking a bit more later and tomorrow.
> 
> PS. We will have to check all TBC / Wotlk ones as well.

We don't have the book for Wotlk creatures.
Your best bet to fix wotlk creature damages is to just wait for Wotlk classic in 2 years.

2021-03-31 21:19 UTC, Helias commented on data/sql/updates/pending_db_world/rev_1616275490460233200.sql
> +UPDATE `creature_template` SET `DamageModifier`='2.45' WHERE  `entry`=645;
you can merge these two UPDATE query into one
```SQL
UPDATE `creature_template` SET `DamageModifier`='2.45' WHERE  `entry` IN (647, 645);

```

2021-05-10 23:21 UTC, Hacki95 commented
@Knindzagxg Did you have time to test these? I tested a few and they seem to reflect the values from the book. I would approve this PR.

2021-05-18 15:45 UTC, Knindzagxg commented
I totally forgot to comment, even tho we talked on Disc xD
Didn't find any issues trough Raid or etc while testing, so yeah, everything is fine.

Yet again, sorry cause super late post, just super busy with work atm and 10hr shifts xD

2021-05-18 15:46 UTC, Knindzagxg approved these changes

2021-05-19 20:52 UTC, Hacki95 commented
All good! Thank you!

2021-06-15 00:43 UTC, T1ti commented
is this getting merged ?

2021-06-15 00:45 UTC, Kitzunu requested changes

2021-06-15 00:45 UTC, Kitzunu commented on data/sql/updates/pending_db_world/rev_1616275490460233200.sql
> +UPDATE `creature_template` SET `DamageModifier`='16' WHERE  `entry`=12118;
https://www.azerothcore.org/wiki/sql-standards#general-standards

Dont use '' around non-strings

2021-06-16 00:39 UTC, T1ti commented
I deleted this fork I can't edit it anymore

2021-06-16 13:56 UTC, FrancescoBorzi commented
we will merge this soon unless someone has anything against it.

2021-06-18 07:35 UTC, merged