fix(Core/PetAI): Fixed logic in PetAI to determine if pet can cast co…
azerothcore/azerothcore-wotlk pull request #5038
Opened 2021-03-28 16:16 UTC by UltraNix

…mbat spells.

Fixed #4992.

## Changes Proposed:
-  Fixed wrong logic.
-  

## Issues Addressed:
- Closes  #4992

## SOURCE:

## Tests Performed:

-  Tested ingame with Imp.
- 

## How to Test the Changes:

1. Create warlock.
2. `.level 79`
3. `.learn all my class`
4. Summon Imp
5. Set Blood Pact to autocast spell

## Known Issues and TODO List:

- [ ]
- [ ] 

## Target Branch(es):
- [x] Master

 
## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

2021-03-28 16:17 UTC, UltraNix commented
@T1ti  Please, test it.

2021-03-28 16:57 UTC, FrancescoBorzi approved these changes

2021-03-29 06:38 UTC, pklloveyou commented
Tested

2021-03-29 13:10 UTC, FrancescoBorzi commented
@pklloveyou can you please be more specific about what have you tested?

for example, have you tested only the issue fixed by this PR or have you also tested pets in general to make sure there is no regression (i.e. no new bugs) ?

2021-03-29 21:31 UTC, pklloveyou commented
I also tested hunter and mage pets

2021-03-30 13:31 UTC, FrancescoBorzi commented
> I also tested hunter and mage pets

ok good, thank you

2021-03-31 02:31 UTC, pklloveyou commented
@FrancescoBorzi We can't merge yet

2021-03-31 02:39 UTC, pklloveyou commented
Not in combat, hunter pets are releasing skills all the time. Is that wrong?

2021-03-31 05:26 UTC, UltraNix commented
If they are useable out of combat - why not? But I'm not sure - need confirmation.
@pklloveyou What specific skills do you mean?

2021-03-31 06:30 UTC, pklloveyou commented
Pets are constantly releasing skills, but not in combat

2021-03-31 06:33 UTC, pklloveyou commented
Well, maybe someone else should test it

2021-03-31 08:38 UTC, UltraNix commented
Once again - what specific skills do you mean?

2021-03-31 21:23 UTC, pklloveyou commented
![image](https://user-images.githubusercontent.com/18535853/113213157-569a9900-92aa-11eb-8901-a6fcec0fe7ea.png)

2021-03-31 21:29 UTC, Helias requested changes

2021-03-31 21:29 UTC, Helias commented on src/server/game/AI/CoreAI/PetAI.cpp
> +                    continue;
```suggestion
                if ((me->IsInCombat() || me->GetCharmInfo()->IsCommandAttack()) && !spellInfo->CanBeUsedInCombat())
                {
                    continue;
                }
```

2021-04-01 00:18 UTC, FrancescoBorzi commented
> @FrancescoBorzi We can't merge yet

ok, waiting for more feedback then

2021-04-01 09:06 UTC, UltraNix commented
@pklloveyou Test again (Blood Pact too).

2021-04-02 00:18 UTC, pklloveyou commented
Tested

2021-04-06 12:23 UTC, merged