fix(DB): Drop for Humbert's Helm
azerothcore/azerothcore-wotlk pull request #5260
Opened 2021-04-11 23:10 UTC by Hacki95

### Fix Drop for Humberts Helm

## Changes Proposed:
- Humbert's Helm was dropped by around 475 mobs while it should only drop for one 
- Delete the drop from every other mob and align the dropchange with Vanillawowdb/Wotlkwowdb

## Issues Addressed:
- Part https://github.com/azerothcore/azerothcore-wotlk/issues/4987

## SOURCE:

- https://vanillawowdb.com/?item=4724
- https://classic.wowhead.com/item=4724/humberts-helm
- https://wotlkdb.com/?item=4724

## Tests Performed:

- Applied SQL and checked the DB
- Not really any need to kill maybe hundreds of mobs to confirm.

## How to Test the Changes:

- Apply the SQL
- Check the DB

## Known Issues and TODO List:

- /

## Target Branch(es):
- [x] Master

 
## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

2021-04-11 23:16 UTC, Kitzunu commented
Whatever you do, do not trust vanillawowdb or wotlkwowdb, they are probably connected to someones private project

I dont doubt that you are wrong for this, I just freak out when I see it.

This is a cool trick if you want wowhead data from wotlk https://github.com/offl/ScriptInfo/wiki/How-to:-Web-archive

2021-04-11 23:18 UTC, Kitzunu requested changes
Remove ' from numbers and add backticks to column name

2021-04-12 06:44 UTC, Hacki95 commented
> 
> 
> Whatever you do, do not trust vanillawowdb or wotlkwowdb, they are probably connected to someones private project
> 
> I dont doubt that you are wrong for this, I just freak out when I see it.
> 
> This is a cool trick if you want wowhead data from wotlk https://github.com/offl/ScriptInfo/wiki/How-to:-Web-archive

I don't trust them, I just wanted to post more than one source. But I will keep the web archive thing in the back of my mind.

> 
> 
> Remove ' from numbers and add backticks to column name

When I remove the '' I get an SQL error but I can try again.

2021-04-12 08:59 UTC, Kitzunu approved these changes

2021-04-18 22:33 UTC, merged