Core/Movement: Use time synchronisation to better interpret client timestamps
azerothcore/azerothcore-wotlk pull request #5300
Opened 2021-04-15 18:42 UTC by chaodhib

Hello,

This is a port of [the time synchronization mechanism implemented in TrinityCore](https://github.com/TrinityCore/TrinityCore/pull/18189). The biggest hurdle for this port was to replace the usage of Boost. 2 utility files (MathUtil.h and CircularBuffer.h) could be removed in the future, once (if) Boost is added as a dependency to the project.

**Changes proposed:** _Copied from the original PR_

- Implement [Simple Network Time Protocol](https://tools.ietf.org/html/rfc4330) (SNTP) using the `SMSG_TIME_SYNC_REQUEST `/  `CMSG_TIME_SYNC_RESPONSE` exchange. No need to read however the RFC. The mechanism is quite simple and it is explained in the code. This packet exchange initiated by the server provides to the server the following information: the difference between its own clock and the clock of the client. With that clock delta, the server can precisely interpret timestamps sent by the client.
- On top of SNTP, I implemented the approach described [HERE](https://web.archive.org/web/20180430214420/http://www.mine-control.com/zack/timesync/timesync.html). That approach is necessary to use on top of SNTP because plain SNTP is designed to work on UDP, not TCP. The fact that TCP can resend dropped packets without any warning requires extra care.
- Using the server newly found information, which is the clock delta, we can now interpret the only timestamps sent by the client to the server: The movement timestamps. Now, when movement events occur on the client, we can precisely know their time on server clock (such as the player has started to move forward, for example). And send these movement timestamps on server clock to the observing nearby players.

**Issues addressed:** It should improve the visual perception of the other players on screen. 

## SOURCE:

## Tests Performed:

- Tested in game locally.

## How to Test the Changes:

## Known Issues and TODO List:

- [ ]
- [ ] 

## Target Branch(es):
- [x] Master

 
## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

2021-04-15 19:41 UTC, Winfidonarleyan commented
Very nice

2021-04-15 23:04 UTC, Winfidonarleyan commented on src/common/Utilities/CircularBuffer.h
> + */
```cpp
/*
 * Copyright (C) 2016+     AzerothCore <www.azerothcore.org>, released under GNU GPL v2 license, you may redistribute it and/or modify it under version 2 of the License, or (at your option), any later version.
 *
 * This file was based on
 * https://embeddedartistry.com/blog/2017/05/17/creating-a-circular-buffer-in-c-and-c/
 * https://github.com/embeddedartistry/embedded-resources/blob/master/examples/cpp/circular_buffer.cpp
 */
```

2021-04-15 23:05 UTC, Winfidonarleyan commented on src/common/Utilities/MathUtil.h
> + */
```cpp
/*
 * Copyright (C) 2016+ AzerothCore <www.azerothcore.org>, released under GNU AGPL v3 license: https://github.com/azerothcore/azerothcore-wotlk/blob/master/LICENSE-AGPL3
 */
```

2021-04-15 23:07 UTC, Winfidonarleyan commented on src/server/game/Server/WorldSocket.cpp
> +        if(opcode != CMSG_PING && opcode != CMSG_TIME_SYNC_RESP)
after `if` need add whitespace

2021-04-15 23:18 UTC, Winfidonarleyan commented
@chaodhib Big thanks for PR.

About license
- For new files need add
```cpp
/*
 * Copyright (C) 2016+ AzerothCore <www.azerothcore.org>, released under GNU AGPL v3 license: https://github.com/azerothcore/azerothcore-wotlk/blob/master/LICENSE-AGPL3
 */
```

2021-04-18 12:23 UTC, Footman commented
tested on live. everything fine

2021-04-18 12:32 UTC, chaodhib commented
@Footman thank you for testing.
@Winfidonarleyan thank you for making the necessary fixes to the headers and codestyle. I have added the missing section (how to test).

2021-04-18 13:23 UTC, Yehonal approved these changes

2021-04-18 13:24 UTC, Yehonal commented
Keep up the Good Work ™️

2021-04-20 22:03 UTC, Helias requested changes

2021-04-20 22:03 UTC, Helias commented on src/server/game/Server/WorldSocket.cpp
>      ACE_NOTREACHED (return 0);
this will never happen

2021-04-20 22:03 UTC, Helias commented on src/server/game/Server/WorldSocket.cpp
> +    }
```suggestion
    LOG_ERROR("server", "WorldSocket::ProcessIncoming: Client not authed opcode = %u", uint32(opcode));
    return -1;
```

2021-04-21 08:08 UTC, FrancescoBorzi commented
@chaodhib before merging this, can you please check them comments from @Helias and see if they make sense to you?

2021-04-21 20:02 UTC, chaodhib commented
Sure, will do

2021-04-22 19:28 UTC, pklloveyou commented on src/server/game/Handlers/MovementHandler.cpp
> +    uint32 roundTripDuration = getMSTimeDiff(serverTimeAtSent, recvData.GetReceivedTime());
Errors are reported here

2021-04-22 19:30 UTC, pklloveyou commented on src/server/game/Handlers/MovementHandler.cpp
> +    vector<int64> clockDeltasAfterFiltering;
std::vector<uint32> latencies;
    std::vector<int64> clockDeltasAfterFiltering;

2021-04-22 20:19 UTC, pklloveyou commented
![image](https://user-images.githubusercontent.com/18535853/115779899-1cc13c00-a3eb-11eb-93fc-ea0919c3f98b.png)
It's really much better

2021-04-22 21:48 UTC, chaodhib commented on src/common/Utilities/CircularBuffer.h
> +            return std::vector<T>(buf_.get(), buf_.get() + head_ - tail_);
I changed to something even shorter, thank you for the review

2021-04-22 21:54 UTC, chaodhib commented on src/server/game/Server/WorldSocket.cpp
>      ACE_NOTREACHED (return 0);
Removed

2021-04-22 21:54 UTC, chaodhib commented on src/server/game/Server/WorldSocket.cpp
> +    }
Done

2021-04-22 21:54 UTC, chaodhib commented on src/server/game/Handlers/MovementHandler.cpp
> +    vector<int64> clockDeltasAfterFiltering;
Done

2021-04-22 22:00 UTC, chaodhib commented
Done. Let me know if there is something else that could be improved.

@pklloveyou thanks for the feedback! Appreciated!

2021-04-23 06:56 UTC, pklloveyou commented
Tested

2021-04-23 10:21 UTC, FrancescoBorzi commented
good job @chaodhib ! I will merge this as soon as the build passes.

PS: would you like to join our [Discord chat](https://discordapp.com/invite/gkt4y2x)?

2021-04-23 13:53 UTC, merged

2021-04-23 21:10 UTC, chaodhib commented
@FrancescoBorzi Thank you! Sure, I'm in the Discord already. My handle is #7251.

2021-04-23 22:50 UTC, Winfidonarleyan commented
Thanks for pr

2021-04-24 09:36 UTC, FrancescoBorzi commented
> @FrancescoBorzi Thank you! Sure, I'm in the Discord already. My handle is #7251.

@chaodhib  what's your username? I cannot find you

2021-04-24 11:07 UTC, chaodhib commented
Chaouki