fix(DB/Graveyard): add ghostZone for zone 1537
azerothcore/azerothcore-wotlk pull request #5581
Opened 2021-05-01 18:00 UTC by Crypticaz

## Changes Proposed:
-  Add graveyard for zone 1537 (ironforge)

## Issues Addressed:
- Closes [5579](https://github.com/azerothcore/azerothcore-wotlk/issues/5579)
- Issue wasn't just in lava, but all of Ironforge as well.

## Tests Performed:

- Teleports player to correct graveyard in Ironforge.
![WoWScrnShot_050121_125757](https://user-images.githubusercontent.com/25990459/116790983-ffd8d880-aa7c-11eb-9070-65f9dcc65db3.jpg)
![WoWScrnShot_050121_125802](https://user-images.githubusercontent.com/25990459/116790984-01a29c00-aa7d-11eb-803c-a6d91ba18ad6.jpg)

## How to Test the Changes:
- .tele ironforge
- select yourself and .die
- release spirit

## Target Branch(es):
- [x] Master

 
## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

2021-05-01 18:13 UTC, Helias approved these changes

2021-05-01 18:36 UTC, Kitzunu requested changes

2021-05-01 18:36 UTC, Kitzunu commented on data/sql/updates/pending_db_world/rev_1619891302194258700.sql
> +(852, 1537, 469, 'Ironforge');
```suggestion
(852, 1537, 469, 'Dun Morogh, Gates of Ironforge - Ironforge');
```

2021-05-01 18:36 UTC, Kitzunu commented on data/sql/updates/pending_db_world/rev_1619893844216235100.sql
> +DELETE FROM `creature_loot_template` WHERE  `Entry`=3928 AND `Item`=5519;
Not for this PR

2021-05-02 00:07 UTC, Kitzunu approved these changes

2021-05-06 13:35 UTC, merged