Fix(Core/Script): Molten Core: Garr
azerothcore/azerothcore-wotlk pull request #5690
Opened 2021-05-07 12:41 UTC by Hacki95

Co-Author: @sanctum32 (Code)
Co-Author: @T1ti (Research)
Co-Author: @Hacki95 (Coordination)

## Changes Proposed:
- Correct Garr's timers
- Add the missing mechanics to Garrs adds

## Issues Addressed:

- Closes #5803 

## SOURCE:

## Tests Performed:

- Applied patch
- Fought Garr

## How to Test the Changes:

1. Apply patch
2. .tele moltencore
3. Fight Garr

## Known Issues and TODO List:

- Seperation anxiety
- Move some spells to DB

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

2021-05-07 13:40 UTC, FrancescoBorzi commented on src/server/scripts/EasternKingdoms/BlackrockMountain/MoltenCore/boss_garr.cpp
> +                for (Creature* fireworn : fireworns)
feel free to use `auto` in cases like this
```suggestion
                for (auto fireworn : fireworns)
```

2021-05-07 17:32 UTC, Si1ker requested changes

2021-05-07 17:32 UTC, Si1ker commented on src/server/scripts/EasternKingdoms/BlackrockMountain/MoltenCore/boss_garr.cpp
> +                                              aniexityTimer(10000),
```suggestion
                                              anxietyTimer(10000),
```

2021-05-07 17:32 UTC, Si1ker commented on src/server/scripts/EasternKingdoms/BlackrockMountain/MoltenCore/boss_garr.cpp
> +            if (aniexityTimer <= diff)
```suggestion
            if (anxietyTimer <= diff)
```

2021-05-07 17:32 UTC, Si1ker commented on src/server/scripts/EasternKingdoms/BlackrockMountain/MoltenCore/boss_garr.cpp
> +                aniexityTimer -= diff;
```suggestion
                anxietyTimer -= diff;
```

2021-05-07 17:32 UTC, Si1ker commented on src/server/scripts/EasternKingdoms/BlackrockMountain/MoltenCore/boss_garr.cpp
> +        uint32 aniexityTimer;
```suggestion
        uint32 anxietyTimer;
```

2021-05-07 17:32 UTC, Si1ker commented on src/server/scripts/EasternKingdoms/BlackrockMountain/MoltenCore/boss_garr.cpp
> +                aniexityTimer = 250;
```suggestion
                anxietyTimer = 250;
```

2021-08-02 21:02 UTC, ChrisCGalbraith commented on src/server/scripts/EasternKingdoms/BlackrockMountain/MoltenCore/boss_garr.cpp
> +            std::list<Creature*> fireworns;
Pedantic typo, however, this should be firesworn as opposed to fireworns.

2021-08-04 12:54 UTC, Winfidonarleyan commented on src/server/scripts/EasternKingdoms/BlackrockMountain/MoltenCore/boss_garr.cpp
> +enum Texts
```suggestion
enum GarrTexts
```

2021-08-04 13:51 UTC, ChrisCGalbraith commented on src/server/scripts/EasternKingdoms/BlackrockMountain/MoltenCore/boss_garr.cpp
> +            std::list<Creature*> fireworns;
> ? usually the lists have a plural name, so I think it seems ok to me

I should've been more explicit: fireworns is a typo, it is missing an S to make it fireSWORN. 
I'm not sure it matters, but I think the word firesworn might work like the word sheep: there are 6 sheep, there are 6 firesworn? The main thing i meant to point out was the spelling mistake of their name

2021-10-06 00:32 UTC, Nefertumm approved these changes
All seems fine, commit what Winfi suggested as it seems the right call.

2021-10-31 16:00 UTC, closed without merging