fix(DB/creature): Adjust creature spawn location at Badlands
azerothcore/azerothcore-wotlk pull request #5719
Opened 2021-05-08 09:43 UTC by Hacki95

## Changes Proposed:
- Update x, y, z and orientation of those 3 NPCS

## Issues Addressed:

- Closes #5696
- Closes https://github.com/chromiecraft/chromiecraft/issues/562

## SOURCE:

- https://github.com/brotalnia/database/blob/master/world_full_12_november_2020.7z

## Tests Performed:

- Applied SQL
- Checked ingame

## How to Test the Changes:

1. Apply SQL
2. .go cr guid

## Known Issues and TODO List:

- /

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

2021-05-08 15:26 UTC, FrancescoBorzi approved these changes

2021-05-10 04:21 UTC, Si1ker requested changes
Your fix is making them fall to the void. (7614 and 6915)

![image](https://user-images.githubusercontent.com/61223313/117605439-ed157200-b114-11eb-860d-e18aca955638.png)

2021-05-10 10:30 UTC, Hacki95 commented
Ahh okay this seems to be part of the map problem then, in vmangos they don't.

2021-09-03 19:17 UTC, Si1ker commented on data/sql/updates/pending_db_world/rev_1620466647964636420.sql
> +UPDATE `creature` SET `position_x`=-6649.06, `position_y`=-3482.49, `position_z`=259.517, `orientation` = 4.37896 WHERE `guid`=6915;
```suggestion
UPDATE `creature` SET `position_x`=-6649.06, `position_y`=-3482.49, `position_z`=263.517, `orientation` = 4.37896 WHERE `guid`=6915;
```

6947 ✔️ perfect
7614 ✔️ at the server start it falls, after 2 seconds, it always gets the right position above the ground. 
6915 ❌ always fails underground, still needs a small adjustment of 4, 263 always works

@Hacki95 🐱

2021-09-23 22:58 UTC, Si1ker approved these changes

2021-09-23 23:04 UTC, merged