fix(DB/loot): Fix Shiver Blade drop
azerothcore/azerothcore-wotlk pull request #5944
Opened 2021-05-19 09:38 UTC by anguaive

Only Gesharahan (id: 3398) should be able to drop Shiver Blade (id: 5182), with a ~72% drop chance.

Currently no gameobjects or creatures drop Shiver Blade directly. It's only included in a reference table:

```
SELECT * FROM `creature_loot_template` WHERE `Item` = 5182;
Empty set (0.080 sec)

SELECT * FROM `gameobject_loot_template` WHERE `Item` = 5182;
Empty set (0.018 sec)
```
```
SELECT * FROM `reference_loot_template` WHERE `Item` = 5182;
+-------+------+-----------+--------+---------------+----------+---------+----------+----------+--------------+
| Entry | Item | Reference | Chance | QuestRequired | LootMode | GroupId | MinCount | MaxCount | Comment      |
+-------+------+-----------+--------+---------------+----------+---------+----------+----------+--------------+
| 24060 | 5182 |         0 |      0 |             0 |        1 |       1 |        1 |        1 | Shiver Blade |
+-------+------+-----------+--------+---------------+----------+---------+----------+----------+--------------+
```

Since Gesharahan is the only creature who's supposed to drop the Shiver Blade, I have removed the item from the reference table and added it to Gesharahan's loot table directly, with the drop chance taken from wowhead.

## Changes Proposed:
- Remove Shiver Blade from the reference table that includes it
- Add Shiver Blade to Gesharahan's loot table directly

## Issues Addressed:

- Closes #5943
- Closes https://github.com/chromiecraft/chromiecraft/issues/672

## SOURCE:

https://classic.wowhead.com/item=5182/shiver-blade

## Tests Performed:

- Made sure the new loot table lines up with what's expected

## How to Test the Changes:

1. Look up new loot table for Gesharahan
2. Look up where Shiver Blade drops from

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

2021-05-19 09:45 UTC, Kitzunu requested changes
Always delete before insert

2021-05-19 09:47 UTC, anguaive commented
Whoops

2021-05-19 18:53 UTC, Helias approved these changes

2021-05-20 15:13 UTC, FrancescoBorzi approved these changes

2021-05-25 14:24 UTC, merged