fix(Core/ScriptsMgr): correct hooks name
azerothcore/azerothcore-wotlk pull request #6434
Opened 2021-06-19 12:52 UTC by Winfidonarleyan

## Changes Proposed:
-  
-

2021-06-19 13:38 UTC, Winfidonarleyan commented
@Yehonal please check

2021-06-19 14:40 UTC, Yehonal commented on doc/changelog/pendings/changes_1624109504178983100.md
> +- Just rename all hooks from `CanExitJoinMessageArenaQueue` to `CanSendExitMessageArenaQueue`
```suggestion
- Just rename all hooks from `CanExitJoinMessageArenaQueue` and `CanSendMessageArenaQueue`, to `CanSendExitMessageArenaQueue`
```

2021-06-19 14:40 UTC, Yehonal commented on doc/changelog/pendings/changes_1624109504178983100.md
> +- Just rename all hooks from `CanExitJoinMessageArenaQueue` to `CanSendExitMessageArenaQueue`
The original hook was called CanSendMessageArenaQueue, some modules are still using that one

2021-06-19 15:00 UTC, Yehonal commented
Based on our [naming conventions](https://www.azerothcore.org/wiki/hooks-script#naming-conventions) the hook names should follow the structure: `On[When]<Action>`

Since we're doing a renaming here I'd suggest starting using the correct convention and documenting them properly.

Here you are an example of a proper named and documented hook for the SendExitMessageArenaQueue (the same should be done for the other one):

```cpp
/**
 * @brief This hook runs before sending the exit message during the arena queue, allowing you to run extra operations or disabling the exit message
 *
 * @param queue Contains information about the Arena queue
 * @param ginfo Contains information about the group of the queue
 * @return True if you want to continue sending the message, false if you want to disable the message
 */
[[nodiscard]] virtual bool OnBeforeSendExitMessageArenaQueue(BattlegroundQueue* /*queue*/, GroupQueueInfo* /*ginfo*/) { return true; }
};
```

NOTE: I'm not sure about what the  ginfo param contains though, feel free to change it.

2021-06-26 18:00 UTC, Yehonal commented
@Winfidonarleyan can you complete these, please? so we can merge it

2021-06-27 05:41 UTC, Winfidonarleyan commented
@Yehonal done, need re-review

2021-06-27 09:21 UTC, Yehonal requested changes

2021-06-27 09:21 UTC, Yehonal commented on doc/changelog/pendings/changes_1624109504178983100.md
> +- Just rename all hooks from `CanExitJoinMessageArenaQueue` and `CanSendMessageArenaQueue`, to `CanSendExitMessageArenaQueue`
```suggestion
- Just rename all hooks from `CanExitJoinMessageArenaQueue` and `CanSendMessageArenaQueue`, to `OnBeforeSendExitMessageArenaQueue`
```

2021-06-27 10:39 UTC, Yehonal approved these changes

2021-06-28 06:34 UTC, merged