fix(DB): Spanish lost texts (Battle for the Undercity)
azerothcore/azerothcore-wotlk pull request #6573
Opened 2021-06-25 17:00 UTC by MathematicalWTF

## Changes Proposed:
-  Creates the respective Spanish text (Quest/Gossip/creature text) of the event battle for Undercity.

## Issues Addressed:

- Closes 

## SOURCE:

## Tests Performed:

- Statements  executed in my database to check for errors.
- In-game changes seen

## How to Test the Changes:

1. Inserting the sql to your database.

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs

When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

2021-06-25 21:42 UTC, pangolp commented
Avoid using the INSERT twice, it can be done in the same query as I explained to you on discord. You also have to check the IDs issue when doing the deletion. Because it could be the only dialog for this NPC, but it might not be or maybe the next time you make a deletion you have to try to remember to do it.

2021-06-25 21:44 UTC, pangolp requested changes
Avoid using the INSERT twice, it can be done in the same query as I explained to you on discord. You also have to check the IDs issue when doing the deletion. Because it could be the only dialog for this NPC, but it might not be or maybe the next time you make a deletion you have to try to remember to do it.

2021-06-25 21:44 UTC, pangolp commented on data/sql/updates/pending_db_world/rev_1624636115436386300.sql
> +INSERT INTO `gossip_menu_option_locale` (`MenuID`, `OptionID`, `Locale`, `OptionText`, `BoxText`) VALUES
You can delete 1 INSERT and use only 1.

2021-06-25 21:44 UTC, pangolp commented on data/sql/updates/pending_db_world/rev_1624636115436386300.sql
> +DELETE FROM `gossip_menu_option_locale` WHERE `MenuID` = 10189 AND `Locale` IN ('esES','esMX');
When doing a DELETE, remember to specify in this case the OptionID

2021-06-26 00:41 UTC, pangolp commented on data/sql/updates/pending_db_world/rev_1624636115436386300.sql
> +
You have one space too many.

2021-06-26 00:42 UTC, pangolp commented on data/sql/updates/pending_db_world/rev_1624636115436386300.sql
> +DELETE FROM `creature_text_locale` WHERE `CreatureID` IN (32364, 32346) AND `Locale` IN ('esES','esMX');
I think it would be good to specify the ID, because today the dialog may not exist, but it is a good practice to delete only what we add.

2021-06-26 00:51 UTC, closed without merging

2021-06-26 00:52 UTC, MathematicalWTF commented
Many meaningless commits.

2021-06-26 01:19 UTC, MathematicalWTF commented
I created another pll about it: https://github.com/azerothcore/azerothcore-wotlk/pull/6582