fix(DB/Creature): InhabitType of ICC flying Creatures
azerothcore/azerothcore-wotlk pull request #6661
Opened 2021-06-30 20:47 UTC by bronzato

Ids: 37955,38434,38435,38436,37501,38197,37502,38198,37232,38362
Was with wrong InhabitType making then fly on the floor

Closes AzerothCore issue 4661
https://github.com/azerothcore/azerothcore-wotlk/issues/4661

## Changes Proposed:
-    Changing InhabitType for some flying creatures inside ICC (Some Nerubians and Blood Queen Boss)

## Issues Addressed:
- Closes issue 4661
- https://github.com/azerothcore/azerothcore-wotlk/issues/4661

## Tests Performed:
- No Erros
- Tested in game with the current build of AzerothCore
- In the Blood Queen Boss she body was half in the floor with the Inhabittype 4, i change to 1 and she in on the floor in right place, and she still can fly in the air phase (the creature script do the job)
- Tested in Ubuntu Server 20.04

## How to Test the Changes:

1.Go to ICC
2.Go to Blood Queen Boss
3.She body is not half on the floor
4.Nerubians before Sindragosa Boss, should be on the floor to (after descending from the roof in the web)

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

2021-07-01 11:40 UTC, Yehonal approved these changes
Good one! approved!

Can someone test it please? (all the bosses inside the **IN** list)

2021-07-01 14:51 UTC, FrancescoBorzi commented
> Good one! approved!
> 
> Can someone test it please? (all the bosses inside the **IN** list)

These are the NPCs to check:

```
37955,38434,38435,38436,37501,38197,37502,38198,37232,38362
```

cc @azerothcore/testers

2021-07-06 16:21 UTC, morpheux commented
@FrancescoBorzi 

Works for me.

2021-07-06 16:44 UTC, Helias approved these changes

2021-07-06 17:40 UTC, FrancescoBorzi commented
good job @bronzato and thanks @morpheux for testing this!

2021-07-07 04:10 UTC, Kitzunu requested changes

2021-07-07 04:10 UTC, Kitzunu commented on data/sql/updates/pending_db_world/rev_1625085335146756200.sql
> +UPDATE creature_template SET InhabitType = 1 WHERE entry IN (37955,38434,38435,38436,37501,38197,37502,38198,37232,38362);
backticks
https://www.azerothcore.org/wiki/sql-standards

2021-07-07 15:28 UTC, FrancescoBorzi commented on data/sql/updates/pending_db_world/rev_1625085335146756200.sql
> +UPDATE creature_template SET InhabitType = 1 WHERE entry IN (37955,38434,38435,38436,37501,38197,37502,38198,37232,38362);
I added them myself

2021-07-07 23:51 UTC, merged