fix(DB/Creature): Fix static Ironjaw Basilisks
azerothcore/azerothcore-wotlk pull request #6903
Opened 2021-07-12 14:50 UTC by jamadaha

- The Ironjaw Basilisks (GUID 373, 612, 756, 981 and 1062) were the only non moving in the cave, whereas they wander.
 - Closes #6899

## Changes Proposed:
-  Add wandering to the Ironjaw Basilisks (GUID 373, 612, 756, 981 and 1062).

## Issues Addressed:

- Closes #6899

## SOURCE:

## Tests Performed:

- .go c 373/612/756/981/1062
- Observe

## How to Test the Changes:

1. .go c 373/612/756/981/1062
2. Observe
3.

## Known Issues and TODO List:

N/A

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

2021-07-12 16:26 UTC, LukasVolgger requested changes

2021-07-12 16:26 UTC, LukasVolgger commented on data/sql/updates/pending_db_world/rev_1626100751770962700.sql
> +UPDATE `creature` SET `MovementType` = 1, `wander_distance` = 5 WHERE `id` = 1551 AND `guid` = 1062;
Please add new line at the end of file

2021-07-12 17:29 UTC, jamadaha commented on data/sql/updates/pending_db_world/rev_1626100751770962700.sql
> +UPDATE `creature` SET `MovementType` = 1, `wander_distance` = 5 WHERE `id` = 1551 AND `guid` = 1062;
Should be fixed now

2021-07-12 17:37 UTC, LukasVolgger approved these changes
Either my app or Github has a problem, sry it was fine!

2021-07-13 08:20 UTC, Eldarix commented
Checked (AC HASH/COMMIT: 05bbf4a), they move correctly I would say ;)

![WoWScrnShot_071321_111454](https://user-images.githubusercontent.com/82579073/125416975-a8be2a50-fc05-4a0f-82f0-78b22c899511.jpg)
![WoWScrnShot_071321_111513](https://user-images.githubusercontent.com/82579073/125417036-186467d2-6cef-4d58-865d-34b8fb23bedf.jpg)
![WoWScrnShot_071321_111537](https://user-images.githubusercontent.com/82579073/125417081-f39670e0-fc1b-4604-ae4f-99501e0ceccf.jpg)
![WoWScrnShot_071321_111554](https://user-images.githubusercontent.com/82579073/125417141-5daace2c-300a-46c7-89db-dc655d991096.jpg)
![WoWScrnShot_071321_111618](https://user-images.githubusercontent.com/82579073/125417231-04a056e4-b859-45b2-9366-2309110fcada.jpg)

2021-07-13 10:45 UTC, LukasVolgger commented
Thx @jamadaha for your contribution and @Eldarix for testing!

2021-07-13 14:39 UTC, FrancescoBorzi approved these changes

2021-07-14 16:36 UTC, merged