Remove Fire Immunity Mask from Warlock's Infernal (Inferno Spell)
azerothcore/azerothcore-wotlk pull request #7002
Opened 2021-07-17 03:43 UTC by markvetx

## Changes Proposed:
-  Removed `spell_school_immune_mask` from Warlock's [Infernal](https://wotlkdb.com/?npc=89)
-  [Infernal](https://wotlkdb.com/?npc=89) doesn't need it since it already have [Immunity:Fire](https://wotlkdb.com/?spell=7942) spell in `creature_addon`
- After removing `spell_school_immune_mask` [Immolation](https://wotlkdb.com/?spell=19483) spell started triggering from [Infernal](https://wotlkdb.com/?npc=89)

## SOURCE:

https://youtu.be/dPORXIbZKkw?t=80

## Tests Performed:

- Checked [Immolation](https://wotlkdb.com/?spell=19483) triggering
- Summoned [Infernal](https://wotlkdb.com/?npc=89) through `.npc add 89` and tested fire spells against him

## How to Test the Changes:

1. Cast [Inferno](https://wotlkdb.com/?spell=1122) at any mob/pack
2. Check for [Immolation](https://wotlkdb.com/?spell=19483) to trigger
3. `.npc add 89`
4. Try to cast fire spells on him

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

2021-07-19 07:40 UTC, LukasVolgger requested changes

2021-07-19 07:40 UTC, LukasVolgger commented on data/sql/updates/pending_db_world/rev_1626462644022857380.sql
> +UPDATE `creature_template` SET `spell_school_immune_mask` = 0 WHERE `entry` = 89;
Please add a new line at the end of the file

2021-07-21 15:45 UTC, FrancescoBorzi commented
@markvetx what's the status of this?

2021-07-21 15:52 UTC, laasker commented
working for me, infernal is still immune to fire damage and deals Immolation AoE damage

2021-07-21 17:07 UTC, FrancescoBorzi approved these changes

2021-07-23 17:51 UTC, LukasVolgger approved these changes

2021-07-23 19:41 UTC, merged