Core/Movement:
azerothcore/azerothcore-wotlk pull request #7008
Opened 2021-07-17 15:06 UTC by UltraNix

Get zone/area IDs from vmap data in the liquid update.
Add new method Map::getFullVMapDataForPosition to get area info and liquid info in a single vmap lookup
Adjust GetZoneId/GetAreaId on WorldObject to always return these cached fields.
Clean up liquid state handling on Unit and Player
Implemented getting area id from gameobject spawns.
Removed old core related to getting movement flags dependent on environment.
Movement flags are now processed more precisely and dynamically.
Original source: TrinityCore.
Fixed #5086
Updated #2208.

## Changes Proposed:
-  Backported changes from TrinityCore about getting cached data (areaId, zoneId, bolean outdoor and liquid data) when unit/object is moving
-  Cleanup liquid data code.
- Removed old and not smooth `UpdateEnvironmentIfNeeded` and everything related to it.

## Issues Addressed:

- Closes #5086.

## SOURCE:

## Tests Performed:

- Tested ingame in open world with players, flying mobs, mounts, swiming, etc

## How to Test the Changes:

There is a list what to test:
1. Spells/items that should be usable only/forbidden outdoor/indoor (e.g. mounts)
2. Test breathing timer/bar while swimming/entering/leaving water/lava/ocean.
3. Test proper area/zone ids by typiing ingame `.gps` in different locations all the world.
4. Test flying/flyable mobs/NPCs and their transition between flying/walking on the ground.

The best spots to test it is IcecrownCitadel and cities.

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

2021-07-17 15:08 UTC, UltraNix commented
Fixes all the flying mobs that still have flying animation when landing/walking on the ground.

2021-07-17 15:27 UTC, FrancescoBorzi commented
@azerothcore/testers @azerothcore/senior-bug-triaging @azerothcore/developers please check this PR

2021-07-17 18:56 UTC, pklloveyou commented on src/server/game/Entities/Object/Object.h
> +    LiquidData const& GetLiquidData() const { return _liquidData; }
```
    [[nodiscard]] uint32 GetZoneId() const;
    [[nodiscard]] uint32 GetAreaId() const;
    void GetZoneAndAreaId(uint32& zoneid, uint32& areaid) const;
    [[nodiscard]] bool IsOutdoors() const;
    LiquidData const& GetLiquidData() const;
```

2021-07-17 18:57 UTC, pklloveyou commented
In many outdoor places, riding automatically unloads the mount

2021-07-17 19:55 UTC, UltraNix commented
@pklloveyou Give me the exact coords.
It looks okay on my local.

2021-07-17 20:55 UTC, pklloveyou commented
It may have something to do with my anti cheating module O.o

2021-07-17 22:13 UTC, FrancescoBorzi commented
@UltraNix the build is failing and there are conflicts

2021-07-18 12:38 UTC, Azcobu commented
Checking this vs an old ticket about mounts being useable indoors in Grom'gol Base Camp's inn (https://github.com/azerothcore/azerothcore-wotlk/issues/6640) and found this issue is still occurring:

![WoWScrnShot_071821_220444](https://user-images.githubusercontent.com/81782124/126067324-5671926c-19e4-4d86-bc06-74d420e60742.jpg)

But I don't know enough about this problem to say if these changes are supposed to fix this, as it could be a problem with this particular inn. But it is an instance of a forbidden indoor item working when it shouldn't.

2021-07-18 13:35 UTC, UltraNix commented
#6093 is not handled by this PR.
#6640 is not a bug.

2021-07-18 13:52 UTC, Azcobu commented
Would this PR affect NPC transitions between land and water as well? We had some issues like that (https://github.com/azerothcore/azerothcore-wotlk/issues/6541, https://github.com/azerothcore/azerothcore-wotlk/issues/6171) and someone said it might be the land/water transition. Would you expect this PR to solve those, or wouldn't it apply?

2021-07-18 13:58 UTC, UltraNix commented
@Azcobu Might be another problem (with missing swimming flag or spline run), but you can test it.

2021-07-18 14:03 UTC, mpfans commented
I will test it in the near future

2021-07-21 15:33 UTC, FrancescoBorzi commented
> I will test it in the near future

thanks @mpfans , please let us know

2021-08-16 09:01 UTC, Mitradis commented
it helps with https://github.com/azerothcore/azerothcore-wotlk/issues/7359 ?

2021-08-16 14:36 UTC, FrancescoBorzi commented
@UltraNix  there are conflicts

2021-08-18 09:13 UTC, FrancescoBorzi commented
@UltraNix build failing

2021-08-18 20:03 UTC, Helias commented
```
In file included from /home/runner/work/azerothcore-wotlk/azerothcore-wotlk/modules/mod-eluna-lua-engine/LuaEngine/LuaFunctions.cpp:35:
/home/runner/work/azerothcore-wotlk/azerothcore-wotlk/modules/mod-eluna-lua-engine/LuaEngine/MapMethods.h:198:46: fatal error: too few arguments to function call, expected 4, have 3
        Eluna::Push(L, map->GetAreaId(x, y, z));
                       ~~~~~~~~~~~~~~        ^
/home/runner/work/azerothcore-wotlk/azerothcore-wotlk/src/server/game/Maps/Map.h:378:19: note: 'GetAreaId' declared here
    [[nodiscard]] uint32 GetAreaId(uint32 phaseMask, float x, float y, float z) const;
                  ^
1 error generated.
```

still failing :(

2021-08-18 20:08 UTC, UltraNix commented
@Helias Look here: https://github.com/ElunaLuaEngine/Eluna/pull/377

2021-08-18 20:26 UTC, Kitzunu requested changes

2021-08-18 20:26 UTC, Kitzunu commented on src/common/Collision/DynamicTree.h
> +    void getAreaAndLiquidData(float x, float y, float z, uint32 phasemask, uint8 reqLiquidType, VMAP::AreaAndLiquidData& data) const;
```suggestion
    bool GetAreaInfo(float x, float y, float& z, uint32 phasemask, uint32& flags, int32& adtId, int32& rootId, int32& groupId) const;
    void GetAreaAndLiquidData(float x, float y, float z, uint32 phasemask, uint8 reqLiquidType, VMAP::AreaAndLiquidData& data) const;
```

2021-08-18 20:26 UTC, Kitzunu commented on src/common/Collision/Management/IVMapManager.h
> +        virtual void getAreaAndLiquidData(uint32 mapId, float x, float y, float z, uint8 reqLiquidType, AreaAndLiquidData& data) const = 0;
same as above

2021-08-18 20:26 UTC, Kitzunu commented on src/common/Collision/Models/GameObjectModel.cpp
> +void GameObjectModel::intersectPoint(G3D::Vector3 const& point, VMAP::AreaInfo& info, uint32 ph_mask) const
same as above

2021-08-18 20:26 UTC, Kitzunu commented on src/common/Collision/Models/GameObjectModel.h
> +    [[nodiscard]] bool isMapObject() const { return isWmo; }
same as above

2021-08-18 20:26 UTC, Kitzunu commented on src/server/game/Entities/Creature/Creature.cpp
> +    bool IsInAir = false;
```suggestion
    bool isInAir = false;
```

2021-08-23 18:11 UTC, Mitradis approved these changes

2021-08-25 10:41 UTC, merged