fix(DB/Creature): Added skills to Razorbeak Gryphon and Razorbeak Skylord
azerothcore/azerothcore-wotlk pull request #7026
Opened 2021-07-19 10:33 UTC by Asthalor

I added the skills Rend Flesh and Wing Flap on both of them as the source indicates

Closes AzerothCore issue#6798

## Changes Proposed:
-  Added the skill Rend Flesh to use it every 14 seconds
-  Added the skill Wing Flap to uise it every 10 seconds

## Issues Addressed:

- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/6798

## SOURCE:

https://wowpedia.fandom.com/wiki/Razorbeak_Skylord
https://www.wowhead.com/npc=2659/razorbeak-skylord#abilities

## Tests Performed:

- .go c id 2658 and  .go c id 2659
- attack and see if they use them

Small video proof

https://user-images.githubusercontent.com/87535580/126146894-11eef505-8db7-4041-8286-061ab18e8fe0.mp4

## How to Test the Changes:

1.  .go c id 2658 and  .go c id 2659
2. Attack and see if they use them

## Known Issues and TODO List:

- I choosed 14 and 10 seconds. The bleed one is a bleed that last 12 seconds, so i wanted to give some time to use it again. The knockup is quicker so it will not happen both attacks at the same time.
- I dont know much about difficulty, so if the timers need to be changed please advise

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

2021-07-19 11:23 UTC, LukasVolgger approved these changes
Ready to test and pls give feedback about the known issues during tests.

2021-07-19 18:13 UTC, syssneck commented
Hi, here are my test results and what I found out:
- Razorbeak Gryphon (.go c id 2658) and Razorbeak Skylord (.go c id 2659) are both not moving (they have no random movement). It would be really nice, if you could add this in this PR @Asthalor :)
- Both are now friendly to Alliance characters, but hostile to Horde characters (please fix):
![unknown_2021 07 19-19 43_1](https://user-images.githubusercontent.com/68868567/126205630-bd968937-57b2-4224-8483-bcf5321eebb0.jpg)
- Both are using Rend Flesh and Wing Flap. 
- Rend Flesh does, dependent on the creature level, between 55-65 dmg per tick. This seems reasonable for this level range (not too easy, not too hard)
- Wing Flap works and knocks my characters back a bit (when hit)
- I checked the db, there are indeed only these two Razorbeaks
Test combat video:

https://user-images.githubusercontent.com/68868567/126207142-9054b769-f828-46a0-ad02-4b4f3cc7ada5.mp4

2021-07-19 19:45 UTC, LukasVolgger commented
Thx @syssneck for your great test results!
Imo it sounds to be a better behaviour and even more blizzlike then before the PR and this could be merged.

Any objections?

2021-07-19 19:47 UTC, syssneck commented
All good, no objections. I will just create another issue for the movement then. Ty!

2021-07-19 20:00 UTC, LukasVolgger commented
> All good, no objections. I will just create another issue for the movement then. Ty!

@Asthalor maybe you wanna have a look at this too? It could also be done in this PR by fixing two issues

2021-07-19 20:43 UTC, Asthalor commented
> > All good, no objections. I will just create another issue for the movement then. Ty!
> 
> @Asthalor maybe you wanna have a look at this too? It could also be done in this PR by fixing two issues

Hello! Thanks a lot for the testing and feedback @syssneck .
Ive yet to do something related to movements of creatures, i started here 2 or 3 days ago, but i can definively take a look at that if you dont mind waiting a bit more to merge @LukasVolgger

2021-07-19 21:07 UTC, syssneck commented
@Asthalor ty for taking a look at it! I think it has something to do with MovementType.

2021-07-20 10:31 UTC, Asthalor commented
@syssneck  thanks for the tip! In the end it was not hard :P

Added movement patterns to both of them.
TEST

Razorbeak Gryphon
https://user-images.githubusercontent.com/87535580/126309302-157e51ce-d380-496f-9ec7-de1942191e21.mp4

Razorbeak Skylord

https://streamable.com/cwpljt

2021-07-20 10:48 UTC, LukasVolgger requested changes

2021-07-20 10:48 UTC, LukasVolgger commented on data/sql/updates/pending_db_world/rev_1626690253021473300.sql
> +(93615, 2659, 0, 0, 0, 1, 1, 1148, 0, 200.395, -3662.88, 133.817, 3.43305, 350, 10, 0, 2399, 0, 1, 0, 0, 0, '', 0);
Are you updating the movement type and radius? If so ut would be better to change them with an `UPDATE`

2021-07-20 11:05 UTC, Asthalor commented
Changed the SQL query and tested again. 
All good on my machine.

2021-07-20 12:17 UTC, syssneck commented
Checked in-game, they both wander now. Good job!

2021-07-20 13:07 UTC, LukasVolgger commented
Good job @Asthalor and @syssneck !

2021-07-23 13:04 UTC, merged