fix(DB/Quest): Fixed some of the Stave of the Ancients quest
azerothcore/azerothcore-wotlk pull request #7194
Opened 2021-07-31 16:56 UTC by Asthalor

## Changes Proposed:
-  Added scripting, fixed waypoints and added gossip options to the 4 demons

## Issues Addressed:

- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/6966

## SOURCE:

## Tests Performed:

- .go c 14527, 14529, 14531, 14536
- Check if the gossip works.
- Check if they move
- Check if they fight like they should

Small video

https://streamable.com/57dksm

## How to Test the Changes:

1. .go c 14527, 14529, 14531, 14536
2.  Check if the gossip works.
3.  Check if they move
4.  Check if they fight like they should

## Known Issues and TODO List:

- The script npc_stave_of_the_ancientsAI break this quest. Im still need to check it, but im more of a Java guys, so i might need somone to check it for me.

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

2021-08-01 07:16 UTC, LukasVolgger approved these changes

2021-08-01 07:17 UTC, LukasVolgger commented
Because this is a big change i wan't someone else to test this. Thx for this @Asthalor !

2021-08-05 22:13 UTC, Shybuia commented
Test result:
".go creature id 14529" - Patrolling, after dialog not responding waiting to be attacked.


https://user-images.githubusercontent.com/88005118/128427206-11bf95fa-e78c-4d86-999b-d07b9aef5c50.mp4


".go creature id 14531" - Patrolling, after dialog not responding waiting to be attacked.

https://user-images.githubusercontent.com/88005118/128426528-23995998-83ed-4bd2-813b-bf224cc4be8e.mp4

".go creature id 14527" - Patrolling, after dialog not responding waiting to be attacked + pet was not patrolling with her.


https://user-images.githubusercontent.com/88005118/128426762-b20be3f2-5f06-4de1-b7be-c3b3913138bd.mp4


".go creature id 14536" - Patrolling, after dialog not responding waiting to be attacked + no loot, tried multiple times.


https://user-images.githubusercontent.com/88005118/128427333-bcb1bb26-0f9d-4dd9-94e5-ac4b206e7001.mp4

This was my first test of PR, guided by web instructions. I am confident that I did everything well from my side.

2021-08-06 06:15 UTC, Asthalor commented
Thanks for the testing, i will take a look at those things.

2021-08-06 06:23 UTC, syssneck commented
Hey,
I also wanted to test it later today. I will need a bit more time for this one. 
Mhh why is none of them transforming into their demon form?

2021-08-06 06:26 UTC, Asthalor commented
> Hey,
> I also wanted to test it later today. I will need a bit more time for this one.
> Mhh why is none of them transforming into their demon form?

They take like 10 seconds to do the rp talk and transform. On that time they can be attacked, which i think they should not, so they are interrumpted i think.

2021-08-06 06:30 UTC, syssneck commented
> 
> 
> > Hey,
> > I also wanted to test it later today. I will need a bit more time for this one.
> > Mhh why is none of them transforming into their demon form?
> 
> They take like 10 seconds to do the rp talk and transform. On that time they can be attacked, which i think they should not, so they are interrumpted i think.

Ahh, I see. Yeah, they shouldn't be attackable until they have transformed.
Okay, so then I will test it later after the changes? Ty!

2021-08-06 09:02 UTC, Asthalor commented
Another thing ive notice is that the human forms, except Nelson can loot the heads, while on retail there are inconsistences.
For example Simone on human form should not drop it according to this page, but she does on our database,
https://classic.wowhead.com/npc=14527/simone-the-inconspicuous
but Artoriuscan drop it, according to this https://classic.wowhead.com/npc=14531/artorius-the-amiable and so does Franklin
https://classic.wowhead.com/npc=14529/franklin-the-friendly and so does Franklin

On our database only Nelson the Nice (14536) dont have the head added to his loot table, but his demon form https://classic.wowhead.com/npc=14530/solenor-the-slayer has the head.
So should we add the heads to the human forms, even tho its impossible for them to be killed without gm commands?

2021-08-18 14:18 UTC, Asthalor commented
I fixed the errors that showed on the console, and fixed a lot of events that had a lot of errors after merging the script from Trinitycore to us. I will have to test it a bit more deeply, but i think its starting to come close to finish.

2021-08-18 21:50 UTC, Shybuia commented
@Asthalor just let me know when it will be ready and I will test it fully, keep up the good work 👍

2021-08-18 21:55 UTC, Kitzunu requested changes

2021-08-18 21:55 UTC, Kitzunu commented on data/sql/updates/pending_db_world/rev_1627747768504565000.sql
> +UPDATE `creature_template` SET speed_run = 0.33, speed_walk = 0.33 WHERE entry = 14761;
backticks

2021-08-18 21:55 UTC, Kitzunu commented on data/sql/updates/pending_db_world/rev_1627747768504565000.sql
> +UPDATE `creature_template` SET `gossip_menu_id` = '60004' WHERE `entry` = 14531;
Dont use single quotes around integers

2021-08-18 22:12 UTC, Asthalor commented on data/sql/updates/pending_db_world/rev_1627747768504565000.sql
> +UPDATE `creature_template` SET speed_run = 0.33, speed_walk = 0.33 WHERE entry = 14761;
Added

2021-08-18 22:13 UTC, Asthalor commented on data/sql/updates/pending_db_world/rev_1627747768504565000.sql
> +UPDATE `creature_template` SET `gossip_menu_id` = '60004' WHERE `entry` = 14531;
Quotes removed

2021-08-19 08:36 UTC, Asthalor commented
Hello @Shybuia 
I think there are some things to fix here, specially the conditions that let other classes interact with the gossip (still figuring that out).
Still could you test the combats and the special things when the are struck with hunter spells and check that at least that works well? Example Simone when hit with viper sting she gets silenced.
It would help me a lot to fix the scripts if needed. Ive tested them so many times that i am probably missing something obvious.
There is no need for videos if you dont want, with written report is perfect

2021-08-19 10:52 UTC, Shybuia commented
> Hello @Shybuia
> I think there are some things to fix here, specially the conditions that let other classes interact with the gossip (still figuring that out).
> Still could you test the combats and the special things when the are struck with hunter spells and check that at least that works well? Example Simone when hit with viper sting she gets silenced.
> It would help me a lot to fix the scripts if needed. Ive tested them so many times that i am probably missing something obvious.
> There is no need for videos if you dont want, with written report is perfect

No problem, I can try to also fix it with you.

2021-08-19 10:59 UTC, Kitzunu commented on data/sql/updates/pending_db_world/rev_1627747768504565000.sql
> +UPDATE `creature_template` SET `speed_run` = 0.33, `speed_walk` = 0.33 WHERE entry = 14761;
backtick on entry

2021-08-19 11:00 UTC, Kitzunu requested changes

2021-08-19 12:49 UTC, Asthalor commented on data/sql/updates/pending_db_world/rev_1627747768504565000.sql
> +UPDATE `creature_template` SET `speed_run` = 2.6, `Mechanic_Immune_Mask` = 650870623, `MovementType` = 0 WHERE entry = 14503;
Added

2021-08-19 12:49 UTC, Asthalor commented on data/sql/updates/pending_db_world/rev_1627747768504565000.sql
> +UPDATE `creature_template` SET `unit_class`= '1' WHERE `entry` IN (14530,14535,14534);
Removed

2021-08-19 12:49 UTC, Asthalor commented on data/sql/updates/pending_db_world/rev_1627747768504565000.sql
> +UPDATE `creature_template` SET `speed_run` = 0.33, `speed_walk` = 0.33 WHERE entry = 14761;
Added

2021-08-19 20:57 UTC, Asthalor commented
This last commit deleting the c++ script is giving a startup error:
Script named 'npc_stave_of_the_ancients' is assigned in the database, but has no code!

Using SELECT * FROM `creature_template` where `ScriptName` = 'npc_stave_of_the_ancients'; cant find any creature that use the script.

2021-09-29 14:00 UTC, Asthalor commented
Because lately im not having that much time to fix things and because https://github.com/azerothcore/azerothcore-wotlk/pull/7929 has very good feeling im going to close this one for now.
The code is saved here in case we need to check in the future.
Thanks to the testers that helped with this.

2021-09-29 14:00 UTC, closed without merging