[Core/Spells]: Fix glyph of arcane shot not refunding mana.
azerothcore/azerothcore-wotlk pull request #7395
Opened 2021-08-16 19:20 UTC by lineagedr

## Changes Proposed:
-  Add arcane shot spell script.

## Issues Addressed:

- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/6622

## SOURCE:

## Tests Performed:

- Logged in on a hunter applied glyph of arcane shot then shot a dummy with my arcane shot and got 20% of the mana refunded.

## How to Test the Changes:

1. Login on a hunter
2. Apply glyph of arcane shot
3. Use arcane shot on a enemy target
4. Check if you've been refunded 20% of your mana

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

2021-08-16 20:14 UTC, Helias approved these changes

2021-08-17 13:23 UTC, UltraNix approved these changes

2021-08-17 16:06 UTC, Kitzunu requested changes

2021-08-17 16:06 UTC, Kitzunu commented on data/sql/updates/pending_db_world/rev_1629141434760979400.sql
> +INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) values (56841,'spell_hun_glyph_of_arcane_shot');
Always delete before insert.

2021-08-17 16:06 UTC, Kitzunu commented on src/server/scripts/Spells/spell_hunter.cpp
> +            return ValidateSpellInfo({ SPELL_HUNTER_GLYPH_OF_ARCANE_SHOT, SPELL_HUNTER_VICIOUS_VIPER });
Why do you validate SPELL_HUNTER_VICIOUS_VIPER when you do not use it within the script?

2021-08-17 19:17 UTC, Kitzunu commented on data/sql/updates/pending_db_world/rev_1629141434760979400.sql
> +DELETE FROM `spell_script_names` WHERE `spell_id` = 56841;
```suggestion
DELETE FROM `spell_script_names` WHERE `spell_id` = 56841 AND `ScriptName` = 'spell_hun_glyph_of_arcane_shot';
```

2021-08-17 19:18 UTC, Kitzunu approved these changes

2021-08-17 19:18 UTC, lineagedr commented
@Kitzunu good catch

2021-08-18 03:08 UTC, Winfidonarleyan approved these changes

2021-08-20 17:18 UTC, merged