[Core/Item]: Remove item auras after unequipping an item.
azerothcore/azerothcore-wotlk pull request #7398
Opened 2021-08-16 20:35 UTC by lineagedr

## Changes Proposed:
-  Add a function to remove item auras after unequipping an item

## Issues Addressed:

- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/6782

## SOURCE:

## Tests Performed:

- Compiled and Tested using the method below

## How to Test the Changes:

1. Equip a character with Pursuit of Justice
2. Right click on the equipped item
3. Unequip the item

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

2021-08-16 21:51 UTC, Helias commented on src/server/game/Entities/Player/PlayerStorage.cpp
> +            continue;
```suggestion
        if (!spellData.SpellId)
        {
            continue;
        }
```

2021-08-16 21:52 UTC, Helias approved these changes

2021-08-17 05:44 UTC, pklloveyou commented
Tested

2021-08-17 13:24 UTC, UltraNix commented
It's already done via `ApplyItemEquipSpell`

2021-08-17 13:27 UTC, UltraNix requested changes
It's already done via `ApplyItemEquipSpell`.
Right now you are removing all auras which is wrong.

2021-08-17 14:38 UTC, lineagedr commented
> It's already done via `ApplyItemEquipSpell`.
> Right now you are removing all auras which is wrong.

It's not all auras. It's only the ones the player has active.

If it's already handled in ApplyItemEquipSpell

How about:

```c++
for (uint8 i = 0; i < MAX_ITEM_PROTO_SPELLS; ++i)
{
    _Spell const&    spellData = pItem->GetTemplate()->Spells[i];
    SpellInfo const* spellInfo = sSpellMgr->GetSpellInfo(spellData.SpellId);
    if (spellInfo)
    {
        ApplyEquipSpell(spellInfo, pItem, false, false);
    }
}
```

2021-08-17 14:41 UTC, UltraNix commented
Yes. I meant - all auras applied by items and still active on players. As you can see in `ApplyItemEquipSpell` not all these auras should be removed on item unequip.

2021-08-17 17:25 UTC, UltraNix commented
Tell me: `ApplyEquipSpell` does not handle that case?

2021-08-17 18:55 UTC, lineagedr commented
@UltraNix Was you not including the form_change intended? https://github.com/azerothcore/azerothcore-wotlk/commit/69c214bec59e3fe636e15abc680adb793501dbcf#diff-baadebd8cd1117ca48225f316a5ab3fd5fd55b20963394d302341147183db067L8621

2021-08-17 18:57 UTC, lineagedr commented
https://user-images.githubusercontent.com/12139798/129784632-f08eee2e-a374-4fce-9664-9a9e24769154.mp4

2021-08-17 19:29 UTC, UltraNix commented
@lineagedr Yes - it was intended.

2021-08-18 18:51 UTC, UltraNix approved these changes

2021-08-18 19:59 UTC, Helias commented
is it to be merged for you?
@UltraNix @lineagedr

2021-08-18 20:05 UTC, lineagedr commented
@Helias Yes.

2021-08-20 18:17 UTC, merged