feat(Core/Commands): Gear
azerothcore/azerothcore-wotlk pull request #7717
Opened 2021-09-04 06:23 UTC by IntelligentQuantum

@BarbzYHOOL
OLD PR: https://github.com/IntelligentQuantum/azerothcore-wotlk/commit/fdb85ebf2d571dfbee9531449c0f8e569be17ac8

## Issues Addressed:

- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/4105

## Tests Performed:

- Tested in game
- Arch Linux

## How to Test the Changes:

1. .gear repair
2. .gear stats (PlayerSave.Stats.MinLevel = 0) Shows only average item level
3. If you want to see player stats enable this PlayerSave.Stats.MinLevel = 1

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

2021-09-04 13:21 UTC, Helias approved these changes

2021-09-04 23:42 UTC, Kitzunu commented on src/server/scripts/Commands/cs_misc.cpp
> +        handler->PSendSysMessage("Current equipment average item level: |cff00ffff%u|r", (int)player->GetAverageItemLevel());
```suggestion
        handler->PSendSysMessage("Current equipment average item level: |cff00ffff%u|r", (int32)player->GetAverageItemLevel());
```

2021-09-04 23:44 UTC, Kitzunu requested changes

2021-09-04 23:44 UTC, Kitzunu commented on src/server/scripts/Commands/cs_misc.cpp
> +            return false;
brackets

2021-09-08 11:08 UTC, FrancescoBorzi commented
@IntelligentQuantum I guess no need for further testing as you have already tested it in game and it doesn't seem big change. What do you think?

2021-09-08 11:25 UTC, IntelligentQuantum commented
@FrancescoBorzi We can merge it, if you have not problem with .gear stats because player can use this command

2021-09-08 18:15 UTC, Kitzunu commented
Please update the wiki as well

2021-09-11 22:27 UTC, FrancescoBorzi approved these changes

2021-09-12 10:19 UTC, merged