Dalaran Sewers Knockback
azerothcore/azerothcore-wotlk pull request #7739
Opened 2021-09-06 08:04 UTC by IntelligentQuantum

## Changes Proposed:
-  
-  

## Issues Addressed:

- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/7642
- Closes https://github.com/chromiecraft/chromiecraft/issues/927

## Tests Performed:

- Tested in game
- Arch Linux

## How to Test the Changes:

https://user-images.githubusercontent.com/14080516/131362193-2ce8de1e-9b0b-4f02-99ca-36acdd665301.png

1.queue into dalaran arena and stay in the position I did

2021-09-06 16:54 UTC, Helias approved these changes

2021-09-08 12:03 UTC, FrancescoBorzi approved these changes

2021-09-08 12:04 UTC, FrancescoBorzi commented
@IntelligentQuantum as you tested this in-game already, and it's a small change, I don't think further tests are needed. Correct me if you disagree.

2021-09-08 18:14 UTC, Kitzunu requested changes

2021-09-08 18:14 UTC, Kitzunu commented on data/sql/updates/pending_db_world/rev_1630914827730930867.sql
> +UPDATE `spell_dbc` SET `RangeIndex` = '5' WHERE `ID` = 61698;
```suggestion
UPDATE `spell_dbc` SET `RangeIndex` = 5 WHERE `ID` = 61698;
```

2021-09-10 13:04 UTC, merged