fix(Core/Spell): Warlock Banish
azerothcore/azerothcore-wotlk pull request #7832
Opened 2021-09-12 07:04 UTC by IntelligentQuantum

## Changes Proposed:
-  
-  

## Issues Addressed:

- Closes https://github.com/chromiecraft/chromiecraft/issues/1702
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/7829

## SOURCE:

## Tests Performed:

-  Tested
- Archlinux

## How to Test the Changes:

1. Target a demon enemey NPC
2. Cast Banish
3. Recast Banish
4. Casting banish on a banished target will cancel the spell

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

2021-09-12 09:56 UTC, Kitzunu requested changes

2021-09-12 09:56 UTC, Kitzunu commented on src/server/scripts/Spells/spell_warlock.cpp
> +                    banishAura->Remove();
brackets

2021-09-12 09:56 UTC, Kitzunu commented on src/server/scripts/Spells/spell_warlock.cpp
> +                    banishAura->Remove();
Also the * should be connected to Aura

2021-09-12 23:12 UTC, FrancescoBorzi approved these changes

2021-09-14 23:50 UTC, Kitzunu approved these changes

2021-09-15 14:30 UTC, UltraNix approved these changes

2021-09-16 15:10 UTC, merged