fix: solved issue 6585
azerothcore/azerothcore-wotlk pull request #7873
Opened 2021-09-14 10:50 UTC by Cold-Martijn

https://github.com/azerothcore/azerothcore-wotlk/issues/6585

## Changes Proposed:
-  Set wanderdistance for specific GUIDs
-  

## Issues Addressed:

- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/6585

## SOURCE:

## Tests Performed:

- 
- 

## How to Test the Changes:

1.
2.
3.

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

2021-09-14 10:56 UTC, Kitzunu requested changes

2021-09-14 10:56 UTC, Kitzunu commented on data/sql/updates/pending_db_world/rev_1631616272860535120.sql
> +UPDATE creature SET wander_distance = 5 WHERE guid = 56150;
Add backticks and make this one query please https://www.azerothcore.org/wiki/sql-standards#compact-queries

2021-09-14 11:04 UTC, Kitzunu commented on data/sql/updates/pending_db_world/rev_1631616272860535120.sql
> +UPDATE creature SET wander_distance = 5 WHERE guid = 56150;
Also when working in the creature table it is preferred if you update guid AND id

2021-09-14 11:18 UTC, Kitzunu approved these changes

2021-09-14 12:09 UTC, Cold-Martijn commented
Fixed an extra ; between GUID (..., , .... , ...); AND ID, sorry :)

2021-09-14 12:12 UTC, Kitzunu approved these changes

2021-09-15 22:13 UTC, FrancescoBorzi commented
@Cold-Martijn welcome to AzerothCore and thanks for your contribution!

@Kitzunu don't forget to apply the workflow labels ;)

2021-09-19 22:47 UTC, merged