fix(DB/Quest):Corruption of Earth and Seed repeatable after faction c…
azerothcore/azerothcore-wotlk pull request #7970
Opened 2021-09-18 19:43 UTC by baranzadeoglu

…hange

Puts quest ids 7064 and 7065 into same exclusive group as suggested by the relevant documentation.
Fixes #7273
Note that the reputation issue in #7273 is a replication of a visual bug on Keira3 and should be ignored.

## Changes Proposed:
-  
Put quest ids 7064 and 7065 into the same exclusive group 7064.
-  

## Issues Addressed:

- Closes  #7273  https://github.com/chromiecraft/chromiecraft/issues/1372

## SOURCE:

## Tests Performed:

- 
- 

## How to Test the Changes:

1. complete either quest
2.change faction
3.try to complete the other

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

2021-09-19 16:09 UTC, Helias commented on data/sql/updates/pending_db_world/rev_1631992050760579041.sql
> +UPDATE quest_template_addon SET ExclusiveGroup = 7064 WHERE (ID = 7065);
```suggestion
UPDATE quest_template_addon SET ExclusiveGroup = 7064 WHERE (ID IN (7064,7065));
```

2021-09-19 17:57 UTC, Kitzunu requested changes

2021-09-19 17:57 UTC, Kitzunu commented on data/sql/updates/pending_db_world/rev_1631992050760579041.sql
> +UPDATE quest_template_addon SET ExclusiveGroup = 7064 WHERE (ID IN (7064,7065));
backticks

2021-09-19 20:22 UTC, Helias approved these changes

2021-09-28 15:28 UTC, Kitzunu requested changes

2021-09-28 15:28 UTC, Kitzunu commented on data/sql/updates/pending_db_world/rev_1631992050760579041.sql
> +UPDATE 'quest_template_addon' SET 'ExclusiveGroup' = '7064' WHERE ('ID' IN (7064,7065));
```suggestion
UPDATE `quest_template_addon` SET `ExclusiveGroup` = 7064 WHERE (`ID` IN (7064,7065));
```
Use backticks \` \` and dont use single quotes around non string values

2021-09-29 20:29 UTC, FrancescoBorzi commented
![image](https://user-images.githubusercontent.com/75517/135343678-d0b44dec-dc7e-470d-b044-f1fe5fc0570a.png)

@baranzadeoglu can you please specify what tests have you made with your code

2021-09-30 07:00 UTC, baranzadeoglu commented
> @baranzadeoglu can you please specify what tests have you made with your code

none.

2021-10-06 11:45 UTC, stoudtlr commented
Test results:
1. Completed quest id 7065 as alliance and received 500 rep
2. Faction change and relog
3. completed quest id 7064 as horde and received another 500 rep

![image](https://user-images.githubusercontent.com/36058236/136195646-0f8e0613-e9ef-4fa3-8fd1-82d756170a83.png)

2021-10-06 11:48 UTC, baranzadeoglu commented
> Test results:
> 
>     1. Completed quest id 7065 as alliance and received 500 rep
> 
>     2. Faction change and relog
> 
>     3. completed quest id 7064 as horde and received another 500 rep
This is strange. I am not an expert or anything with exclusive groups but from the Wiki,

>    if ExclusiveGroup > 0
>
>Allows to define a group of quests of which only one may be chosen and completed. E.g. if from quests 1200, 1201 and 1202 >only one should be allowed to be chosen, insert 1200 into ExclusiveGroup of all 3 quests.

2021-11-24 10:57 UTC, FrancescoBorzi commented
what's the status of this?

2021-11-24 11:17 UTC, baranzadeoglu commented
> what's the status of this?

this fix does not seem to work although it is in line with the wiki. To best of my understanding there is something above me going on.

2022-01-19 14:14 UTC, acidmanifesto commented
What is the status of this PR? is it abandoned now?

2022-01-19 14:35 UTC, baranzadeoglu commented
> What is the status of this PR? is it abandoned now?

well, the documentation for the command is incorrect. I am waiting for someone to figure out what exactly is wrong with the documentation.

2022-04-15 11:34 UTC, Kitzunu commented
This is wrong anyways. https://github.com/azerothcore/azerothcore-wotlk/pull/11403 is correct fix

2022-04-15 11:34 UTC, closed without merging