Translation and modifications in extractor.bat
azerothcore/azerothcore-wotlk pull request #7992
Opened 2021-09-19 20:46 UTC by pangolp

## Changes Proposed:
-  Create the mmaps and vmaps directories if they do not exist, as well as add some messages to tell the user to press a key to continue, in the case of vmaps, and mmaps
-  The extractor file is created in Spanish.

## Issues Addressed:

- Closes 

## SOURCE:

## Tests Performed:

- Windows 10

## How to Test the Changes:

1. Move the extractor to where the game client is located, along with the executables, and use it.
2. You can use either the original extractor or the Spanish extractor, both work in the same way.
3. If you did not create the mmaps and vmaps folders before running the script, the script will create them for you.

## Known Issues and TODO List:

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

2021-09-19 21:06 UTC, Kitzunu requested changes

2021-09-19 21:06 UTC, Kitzunu commented on apps/extractor/extractor.bat
> +ECHO Press a key to continue.
You dont need this. PAUSE will prompt this message by itself

2021-09-19 21:06 UTC, Kitzunu commented on apps/extractor/extractor.bat
> +if not exist vmaps md vmaps
This does nothing.

use something like
```batch
if exist maps\ (
    echo folder found.
) else (
    echo creating folder "maps".
    mkdir "maps"
)
```

2021-09-19 21:06 UTC, Kitzunu commented on apps/extractor/extractor.bat
> +if not exist mmaps md mmaps
This does nothing.

use something like
```batch
if exist maps\ (
    echo folder found.
) else (
    echo creating folder "maps".
    mkdir "maps"
)
```

2021-09-19 21:06 UTC, Kitzunu commented on apps/extractor/extractor.bat
> +if not exist mmaps md mmaps
This does nothing.

use something like
```batch
if exist maps\ (
    echo folder found.
) else (
    echo creating folder "maps".
    mkdir "maps"
)
```

2021-09-19 21:06 UTC, Kitzunu commented on apps/extractor/extractor.bat
> +cls
dont run cls. If the extractor fails, we want to know why

2021-09-19 21:06 UTC, Kitzunu commented on apps/extractor/extractor.bat
> +cls
dont run cls. If the extractor fails, we want to know why

2021-09-19 21:06 UTC, Kitzunu commented on apps/extractor/extractor.bat
> +ECHO Press a key to continue.
You dont need this. PAUSE will prompt this message by itself

2021-09-19 21:34 UTC, Helias commented
???

2021-09-19 21:37 UTC, pangolp commented
I got the wrong PR hahaha

2021-09-19 21:48 UTC, pangolp commented
Ready, I applied all the changes, although I did not test them. I did test them the old way and it works without problems. With these new changes, I really don't know if it will work. I ask you to tell me if it works @Kitzunu

2021-09-19 21:49 UTC, Kitzunu commented
if the point is to create the folders, then yes this will work.

2021-09-19 21:50 UTC, pangolp commented
Yes, the goal is to create the folders, in case they don't exist, since in the wiki, it mentions that they should be created, so basically the idea is to create them, in case people don't do it.

2021-09-19 21:51 UTC, Kitzunu commented
then it works =)

2021-09-27 07:11 UTC, pangolp commented
If you believe that all requested changes have been corrected, please change your change request, so that others can approve it. Thank you. If not, let me know what other changes I need to make. @Kitzunu

2021-09-28 15:27 UTC, Kitzunu approved these changes

2021-09-28 22:03 UTC, pangolp commented
@Kitzunu thanks.

2021-09-29 20:40 UTC, FrancescoBorzi commented
is this ready to be merged? if yes apply [To Be Merged] please...

2021-09-30 21:54 UTC, merged