Fix Item Fresh Brewfest Hops
azerothcore/azerothcore-wotlk pull request #8010
Opened 2021-09-21 11:42 UTC by IntelligentQuantum

## Changes Proposed:
-  
-  

## Issues Addressed:

- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/7997
- Closes https://github.com/chromiecraft/chromiecraft/issues/1800

## SOURCE:

## Tests Performed:

- Tested, Everything works fine except i don't know how can i get speed mount on HandleAuraMounted function
- Arch Linux

## How to Test the Changes:

1. Buy any of brewfest transformation items
2. Mount up
3. Your mount transform to brewfest kodo

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

2021-09-21 16:09 UTC, Helias commented on src/server/game/Spells/Auras/SpellAuraEffects.cpp
> +                creatureEntry = 27707;
we should make an enum with all constants of this and remove these magic numbers
like
```c++
enum brewfestEntries = {
  GREAT_BREWFEST_KODO = 27707,
  npc_name_2 = 30507,
  FESTIVE_BREWFEST_MOUNT = 66052,
  ... and so on ...
}
```

2021-09-21 16:09 UTC, Helias requested changes
replace the numbers with constant

2021-09-27 21:52 UTC, Helias commented on src/server/game/Spells/Auras/SpellAuraEffects.cpp
> +                    case 66052: // Festive Brewfest Mount
you can convert this into a constant and add in the enum below

2021-09-28 15:37 UTC, Kitzunu commented on src/server/game/Spells/Auras/SpellAuraEffects.cpp
> +                                creatureEntry = target->GetAuraEffectsByType(SPELL_AURA_MOUNTED).front()->GetMiscValue();
brackets

2021-11-03 22:31 UTC, Nefertumm approved these changes
Related to get mount speed, you can check if the player has X riding skill level (if I understand it properly hehe)

2021-11-03 22:36 UTC, Nefertumm approved these changes
As for the mount speed, you can check riding skill (if I understand you properly hehe)

2021-11-04 19:56 UTC, Helias approved these changes

2021-11-20 11:18 UTC, Nefertumm commented
Tested 
![image](https://user-images.githubusercontent.com/19627365/142724376-2a3f9bde-e3a9-4f08-918e-5b7f92fec44c.png)

2021-11-21 13:50 UTC, merged