Fix Golorn Frostbeard and Curator Thorius
azerothcore/azerothcore-wotlk pull request #8122
Opened 2021-09-27 20:16 UTC by banehammer

## Changes Proposed:
-  
-  

## Issues Addressed:

- Closes 

## SOURCE:

## Tests Performed:

- 
- 

## How to Test the Changes:

1.
2.
3.

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

2021-09-27 21:53 UTC, syssneck commented on data/sql/updates/pending_db_world/rev_1632773438019686726.sql
> +(2190, 6, -5640.07, -497.906, 396.669, 0, 0, 0, 0, 100, 0);
```INSERT INTO `waypoint_data` (...) Values``` missing here

2021-09-28 06:22 UTC, banehammer commented on data/sql/updates/pending_db_world/rev_1632773438019686726.sql
> +(2190, 6, -5640.07, -497.906, 396.669, 0, 0, 0, 0, 100, 0);
Will edit when back home

2021-09-28 15:35 UTC, Kitzunu requested changes

2021-09-28 15:35 UTC, Kitzunu commented on data/sql/updates/pending_db_world/rev_1632773438019686726.sql
> +INSERT INTO `waypoint_scripts` (`id`, `delay`, `command`, `datalong`, `datalong2`, `dataint`, `x`, `y`, `z`, `o`, `guid`) VALUES
always delete before insert.

2021-09-28 15:35 UTC, Kitzunu commented
Please do not remove the PR template. Edit and fill it in please.

2021-09-29 17:03 UTC, banehammer commented
Resolved the errors.

2021-09-30 15:13 UTC, Asthalor commented
Tested

Curator Thorius seems to have a good route. I dont know the blizzlike one, but he uses emotes and seems like a normal route. All good.

![image](https://user-images.githubusercontent.com/87535580/135481760-9723a93b-2aac-4ae8-96f3-c809c7bbc63e.png)

Golorn Frostbeard seems like he is very shy, because it is not facing us and is moving between the 2 boxes behind him. 

![image](https://user-images.githubusercontent.com/87535580/135482006-1884c6f5-e484-4839-895a-4a852127a8e1.png)

![image](https://user-images.githubusercontent.com/87535580/135482091-7a831466-4b95-48d7-8d64-36cfba9ab127.png)

Without visual patches(if its important)

![image](https://user-images.githubusercontent.com/87535580/135482349-44fd59c0-a222-48e0-b806-6cef66a33f4e.png)

Wowhead image is looking at us. Maybe he should be waiting for some time looking at us in between routes?

![image](https://user-images.githubusercontent.com/87535580/135482657-be1b743d-c74a-4133-97b7-d2550c137bf8.png)

2021-09-30 17:52 UTC, banehammer commented
Hmmm Golorn that weirdo. He is supposed to stop being shy with this commit. Wait...

2021-09-30 18:01 UTC, banehammer commented
Okay updated the orientation.

2021-10-02 09:50 UTC, Asthalor commented
Ok. Now is looking at us.

![image](https://user-images.githubusercontent.com/87535580/135711298-5dc1c7f7-3ef7-43fe-a721-f6730fbc0a2f.png)

Seems good to me.

2021-10-04 14:00 UTC, closed without merging