Fixed hunter pets not being revived inside battlegrounds.
azerothcore/azerothcore-wotlk pull request #8132
Opened 2021-09-28 14:02 UTC by ChrisCGalbraith

Fixed hunter pets not having max health when player is resurrected in battlegrounds.

Signed-off-by: ChrisCGalbraith <chriscgalbraith@gmai.com>

## Changes Proposed:
-  New summon of the players pet occurs when revived by the battleground spirit healer

## Issues Addressed:

- Closes https://github.com/chromiecraft/chromiecraft/issues/1193

## SOURCE:

## Tests Performed:

- Performed tests on hunters and warlocks with pets that are dead at the time of resurrection and pets that have a portion of their health missing.
- Built on Windows 10, no errors.

## How to Test the Changes:

1. .debug bg on
2. Enter a battleground and wait for it to begin
3. .die your pet and then yourself
4.  Observe that pet is revived at full health when the player is.
5.  Repeat the above steps but instead of killing your pet, .damage him

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

2021-09-28 15:33 UTC, Kitzunu requested changes

2021-09-28 15:33 UTC, Kitzunu commented on src/server/game/Battlegrounds/Battleground.cpp
> +            Pet*  pet = player->GetPet();
remove double space and add a newline between this and the if statement above.

2021-09-28 15:42 UTC, Nyeriah commented
This is wrong. Players use spell 6962 to summon pets, and it's scripted here: https://github.com/azerothcore/azerothcore-wotlk/blob/master/src/server/scripts/Spells/spell_generic.cpp#L2234

Right solution would be to find why those lines are failing: https://github.com/azerothcore/azerothcore-wotlk/blob/master/src/server/scripts/Spells/spell_generic.cpp#L2251-L2252

But it seems to me Trinity has it working and we just need a port: https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/scripts/Spells/spell_generic.cpp#L2885-L2914

2021-09-28 17:04 UTC, Nyeriah commented
> > This is wrong. Players use spell 6962 to summon pets, and it's scripted here: https://github.com/azerothcore/azerothcore-wotlk/blob/master/src/server/scripts/Spells/spell_generic.cpp#L2234
> > Right solution would be to find why those lines are failing: https://github.com/azerothcore/azerothcore-wotlk/blob/master/src/server/scripts/Spells/spell_generic.cpp#L2251-L2252
> > But it seems to me Trinity has it working and we just need a port: https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/scripts/Spells/spell_generic.cpp#L2885-L2914
> 
> Cheers for pointing this out - I noticed that the hunter receives a spell failed as the target is dead error when casting 6962. I'll investigate this some more. While this pull request does solve the issue, shall I close this PR in favour of developing a better solution in line with your comment?

You don't need to close it, you can just edit the files and push to this branch, it'll automatically update the PR.

The source I linked there from the TrinityCore repository is a good hint. They're doing a lot of things to pets we currently don't (like reseting health etc.)

2021-09-30 17:24 UTC, bgcfb commented
The pr not fix Wintergrasp
just add code to game\Battlefield\Battlefield.cpp L743

2021-09-30 17:32 UTC, Nyeriah commented
@bgcfb This is a work-in-progress PR. Indeed, it won't affect Wintergrasp. Thanks for checking it out, but the author is working on updates that will eventually address that issue. Please test it again once this PR is updated.

2021-09-30 19:50 UTC, closed without merging

2021-10-10 02:45 UTC, slicplaya commented
This issue has not been fixed.