fix(Core\Scripts):Jiklik's bats from phase 2 now won't engage players…
azerothcore/azerothcore-wotlk pull request #8142
Opened 2021-09-28 21:13 UTC by Ragelezz

… directly and will fly

## Changes Proposed:
-  
-  

## Issues Addressed:

- Closes https://github.com/azerothcore/azerothcore-wotlk/pull/8141

## SOURCE:

## Tests Performed:

- Engage Jiklik and change to phase 2 (50% of her total health) and see that the bats spawned during this phase will come down to players and meele them
- 

## How to Test the Changes:

1. Engage Jiklik and change to phase 2 (50% of her total health) and see that now the bats spawned during this phase will keep flying and throw missiles accordingly.
2.
3.

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

2021-09-29 20:39 UTC, FrancescoBorzi commented
build failing

2021-09-29 20:43 UTC, Ragelezz commented
can't figure from what since its configure os which fails, any clues? i know something related to this https://github.com/azerothcore/azerothcore-wotlk/issues/8083 but its beyond me.

2021-09-30 13:31 UTC, Nyeriah commented
@Ragelezz I ran the checks again and they passed this time, I don't think that failure was related to your changes, looks like some internal stuff that didn't happen again.

2021-10-01 10:52 UTC, Kitzunu requested changes

2021-10-01 10:52 UTC, Kitzunu commented on data/sql/updates/pending_db_world/rev_1632863354170415400.sql
> +UPDATE `creature_template` SET `InhabitType`='4' WHERE  `entry`=14965;
dont use singlequotes on non-string values

2021-10-01 10:52 UTC, Kitzunu commented on data/sql/updates/pending_db_world/rev_1632863354170415400.sql
> +UPDATE `creature_template` SET `ScriptName`='npc_batrider' WHERE entry=14965;
please add backticks to `entry`

2021-10-01 10:52 UTC, Kitzunu commented on src/server/scripts/EasternKingdoms/ZulGurub/boss_jeklik.cpp
> +                        targets.resize(1);
please add brackets

2021-10-01 10:52 UTC, Kitzunu commented on src/server/scripts/EasternKingdoms/ZulGurub/boss_jeklik.cpp
> +                for (std::list<Unit*>::iterator itr = targets.begin(); itr != targets.end(); ++itr) me->CastSpell((*itr), SPELL_BOMB);
```suggestion
                for (std::list<Unit*>::iterator itr = targets.begin(); itr != targets.end(); ++itr)
                {
                    me->CastSpell((*itr), SPELL_BOMB);
                }

```

2021-10-30 16:33 UTC, Nyeriah commented on data/sql/updates/pending_db_world/rev_1632863354170415400.sql
> +
```suggestion
```

2021-11-02 16:29 UTC, Ragelezz commented
@azerothcore/testers

2021-11-06 20:10 UTC, Ragelezz commented
This was already tested by me when I first made this PR, shall I wait for another test from somebody else or can we merge it ?

2021-11-16 13:42 UTC, merged