fix hodir and leviathan
azerothcore/azerothcore-wotlk pull request #8169
Opened 2021-09-30 11:04 UTC by bgcfb

## Changes Proposed:
-  fix hodir cache and achievement
-  fix leviathan status

## Issues Addressed:

- Closes #8168

## SOURCE:

## Tests Performed:

- 
- 

## How to Test the Changes:

1.
2.
3.

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

2021-09-30 11:05 UTC, bgcfb commented
It's my first time to make pr,pls check

2021-09-30 11:15 UTC, Nyeriah commented
Please include what tests have you performed and how users can test the changes you have made in the pull request description.

2021-09-30 11:20 UTC, bgcfb commented
> Please include what tests have you performed and how users can test the changes you have made in the pull request description.

It's fixed a month ago and I'am running now with no error

2021-10-02 19:18 UTC, FrancescoBorzi commented on data/sql/updates/pending_db_world/rev_1633001158089619377.sql.sql
> +(33686, 0, 16, 0, 61, 0, 100, 0, 10477, 0, 0, 0, 0, 45, 1, 1, 0, 0, 0, 0, 10, 136253, 33579, 0, 0, 0, 0, 0, 0, 'Lore Keeper of Norgannon - On Gossip Option 0 Selected - Set Data 1 1');
Hello, thanks for your contribution! You can combine the 2 inserts in one. See https://www.azerothcore.org/wiki/sql-standards

2021-12-08 14:36 UTC, acidmanifesto commented
@bgcfb what is the current status of this pr?

2021-12-08 15:27 UTC, bgcfb commented
> @bgcfb what is the current status of this pr?

Sql check fail

2021-12-14 00:41 UTC, claudiodfc commented on data/sql/updates/pending_db_world/rev_1633001158089619377.sql
> +
remove this line for SQL checks

2021-12-14 13:07 UTC, claudiodfc commented
https://pastebin.com/TV0SrhE5 take a look into the crash if you will

2021-12-14 16:13 UTC, bgcfb commented
> https://pastebin.com/TV0SrhE5 take a look into the crash if you will

New PR break ulduar and it is not related to my fix
I run this fix for month with no error

2021-12-20 16:39 UTC, claudiodfc requested changes

2021-12-20 16:39 UTC, claudiodfc commented on src/server/scripts/Northrend/Ulduar/Ulduar/instance_ulduar.cpp
> +                    SpawnHodirChests(m_difficulty == 0 ? 1 : 0);
change to
``` c++
SpawnHodirChests(m_difficulty);
```

2022-01-19 14:15 UTC, acidmanifesto commented
What is the status of this PR? Is it abandoned now?

2022-02-05 16:43 UTC, closed without merging