feat(Core/Modules): Preparation to implement progression-system module.
azerothcore/azerothcore-wotlk pull request #8837
Opened 2021-10-30 09:56 UTC by UltraNix

## How to Test the Changes:

Nothing to test.

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

2021-10-31 09:05 UTC, FrancescoBorzi commented
2 failures:

> src/server/scripts/CMakeLists.txt:356:    
Remove whitespace at the end of the lines above

> PlayerCommand.h:21:23: fatal error: unknown type name 'ChatHandler'
    static bool Learn(ChatHandler* handler, Player* targetPlayer, uint32 spell, char const* all);

meanwhile @Winfidonarleyan and @Yehonal please review this PR

2021-11-01 15:34 UTC, UltraNix commented
I don't know why build fails. 
```PlayerCommand.h:21:23: fatal error: unknown type name 'ChatHandler'
static bool Learn(ChatHandler* handler, Player* targetPlayer, uint32 spell, char const* all);```
It's not related to thisPR at all.

```src/server/scripts/CMakeLists.txt:356:
Remove whitespace at the end of the lines above```
I don;t see any whitespace there.

2021-11-03 04:25 UTC, Winfidonarleyan commented on src/server/database/Updater/UpdateFetcher.cpp
> +                          "Cleanup is disabled! There were  " SZFMTD " dirty files applied to your database, "
```suggestion
                          "Cleanup is disabled! There were " SZFMTD " dirty files applied to your database, "
```

2021-11-03 04:27 UTC, Winfidonarleyan approved these changes

2021-11-03 04:27 UTC, Winfidonarleyan commented
Looks good at first glance

2021-11-03 21:30 UTC, Nyeriah commented
@Winfidonarleyan do you have any clues about why would the module build be failing? It's complaining about a file not touched by this PR, I don't understand it. We really need this PR merged as soon as possible :)

2021-11-04 14:44 UTC, Winfidonarleyan commented
- [ ] Wait merge #8947

2021-11-04 21:40 UTC, Nyeriah commented
Ultranix, please try now

2021-11-05 10:37 UTC, Yehonal requested changes

2021-11-05 10:37 UTC, Yehonal commented on src/server/game/Scripting/ScriptMgr.cpp
> +void ScriptMgr::AfterDatabasesLoaded(uint32 updateFlags)
Correct naming is: ```On<When><Action>``` 

Hence: OnAfterDatabasesLoaded

2021-11-06 08:32 UTC, FrancescoBorzi commented
I did some research [here](https://github.com/azerothcore/azerothcore-wotlk/pull/8992) and I found out that it's the [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter) that is causing the issue

cc @UltraNix @sanctum32 @r-o-b-o-t-o  @Nyeriah

2021-11-06 10:10 UTC, UltraNix commented
Resolved by https://github.com/azerothcore/mod-chat-transmitter/pull/2/

2021-11-06 13:06 UTC, merged