Allows Value 3 for react SAI WP Start
azerothcore/azerothcore-wotlk pull request #8926
Opened 2021-11-03 14:23 UTC by acidmanifesto

Refactored from tc
This is a refactor from TC to deal with react state 3 invalid failure\error message dealing with SMART_ACTION_WP_START (19). This is in support of PR https://github.com/azerothcore/azerothcore-wotlk/pull/8923

## Changes Proposed:
-  Refactor how to handle the react value of 3 from tc.

## Issues Addressed:
https://github.com/azerothcore/azerothcore-wotlk/runs/4092916912?check_suite_focus=true

## SOURCE:
https://github.com/TrinityCore/TrinityCore/blob/3e6a4e0b4484b241a103a912ebc180b163fe815c/src/server/game/AI/SmartScripts/SmartScriptMgr.cpp#L1796

## Tests Performed:
Builds and compiles locally with no issues.

## How to Test the Changes:
Need Compile Testing or see if errors are reported on world screen.

## Known Issues and TODO List:

- [ ] Test PR https://github.com/azerothcore/azerothcore-wotlk/pull/8923 with this PR
- [ ] Is error being reported in world console fix?
- [ ] Is compile test failure fix?

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

2021-11-03 16:12 UTC, malcrom commented
Yes it does exceed yours.

2021-11-03 16:14 UTC, acidmanifesto commented
> Yes it does exceed yours.

thats why the box is checked.
![image](https://user-images.githubusercontent.com/16887899/140099395-b70260b9-56c7-48aa-beb7-001a7a4b705d.png)

2021-11-03 21:04 UTC, acidmanifesto commented
Need review

2021-11-03 21:47 UTC, Nefertumm requested changes
Seems ok, just match the codestyle

2021-11-03 21:47 UTC, Nefertumm commented on src/server/game/AI/SmartScripts/SmartScript.cpp
> +                    me->SetReactState((ReactStates)e.action.wpStart.reactState);
add brackets here

2021-11-03 21:47 UTC, Nefertumm commented on data/sql/updates/db_world/rev_1635936745734477829.sql
> +(8115, 6, -4375.68, 269.717, 25.4947, 'Witch Doctor Uzer''i');
add a new line

2021-11-03 21:49 UTC, Nefertumm commented
Just for references, ported from https://github.com/TrinityCore/TrinityCore/commit/60379cf2c15d9cee1414fbaec2b217b89b8dc67e

2021-11-03 23:01 UTC, acidmanifesto commented on src/server/game/AI/SmartScripts/SmartScript.cpp
> +                    me->SetReactState((ReactStates)e.action.wpStart.reactState);
done

2021-11-03 23:01 UTC, acidmanifesto commented on data/sql/updates/db_world/rev_1635936745734477829.sql
> +(8115, 6, -4375.68, 269.717, 25.4947, 'Witch Doctor Uzer''i');
done

2021-11-06 12:34 UTC, acidmanifesto commented
## How to Test the Changes:
Need Compile Testing or see if errors are reported on world screen.
then test quest https://classic.wowhead.com/quest=3129/weapons-of-spirit to see if the role play with the Witch Doctor Uzer'i  npc occurs.

2021-11-06 22:52 UTC, Nefertumm approved these changes

2021-11-06 23:21 UTC, merged