Fix dropchance and conditions of [A Letter to Yvette]
azerothcore/azerothcore-wotlk pull request #9219
Opened 2021-11-16 21:26 UTC by schell244

## Changes Proposed:
-  drop chances according to https://classic.wowhead.com/item=2839
- add drop chance to some additional npc's 
-  add missing condition: Horde only drop

Condition Horde only is a "custom fix", on classic the item seems to drop for Alliance player as well, but they cannot start the quest.
https://classic.wowhead.com/item=2839/a-letter-to-yvette#comments
_I actually found this as my Night Elf druid (33 at the time) west of Brill. Was kind of funny, wish I was eligible for the quest...told me I wasn't the correct race._

## Issues Addressed:
-  

## SOURCE:
https://classic.wowhead.com/item=2839

## Tests Performed:
-  insert sql works, tested ingame with both factions

## How to Test the Changes:
1. (try) to farm item [A Letter to Yvette] with both Horde and Alliance characters
2. it should only drop for Horde characters

## Known Issues and TODO List:
- 

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

2021-11-16 21:29 UTC, Kitzunu commented
While I appreciate your contribution we got two issues.

1. We do not use Replace Into. Use either DELETE/INSERT or UPDATE.
2. Do not add custom fixes, as this also happened on retail 3.3.5a as far as I can tell, it should be that way here too.

2021-11-16 21:40 UTC, schell244 commented
Thanks for your feedback, I've updated the PR accordingly.

2021-11-17 03:06 UTC, Nefertumm requested changes

2021-11-17 03:06 UTC, Nefertumm commented on data/sql/updates/pending_db_world/rev_1637094877418094500.sql
> +(1532,2839,0,0.01,0,1,0,1,1,'Wandering Spirit - A Letter to Yvette');
Merge these lines into 1

2021-11-17 08:59 UTC, Nefertumm approved these changes

2021-11-17 08:59 UTC, Nefertumm commented on data/sql/updates/pending_db_world/rev_1637094877418094500.sql
> +(1532,2839,0,0.01,0,1,0,1,1,'Wandering Spirit - A Letter to Yvette');
add a new line at the end please.

2021-11-19 15:46 UTC, Kitzunu requested changes
always delete before insert

2021-11-21 17:31 UTC, claudiodfc commented
### Test result: ✔
- Low chance drop for all NPCs.
- Killed 300 `Moonrage Darkrunner` and none dropped the item.
- Killed 60 `Darkeye Bonecasters` and dropped the quest item.
- Drops for Alliance but they can't start the quest `That quest isn't available for your race`.

2021-11-21 17:32 UTC, claudiodfc approved these changes

2021-11-21 21:59 UTC, Winfidonarleyan approved these changes

2021-11-23 09:30 UTC, merged