refactor(Scripts/Onyxia): Update Onyxia's script
azerothcore/azerothcore-wotlk pull request #9371
Opened 2021-11-26 17:51 UTC by Nyeriah

## Changes Proposed:
-  Moved her to BossAI
-  Updated instance to use BossStates
- Removed useless creature scripts

## Issues Addressed:

- Closes 

## SOURCE:

## Tests Performed:

- WIP / Not tested
- 

## How to Test the Changes:

1.
2.
3.

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

2021-11-26 21:02 UTC, Kitzunu commented
as you are refactoring it, please also update to new script system

2021-11-27 13:42 UTC, Nyeriah commented
This is ready to be tested and reviewed

2021-11-27 13:44 UTC, Kitzunu requested changes

2021-11-27 13:44 UTC, Kitzunu commented on src/server/scripts/Kalimdor/OnyxiasLair/onyxias_lair.h
> +#define RegisterOnyxiaLairCreatureAI(ai_name) RegisterCreatureAIWithFactory(ai_name, GetOnyxiasLairAI)
```suggestion
#define RegisterOnyxiasLairCreatureAI(ai_name) RegisterCreatureAIWithFactory(ai_name, GetOnyxiasLairAI)
```

2021-11-27 15:56 UTC, temperrr commented
Tested (havent tested without refactor)

- [ ] Onyxia isn't tauntable
- [x] used flamebreath
- [x] used wing buffet
- [x] used tail sweep
- [x] used cleave
- [x] phase 2 correctly engaged
- [x] fireball
- [x] spawning guards and whelps
- [x] fire breath
- [x] phase 3 engaged
- [x] Fear
- [x] eruption
- [x] few whelps spawned

achievements
10 player:
- [x] Onyxias lair 10 player
- [x] Defeat Onyxia in less than 5 minutes
- [x] Cause 50 Onyxia Whelplings to hatch within 10 seconds of Onyxia's liftoff, and then defeat her
- [x] Defeat Onyxia without anyone taking damage from a Deep Breath

25 player

- [x] Onyxias lair 10 player
- [x] Defeat Onyxia in less than 5 minutes
- [x] Cause 50 Onyxia Whelplings to hatch within 10 seconds of Onyxia's liftoff, and then defeat her
- [x] Defeat Onyxia without anyone taking damage from a Deep Breath

2021-11-27 16:04 UTC, Nefertumm approved these changes

2021-11-27 16:05 UTC, Nefertumm commented
Looking good for me. I'm just wondering why did you use a variable for phases instead of events.IsInPhase(...) but it's the same :) Good work

2021-11-27 16:19 UTC, Nyeriah commented
> Looking good for me. I'm just wondering why did you use a variable for phases instead of events.IsInPhase(...) but it's the same :) Good work

I didn't use it, it's old code, since this is a side-project to me I didn't want to invest too much time rewriting that logic, it's working fine as it is

2021-11-27 16:33 UTC, merged