fix(Core/DB): Fire Elemental Invasion changes
azerothcore/azerothcore-wotlk pull request #9372
Opened 2021-11-26 18:56 UTC by claudiodfc

## Changes Proposed:
- Blazing Invader's SAI rework.
- SMART_ACTION_SET_COUNTER extra parameter for subtracting values to the counter.
- Changed `Map::TempSummon* SummonCreature` to have WorldObjects as summoner and not just Units.
- Added a nullptr check for `SmartScript::GetTargets`

## Issues Addressed:

- Closes #8080 
https://github.com/chromiecraft/chromiecraft/issues/1440

## SOURCE:

## Tests Performed:

- Compiled and tested in Windows 10

## How to Test the Changes:

1. Go to ungoro and check the elemental Invasion
2. Only maximum of 3 Blazings should spawn at a time per Rift
3. After one is killed, after a while another spawns.

## Known Issues and TODO List:

None

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

2021-11-26 22:02 UTC, Nyeriah commented on src/server/game/AI/SmartScripts/SmartScript.cpp
> +            if (ObjectList* targets = GetTargets(e, unit))
I might be wrong, but this probably should be four spaces to the right

2021-11-26 22:03 UTC, Nyeriah commented on src/server/game/AI/SmartScripts/SmartScript.cpp
> +                        if (Unit* base = ObjectAccessor::GetUnit(*owner, owner->GetCharmerOrOwnerGUID()))
missing brackets

2021-11-26 22:04 UTC, Nyeriah commented on src/server/game/AI/SmartScripts/SmartScript.h
> +            if (!reset && !subtract)
missing brackets here too

2021-11-26 22:05 UTC, Nyeriah commented
Changing summoner to worldobject is a natural approach, trinity did it too (IsSummonedBy()) and its something we probably should do for all functions, but it will take time

2021-11-27 05:29 UTC, IntelligentQuantum commented
```
/home/runner/work/azerothcore-wotlk/azerothcore-wotlk/src/server/game/AI/SmartScripts/SmartScript.cpp: In member function ‘void SmartScript::ProcessAction(SmartScriptHolder&, Unit*, uint32, uint32, bool, const SpellInfo*, GameObject*)’:
/home/runner/work/azerothcore-wotlk/azerothcore-wotlk/src/server/game/AI/SmartScripts/SmartScript.cpp:1723:13: error: this ‘else’ clause does not guard... [-Werror=misleading-indentation]
 1723 |             else
      |  
```

2021-11-27 09:22 UTC, claudiodfc commented
Yea there's an issue with indentation, I'll take care of it Monday.

2021-11-27 16:10 UTC, UltraNix approved these changes

2021-12-14 14:16 UTC, temperrr commented
Looks good, respawn works,

however,

When I killed the bossof the invasion, server froze, eventually resulting in 
![image](https://user-images.githubusercontent.com/20357406/146015241-09e4e15b-4155-4309-a161-233fc3c9e011.png)

2021-12-14 16:50 UTC, Nyeriah approved these changes

2021-12-14 23:00 UTC, claudiodfc commented
@temperrr can you re-test? I tried on my local and server didn't freeze for me. Maybe un-related to this PR?

2021-12-17 13:50 UTC, temperrr commented
Cant get the event to start this time round.

event start 13 does nothing

2021-12-17 14:03 UTC, claudiodfc commented
I'll see what I can do about that

2021-12-20 17:11 UTC, claudiodfc commented
@temperrr Can you take a look? Added him to the `Elemental Invasions` event. None of the other elemental bosses are on the even so They'll have to be added on other PRs since this is for the Fire invasion.

2021-12-22 00:45 UTC, claudiodfc commented
@azerothcore/testers please someone take a look

2021-12-22 15:03 UTC, temperrr commented
![image](https://user-images.githubusercontent.com/20357406/147112331-1993bc6c-84cc-4694-83e9-421809beb13c.png)
![image](https://user-images.githubusercontent.com/20357406/147112539-06e2af26-e3e6-4cd6-bc52-58975cc5d04d.png)
[9c84b13a8bd3_worldserver.exe_[22-12_16-0-5].txt](https://github.com/azerothcore/azerothcore-wotlk/files/7763379/9c84b13a8bd3_worldserver.exe_.22-12_16-0-5.txt)

2021-12-22 22:41 UTC, claudiodfc commented
It's strange how this doesn't crash mine, but it's obviously this PR. I'll have to take a look why tempsummon is crashing the server.

2021-12-24 15:37 UTC, claudiodfc commented
@temperrr Made some changes, please take a look again when you got time.

It should no longer cause this freeze.

To further prove the change doesn't break the smart target, please execute this test bellow aswell:

#### Test case
.additem 49693 (Learn KT)
.cast 69731 (He laughs when hit by this spell)

2021-12-24 15:38 UTC, claudiodfc commented
@Nyeriah @UltraNix I made a new change on the smart target, can you guys give it a look if It's ok?

2022-01-04 09:58 UTC, temperrr commented
doesnt crash now :)

2022-01-04 12:50 UTC, Kitzunu requested changes

2022-01-04 12:50 UTC, Kitzunu commented on data/sql/updates/pending_db_world/rev_1637890270049187700.sql
> +INSERT INTO `game_event_creature` (`eventEntry`, `guid`) VALUES ('13', '14461');
quotes on ints. No.

2022-01-04 19:45 UTC, Kitzunu approved these changes

2022-01-06 18:30 UTC, merged