[Raid]Fix ZAM 10 chest unlootble
azerothcore/azerothcore-wotlk pull request #9380
Opened 2021-11-27 02:15 UTC by betayi

## Changes Proposed:
-  continue #9378 
-  

## Issues Addressed:

- Closes #9155 

## SOURCE:

## Tests Performed:

- 
- 

## How to Test the Changes:

1.enter zam talk door keepera open door and start hostage rescue
2.kill any 3 of boss  Akil'zon Jan'alai Nalorakk and Halazzi
3.the hostage summoned a chest
4.loot it

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

2021-11-27 17:33 UTC, temperrr commented
Hey!

Thanks for your PR! What is the status (WIP, Ready to be reviewed/tested)?

2021-11-28 01:17 UTC, betayi commented
> Hey!
> 
> Thanks for your PR! What is the status (WIP, Ready to be reviewed/tested)?

I ‘m tested， but it seems  the status flag was not changed by me ...

2021-11-29 19:12 UTC, Nefertumm requested changes
Please, address the changes I made

2021-11-29 19:12 UTC, Nefertumm commented on data/sql/updates/pending_db_world/rev_1637978286218341866.sql
> +delete from gameobject_template_addon where entry in (186648,187021,186672,186667);
```suggestion
DELETE FROM `gameobject_template_addon` WHERE `entry` IN (186648,187021,186672,186667);
```

2021-11-29 19:12 UTC, Nefertumm commented on data/sql/updates/pending_db_world/rev_1637978286218341866.sql
> +insert into gameobject_template_addon values
```suggestion
INSERT INTO `gameobject_template_addon` (`entry`, `faction`, `flags`, `mingold`, `maxgold`) VALUES
```

2021-11-30 15:47 UTC, Nefertumm approved these changes

2021-12-04 11:03 UTC, betayi commented
same issue with #9155

2021-12-07 22:37 UTC, Voxstrasza commented
I tested this.  3 chests from 3 bosses.  Video:

https://youtu.be/xT8PIotJkiY

2021-12-09 00:40 UTC, merged