Core/Players: Update the player's zone and area only after update the player's position server-side
azerothcore/azerothcore-wotlk pull request #9419
Opened 2021-11-29 22:33 UTC by schell244

## Changes Proposed:
Port player zone and area update logic from TC.
I was looking into player map explore code and found this commit while comparing with TC. 

Sadly this does not fix the map explore issue after login mentioned in the comment of https://github.com/azerothcore/azerothcore-wotlk/issues/7737

## Issues Addressed:
- 

## SOURCE:
https://github.com/TrinityCore/TrinityCore/pull/12171

## Tests Performed:
builds, checked ingame

## How to Test the Changes:
1. create new character
2. enter new areas and zone
3. check map explore, channel messages, unmount in buildings, ...

## Known Issues and TODO List:
- 

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

2021-11-29 23:24 UTC, Nyeriah approved these changes

2021-12-09 11:16 UTC, claudiodfc commented
## Test result 🦗

No changes after the PR:
![image](https://user-images.githubusercontent.com/54484196/145386649-97d6bb41-38ce-4744-9456-958f9dde3afe.png)

2021-12-09 11:21 UTC, claudiodfc commented
The relog issue still remains, however the chat messages and discovery states are still ok.

2021-12-09 14:15 UTC, Kitzunu requested changes

2021-12-09 14:15 UTC, Kitzunu commented on src/server/game/Entities/Player/Player.h
> +    void SetNeedsZoneUpdate(bool needsUpdate) {m_needsZoneUpdate = needsUpdate;}
```suggestion
    void SetNeedZoneUpdate(bool needUpdate) { m_needsZoneUpdate = needsUpdate; }
```

2021-12-09 14:15 UTC, Kitzunu commented on src/server/game/Entities/Player/Player.cpp
> +    m_needsZoneUpdate = false;
```suggestion
    m_needZoneUpdate = false;
```

2021-12-09 14:15 UTC, Kitzunu commented on src/server/game/Entities/Player/Player.h
> +    bool m_needsZoneUpdate;
```suggestion
    bool m_needZoneUpdate;
```

2021-12-09 14:15 UTC, Kitzunu commented on src/server/game/Entities/Player/PlayerUpdates.cpp
> +    if (m_needsZoneUpdate)
```suggestion
    if (m_needZoneUpdate)
```

2021-12-09 14:15 UTC, Kitzunu commented on src/server/game/Entities/Player/PlayerUpdates.cpp
> +        m_needsZoneUpdate = false;
```suggestion
        m_needZoneUpdate = false;
```

2021-12-09 14:15 UTC, Kitzunu commented on src/server/game/Handlers/MiscHandler.cpp
> +    GetPlayer()->SetNeedsZoneUpdate(true);
```suggestion
    GetPlayer()->SetNeedZoneUpdate(true);
```

2021-12-09 16:00 UTC, Kitzunu requested changes
forgot about these lol

2021-12-09 16:00 UTC, Kitzunu commented on src/server/game/Entities/Player/Player.h
> +    void SetNeedZoneUpdate(bool needUpdate) { m_needsZoneUpdate = needsUpdate; }
```suggestion
    void SetNeedZoneUpdate(bool needUpdate) { m_needZoneUpdate = needUpdate; }
```

2021-12-09 16:02 UTC, schell244 commented
Thanks for checking :)

2021-12-09 16:05 UTC, Kitzunu approved these changes

2021-12-10 00:58 UTC, merged