fix(DB/Creature): Apply POF Aura and Apply Voice Lines to LK
azerothcore/azerothcore-wotlk pull request #9503
Opened 2021-12-04 22:13 UTC by Voxstrasza

## Changes Proposed:
-  Applies Path of Frost aura to Lich King during Phase 3 of the Ebon Hold questlines.  Spell ID is already applied to the phase 1 counterpart.
-  Add audio, create text group and apply SAI to Lich King during Phase 3 of Ebon Hold.  The voicefiles are called A_EH_LichKing_Chapter3Shout01-17 to confirm that these are in the right place.

## SOURCE:
https://youtu.be/b863yUtcCzM?t=4920
https://youtu.be/kqqxXo9FEbI?t=3628

https://www.wowhead.com/npc=29110/the-lich-king quotes also list Battle of Light's Hope for some reason

## Tests Performed:
I applied the SQL and sat and wait while the npc went through the voice files.  There are 17 in total.

## How to Test the Changes:
.go c 130896

2021-12-04 22:23 UTC, Kitzunu commented on data/sql/updates/pending_db_world/rev_1638655418843943400.sql
> +INSERT INTO `creature_text` (`CreatureID`, `GroupID`, `ID`, `Text`, `Type`, `Language`, `Probability`, `Emote`, `Duration`, `Sound`, `BroadcastTextId`, `TextRange`, `comment`) VALUES (29110, 250, 16,
Please fix the sql style

2021-12-04 22:36 UTC, Voxstrasza commented on data/sql/updates/pending_db_world/rev_1638655418843943400.sql
> +INSERT INTO `creature_text` (`CreatureID`, `GroupID`, `ID`, `Text`, `Type`, `Language`, `Probability`, `Emote`, `Duration`, `Sound`, `BroadcastTextId`, `TextRange`, `comment`) VALUES (29110, 250, 16,
> 

fixed the formatting

2021-12-24 20:33 UTC, claudiodfc requested changes

2021-12-24 20:33 UTC, claudiodfc commented on data/sql/updates/pending_db_world/rev_1638655418843943400.sql
> +DELETE FROM `creature_text` WHERE (`CreatureID` = 29110) AND (`GroupID` = 250);
Change delete query to this:

``` sql
DELETE FROM `creature_text` WHERE (`CreatureID` = 29110) AND (`GroupID` IN (0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16));
```

2021-12-25 00:23 UTC, claudiodfc commented
### Test Case
- Turn GM mode
- Executing command `.go c 130896`
- The Lich King does use his creature_text

2021-12-25 00:24 UTC, claudiodfc commented
@azerothcore/developers can someone give a review?

2021-12-25 00:27 UTC, acidmanifesto commented
> @azerothcore/developers can someone give a review?

Is his sql good or no? I am really not a sql guys really.

2021-12-25 00:41 UTC, claudiodfc commented
Other than the change I pointed out, it looks good. Otherwise, you can't re-run the query.

2021-12-25 13:26 UTC, Voxstrasza commented
> Other than the change I pointed out, it looks good. Otherwise, you can't re-run the query.

Should be G2G now.  I've been away.  Apologies.

2021-12-25 15:32 UTC, acidmanifesto approved these changes

2021-12-25 15:32 UTC, merged