fix(DB/quest_poi): Update WorldMapAreaId to match respective quests
azerothcore/azerothcore-wotlk pull request #9584
Opened 2021-12-08 05:44 UTC by Voxstrasza

## Changes Proposed:
-  Update WorldMapAreaId to match respective quests in issues linked below

## Issues Addressed:
- Closes #8531
- Closes #8713

## How to Test the Changes:
1. Add the quests from the issues above
2. Right click on quest tracker and show map
3. Should now bring you to where the quest is located and not the next zone over

2021-12-08 05:52 UTC, IntelligentQuantum requested changes

2021-12-08 05:52 UTC, IntelligentQuantum commented on data/sql/updates/pending_db_world/rev_1638942051959578400.sql
> +UPDATE `quest_poi` SET `WorldMapAreaId`='11' WHERE `QuestID`=3924 AND `id`=3;
`WorldMapAreaId`='11' > `WorldMapAreaId`=11
`WorldMapAreaId`='23' > `WorldMapAreaId`=23

2021-12-08 05:58 UTC, IntelligentQuantum approved these changes

2021-12-08 16:11 UTC, acidmanifesto commented
@azerothcore/testers please confirm this sql based pr is tested working.

2021-12-08 20:16 UTC, Shineslippers commented
Tested:

- [X] Quest 887. Both `accept` and `complete` POI are correct
- [X] Quest 888. Both `accept` and `complete` POI are correct
- [X] Quest 890. Both `accept` and `complete` POI are correct
- [X] Quest 892. Both `accept` and `complete` POI are correct
- [X] Quest 896. Both `accept` and `complete` POI are correct
- [X] Quest 896. Both `accept` and `complete` POI are correct
- [X] Quest 1125. Both `accept` and `complete` POI are correct
- [X] Quest 1126. Both `accept` and `complete` POI are correct
- [X] Quest 6164. Both `accept` and `complete` POI are correct
- [X] Quest 6570. Both `accept` and `complete` POI are correct

<details><summary>Spoiler</summary>

![WoWScrnShot_120821_230643](https://user-images.githubusercontent.com/85256266/145278050-c6458afd-0517-4126-8880-3af54e9466d6.jpg)
![WoWScrnShot_120821_230857](https://user-images.githubusercontent.com/85256266/145278063-345b3631-c130-41ce-8b38-c3a7e40cad50.jpg)
![WoWScrnShot_120821_230953](https://user-images.githubusercontent.com/85256266/145278065-5642e5b6-37f7-4c04-8f37-c94b0f1804a9.jpg)
![WoWScrnShot_120821_231002](https://user-images.githubusercontent.com/85256266/145278066-c952146b-c157-4a38-a475-371ba7d29c68.jpg)
![WoWScrnShot_120821_231016](https://user-images.githubusercontent.com/85256266/145278068-c8e62dff-801b-4525-98f3-273845caead9.jpg)
![WoWScrnShot_120821_231025](https://user-images.githubusercontent.com/85256266/145278069-bd842ac0-20ec-47c3-ac70-a73caa58da1d.jpg)
![WoWScrnShot_120821_231118](https://user-images.githubusercontent.com/85256266/145278070-64979e09-6183-43b4-a0f1-e2d03d1342c9.jpg)
![WoWScrnShot_120821_231241](https://user-images.githubusercontent.com/85256266/145278073-a0ee6d64-3185-4878-beaa-1e370c682fc0.jpg)
![WoWScrnShot_120821_231343](https://user-images.githubusercontent.com/85256266/145278077-7c2eae9d-c9a6-429d-9675-3013ce249593.jpg)
![WoWScrnShot_120821_231417](https://user-images.githubusercontent.com/85256266/145278078-b16aefb2-0610-49e0-9c91-d8bcfb9448d6.jpg)
![WoWScrnShot_120821_231425](https://user-images.githubusercontent.com/85256266/145278081-3c0514cd-fd6a-486b-8f4b-12e2523f418a.jpg)
![WoWScrnShot_120821_231459](https://user-images.githubusercontent.com/85256266/145278084-d9e32428-fe52-487e-9641-07252c23fbd6.jpg)
![WoWScrnShot_120821_231511](https://user-images.githubusercontent.com/85256266/145278091-af2892f3-836b-4217-8ca6-c194c2aec49d.jpg)
![WoWScrnShot_120821_231543](https://user-images.githubusercontent.com/85256266/145278093-ef55cd6f-26db-4927-8a2b-da327eb9eabc.jpg)
![WoWScrnShot_120821_231551](https://user-images.githubusercontent.com/85256266/145278096-122f1581-eea4-42ba-9aca-624568ca108b.jpg)


</details>

2021-12-08 22:51 UTC, Voxstrasza commented
> Quest 3924. `accept` POI is correct, but `complete` doesn't open Orgrimmar map.

okay, I'll fix that

2021-12-09 00:01 UTC, Shineslippers commented
@Voxstrasza please use all links from AC reports to your `Issues Addressed` field. There is existing `Original report` line in most of reports. Thank you.

2021-12-09 21:05 UTC, Voxstrasza commented
Quest 3924 will now open map Orgrimmar when completion requirements are met.  https://i.imgur.com/7Bri9Dh.jpg

2021-12-10 12:06 UTC, acidmanifesto approved these changes

2021-12-12 23:20 UTC, merged