[WIP] Core/Creature: Trainer
azerothcore/azerothcore-wotlk pull request #9586
Opened 2021-12-08 09:15 UTC by IntelligentQuantum

## Changes Proposed:
-  
-  

## Issues Addressed:

- Closes 

## SOURCE:

## Tests Performed:

- 
- 

## How to Test the Changes:

1.
2.
3.

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

2021-12-09 14:20 UTC, Kitzunu commented
https://github.com/azerothcore/azerothcore-wotlk/issues/5420 ?

2021-12-09 14:37 UTC, IntelligentQuantum commented
> #5420 ?

Hmmm, I had not seen this issue.

2021-12-09 14:37 UTC, Kitzunu commented
I have tried doing this 3 times and gave up cuz of it being so big xd

2021-12-09 18:56 UTC, acidmanifesto commented
i may regret asking this, how important is this needing to be done?

2021-12-09 18:58 UTC, Kitzunu commented
> 

That's what I concluded too haha

2021-12-09 18:58 UTC, Kitzunu commented
> i may regret asking this, how important is this needing to be done?

Not life or death, but it is a nice system

2021-12-09 19:00 UTC, acidmanifesto commented
> > i may regret asking this, how important is this needing to be done?
> 
> Not life or death, but it is a nice system

well then... hold my beer, lets see what i can do the next few days

2021-12-09 19:05 UTC, Kitzunu commented
Famous last words

2021-12-18 20:41 UTC, UltraNix commented on src/server/game/Entities/Creature/Creature.cpp
>          return false;
Brackets.

2021-12-18 20:43 UTC, UltraNix commented on src/server/game/Entities/Creature/Trainer.cpp
> +        if (!IsTrainerValidForPlayer(player))
Brackets.

2021-12-18 20:43 UTC, UltraNix commented on src/server/game/Entities/Creature/Trainer.cpp
> +            player->CastSpell(player, trainerSpell->SpellId, true);
Brackets.

2021-12-18 20:43 UTC, UltraNix commented on src/server/game/Entities/Creature/Trainer.cpp
> +            player->learnSpell(trainerSpell->SpellId, false);
Brackets.

2021-12-18 20:44 UTC, UltraNix commented on src/server/game/Entities/Creature/Trainer.cpp
> +            return &(*itr);
Brackets.

2021-12-18 20:44 UTC, UltraNix commented on src/server/game/Entities/Creature/Trainer.cpp
> +            return false;
Brackets.

2021-12-18 20:44 UTC, UltraNix commented on src/server/game/Entities/Creature/Trainer.cpp
> +            return false;
Brackets.

2021-12-18 20:44 UTC, UltraNix commented on src/server/game/Entities/Creature/Trainer.cpp
> +            return SpellState::Known;
Brackets.

2021-12-18 20:44 UTC, UltraNix commented on src/server/game/Entities/Creature/Trainer.cpp
> +            return SpellState::Unavailable;
Brackets.

2021-12-18 20:45 UTC, UltraNix commented on src/server/game/Entities/Creature/Trainer.cpp
> +            return SpellState::Unavailable;
Brackets.

2021-12-18 20:45 UTC, UltraNix commented on src/server/game/Entities/Creature/Trainer.cpp
> +            if (reqAbility && !player->HasSpell(reqAbility))
Brackets.

2021-12-18 20:45 UTC, UltraNix commented on src/server/game/Entities/Creature/Trainer.cpp
> +            return SpellState::Unavailable;
Brackets.

2021-12-18 20:45 UTC, UltraNix commented on src/server/game/Entities/Creature/Trainer.cpp
> +        for (int32 reqAbility : trainerSpell->ReqAbility)
Why int32 (not uint32)?

2021-12-18 20:45 UTC, UltraNix commented on src/server/game/Entities/Creature/Trainer.cpp
> +            if (!spellInfo || spellInfo->Effects[i].Effect != SPELL_EFFECT_LEARN_SPELL)
Brackets.

2021-12-18 20:46 UTC, UltraNix commented on src/server/game/Entities/Creature/Trainer.cpp
> +            if (!player->HasSpell(spellInfo->Effects[i].TriggerSpell))
Brackets.

2021-12-18 20:46 UTC, UltraNix commented on src/server/game/Entities/Creature/Trainer.cpp
> +                if (!player->HasSpell(previousRankSpellId))
Brackets.

2021-12-18 20:47 UTC, UltraNix commented on src/server/game/Entities/Creature/Trainer.cpp
> +                if (!player->HasSpell(previousRankSpellId))
Trainer::GetSpellStat

2021-12-18 20:48 UTC, UltraNix commented on src/server/game/Entities/Creature/Trainer.cpp
> +            return SpellState::Known;
Brackets.

2021-12-18 20:48 UTC, UltraNix commented on src/server/game/Entities/Creature/Trainer.cpp
> +            if (!player->HasSpell(requirePair.second))
Brackets.

2021-12-18 20:48 UTC, UltraNix commented on src/server/game/Entities/Creature/Trainer.cpp
> +        if (!GetTrainerRequirement())
Brackets.

2021-12-18 20:48 UTC, UltraNix commented on src/server/game/Entities/Creature/Trainer.cpp
> +            return _greeting[DEFAULT_LOCALE];
Brackets.

2021-12-18 20:51 UTC, UltraNix commented on src/server/game/Entities/Creature/Trainer.cpp
> +        for (int32 reqAbility : trainerSpell->ReqAbility)
Why `int32` (and not `uint32`)?

2021-12-18 20:54 UTC, UltraNix commented on src/server/game/Entities/Player/PlayerGossip.cpp
> +                    // no break;
`[[fallthrough]]`

2021-12-18 20:57 UTC, UltraNix commented on src/server/game/Globals/ObjectMgr.cpp
> +    std::unordered_map<int32, std::vector<Trainer::Spell>> spellsByTrainer;
Why `int32` (and not `uint32`)?

2021-12-18 21:01 UTC, UltraNix requested changes
Missing brackets (mainly in `Trainer.cpp`) and `[[nodiscard]]` attribute (mainly in `Trainer.h`.

2022-01-25 06:53 UTC, IntelligentQuantum commented
CONFLICT

2022-01-25 06:53 UTC, closed without merging

2022-01-25 11:38 UTC, UltraNix commented
> CONFLICT

FIGHT!

2022-01-25 11:40 UTC, IntelligentQuantum commented
> > CONFLICT
> 
> FIGHT!

I CAN'T