feat(DB/Creature): Throw error if npcflag and gossip_menu_id is not c…
azerothcore/azerothcore-wotlk pull request #9665
Opened 2021-12-11 23:06 UTC by Kitzunu

…ombined

*cherry-pick commit (https://github.com/TrinityCore/TrinityCore/commit/a513922fc1572137c4e8b7b75d7ba931b15cf26a)

## Changes Proposed:
- Make sure that creatures with a gossip menu also has gossip flag
-  Make sure that creatures that does not have a gossip does not have a gossip flag+

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

2021-12-12 00:37 UTC, Kitzunu commented
I just want to throw it out there that the module error
```
Creature (Entry: 190010) has npcflag UNIT_NPC_FLAG_GOSSIP (1), but gossip menu is unassigned.
```

Is caused by some unknown module and is not something from the core.
If someone knows which module it is, I can fix it there.

2021-12-12 00:45 UTC, TheLegendaryKingdom commented
> I just want to throw it out there that the module error
> 
> ```
> Creature (Entry: 190010) has npcflag UNIT_NPC_FLAG_GOSSIP (1), but gossip menu is unassigned.
> ```
> 
> Is caused by some unknown module and is not something from the core. If someone knows which module it is, I can fix it there.

I guess 190010 is the [default Transmogrifier provided](https://github.com/azerothcore/mod-transmog/blob/master/data/sql/db-world/trasm_world_NPC.sql) with the module [mod-transmog](https://github.com/azerothcore/mod-transmog)

2021-12-25 12:04 UTC, acidmanifesto approved these changes

2022-01-04 18:55 UTC, acidmanifesto commented
What is the Status of this PR? @Kitzunu

2022-01-04 19:06 UTC, Kitzunu commented
trying to get a half good way to exclude entries

2022-01-19 14:04 UTC, acidmanifesto approved these changes

2022-01-19 21:34 UTC, FrancescoBorzi requested changes

2022-01-19 21:34 UTC, FrancescoBorzi commented on src/server/game/Globals/ObjectMgr.cpp
> +        }
```suggestion
        case 190010: // Transmog Module
            break;
        default:
            if (cInfo->GossipMenuId && !(cInfo->npcflag & UNIT_NPC_FLAG_GOSSIP))
            {
                LOG_ERROR("sql.sql", "Creature (Entry: %u) has assigned gossip menu %u, but npcflag does not include UNIT_NPC_FLAG_GOSSIP (1).", cInfo->Entry, cInfo->GossipMenuId);
            }
            else if (!cInfo->GossipMenuId && (cInfo->npcflag & UNIT_NPC_FLAG_GOSSIP))
            {
                LOG_ERROR("sql.sql", "Creature (Entry: %u) has npcflag UNIT_NPC_FLAG_GOSSIP (1), but gossip menu is unassigned.", cInfo->Entry);
            }
```

2022-01-19 21:37 UTC, FrancescoBorzi commented on src/server/game/Globals/ObjectMgr.cpp
> +    }
```suggestion
    switch (cInfo->Entry)
    {
        case 190010: // Transmog Module
          return;
    }
    
    if (cInfo->GossipMenuId && !(cInfo->npcflag & UNIT_NPC_FLAG_GOSSIP))
    {
        LOG_ERROR("sql.sql", "Creature (Entry: %u) has assigned gossip menu %u, but npcflag does not include UNIT_NPC_FLAG_GOSSIP (1).", cInfo->Entry, cInfo->GossipMenuId);
    }
    else if (!cInfo->GossipMenuId && (cInfo->npcflag & UNIT_NPC_FLAG_GOSSIP))
    {
        LOG_ERROR("sql.sql", "Creature (Entry: %u) has npcflag UNIT_NPC_FLAG_GOSSIP (1), but gossip menu is unassigned.", cInfo->Entry);
    }
```

2022-01-19 21:38 UTC, FrancescoBorzi requested changes

2022-01-19 21:38 UTC, FrancescoBorzi commented on src/server/game/Globals/ObjectMgr.cpp
> +    }
```suggestion
    switch (cInfo->Entry)
    {
        case 190010: // Transmog Module
          return;
    }
    
    if (cInfo->GossipMenuId && !(cInfo->npcflag & UNIT_NPC_FLAG_GOSSIP))
    {
        LOG_ERROR("sql.sql", "Creature (Entry: %u) has assigned gossip menu %u, but npcflag does not include UNIT_NPC_FLAG_GOSSIP (1).", cInfo->Entry, cInfo->GossipMenuId);
    }
    else if (!cInfo->GossipMenuId && (cInfo->npcflag & UNIT_NPC_FLAG_GOSSIP))
    {
        LOG_ERROR("sql.sql", "Creature (Entry: %u) has npcflag UNIT_NPC_FLAG_GOSSIP (1), but gossip menu is unassigned.", cInfo->Entry);
    }
```

2022-01-19 21:40 UTC, FrancescoBorzi commented
@Kitzunu refactored the code to look cleaner, also don't forget to add `Core` in the commit name when touching core stuff ;)

2022-01-19 21:45 UTC, Kitzunu commented on src/server/game/Globals/ObjectMgr.cpp
> +
```suggestion

```

2022-01-20 09:50 UTC, Nyeriah approved these changes

2022-01-20 09:50 UTC, merged