fix(Spawning/Pathing) An'daroth, Ghostlands
azerothcore/azerothcore-wotlk pull request #9696
Opened 2021-12-14 04:21 UTC by malcrom

## Changes Proposed:
-  Respawn, Add pathing, script Sentinel Leader

## Issues Addressed:

## SOURCE:
Sniff

## Tests Performed:
- compiles and inserts
- Tested in game

## How to Test the Changes:
1. .g c 82157
2. .g c 82139
3. .g c 82136

2021-12-14 06:07 UTC, IntelligentQuantum approved these changes

2021-12-15 00:29 UTC, Kitzunu requested changes

2021-12-15 00:29 UTC, Kitzunu commented on src/server/scripts/EasternKingdoms/zone_ghostlands.cpp
> +    struct npc_sentinel_leaderAI : public ScriptedAI
Use new script model

2021-12-15 00:35 UTC, Kitzunu commented on src/server/scripts/EasternKingdoms/zone_ghostlands.cpp
> +    struct npc_sentinel_leaderAI : public ScriptedAI
RegisterCreatureAI

2021-12-15 01:05 UTC, malcrom commented on src/server/scripts/EasternKingdoms/zone_ghostlands.cpp
> +    struct npc_sentinel_leaderAI : public ScriptedAI
done

2021-12-15 01:06 UTC, Kitzunu approved these changes

2021-12-16 12:35 UTC, temperrr commented
Tested


- [x] Walks around, talks to other npcs
- [x] uses sinister strike
- [x] uses backstab when back is turned

2021-12-17 17:33 UTC, FrancescoBorzi commented
when content-specific PR (e.g. 1-19) aren't linked to any open issue, like in this case, please add the Project to the PR as well

2021-12-17 17:35 UTC, merged