fix(DB/Creature): Removed duplicated creatures from Midsummer event.
azerothcore/azerothcore-wotlk pull request #9710
Opened 2021-12-14 22:03 UTC by UltraNix

Fixes #6469

## Issues Addressed:

- Closes #6469
- Closes https://github.com/chromiecraft/chromiecraft/issues/928
- Closes https://github.com/chromiecraft/chromiecraft/issues/935
- Closes https://github.com/chromiecraft/chromiecraft/issues/936
- Closes https://github.com/chromiecraft/chromiecraft/issues/937

## Tests Performed:

- Not tested.

## How to Test the Changes:

More info[here](https://github.com/azerothcore/azerothcore-wotlk/issues/6469)

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

2021-12-16 12:00 UTC, temperrr commented
tested

Checked several locations and haven't seen double spawns.

2021-12-17 08:41 UTC, Nefertumm approved these changes

2021-12-24 01:09 UTC, acidmanifesto requested changes

2021-12-24 01:09 UTC, acidmanifesto commented on data/sql/updates/pending_db_world/rev_1639519249292727400.sql
> +DELETE FROM `creature_addon` WHERE `guid ` IN (86249,86258,86264,86265,86716,86898,90490,94518,94553,94555,94603,94604,94634,94635,94637,94649,94693,94694,94699,94700,
you have a space after guid. Please Change to
```
DELETE FROM `creature_addon` WHERE `guid` IN (86249,86258,86264,86265,86716,86898,90490,94518,94553,94555,94603,94604,94634,94635,94637,94649,94693,94694,94699,94700,
94704,94710,94711,94738,94747,94753,94760,94761,94762,94765,94773,94786,94796,94803,94805,94808,94814,94831,94839,94840,94862,94862,94862,94863,94863,94863,94920,
94920,94921,94921,94922,94923,94924,94925,94926,94927,94928,94929,94930,94930,94930,94930,94931,94931,94931,94931,94932,94932,94932,94932,94933,94933,94933,94933,
94934,94934,94934,94935,94935,94935,94936,94936,94936,94937,94937,94937,94950,94956,202858,202859,202860,202861,248565,248566,248567,248568,248569,248570,248571,
248573,248574,248576,248577,248578,248579,248580,248583);
```

2022-01-03 19:54 UTC, acidmanifesto approved these changes

2022-01-03 19:54 UTC, merged