fix(DB): Terenthis quest chain
azerothcore/azerothcore-wotlk pull request #9714
Opened 2021-12-15 01:59 UTC by claudiodfc

## Changes Proposed:
- Imported from trinitycore and vmangos data
- Fixed Volcor's gossip and quest deliver
- Fixed Sentinel Selarin's pathing and flags
- Scripted events for quests:
Quest 984 How Big a Threat Part 1
Quest 985 How Big a Threat Part 2
Quest 986 A Lost Master Part 1
Quest 993 A Lost Master Part 2
Quest 994 or 995 Escape Through Stealth or Escape Through Force

## Issues Addressed:

- Closes #2118

## SOURCE:

Check issue for Source

## Tests Performed:

- Tested in windows 10

## How to Test the Changes:

1. .go c id 3693
2. Be around level 15 and do the quest chain checking for the RP interactions displayed on the issue

## Known Issues and TODO List:

None

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

2021-12-15 08:28 UTC, IntelligentQuantum approved these changes

2021-12-24 16:12 UTC, claudiodfc commented
@azerothcore/testers can someone take a look at this?

2022-01-09 22:59 UTC, yuzifc commented
Tested, working great :)

https://user-images.githubusercontent.com/70452524/148704628-ed9b5ddc-e009-4d15-ad0b-6880c814ea71.mp4

2022-01-09 23:07 UTC, Kitzunu requested changes

2022-01-09 23:07 UTC, Kitzunu commented on data/sql/updates/pending_db_world/rev_1639532770750121300.sql
> +UPDATE `creature_template` SET `speed_walk`=1 WHERE `entry`= 3694;
sniffed?

2022-01-09 23:07 UTC, Kitzunu commented on data/sql/updates/pending_db_world/rev_1639532770750121300.sql
> +INSERT INTO `waypoints` (`entry`, `pointid`, `position_x`, `position_y`, `position_z`, `orientation`, `point_comment`) VALUES
sniffed?

2022-01-10 00:21 UTC, claudiodfc commented on data/sql/updates/pending_db_world/rev_1639532770750121300.sql
> +INSERT INTO `waypoints` (`entry`, `pointid`, `position_x`, `position_y`, `position_z`, `orientation`, `point_comment`) VALUES
Vmangos

2022-01-10 00:21 UTC, claudiodfc commented on data/sql/updates/pending_db_world/rev_1639532770750121300.sql
> +UPDATE `creature_template` SET `speed_walk`=1 WHERE `entry`= 3694;
Vmangos

2022-01-10 00:52 UTC, yuzifc commented
tested, grimclaw looking the wrong way, sentinel the same thing.

https://user-images.githubusercontent.com/70452524/148708158-45a1556b-e28f-4df2-873c-33ee0c9be530.mp4

2022-01-10 01:23 UTC, claudiodfc commented
Looks like a smartai problem. When the waypoint pauses it should either use the orientation from db or keep the current orientation from movement. This is a generic issue but I'll take a look later.

2022-01-14 19:48 UTC, claudiodfc commented
@IntelligentQuantum Can you give another review on core change?

2022-01-15 03:23 UTC, IntelligentQuantum approved these changes

2022-01-15 09:10 UTC, temperrr commented
Looks good!

2022-01-17 03:35 UTC, acidmanifesto commented
@Kitzunu can you go over the re-review and approve if you find nothing wrong please? Since this deals with a quest chain and addresses a slight smart ai issue, i would like to see this go forward if there is no further issue identified.

2022-01-19 14:10 UTC, acidmanifesto approved these changes

2022-01-19 21:39 UTC, merged

2022-03-25 00:14 UTC, fendwe commented
See also https://github.com/chromiecraft/chromiecraft/issues/3216

2022-03-25 10:05 UTC, claudiodfc commented
The issue can't be this PR since I tested several times doing the full chain on several machines and no issues were found.

2022-03-25 23:11 UTC, Kosiak commented
It's very hard to explain everything in details in here but ill try. You fixed the quest chain but u broke Grimclaw(3695). With scripts u summoning creature which already exists. And all scripts applied to the [Grimclaw](https://classic.wowhead.com/npc=3695/grimclaw) which is supposed to be at he's location.  So your quest is working because u summon him and do waypoints from very close to quest. But u broke original Grimclaw which supposed to be at his location all the time and at respawn aka server restart he constantly on the move which explained in this [PR](https://github.com/azerothcore/azerothcore-wotlk/issues/10925). But he's constantly on the move due to your scripts starts on respawn(exactly what happens after server restarts). U "fixed" it with scripts but they broke Grimclaw completely. And while your quest chain was working. [This](https://github.com/azerothcore/azerothcore-wotlk/pull/10926) pr however overruled your waypoints and all the quest chain in a big mess now. We need to find a way to separate original Grimclaw from the one that is summoned for quest. I hope it wasn't too long.

2022-03-27 15:45 UTC, claudiodfc commented
I see.. I'll see what I can do about it. Thanks for the feedback.