fix(Core/Spells): Passive auras with SPELL_ATTR0_ONLY_INDOORS/SPELL_A…
azerothcore/azerothcore-wotlk pull request #9837
Opened 2021-12-21 21:21 UTC by UltraNix

…TTR0_ONLY_OUTDOORS should not be removed when entering/leaving buildings.

Fixes #9209

## Issues Addressed:

- Closes #9209
- Closes https://github.com/chromiecraft/chromiecraft/issues/2340

## Tests Performed:

- Tested ingame.

## How to Test the Changes:

.additemset 742
.modify reputation 947 9000
.modify reputation 935 9000
.modify reputation 942 9000
.modify reputation 1011 9000
.modify reputation 989 9000

Add speed checker macro somewhere: /script print(string.format("Current speed: %d%%", GetUnitSpeed("player") / 7 * 100))
Run into the building in bear/cat form with 4set PvP bonus
Leave the building
Not getting the set bonus, you need to reshift bear/cat form instead of getting bonus automatically

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

2022-01-15 07:48 UTC, UltraNix commented
@azerothcore/testers Please, test it.

2022-01-15 09:44 UTC, temperrr commented
tested, works :)

2022-01-17 07:13 UTC, Nyeriah approved these changes

2022-01-17 07:14 UTC, Nyeriah commented
Codestyle check script:

  Checking RegEx: '\t'
  Checking RegEx: 'LOG_.+GetCounter'
  Checking RegEx: '[[:blank:]]$'
src/server/game/Entities/Player/Player.h:2963:    

Remove whitespace at the end of the lines above

2022-01-18 17:17 UTC, acidmanifesto requested changes

2022-01-18 17:17 UTC, acidmanifesto commented on src/server/game/Entities/Player/Player.h
> +
remove the blank space on line 2963.
![image](https://user-images.githubusercontent.com/16887899/149986116-a12f59c7-ad4c-41a2-8dbc-54ac0d49a776.png)

2022-01-19 17:00 UTC, Nyeriah commented on src/server/game/Entities/Player/Player.h
> +
```suggestion
    bool _wasOutdoor;

```

2022-01-23 02:09 UTC, merged