fix(DB): Goblin pit crew's gossip probability
azerothcore/azerothcore-wotlk pull request #9905
Opened 2021-12-28 16:01 UTC by claudiodfc

## Changes Proposed:
- Since these guys have 5 possible gossip options, setting this to 25
  each option will equal to 100 percentage.
- There are plenty more gossips like this one only have % of 1 to show
  that need to me manually fixed since we don't know how many npc_text
  they may have. A query to count the text_x_x and update the according
  % should be good to go, however this way is safer.

## Issues Addressed:

- Closes #5408

## SOURCE:

## Tests Performed:

- Not tested

## How to Test the Changes:

1. .go c id 4429
2. Check for several gossip menus and check different texts.

## Known Issues and TODO List:

None.

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

2021-12-28 16:22 UTC, acidmanifesto approved these changes

2021-12-28 19:39 UTC, Kitzunu requested changes

2021-12-28 19:39 UTC, Kitzunu commented on data/sql/updates/pending_db_world/rev_1640706977785890600.sql
> +UPDATE `npc_text` SET Probability0 = @PROBABILITY, Probability1 = @PROBABILITY, Probability2 = @PROBABILITY, Probability3 = @PROBABILITY, Probability4 = @PROBABILITY WHERE `ID` IN (778);
fix sql style

2021-12-31 14:13 UTC, claudiodfc commented on data/sql/updates/pending_db_world/rev_1640706977785890600.sql
> +UPDATE `npc_text` SET Probability0 = @PROBABILITY, Probability1 = @PROBABILITY, Probability2 = @PROBABILITY, Probability3 = @PROBABILITY, Probability4 = @PROBABILITY WHERE `ID` IN (778);
done

2022-01-04 19:44 UTC, acidmanifesto approved these changes

2022-01-04 21:12 UTC, claudiodfc commented
#### Test case - Several Gossip texts

![image](https://user-images.githubusercontent.com/54484196/148124356-5cc35cdb-e4e3-4372-b090-d54a21add5d9.png)

![image](https://user-images.githubusercontent.com/54484196/148124410-09071a1f-5cfa-4539-a386-07f619f6a742.png)

![image](https://user-images.githubusercontent.com/54484196/148124503-9827864c-b106-437a-88cd-d826ff3c9a83.png)

2022-01-05 20:36 UTC, Kitzunu approved these changes

2022-01-06 10:57 UTC, merged