Fix[Core/Instance] Culling_of_stratholme Chromie give wrong item repeatly
azerothcore/azerothcore-wotlk pull request #9992
Opened 2022-01-04 04:49 UTC by betayi

Fix Chromie add wrong item 37889 to player cause of cast a wrong spell

## Changes Proposed:
-  as title
-  

## Issues Addressed:

- Closes 

## SOURCE:

## Tests Performed:

Tested

## How to Test the Changes:

1.make a chracters that has finish Quest 13149
2.Tele to Culling_of_Stratholme
3.speak to chromie
3.see if she give you item 37888 but not repeatly 37889

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

2022-01-04 11:53 UTC, pklloveyou commented
![image](https://user-images.githubusercontent.com/18535853/148054968-bc4d5260-c619-489f-85ee-01c2aef3d861.png)
The wrong data is here

2022-01-04 12:22 UTC, betayi commented
> ![image](https://user-images.githubusercontent.com/18535853/148054968-bc4d5260-c619-489f-85ee-01c2aef3d861.png) The wrong data is here

you are right,  and i also exclained this in the first line of this issue content

2022-01-04 12:34 UTC, betayi commented
did you means correct the customized spell's effectitemtype field with 37888 to replace additem 37888 ?

2022-01-04 12:46 UTC, Kitzunu commented
It's not a custom spell, it is just a serverside spell. Blizzard often added items with spells and not by just adding items.

So in this case, you fix the data in ApplySpellFix and you should not just additem

2022-01-04 12:46 UTC, Kitzunu requested changes

2022-01-04 12:46 UTC, Kitzunu commented on src/server/scripts/Kalimdor/CavernsOfTime/CullingOfStratholme/culling_of_stratholme.cpp
> +                    player->AddItem(ITEM_ARCANE_DISRUPTOR, 1);
```cpp
me->CastSpell(player, SPELL_SUMMON_ARCANE_DISRUPTOR);
```
is correct. Fix the spell

2022-01-04 13:49 UTC, betayi commented on src/server/scripts/Kalimdor/CavernsOfTime/CullingOfStratholme/culling_of_stratholme.cpp
> +                    player->AddItem(ITEM_ARCANE_DISRUPTOR, 1);
got it

2022-01-04 13:56 UTC, Kitzunu approved these changes

2022-01-23 17:56 UTC, claudiodfc commented
Test result: ✔

- After quest complete and talking to the NPC the first gossip options, Chromie gives you the item 37888 

![image](https://user-images.githubusercontent.com/54484196/150691449-8bc39599-653b-46a4-9082-96889d3a9ab3.png)

2022-01-27 23:29 UTC, merged